### ISSUE TITLE
Yaw rate message or faster yaw from MainController?

### ISSUE THREAD

**Issue by y22ma** [dji-sdk/Mobile-SDK-Android#10]
Is there anyway to get yaw rate from the SDK? Currently I'm estimating the yaw rate from the yaw status message from the MainController class, but the status only comes in at 10hz, and I'm wondering:
1) if there exists another API call that obtains yaw speed from the onboard filter and if not, 
2) if there's a way to get faster yaw update.

**Comment by SilverChangjian** [comment]
Sorry, the communication between rc and aircraft is limited by the frequency and the maximum of the communication is around 10Hz. We want to improve the frequency, however, the hardware limited the functionality.

**Comment by SilverChangjian** [comment]
Please use the latest SDK for your project, we are not going to support the 2.x version of the SDK.
