### ISSUE TITLE
CrystalSky questions and compatability

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#102]
Does the DJI CystalSky run Android, and can applications be installed on it that are using the DJI SDK?

**Comment by jtuchek** [comment]
Same question for the RC controllers with screens such as the Phantom 4 Pro Plus

**Comment by oliverou** [comment]
Hi @jtuchek, currently, the DJI Mobile SDK doesn't support DJI CystalSky and Phantom 4 Pro RC Screen, will inform developers if we support them in the future SDK release.
