### ISSUE TITLE
DJIWaypoint.speed claims range [0,15] m/s, but values below 1 are floored to 0 m/s. 

### ISSUE THREAD

**Issue by martindroneharmony** [dji-sdk/Mobile-SDK-Android#104]
1. Description of the issue.
According to documentation 
[https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypoint.html?search=waypoint&i=0&#djiwaypoint_speed_inline]
the field DJIWapyoint.speed has a range of [0,15] m/s. Values < 1m/s are floored to 0 m/s. 

2. Steps to reproduce the bug
Create a waypoint mission and set the DJIWaypoint.speed field to 0.9 m/s. Run the mission with simulator and you will notice the drone stops. Run the same mission with 1 m/s speed settings and everything will be fine.

3. Involved software:

- DJI Android mobile SDK 4.0
- DJI Firmware for P4 Pro 01.03.0509
- DJI Firmware for RC 01.04.00.00
- Android 7.0, API 24
- Sony Xperia Z4
- Android Studio 2.3

**Comment by DJI-RobertLiu** [comment]
Thanks for the report on this issue!  We confirmed that this is a bug.  The fix will be included in our next release.

**Comment by talobin** [comment]
@martindroneharmony this should be fixed with the release of 4.4.1.
Please check it out.
Thanks
