### ISSUE TITLE
DJIActiveTrackMission error

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#105]
-  Description of the issue.
Static initializer for DJIActiveTrackMission throws Exception.
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
Unknown. Static initializer would be on app open, so probably nothing? 
-  Crash logs (If you can find it, it would be very helpful)
`Exception java.lang.ExceptionInInitializerError:
dji.sdk.missionmanager.DJIActiveTrackMission.getGestureModeEnabled ()
dji.sdk.missionmanager.DJIMissionManager.disableGesture ()
dji.sdk.missionmanager.DJIMissionManager.onEventBackgroundThread ()
java.lang.reflect.Method.invoke (Method.java)
dji.thirdparty.eventbus.EventBus.invokeSubscriber (EventBus.java:569)
dji.thirdparty.eventbus.EventBus.postToSubscription (EventBus.java:513)
dji.thirdparty.eventbus.EventBus.postSingleEvent (EventBus.java:475)
dji.thirdparty.eventbus.EventBus.post (EventBus.java:365)
dji.midware.data.manager.P3.u.post ()
dji.midware.data.manager.P3.u.setPushRecData ()
dji.midware.data.manager.P3.u.setPushRecPack ()
dji.midware.data.manager.P3.l.b ()
dji.midware.data.manager.P3.l.a ()
dji.midware.data.manager.P3.l.a ()
dji.midware.usb.P3.UsbAccessoryService$1.onGetBody ()
dji.midware.f.a.f.c ()
dji.midware.f.a.f.a ()
dji.midware.usb.P3.UsbAccessoryService$RecvBufferRunnable.run ()
java.lang.Thread.run (Thread.java:761)
Caused by java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
android.os.Handler.<init> (Handler.java:200)
android.os.Handler.<init> (Handler.java:128)
dji.sdk.missionmanager.DJIActiveTrackMission.<clinit> ()
dji.sdk.missionmanager.DJIActiveTrackMission.getGestureModeEnabled ()
dji.sdk.missionmanager.DJIMissionManager.disableGesture ()
dji.sdk.missionmanager.DJIMissionManager.onEventBackgroundThread ()
java.lang.reflect.Method.invoke (Method.java)
dji.thirdparty.eventbus.EventBus.invokeSubscriber (EventBus.java:569)
dji.thirdparty.eventbus.EventBus.postToSubscription (EventBus.java:513)
dji.thirdparty.eventbus.EventBus.postSingleEvent (EventBus.java:475)
dji.thirdparty.eventbus.EventBus.post (EventBus.java:365)
dji.midware.data.manager.P3.u.post ()
dji.midware.data.manager.P3.u.setPushRecData ()
dji.midware.data.manager.P3.u.setPushRecPack ()
dji.midware.data.manager.P3.l.b ()
dji.midware.data.manager.P3.l.a ()
dji.midware.data.manager.P3.l.a ()
dji.midware.usb.P3.UsbAccessoryService$1.onGetBody ()
dji.midware.f.a.f.c ()
dji.midware.f.a.f.a ()
dji.midware.usb.P3.UsbAccessoryService$RecvBufferRunnable.run ()
java.lang.Thread.run (Thread.java:761)`
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
SDK version 3.5.1
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
camera=1.10.1.40, gimbal=01.30.01.28, flightController=02.04.20.28, remoteController=1.7.60, missionManager=unavailable, airLink=unavailable
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc), Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
Manufacturer: Htc
Model: Nexus 9
Board: Flounder
Android API: 25
Android OS: 7.1.1
Brand: Google
-  Android Studio version you are using (Like Android Studio 2.2, etc)
2.3.1 stable

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
