### ISSUE TITLE
Camera keeps taking photos and never stops after setting "waypoint.shootPhotoDistanceInterval" 

### ISSUE THREAD

**Issue by GIS-HowardZhang** [dji-sdk/Mobile-SDK-Android#107]
Documentation says "public float shootPhotoDistanceInterval - The distance interval in meters when two photos are taken as the aircraft moves between the current waypoint and the next waypoint". But after I set the parameter at first waypoint "waypointFirst.shootPhotoDistanceInterval = 5",  camera just keeps taking photos in 5 seconds interval all the way from the first point to the last point. 

What I need is that when I set "waypointFirst.shootPhotoDistanceInterval = 5" and "waypointThird.shootPhotoDistanceInterval = 5", no photo will be taken between the second waypoint and third waypoint. And I think that is exactly what the development documentation means. Or did I  misunderstand that sentence? 
 
- I'm using those waypoints in a custom mission : Waypoints -> WaypointMission -> WaypointStep -> CustomMission
-  DJI Android SDK 3.5
-  Phantom 4 Pro
-  Android 6.0.1
-  Huawei Honor Pad 2
-  Android Studio 2.3.1

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
