### ISSUE TITLE
When am download video from osmo zenmuse x3 device continuously failed in Samsung sky device and htc desire 626 device also?

### ISSUE THREAD

**Issue by duggisetty** [dji-sdk/Mobile-SDK-Android#109]
Am using android studio 2.3.2 and above lollipop 5.0.1 versions devices its continuously shows error like Dji device time out..etc  
One more thing below lollipop versions doesn't support DJI sdk 4.0.2 version? why?

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
