### ISSUE TITLE
关于DJI数传的问题

### ISSUE THREAD

**Issue by pzy2253999075** [dji-sdk/Mobile-SDK-Android#1092]
请问大疆技术专家，我现在想获取无人机的数传，主要就是gps信息。需要做mobile sdk开发来获取，但是我又不想把全部功能都实现，只想获取数传并实时上传服务器，然后无人机的操控还是用DJIGO这类原生软件。请问有没有可能实现这种方案，其实就是2个app同时在用，原生软件用于操控无人机，获取数传的app在后台运行。

**Comment by DJI-William** [comment]
app装在带屏遥控器里可以实现MSDK开发的app和Pilot同时获取飞机数据。
