### ISSUE TITLE
WaypointAction Parameter not possible

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#110]
Within the docu of WaypointActionTypes you describe the following:

"GIMBAL_PITCH -> Rotates the gimbal's pitch. The actionParam value should be in range [-90, 0] degrees."

Range of [-90, 0] but the actionParam is bounded to: (from = 0, to = Short.MAX_VALUE)

How can i use any valid param instead of 0 ???

Regards and thanks for your help!

**Comment by DJI-RobertLiu** [comment]
Thanks for reporting this bug.  Confirmed that we fixed this issue in our coming release 4.1.0.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
