### ISSUE TITLE
 provideTranscodedVideoFeed  监听器回调失效

### ISSUE THREAD

**Issue by pzy2253999075** [dji-sdk/Mobile-SDK-Android#1100]
我想从M300中获取标准的h264码流，我已经知道需要先从getPrimaryVideoFeed的VideoDataListener的回调中进行sendDataToDecoder，然后再从provideTranscodedVideoFeed的VideoDataListener的回调中获取标准h264。我的安卓程序有2个Activity，一个是ConnectionActivity，一个是MainActivity。运行app，无人机连接后，从ConnectionActivity跳到MainActivity，然后在MainActivity中获取转码的数据，第一次可以拿到。但是如果我点击返回键，跳回ConnectionActivity然后再点击open从新进入MainActivity后provideTranscodedVideoFeed的VideoDataListener的回调就拿不到数据了，但是getPrimaryVideoFeed的有数据。除非将app从后台关闭从新运行，否则provideTranscodedVideoFeed一直拿不到数据。请问这个是什么原因呢。

`        codecManager = new DJICodecManager(getApplicationContext(),new SurfaceTexture(texname), 1920, 1080);
        codecManager.resetKeyFrame();
        if (isM300Product()) {
            OcuSyncLink ocuSyncLink = DemoApplication.getProductInstance().getAirLink().getOcuSyncLink();
            // If your MutltipleLensCamera is set at right or top, you need to change the PhysicalSource to RIGHT_CAM or TOP_CAM.
            ocuSyncLink.assignSourceToPrimaryChannel(PhysicalSource.LEFT_CAM, PhysicalSource.FPV_CAM, new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError error) {
                    if (error == null) {
                        showToast("assignSourceToPrimaryChannel success.");
                    } else {
                        showToast("assignSourceToPrimaryChannel fail, reason: "+ error.getDescription());
                    }
                }
            });
        }
        VideoFeeder.getInstance().setTranscodingDataRate(10.0f);
        
        if(VideoFeeder.getInstance().getPrimaryVideoFeed() != null){
            primary_data_listenser = new VideoFeeder.VideoDataListener() {
                @Override
                public void onReceive(byte[] bytes, int i) {
                    codecManager.sendDataToDecoder(bytes, i);
                    if (System.currentTimeMillis() - lastupdate > 2000) {
                        showToast("primary数据大小为 :" + String.valueOf(i));
                        lastupdate = System.currentTimeMillis();
                    }
                }
            };
            VideoFeeder.getInstance().getPrimaryVideoFeed().addVideoDataListener(primary_data_listenser);
        }
        
        if(VideoFeeder.getInstance().provideTranscodedVideoFeed() != null){
            transcoded_data_listener = new VideoFeeder.VideoDataListener() {
                @Override
                public void onReceive(byte[] bytes, int i) {
                    if (System.currentTimeMillis() - lastupdate > 2000) {
                        showToast("transcoded数据大小为 :" + String.valueOf(i));
                        lastupdate = System.currentTimeMillis();
                    }
                }
            };
            VideoFeeder.getInstance().provideTranscodedVideoFeed().addVideoDataListener(transcoded_data_listener);
        }`

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59763'>Zendesk ticket #59763</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
这个问题是已知问题，已经排期检查了，4.16.1版本会给个结论，到时我会更新上来。

**Comment by pzy2253999075** [comment]
> 这个问题是已知问题，已经排期检查了，4.16.1版本会给个结论，到时我会更新上来。

好，谢谢。

**Comment by DJI-William** [comment]
此问题是bug，已经解决，修改提交到了4.16.1分支，预计3月发布。

**Comment by DJI-William** [comment]
它的根本原因是因为每次调用provideTranscodedVideoFeed()都会new一个新的videofeed，所以你如果用
VideoFeeder.getInstance().provideTranscodedVideoFeed().addVideoDataListener(videoDataListener);
VideoFeeder.getInstance().provideTranscodedVideoFeed().removeVideoDataListener(videoDataListener);

会失效，正确用法是保存起来：

VideoFeed feed = VideoFeeder.getInstance().provideTranscodedVideoFeed();
feed.addVideoDataListener(videoDataListener);
feed.removeVideoDataListener(videoDataListener);

不过4.16.1以后用哪个方法都可以，我们会保证provideTranscodedVideoFeed的时候还是使用原来的videofeed而不会新建，和getPrimaryVideoFeed的使用方法保持一致。

**Comment by kin0201** [comment]
你好，我在調用provideTranscodedVideoFeed().addVideoDataListener方法時遇到以下問題，請問兩位有否遇過？

The `provideTranscodedVideoFeed().addVideoDataListener` method return an error, after I updated the MSDK to 4.16. The exact same code works fine with 4.15. Anyone can offer some helps on this?

`VideoFeeder.getInstance().provideTranscodedVideoFeed().addVideoDataListener(this.videoDataListener!!)`

`Attempt to invoke virtual method 'javax.microedition.khronos.egl.EGLContext dji.midware.media.opengl.fdd.hgf()' on a null object reference`

**Comment by DJI-William** [comment]
@kin0201 没遇到过啊，需要完整日志，还有复现手法。
