### ISSUE TITLE
mCamera.getDisplayName() doesn't match the String value "DJICameraDisplayNameMavicPro"

### ISSUE THREAD

**Issue by GIS-HowardZhang** [dji-sdk/Mobile-SDK-Android#111]
As said in API Reference：

DJICamera
 - String	getDisplayName()
   Returns string that represents the type of the camera.

 - public static final String DJICameraDisplayNameMavicPro
   Constant Value: "Mavic Pro Camera"

But after calling the method mCamera.getDisplayName(), the returning string value is always "Mavic Pro", not "Mavic Pro Camera" shown above.  And "mCamera.getDisplayName().equals(DJICamera.DJICameraDisplayNameMavicPro)" will always be false.

Is that a unique mistake only find in Mavic Pro?  

-  DJI Android SDK version you are using (Android SDK 3.5.1)
-  DJI Product you are using  (Mavic Pro)
-  Android system version you are using ( Android 7.0)
-  Android device you are using (Huawei Pad M3)
-  Android Studio version you are using (Android Studio 2.3.2)

**Comment by oliverou** [comment]
Hi @GIS-HowardZhang , I found that you are still using Android SDK 3.5.1. This issue has been resolved in our latest Android SDK 4.1. Please download it from our [developer website](http://developer.dji.com/mobile-sdk/downloads/) and try again. Thanks!

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by kjknair** [comment]
Don't close the issue. I am getting the same problem with DJI SDK 4.5.1. the Camera#getDisplayName returns null.

drone : Phantom 4 pro
mobile : moto g4 plus
sdk : 4.5.1
