### ISSUE TITLE
How to grab live preview with actual SDK

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#112]
Hey everybody,

i updated to newest SDK 4.1 from 3.5.1.
A lot of API changed and now i cannot find out how to register for Live preview.
So you example on your developer page is old and within the SDK examples you are not doing anything with live preview.

I found out that the Camera has a VideoDataCallback interface but no method to register.
Moreover i found a VideoFeeder with an VideoDataCallback.

Can you give me an example how to catch the live preview from the camera??

Regards
xxmaestroxx

**Comment by xxmaestroxx** [comment]
I don't know why, but the live preview is working.

Please can you anyway explain how to do it?

**Comment by oliverou** [comment]
Hi @xxmaestroxx , you can check this [FPVDemo](https://github.com/DJI-Mobile-SDK-Tutorials/Android-FPVDemo) and [Creating a Camera Application](http://developer.dji.com/mobile-sdk/documentation/android-tutorials/index.html) for details.

**Comment by talobin** [comment]
Also, please check out our UI Library.
It has built in FPVWidget that also has live video feed.
