### ISSUE TITLE
DJIAnalyticsEvent Exception while starting 

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#113]
Hey everbody,

I get all the time the following exception:

06-04 13:09:05.965 E/a: Exception serializeDatadji.internal.network.DJIAnalyticsEvent; Incompatible class (SUID): dji.internal.network.DJIAnalyticsEvent: static final long serialVersionUID =3166459872679089193L; but expected dji.internal.network.DJIAnalyticsEvent: static final long serialVersionUID =4547257726269968361L;

It is not breaking my app but it is a little bit annoying to see evertime in the log things like this ;-)

SDK-Version: 4.1

Regards
xxmaestroxx

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
