### ISSUE TITLE
Get IMU data and Gimbal state when taking pictures.

### ISSUE THREAD

**Issue by huynhtnhut97** [dji-sdk/Mobile-SDK-Android#1131]
Dear authors,

Regarding the timeline mission, I have tried to add a waypoint mission to the timeline and do taking a picture at that waypoint. However, I want to collect IMU data and gimbal state when the picture is taken. As far as the mission action is concerned, there is no action to collect these data. May I ask if there is a way to collect IMU data and gimbal state simultaneously while taking pictures?

Thank you for your consideration.

**Comment by DJI-William** [comment]
There is no API interface to collect the IMU raw data. To get the gimbal state, you can call gimbal.setStateCallback to register a callback keep listening the gimbal state.
