### ISSUE TITLE
How to get image data via mobile sdk when app run in the background

### ISSUE THREAD

**Issue by pzy2253999075** [dji-sdk/Mobile-SDK-Android#1132]
I want to get the data of DJI UAV H264. I have got the data through preliminary attempts, but when I run the app in the background, the callback function to get the data seems to be unable to execute, and the log console displays the following error：
E/DJIStreamLocalSocket: ExitSocket =  ContextUtil.isAppBroughtToBackground()
 Does the Mobile SDK support the background app to get image data? If yes, what should I do，thanks。

**Comment by DJI-William** [comment]
Please have a look thsi article : https://sdk-forum.dji.net/hc/en-us/articles/4435288172825-How-to-get-video-stream-from-background-

**Comment by pzy2253999075** [comment]
![image](https://user-images.githubusercontent.com/15712923/163115298-6b172d46-63bc-43d5-b396-9cf38fab5982.png)
I am sorry, I could not find this function

**Comment by pzy2253999075** [comment]
@DJI-William

**Comment by DJI-William** [comment]
Are you using MSDK 4.16.1? This method was created in May 2021?
