### ISSUE TITLE
DJI Mini 3 Support?

### ISSUE THREAD

**Issue by ShakedDovrat** [dji-sdk/Mobile-SDK-Android#1139]
When will the new DJI Mini 3 model be supported by the SDK?
Thanks

**Comment by DJI-William** [comment]
There is no plan to support Mini 3 now. It will be supported after Mavic 3 series. So most likely in Q3,Q4 this year.

**Comment by alzin** [comment]
Are there any updates on this?

**Comment by DJI-William** [comment]
Mavic 3 and Mini 3 will not be supported in 2022, please see this article, [What is the plan for the consumer level aircraft?](https://sdk-forum.dji.net/hc/en-us/articles/8818033368857-What-is-the-plan-for-the-consumer-level-aircraft-)
