### ISSUE TITLE
Flysafe file not found exception

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#114]
Hey everbody,

i got all the time the following warn log:

06-04 13:09:05.715 D/nfz: polygonDjigoSubDb not exits
06-04 13:09:05.715 W/System.err: java.io.FileNotFoundException: flysafe/flysafe_polygon_1860.db
06-04 13:09:05.715  W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
06-04 13:09:05.715  W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
06-04 13:09:05.715  W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
06-04 13:09:05.715  W/System.err:     at dji.midware.data.forbid.util.FlyforbidUtils.copyDatabaseFromAsset(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.getDb(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.midware.data.forbid.db.FlyfrbBaseDbManager.<init>(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.<init>(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.init(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.midware.data.forbid.DJIFlyForbidController.<init>(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.midware.data.forbid.DJIFlyForbidController.getInstance(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.sdk.sdkmanager.GeoSyncFileService.init(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source)
06-04 13:09:05.715 W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source)
06-04 13:09:05.715 W/System.err:     at ...model.dji.DJIProductManager$1.run(DJIProductManager.java:101)
06-04 13:09:05.715 W/System.err:     at java.lang.Thread.run(Thread.java:818)

It's not breaking my app, but here again it's not nice to have it.

SDK-Version: 4.1

Regards
xxmaestroxx

**Comment by oliverou** [comment]
Hi @xxmaestroxx, thanks for the feedbacks. We have addressed this issue and will fix it in the upcoming SDK release.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
