### ISSUE TITLE
Selecting photo saving mode

### ISSUE THREAD

**Issue by lgpaula** [dji-sdk/Mobile-SDK-Android#1140]
How one can select multiple options for photo saving through the MSDK?

![c26f505f-4799-453c-a438-bbbfa8b22bc3](https://user-images.githubusercontent.com/23309087/168002764-8d1f292d-43f3-4c2b-8c15-cc406daf8aa3.jpg)

**Comment by DJI-William** [comment]
Please read this article and it will guide you how to acheive the function in screenshot, https://sdk-forum.dji.net/hc/en-us/articles/4402704759449-How-to-specify-a-lens-to-capture-photo-in-multi-lens-camera-
