### ISSUE TITLE
How to activate payload mode?

### ISSUE THREAD

**Issue by ShakedDovrat** [dji-sdk/Mobile-SDK-Android#1148]
Hi,

In the DJI Fly app there's a toggle button to enable/disable payload mode (payload mode compensates extra weight of e.g. propeller guards).
I couldn't find this enable/disable option in the mobile SDK. Everything regarding payload in the SDK seems to refer to payload devices which communicate with the drone, which is not what I need.

Please help, thank you

**Comment by DJI-William** [comment]
MSDK does not have such API to switch the aircraft to payload mode since we think this function is low frequently usage.

**Comment by DJI-William** [comment]
By the way, which aircraft model are you using, I am going to handle a request for it.

**Comment by ShakedDovrat** [comment]
I'm currently using DJI Mini 2. Planning to use DJI Air 2 (Mavic 2) in the future

**Comment by DJI-William** [comment]
Already raise a requirement ticket for the dev team.

**Comment by DJI-William** [comment]
We have added an additional key FlightControllerKey.PROPELLER_COVER_LIMIT_ENABLED for this function in Android 4.16.3. It is about to release in 2 weeks.

**Comment by Prateek-Jakhar** [comment]
is it not supported in mini 3?
