### ISSUE TITLE
When will the Mavic 3 be supported?

### ISSUE THREAD

**Issue by grabovszky** [dji-sdk/Mobile-SDK-Android#1150]
The DJI Mavic 3 is a great consumer and semi-professional product.

Will it ever be supported in the DJI Mobile SDK, and if yes, what is the possible timeframe it will be released?
Does the DJI development team have a clear roadmap on this?

**Comment by DJI-William** [comment]
Please have a read this article, [Chapter 1 - Hello, MSDK V5!](https://sdk-forum.dji.net/hc/en-us/articles/5976502476441-Chapter-1-Hello-MSDK-V5-?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5Nzg4MTcsInVzZXJfaWQiOjc1NjEwNDU2NTEyMjUsInRpY2tldF9pZCI6NjYxMzAsImNoYW5uZWxfaWQiOjYzLCJ0eXBlIjoiU0VBUkNIIiwiZXhwIjoxNjU4MDI3NTQ4fQ.uPU8euWKnKlKpddhYL6Vj34SCL6FeOF61werXRD4UJo) we plan to support Mavic 3 series in the end of Auguest.

**Comment by borealmotion** [comment]
Hi @DJI-William , are there any plans to Support Mavic 3 consumer models in the future?
