### ISSUE TITLE
Cannot connect Sample Code with Air S2

### ISSUE THREAD

**Issue by s84498** [dji-sdk/Mobile-SDK-Android#1151]
Hello,

I've been trying to run the sample code on my google pixel 6. I connected it via USB with the controller and activated my air s2 drone. But the product is never found.

I made sure by the call the package name the same in the app activiation site in the developer section.

Is there anything I'm forgetting?

Thank you very much for your help!

**Comment by DJI-William** [comment]
What happen if you press the REGISTER APP button?

**Comment by s84498** [comment]
The registration is successful, but I'm getting an error:

"db load success! get version error: The execution could not be executed"

**Comment by DJI-William** [comment]
The db error does not influence. Since you have registered, the open button should become clickable.

**Comment by s84498** [comment]
Ahh it works now! I was so sure we tried the register app button on friday. Does it usually take a day or two for the registration process to go through?

Anyway, thank you so much for the support! I'm closing the issue now. 

Best wishes!

**Comment by DJI-William** [comment]
The registration will be ok instantly, perhaps its a physical connection issue previously.
