### ISSUE TITLE
camera.setDigitalZoomFactor(1f) sets zoom to 2 (Mini 2)

### ISSUE THREAD

**Issue by petered** [dji-sdk/Mobile-SDK-Android#1157]
On mini 2, I'm trying to programatically zoom out with (Kotlin) command:

```
camera.setDigitalZoomFactor(1f) {println("Set digital zoom - error? $it")}
```

Problem is, it doesn't zoom out.  Instead the SDK always seems to interpret the zoom-factor as 2 - no matter what I put in there - so the only way to zoom out after zooming in is to do so manually with the RC controller.

So if I am already zoomed out, and run the above command (telling zoom to go to 1), it will actually zoom IN to 2x.

**Edit:** Found a workaround for now: 
```
camera.restoreFactorySettings { println("Restored camera factory settings: error? $it") }
```
Resets the zoom, but also probably does other things you may not want.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/68377'>Zendesk ticket #68377</a>:<br><br>What version of MSDK are you using? According to this article the zoom function of the mini 2 is supported on MSDK 4.16.1. article：How to adjust the zoom factor for DJI Mini 2? - https://sdk-forum.dji.net/hc/en-us/articles/4501905670553-How-to-adjust-the-zoom-factor-for-DJI-Mini-2-?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo5Nzg4MTcsInVzZXJfaWQiOjg5MjgyNjY3MDI2MTcsInRpY2tldF9pZCI6NjgzNzcsImNoYW5uZWxfaWQiOjYzLCJ0eXBlIjoiU0VBUkNIIiwiZXhwIjoxNjYxNTkwNzQ2fQ.fcJSqdZcKCZBTGmkn39AacVewPpDw2gp1Ib07_0xKQA
<br><p><em><small>°°°</small></em></p>

**Comment by petered** [comment]
I'm on 4.16.1.  That documentation appears to contradict what I observe on the SDK in 2 ways:

1) As mentioned above, no matter what number you input, it always zooms to 2x.

2) The range of inputs that are allowed is 1-2, not 1-4 as it says in that documentation.  You can see this in the decompiled function header: 

```
public void setDigitalZoomFactor(@FloatRange(from = 1.0D,to = 2.0D) float var1, @Nullable CompletionCallback var2)
```

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/68377'>Zendesk ticket #68377</a>:<br><br>The range described in the documentation is based on DJI fly and hardware parameters. The mini 2's hardware specifications mention the different zoom ranges supported by different resolutions.
 ![](https://djisdksupport.zendesk.com/attachments/token/XsF7DP1HoFfFklbF8an2IZkEg/?name=image.png)
I tested the digital zoom function on the mini 2 and it works fine, you can see a video of my test in the link below.
LINK:https://pan-sec.djicorp.com/s/gbWdGroxAn2cGrw password：dji123<br><a href='https://djisdksupport.zendesk.com/attachments/token/XsF7DP1HoFfFklbF8an2IZkEg' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by petered** [comment]
Thank you for investigating this Yating.  What program are you using to test?  It looks different from the MSDK4 app.

I made a small test that reproduces the problem in isolation.  See video: https://photos.app.goo.gl/eUoL92KQBaeATEKz5 

Kotlin code for test activity: 

```
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.TextureView
import android.widget.Button
import android.widget.Toast
import dji.common.error.DJIError
import dji.common.util.CommonCallbacks
import dji.sdk.base.BaseProduct
import dji.sdk.camera.VideoFeeder
import dji.sdk.sdkmanager.DJISDKManager

class DroneTestActivity : AppCompatActivity() {

    private val product: BaseProduct by lazy { DJISDKManager.getInstance().product }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_drone_test)

        findViewById<TextureView>(R.id.livestream_preview_ttv).run {
            surfaceTextureListener = FakeTextureView(
                codecCallback = {VideoFeeder.getInstance().primaryVideoFeed.addVideoDataListener { videoBuffer, size ->
                                    it.sendDataToDecoder(videoBuffer, size)
                                }},
                applicationContext = applicationContext
            )
        }

        findViewById<Button>(R.id.getZoom).setOnClickListener{
            product.camera.getDigitalZoomFactor(object: CommonCallbacks.CompletionCallbackWith<Float>{
                override fun onSuccess(p0: Float?) = Toast.makeText(applicationContext, "Zoom is $p0", Toast.LENGTH_SHORT).show()
                override fun onFailure(p0: DJIError?) = Toast.makeText(applicationContext, "Checking zoom failed with $p0", Toast.LENGTH_SHORT).show()
            })
        }

        findViewById<Button>(R.id.setZoom1).setOnClickListener{
            val zoomLevel = 1f
            product.camera.setDigitalZoomFactor(zoomLevel){Toast.makeText(applicationContext, "Set zoom to $zoomLevel.  Error?: $it", Toast.LENGTH_SHORT).show()}
        }

        findViewById<Button>(R.id.setZoom2).setOnClickListener{
            val zoomLevel = 2f
            product.camera.setDigitalZoomFactor(zoomLevel){Toast.makeText(applicationContext, "Set zoom to $zoomLevel.  Error?: $it", Toast.LENGTH_SHORT).show()}
        }

    }
}
```

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/68377'>Zendesk ticket #68377</a>:<br><br>4.16.2 has been released and you can upgrade to 4.16.2 to solve this problem.
<br><p><em><small>°°°</small></em></p>

**Comment by petered** [comment]
Nice - I confirm that upgrading to 4.16.2 fixes the bug.

Thanks for the quick responses and for being on top of things.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/68377'>Zendesk ticket #68377</a>:<br><br>I‘m glad to help you！
<br><p><em><small>°°°</small></em></p>
