### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Kanhoto** [dji-sdk/Mobile-SDK-Android#1158]
Hi,

I've download the project and opened it in android studio,
but can't complete gradle build cause of these errors :

![image](https://user-images.githubusercontent.com/85866455/181732190-a5bb8739-0b78-43f2-8e0a-facefdf08cb7.png)

Did someone had the same errors and found some solutions ?

Thanks

**Comment by DJI-William** [comment]
We never encounter this problem before, we believe it is a IDE problem.

**Comment by Kanhoto** [comment]
Ok found a solution, just changed the target sdk from 31.0.0 to 30.0.3 and it builded
Dunno why though, maybe my IDE didn't recognize my sdk 31.0.0

**Comment by DJI-William** [comment]
Maybe your IDE is lacking the Android 31 SDK?

**Comment by asegs** [comment]
This is a known bug with Android 31/32, you have to follow [these steps](https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted/68430992#68430992).

In the case of `runOnUiThread` being private, I noticed that each class takes a `Context` as an argument.  In most cases, `Context` can be cast to `Activity`, for example: `this.mainActivity = (Activity) context;`.  Then you can call `mainActivity.runOnUiThread(...action)`.  I believe you can also just do any action on a thread and it will just run in the background to update the UI.  But this worked for me.

**Comment by DJI-William** [comment]
It seems like not a Mobile SDK issue.
