### ISSUE TITLE
M300 ABSOLUTE_GPS_ALTITUDE key value returns null

### ISSUE THREAD

**Issue by RonPercepto** [dji-sdk/Mobile-SDK-Android#1159]
Using the below:
Object heightAboveSeaLevel = KeyManager.getInstance().getValue(FlightControllerKey.create(FlightControllerKey.ABSOLUTE_GPS_ALTITUDE));

return value is null when using m300, in mavic it returns the value.

using:
        DJIKey GPSKey = FlightControllerKey.create(FlightControllerKey.ABSOLUTE_GPS_ALTITUDE);
        DJISDKManager.getInstance().getKeyManager().getValue(GPSKey, new GetCallback() {
            @Override public void onSuccess(@NonNull Object value) {
                
            }
            @Override public void onFailure(@NonNull DJIError error) {
               
            }
        });

returns "The feature is unsupported.(255)"

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/68481'>Zendesk ticket #68481</a>:<br><br>This KEY does not currently support the M300. Do you know how to use MSDK V5, which provides the KEY for obtaining real-time altitude: KeyRTKAbsoluteAltitude?
MSDK V5：https://developer.dji.com/doc/mobile-sdk-tutorial/cn/
<br><p><em><small>°°°</small></em></p>
