### ISSUE TITLE
SDK logs a lot of not needed information all the time

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#116]
Hey everybody,

again me :D

When i have the drone connected the SDK is all the time logging the same uninteresting information for me:

06-04 15:27:20.562 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:20.932 d.v.s.d D/UsbAccessoryService: rate 116,40 KB
06-04 15:27:21.572 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:22.582 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:22.942 d.v.s.d D/UsbAccessoryService: rate 107,54 KB
06-04 15:27:23.582 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:24.592 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:24.942 d.v.s.d D/UsbAccessoryService: rate 117,81 KB
06-04 15:27:25.612 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:26.622 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:26.952 d.v.s.d D/UsbAccessoryService: rate 112,19 KB
06-04 15:27:27.652 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:28.662 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:28.952 d.v.s.d D/UsbAccessoryService: rate 108,02 KB
06-04 15:27:29.662 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:30.672 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:30.952 d.v.s.d D/UsbAccessoryService: rate 114,66 KB
06-04 15:27:31.682 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:27:32.682 d.v.s.d I/RAYLEE: getRealNameSystem false

and moreover the following log:

06-04 15:56:38.882 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.3267770967125 longitude:11.635927297577792
06-04 15:56:38.882 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:38.982 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677720097085 longitude:11.635927199472815
06-04 15:56:38.982 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.092 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.3267772048464 longitude:11.6359272020744795
06-04 15:56:39.092 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.182 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677720839905 longitude:11.635927102993667
06-04 15:56:39.182 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.202 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.326777205656064 longitude:11.635927101643161
06-04 15:56:39.202 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.382 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677730333336 longitude:11.635927001199213
06-04 15:56:39.382 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.482 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677730264958 longitude:11.635927001415575
06-04 15:56:39.482 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.582 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677740171203 longitude:11.635927001226527
06-04 15:56:39.582 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.682 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677740421374 longitude:11.635927000598412
06-04 15:56:39.682 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.752 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:56:39.782 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677750636452 longitude:11.635926900161457
06-04 15:56:39.782 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.882 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677750495896 longitude:11.63592689965317
06-04 15:56:39.882 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:39.982 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677760314004 longitude:11.635926799331717
06-04 15:56:39.982 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.082 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.326777600258055 longitude:11.635926799726223
06-04 15:56:40.082 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.172 d.v.s.d D/UsbAccessoryService: rate 619,46 KB
06-04 15:56:40.192 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.326777701050396 longitude:11.635926798564972
06-04 15:56:40.192 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.282 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677770593278 longitude:11.635926797222191
06-04 15:56:40.282 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.382 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.326777806603104 longitude:11.635926696861413
06-04 15:56:40.382 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.482 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677780463221 longitude:11.63592669719894
06-04 15:56:40.482 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.582 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677790196034 longitude:11.635926597443717
06-04 15:56:40.582 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.682 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.326777902060336 longitude:11.635926597428299
06-04 15:56:40.682 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.752 d.v.s.d I/RAYLEE: getRealNameSystem false
06-04 15:56:40.782 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677800302454 longitude:11.635926498206563
06-04 15:56:40.782 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.882 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677800246636 longitude:11.63592649856835
06-04 15:56:40.882 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:40.982 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.32677810309704 longitude:11.635926499059491
06-04 15:56:40.982 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE
06-04 15:56:41.082 d.v.s.d I/CountryCodeProviderLogic: receive the onEventBackgroundThread: latitude:19.326778104226605 longitude:11.635926498393289
06-04 15:56:41.082 d.v.s.d I/CountryCodeProviderLogic: get countryCode success:DE

Can you turn this of? Because it's INFO and DEBUG level.

Regards
xxmaestroxx

**Comment by oliverou** [comment]
Hi @xxmaestroxx , thanks for your feedbacks. We have addressed the issue and will fix it in the upcoming version.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
