### ISSUE TITLE
[M300][4.16.2] Displaying H20 and FPV simultaneously

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-SDK-Android#1161]
Hello,

I am trying to display two video streams simultaneously when I have my H20 camera connected, just like in DJI Pilot -- one for the H20 and one for the FPV.

Is this possible? I don't see any way to access the FPV camera stream.

**Comment by DJI-William** [comment]
It is possible, jsut try the [MultipleLensCameraView.kt](https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/camera/MultipleLensCameraView.kt).

**Comment by bbenson09** [comment]
This is what I was looking for! Thanks!
