### ISSUE TITLE
[Virtual Sticks] Flight mode doesn't change to JOYSTICK when using advanced mode

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-SDK-Android#1162]
Hi there, when I try to enable virtual sticks using `setIsVirtualStickAdvancedModeEnabled` (after takeoff), the flight mode comes back as GPS_ATTI, instead of JOYSTICK.

This is NOT the case when I use `setVirtualStickModeEnabled`. 

For example, when I call this after take-off, `isEnabled` is true and rcFlightMode is GPS_ATTI.

```
override suspend fun initVirtualSticks() {
        if (flightController == null) return
        flightController.verticalControlMode = VerticalControlMode.VELOCITY
        flightController.rollPitchControlMode = RollPitchControlMode.VELOCITY
        flightController.yawControlMode = YawControlMode.ANGULAR_VELOCITY
        flightController.rollPitchCoordinateSystem = FlightCoordinateSystem.BODY
        flightController.isVirtualStickAdvancedModeEnabled = true
        val isEnabled = flightController.isVirtualStickAdvancedModeEnabled
        Log.d("DJI", "isEnabled: " + isEnabled) <---- prints true
        delay(500)
        val rcFlightKey = create(FLIGHT_MODE)
        val rcFlightMode = DJISDKManager.getInstance().keyManager?.getValue(rcFlightKey)
        Log.d("DJI", rcFlightMode.toString()) <---- prints GPS_ATTI
    }
```

Am I doing something wrong here, or is there a bug? 

VERSION INFO
SDK: 4.16.2
M300 Firmware: V04.00.0200

**Comment by DJI-William** [comment]
The setIsVirtualStickAdvancedModeEnabled must use after setVirtualStickModeEnabled was used. You can not call setIsVirtualStickAdvancedModeEnabled without setVirtualStickModeEnabled is called.

**Comment by bbenson09** [comment]
Ah thank you, ok
