### ISSUE TITLE
Increase Precision for IMU State

### ISSUE THREAD

**Issue by dkapur17** [dji-sdk/Mobile-SDK-Android#1166]
I'm using the `FlightController.state.velocityX`, `FlightController.state.velocityY` and `FlightController.state.velocityZ` to fetch the respective X, Y and Z velocities. From the documentation, I find that this is in m/s. I also see that I can only get the velocity resolution of up to one decimal, i.e. 10 cm/s. This makes it too difficult to do the required analysis from my end. I need to get at least 2-3 decimal places for the analysis. I'm unsure if this is a limitation from the SDK's side or if this is a feature of Kotlin that I cannot understand. Any guidance in this area would be greatly appreciated.

**Comment by DJI-William** [comment]
The raw data from IMU is not given. The velocity X, Y and Z are the fusion data given from firmware. Since the data soruce given from firmware is limited into 1 decimal, we cannot do much things on it. Sorry.
