### ISSUE TITLE
Integration of Android SDK

### ISSUE THREAD

**Issue by Kanhoto** [dji-sdk/Mobile-SDK-Android#1168]
Hi,

I'm facing some difficulties with the mobile SDK.

I've followed the steps written over there https://developer.dji.com/document/76942407-070b-4542-8042-204cfb169168

but for some reasons I get some errors like these ones.

![image](https://user-images.githubusercontent.com/85866455/185050623-d1bca78b-2f07-47be-820e-2231e23144f3.png)

![image](https://user-images.githubusercontent.com/85866455/185050654-e3bebd11-4643-48c3-8609-04ca3e8d52d3.png)

If someone had some tips about that, it would help me ^^

thanks

**Comment by DJI-William** [comment]
The doc is too old, if you follow the guide it won't work. I suggest you just try this final sample straight away.
