### ISSUE TITLE
MSDK 4.x support for the M300

### ISSUE THREAD

**Issue by Salabda** [dji-sdk/Mobile-SDK-Android#1173]
Which versions support the M300?
I have been working with the Phantom 4 for years with the MSDK. Not a problem.
Now, I tried running the app on the M300. The app runs, sometimes it crashes when feeding video onto 
an android device. But even when it doesn't crash. The commands of taking pictures, recording video, and flight
control. Is all off. the Matrice 300 RTK does not react to any command.

**Comment by DJI-William** [comment]
Please use our latest Android 4.16.2 version for now, you can directly try this sample and it supports M300RTK already.
