### ISSUE TITLE
getBattery sometimes returns null on M300

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-SDK-Android#1176]
I'm initializing an instance of Aircraft in my main activity once the drone connects and passing around this instance. When I try to initialize Battery using `product.getBattery()`, sometimes it comes back null (product is not null). I'm initializing other children of Aircraft (e.g., FlightController, Gimbal, RemoteController, etc) and have not seen this issue with any of these classes.

I get around the null Battery by refetching the instance of product from DJISDKMananger and calling getBattery again, but I shouldn't need to do that...

It almost seems like Battery is not getting initialized correctly in the Aircraft class.

SDK Version: 4.16.2
M300 firmware version: latest

**Comment by DJI-William** [comment]
Maybe the time you call getBattery is wrong. The other components are connected after the product is connected a while. Therefore you need to listen the onComponentChange callback in SDKManagerCallback and call getBatteries() method because M300 has multiple batteries.

**Comment by bbenson09** [comment]
Ok got it, thanks

**Comment by danilofariadutra** [comment]
@bbenson09 did you figure out how to get the battery values? I'm having the same problem of getting a null object.

**Comment by bbenson09** [comment]
Hi, it's not ideal: the battery isn't initialized immediately when product is, so you will have to wait for it. Unfortunately, there's no callback in the Battery itself, only in the DJISDKManager.

As DJI-William said, you can observe onComponentChange in the DJISDKManager to detect when the battery gets initialized. If you are registering your app in a custom application class (like I am), you will have to alert your activities somehow. I used LocalBroadcastManager to broadcast initialization events across my app, and it seems to work most of the time (I'm still testing it). The limitation here is that the message will be lost if the component is initialized before your activity is created.

Let me know if you find a better solution!

**Comment by danilofariadutra** [comment]
@bbenson09 Thanks for reply! I will try later, when I get back to work, and let you know If I got it. Regards!
