### ISSUE TITLE
FollowMeMission or VirtualStick support for MavicAir 2

### ISSUE THREAD

**Issue by karikolehmainen** [dji-sdk/Mobile-SDK-Android#1178]
Hello, 

Is it really the case that SDK does not support FollowMe missions for Mavic Air 2 as per this document: https://developer.dji.com/document/52b7f3b9-a773-47b3-b9e5-71c7a3190736

According to table FollowMe missions are supported for Mavic Air. I tried also to use Virtual stick but isVirtualStickControlModeAvailable() returns false... 

Is there plan to support either mode in Mobile SDK for Air 2?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/70623'>Zendesk ticket #70623</a>:<br><br>Mavic air 2 does not support followMe Mission,but AIR 2 is supported by Virtual Stick.You can check to see if the drone meets the requirements to turn on Virtual Stick：When you can enable virtual stick?
sample：https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/flightcontroller/VirtualStickView.java
<br><p><em><small>°°°</small></em></p>

**Comment by karikolehmainen** [comment]
Thanks! 

I was able to enable the virtual stick on Air 2 after some trials. This enabled me to implement the GPS based followme mission.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/70623'>Zendesk ticket #70623</a>:<br><br>I'm glad I could help you.
The issue is now closed.
<br><p><em><small>°°°</small></em></p>
