### ISSUE TITLE
Switching between custom app and DJI Pilot causes crashes in both

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-SDK-Android#1179]
Hi,

I tend to see an increase in the number of native crashes in BOTH my app (running MSDK) and DJI Pilot when I switch back and forth between them. Unfortunately, these tend to be native crashes with no stack trace. 

**Is there a reason this might be occurring, and how can I mitigate it?**

 I haven't reached feature parity with DJI Pilot yet so I sometimes need to switch between the two apps.

MSDK Version: 4.16.2

**Comment by DJI-William** [comment]
To be honest, you shouldn't switch betwwen DJI Pilot and MSDK app very frequently. Which aircraft you are using? I assume you are running these 2 apps inside a Smart Controller. This is becasue the hardware configuration of the Smart Controller is poor.

**Comment by bbenson09** [comment]
Thanks for your response. Correct, yes, I was trying to run both apps on the Smart Controller. I mainly use an M300, but I sometimes test on a Mavic 2 Enterprise.

Seems like solution is easy for Mavic: I can just connect an alternative Android device to the normal RC and run my app. 

For M300, I've connected an alternative Android device to the Enterprise Smart Controller and am trying to run it there, but using an external device seems to work unreliably.

**The New Problem:**

Aircraft connects fine, but sometimes`getWaypointMissionV2Operator()` returns null. This occurs in both my app and the DJI MSDK Sample app. The sample app will crash on pressing "Load" in the WaypointV2 Mission Operator view.

Interestingly, this same problem seems to be occurring in DJI Pilot: when I open DJI Pilot on the alternative device, I'll see the aircraft connected, but there will be an error message in the "Mission Flight" box that says something like "Can't get mission control" and then about 10 seconds later, aircraft will disconnect. 

Turning on/off both controller and aircraft will sometimes fix it. 

Do you know why getWaypointV2Operator would be returning null on an alternative Android device, but not on the Enterprise Smart Controller?

**Comment by bbenson09** [comment]
It's also accompanied by this error:

`E/RTKPM430RTKAbstraction: set rtk source failed: SDK error, please contact <dev@dji.com> for help.`

**Comment by DJI-William** [comment]
It depends on when you call getWaypointMissionV2Opeartor, I suggest you call it when all component is connect in the onComponentChange callback in SDKManagerCallback. For RTK, please read this article, [How to enable RTK?](https://sdk-forum.dji.net/hc/en-us/articles/4404852851481-How-to-enable-RTK-)

**Comment by bbenson09** [comment]
DJI-William, out of curiosity: the main symptom that I see occasionally when I switch back from DJI Pilot to my app is that the camera view screen (I'm using FPVWidget) goes black. When I go back to DJIPilot, same black camera feed there, too.

Do you know why the camera (or the view in Android) is most adversely affected by the switching? And is there anything I can do to mitigate it?

**Comment by bbenson09** [comment]
DJI-William, out of curiosity: the main symptom that I see occasionally when I switch back from DJI Pilot to my app is that the camera view screen (I'm using FPVWidget) goes black. When I go back to DJIPilot, same black camera feed there, too.

Do you know why the camera (or the view in Android) is most adversely affected by the switching? And is there anything I can do to mitigate it?

**Comment by DJI-William** [comment]
I am not sure why the vidoe feed goes off when switching apps. If you kill both of them and re-open it should goes normal.

**Comment by bbenson09** [comment]
Ok thanks
