### ISSUE TITLE
GoToAction actionType is not accessible after event received from MissionControl.Listener

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#118]
Hey everybody,

can you please make more information of various Actions accessible?

e.g. for the GoToAction the actionType, coordinates, speed, altitude?

Maybe other actions have other informative attributes.

Regards
xxmaestroxx

**Comment by xxmaestroxx** [comment]
Hey everbody again,

sorry that i always complain on things,

but for me and my app it is really important to know which type of actions it was.
At the moment i'm working with reflection to get the information but this is not the way i want.

Please can you make the important information of an action readable?

Regards
xxmaestroxx

**Comment by oliverou** [comment]
Hi @xxmaestroxx , could you please provide the following infos for us to help investigate the issue:

-  Description of the issue.
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

Thanks!

**Comment by xxmaestroxx** [comment]
Hey, 
thanks for you feedback, this was more a general intention as of special things.
Why that?
Because of the following answers:

DJI Android SDK version you are using: **4.1.1 from DJI UI Lib 4.1.1**
DJI Product you are using: **Testing with Phantom 4, Inspire 1 and other ones, wants to support most of your drones!**
Android system version you are using: **Testing with 7.1.1, 5.1.1, .... try to support multiple versions**
Android device you are using: Different ones, testing on Nexus 5x, Nvidia Shield, Nexus 9, ....
Android Studio version you are using: 2.3.3

What would be very great is that if some listeners reports updates of maybe waypoint action etc. make all of the settings you have to set while creating these elements readable again.
E.g: GoToActions -> ActionType to distinguish between altitude type or coordinate type, coordinates itself, altitude itself, ....

So a lot of informations are not accessible for me but it would be very great to have access to them.

Hopefully that helps.

Regards
xxmaestroxx

**Comment by talobin** [comment]
Hi @xxmaestroxx ,
Thank you for your request and sorry about the delay in response.
This is a valid request and we will add it to the next release of SDK.

**Comment by talobin** [comment]
@xxmaestroxx  This should be fixed with the release of 4.4.1.
Please check it out.
Thanks!
