### ISSUE TITLE
Cant get the MSDK 4.16.2 to to work on the M300 RTK

### ISSUE THREAD

**Issue by Salabda** [dji-sdk/Mobile-SDK-Android#1180]
Hi, I'm trying to run the sample code MSDK 4.16.2 . I have only updated the manifest to write the app key, I have done nothing else to it.
The app registers successfully.
Shortly after a toast appears on screen ""db load success ! get version error : The execution could not be executed." 

I have tried on two phones. The android versions are 10 and 11.

I have no idea what to try with this.
![Screenshot_20220918_225630](https://user-images.githubusercontent.com/65242931/190914774-99b4b3b1-a109-42d2-8331-1ad091780cee.jpg)

**Comment by DJI-William** [comment]
This issue does not prevent you using this demo. It is a demo issue and it will fix in 4.16.3's Sample

**Comment by Salabda** [comment]
It does prevent me. The application never connects and it cannot be opened.

**Comment by DJI-William** [comment]
Then it is another problem. Which aircraft are you using and what kind of RC you are using?

**Comment by Salabda** [comment]
I get the same problem with both
A) Phantom 4 and its controller and,
B) M300 RTK and its Enterprise Smart Controller

**Comment by DJI-William** [comment]
1. For Phantom 4, you must using a RC without the screen, then you can connect the RC externally with an Android device.
2. Swipe down the M300's RC manual and you can find an USB symbol on top right corner, make sure you are using the host. Then you can connect to the external device. Or you can just install your MSDK Sample inside the M300 RC. I suspect you are meeting a physical connection problem because you have successfully registered the MSDK.

**Comment by Salabda** [comment]
I'm using the Phantom 4 without an external screen. This problem only occurs with the 4.16. version. 
I 'm planning to build an android app, so I need to use the phone with M300 RTK.

**Comment by DJI-William** [comment]
When the cable is connected, have you seen a window pops up and ask you to select the app? Please select your Sample app and the sample will automatically pops up and register. If you have linked the RC with the aircraft and the aircraft is switched on, the open button should be enabled.

**Comment by Salabda** [comment]
It worked when I plug the controller and the phone to be before registering the app.
But it only worked on one phone (vivo x70 pro plus) on the other one(Samsung galaxy j8) the app is unstable.
