### ISSUE TITLE
No addExecutionListener and No addUploadListener Found in SDK

### ISSUE THREAD

**Issue by jayakrishnan1236** [dji-sdk/Mobile-SDK-Android#119]
The documentation in [uploadMission ](https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=upload%20mission&i=0&#djiwaypointmissionoperator_uploadmission_inline)  of WaypointMissionOperator says there is a method `addUploadListener()` to check the progress of upload. but i did not find any in the documentation search.
And also in the [startMission ](https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=startmission&i=4&#djiwaypointmissionoperator_startmission_inline) of the WaypointMissionOperator  says there is `addExecutionListener()` i did not find it either .

**Comment by oliverou** [comment]
Hi @jayakrishnan1236, thanks for your feedbacks. We have fixed the documentation issues you mention, please check them again: <https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=uploadmi&i=0&#djiwaypointmissionoperator_uploadmission_inline>.
