### ISSUE TITLE
Mavic Air 2: `setVideoResolutionAndFrameRate` does not work

### ISSUE THREAD

**Issue by gianlu33** [dji-sdk/Mobile-SDK-Android#1190]
Hi, 

I cannot set any video resolution settings using `setVideoResolutionAndFrameRate` on my Mavic Air 2. I keep getting the error: `Code: 255 Description: Not supported by current firmware.` 

I tried many combinations of resolution and frame rate but nothing.

I have the latest firmware version and SDK version (4.16.2).

**Comment by DJI-William** [comment]
Please read this article and try, [How to set the video resolution of camera?](https://sdk-forum.dji.net/hc/en-us/articles/4402129635993-How-to-set-the-video-resolution-of-camera-)

**Comment by gianlu33** [comment]
Solved, the problem was that I was setting an unsupported combination of resolution and frame rate.

Thank you!
