### ISSUE TITLE
Don't connect the drone when drone is fly first time

### ISSUE THREAD

**Issue by vancuong0429** [dji-sdk/Mobile-SDK-Android#1195]
Do I need to be active on the official app before it works?
I see the docs note: 
Any new product will need to be activated through DJI GO/DJI GO 4 before being used for the first time. DJI GO 4 is available on the [iOS App Store](https://apps.apple.com/us/app/dji-go/id943780750) and [Google Store](https://play.google.com/store/apps/details?id=dji.go.v4&hl=en) and can be used to activate a product.

**Comment by DJI-William** [comment]
All brand new aircraft needs to connect to the official app at the very first time to activate it, then you can use the 3rd party app to fly without any restrictions.
