### ISSUE TITLE
Diff. in behaviours of sendFlightControlData between Angle and Parstance yaw control

### ISSUE THREAD

**Issue by y22ma** [dji-sdk/Mobile-SDK-Android#12]
I'm using sendFlightControlData in my application, and observe the following behaviour:
1) In Parstance yaw control mode, when I send in zero as roll and pitch for sendFlightControlData call, the drone parks itself in position hold, while

2) in Angle yaw control mode, when I send in zero as roll and pitch for sendFlightControlData call, the drone fails to position hold

Just wondering if this is expected?

**Comment by SilverChangjian** [comment]
Yes, in angle mode, there will be no attitude adjustment provided by the flight controller, so the position might not hold if it is windy.

**Comment by y22ma** [comment]
@SilverChangjian ah that's good to know. Just wondering what the reason is behind not offering attitude adjustment in yaw angle mode? It seems to be valuable regardless of the yaw control mode.

**Comment by SilverChangjian** [comment]
Please use the latest SDK for your project, we are not going to support the 2.x version of the SDK. You could use sendVirtualStickData of flight controller in Mobile SDK 3.0.
