### ISSUE TITLE
onExecutionUpdate is not getting called. WaypointMissionState doesnt Change.

### ISSUE THREAD

**Issue by jayakrishnan1236** [dji-sdk/Mobile-SDK-Android#120]
```
private WaypointMissionOperatorListener waypointMissionOperatorListener = new WaypointMissionOperatorListener() {
        @Override
        public void onDownloadUpdate(@NonNull WaypointMissionDownloadEvent waypointMissionDownloadEvent) {
            droneCallback.onError("onDownloadUpdate");
            Timber.e("onDownloadUpdate");
        }

        @Override
        public void onUploadUpdate(@NonNull WaypointMissionUploadEvent waypointMissionUploadEvent) {
            int uploadedIndex = waypointMissionUploadEvent.getProgress().uploadedWaypointIndex;
                droneCallback.message("onUpdate : total :" + waypointsCount + ", uploadIndex : " + uploadedIndex);
            /*Timber.e("onUpdate : total :" + waypointsCount + ", uploadIndex : " + uploadedIndex);
            if (waypointsCount - 1 == uploadedIndex) {
                droneCallback.message("waypoints upload completed");
            }*/
        }

        @Override
        public void onExecutionUpdate(@NonNull WaypointMissionExecutionEvent waypointMissionExecutionEvent) {
            droneCallback.message("onExecutionUpdate");
        }

        @Override
        public void onExecutionStart() {
            droneCallback.message("on execution started");
        }

        @Override
        public void onExecutionFinish(@Nullable DJIError djiError) {
            droneCallback.message("on Execuation finish : " + (djiError != null ? djiError.getDescription() : "No error"));
        }
    }
```
using phantom 4 and android Nougat. The sdk is working fine but the onExecution update is never getting called after upload.
I am getting the upload progress of every waypoint in onUploadUpdate.
after upload, the `WaypointMissionState` is READY_TO_UPLOAD where as it was supposed to be READY_TO_EXECUTE.

here is additional code which shows how i am uploading the mission.
```
if (!uploadFlag) {
List<Waypoint> waypointList;
            WaypointMissionFinishedAction mFinishedAction = WaypointMissionFinishedAction.GO_HOME;
            WaypointMissionHeadingMode mHeadingMode = WaypointMissionHeadingMode.AUTO;

            WaypointMission.Builder waypointMissionBuilder = new WaypointMission.Builder()
                    .finishedAction(mFinishedAction)
                    .headingMode(mHeadingMode)
                    .autoFlightSpeed(droneSpeed)
                    .maxFlightSpeed(droneSpeed)
                    .flightPathMode(WaypointMissionFlightPathMode.NORMAL);

            waypointList = Stream.of(waypoints).map(latLng -> new Waypoint(latLng.latitude, latLng.longitude, droneAltitude)).toList();


            //waypointMissionBuilder.waypointList(new ArrayList<>(waypointList));

            /*for (Waypoint waypoint : waypointList) {
                waypointMissionBuilder.addWaypoint(waypoint);
            }*/

            waypointMissionBuilder.waypointList(waypointList).waypointCount(waypointList.size());

            for (Waypoint waypoint : waypointMissionBuilder.getWaypointList()) {
                waypoint.altitude = droneAltitude;
            }

            callback.onError("altitude " + droneAltitude);

            WaypointMission waypointMission = waypointMissionBuilder.build();

            DJIError djiError = getWaypointMissionOperator().loadMission(waypointMission);

            if (djiError == null) {
                getWaypointMissionOperator().addListener(waypointMissionOperatorListener);
                WaypointMissionState state = getWaypointMissionOperator().getCurrentState();
                if (state == WaypointMissionState.READY_TO_UPLOAD) {
                    getWaypointMissionOperator().uploadMission(new CommonCallbacks.CompletionCallback() {
                        @Override
                        public void onResult(DJIError djiError) {
                            callback.onError(getCurrentStateStr());
                            if (djiError == null) {
                                callback.message("uploading waypoints...");
                            } else {
                                callback.onError(djiError.getDescription());
                                getWaypointMissionOperator().retryUploadMission(null);
                            }
                        }
                    });
                } else {
                    droneCallback.message(getCurrentStateStr());
                }
            } else {
                callback.onError(djiError.getDescription());
            }
            uploadFlag = true;
} else {
            WaypointMissionState state = getWaypointMissionOperator().getCurrentState();
            if (state == WaypointMissionState.READY_TO_EXECUTE) {
                getWaypointMissionOperator().startMission(new CommonCallbacks.CompletionCallback() {
                    @Override
                    public void onResult(DJIError djiError) {
                        if (djiError == null) {
                            droneCallback.message("started Mission");
                        } else {
                            droneCallback.onError("start failed : " + djiError.getDescription());
                        }
                    }
                });
                uploadFlag = false;
            } else {
                droneCallback.message(getCurrentStateStr());
            }
        }
```

**Comment by jayakrishnan1236** [comment]
Okay, I was trying to upload around 80 way-points and that successfully happened but the `WaypointMissionState`  was not changing from `READY_TO_UPLOAD`  to `READ_TO_EXECUTE`. 
Now that i tried to upload only 30 waypoints and that worked . Dont know what is the problem but it keeps failing if i upload many waypoints (don't know the limit) .

**Comment by vascoV** [comment]
The SDK sucks a bit on Android especially Nugat!
Look I have developed something similar and your code looks fine! I don't think you have an issue with the code rather than the Android device! Sometimes it really bad with Android especially Nugat!

**Comment by miladehghani** [comment]
why the topic has been closed, this problem still exists.
everything was okay until I upgraded my firmware to the latest version, and I cant downgrade it!!
phantom 4 pro and 4
firmware:1.04.0602
android SDK: 4.2.1

**Comment by jayakrishnan1236** [comment]
Hai @miladehghani please make sure that you are using only one instance of `WaypointMissionOperatorListener`.

**Comment by DJI-RobertLiu** [comment]
On the Phantom4 
Firmware: 02.00.0106
I cannot see the problem to upload the 99 waypoints mission.  May we get more information to help locate the issue?  Such as how do you generate the waypoints which are valid? Is there any error information when you upload the waypoints?  If there is any error in the uploading, the current mission state will be changed to READY_TO_UPLOAD. Only all the waypoints are uploaded successfully to the aircraft, the current mission state is set to READY_TO_EXECUTE.

First, let's verify if all the 99 waypoints are valid waypoints which can be uploaded to aircraft.  Here I have a sample code which is used in my test app to help generate waypoint mission:
WaypointMission waypointMission = createRandomWaypointMission(99);

    private WaypointMission createRandomWaypointMission(int numberOfWaypoint) {
        WaypointMission.Builder builder = new WaypointMission.Builder();
        final double baseLatitude = (double) KeyManager.getInstance().getValue(FlightControllerKey.create(FlightControllerKey.AIRCRAFT_LOCATION_LATITUDE));
        final double baseLongitude = (double) KeyManager.getInstance().getValue(FlightControllerKey.create(FlightControllerKey.AIRCRAFT_LOCATION_LONGITUDE));
        final float baseAltitude = 50.0f;
        builder.autoFlightSpeed(5f);
        builder.maxFlightSpeed(10f);
        builder.setExitMissionOnRCSignalLostEnabled(false);
        builder.finishedAction(WaypointMissionFinishedAction.NO_ACTION);
        builder.flightPathMode(WaypointMissionFlightPathMode.NORMAL);
        builder.gotoFirstWaypointMode(WaypointMissionGotoWaypointMode.SAFELY);
        builder.headingMode(WaypointMissionHeadingMode.AUTO);
        builder.repeatTimes(1);
        Random randomGenerator = new Random(System.currentTimeMillis());
        List<Waypoint> waypointList = new ArrayList<>();
        for (int i = 0; i < numberOfWaypoint; i++) {
            final double variation = (Math.floor(i / 4) + 1) * 2 * ONE_METER_OFFSET;
            final float variationFloat = (float) (baseAltitude + (i + 1) * 2 * ONE_METER_OFFSET);
            final Waypoint eachWaypoint = new Waypoint(baseLatitude + variation * Math.pow(-1, i) * Math.pow(0, i % 2),
                                                       baseLongitude + variation * Math.pow(-1, (i + 1)) * Math.pow(0,
                                                                                                                    (i
                                                                                                                        + 1)
                                                                                                                        % 2),
                                                       variationFloat);
            waypointList.add(eachWaypoint);
        }
        builder.waypointList(waypointList).waypointCount(waypointList.size());
        return builder.build();
    }
Would you please have a try on this mission object which works fine in my testing.

Secondly, in the waypoint mission operator listener method: onUploadUpdate, could you print the error info in uploadEvent as below sample code: If there is the error in the upload, this error info will very helpful to investigate the issue.  Thanks!

        @Override
        public void onUploadUpdate(WaypointMissionUploadEvent uploadEvent) {
            final StringBuffer sb = new StringBuffer();
            if (uploadEvent.getProgress() != null
                && uploadEvent.getProgress().uploadedWaypointIndex == (uploadEvent.getProgress().totalWaypointCount
                - 1)) {
                showToast("Upload finished");
                sb.append("Upload finished successfully");
            } else {
                if (uploadEvent.getPreviousState() != null) {
                    sb.append("previousState: " + uploadEvent.getPreviousState().getName()).append("\n");
                }
                sb.append("currentState: " + uploadEvent.getCurrentState().getName()).append("\n");
                sb.append("UploadError: " + (uploadEvent.getError() == null
                                             ? "null"
                                             : uploadEvent.getError().getDescription())).append("\n");
                WaypointUploadProgress progress = uploadEvent.getProgress();
                if (progress != null) {
                    sb.append("UploadIsSummaryUploaded: " + progress.isSummaryUploaded).append("\n");
                    sb.append("Total: " + progress.totalWaypointCount).append("\n");
                    sb.append("UploadIndex: " + progress.uploadedWaypointIndex).append("\n");
                }
            }
            handler.post(new Runnable() {
                @Override
                public void run() {
                   // Please use your text view to show the text.
                    waypointMissionStateTextView.setText(sb.toString());
                }
            });
        }

Hope this can help and let us know once you get any new information.

**Comment by adarash** [comment]
I find solution for me. I check my waypoints and found thet distens betwenne two nearest points is less 1 meter. In this case WaypointMissionState doesnt Change to READY_TO_EXECUTE. When I remove this poin - it worked.
P.S. I spent looking for this error 10 hours.  UploadError: Always null. Checkparameters ALWAYS NULL. All place where posibility take error is null. Developers, whay this error is not displayed anywhere?

**Comment by talobin** [comment]
Will go ahead and close this issue.
If @jayakrishnan1236 still see problem using sample code @DJI-RobertLiu suggested, please re-open.
@miladehghani I would suggest to open a new issue and describe your problem more clearly.
I would also be easier for us to assist if you include a gist of your code using our sample app.
Thank you
