### ISSUE TITLE
Image Processing / Computer Vision with Android MSDK

### ISSUE THREAD

**Issue by kylenietfeld** [dji-sdk/Mobile-SDK-Android#1205]
Hello!
I am quite new to Android App development. I am looking to use a Mavic 2 Pro for an autonomous landing application so I to access the drone's camera. I have been looking through the Android API but I am still confused on the implementation. Is there a method to access the live frames of video or do I need to repeatedly take photos? 

I will need the camera in order to locate the landing pad (QR code, Aruco marker, etc). Any and all information is greatly appreciated!

**Comment by DJI-William** [comment]
From this sample, there is a demo to receive the live video stream data, you can get H.264 data from the provideTranscodeVideoFeed or YUV data from the setYuvDataCallback. You can also refer to the [live stream demo](https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample).
