### ISSUE TITLE
Mini 2 claims to support hybrid zoom but does not

### ISSUE THREAD

**Issue by petered** [dji-sdk/Mobile-SDK-Android#1206]
Ok 4.16.4, with Mini2, `product.camera.isHybridZoomSupported==true`

You can even get the hybrid zoom spec with `product.camera.getHybridZoomSpec`. 

But when you try to set the zoom with 
```
product.camera.setHybridZoomFocalLength(it.maxHybridFocalLength){log("Set hybrid zoom - error?: $it")}
```

You get an error.  

Digital zoom works fine.

It would be better if `product.camera.isHybridZoomSupported` returned `false`.  Right now I just use
```
isHybridZoom by lazy{product.camera.isHybridZoomSupported && product.model.name != "DJI_MINI_2"}
```

**Comment by DJI-William** [comment]
Just keep using the digital zoom for Mini 2, leave the hybrid zoom.
