### ISSUE TITLE
The parameter "waypoint.shootPhotoTimeInterval" seems to have been floored.

### ISSUE THREAD

**Issue by GIS-HowardZhang** [dji-sdk/Mobile-SDK-Android#121]
Hi, 

As we can see from logs below, the value of parameter "waypoint.shootPhotoTimeInterval" is a float number 2.7803571. But the real time interval between two photos is about 2.0±0.1 seconds, definitely not the  2.7803571. 

And I also did another test. When I set "waypoint.shootPhotoTimeInterval = 3.8*****", real exposure time interval of camera is about 3.0±0.1 seconds. It seems that the method "Math.floor(*)" is being used. Sometimes it is a big disparity for accurate task. 

Looking forward to your reply asap!

-logcat:
06-15 10:28:09.019 10907-10907/cn.******: waypoint.shootPhotoTimeInterval = 2.7803571
06-15 10:29:46.493 10907-11082/cn.******: Photo index = 0
06-15 10:29:48.479 10907-11082/cn.******: Photo index = 1
06-15 10:29:50.481 10907-11082/cn.******: Photo index = 2
06-15 10:29:52.495 10907-11082/cn.******: Photo index = 3
06-15 10:29:54.583 10907-11082/cn.******: Photo index = 4
06-15 10:29:56.485 10907-11082/cn.******: Photo index = 5
06-15 10:29:58.514 10907-11082/cn.******: Photo index = 6
06-15 10:30:00.485 10907-11082/cn.******: Photo index = 7
06-15 10:30:02.490 10907-11082/cn.******: Photo index = 8
06-15 10:30:04.488 10907-11082/cn.******: Photo index = 9

-  DJI Android SDK 4.1.1
- Mavic Pro
- Android 7.0.
- Huawei M3 Pad
- Android Studio 2.3.3

**Comment by DJI-RobertLiu** [comment]
Thanks for the report! We got this bug in SDK4.3.2.  The fix on it will be available in our next release.

**Comment by talobin** [comment]
@GIS-HowardZhang This should be fixed in 4.4.1.
Please try out.
