### ISSUE TITLE
Android MSDK running on iOS?

### ISSUE THREAD

**Issue by LukasBujnak** [dji-sdk/Mobile-SDK-Android#1210]
Hi, so i googled for a few hours and I’m not still sure if it is possible. I red about a lot of cross-platform development libraries, like Flutter, Xamarin,… but yet, I couldn’t find one, in which you can write in Java/Kotlin as it is in Android Studio nd probably whole MSDK is written in Java.

Is there any way or do you know any to run the newest MSDK 5.0 on iOS through cross platform? Thanks for any ideas.

**Comment by DJI-William** [comment]
Sorry you can't run Android app on iOS platform. The iOS MSDK development has been suspended. I would suggest you consider using Android MSDK instead.

**Comment by LukasBujnak** [comment]
You can find my solution at https://github.com/dji-sdk/Mobile-SDK-iOS/issues/543
