### ISSUE TITLE
DJI Mini 2 SE Support?

### ISSUE THREAD

**Issue by dineshkandan** [dji-sdk/Mobile-SDK-Android#1211]
DJI Mini 2 SE model be supported by the SDK? planning to buy this .Please guide me
https://www.dji.com/mini-2-se

**Comment by DJI-William** [comment]
There is no plan to support the DJI Mini 2 SE, please read this article. [What is the plan for the consumer level aircraft?](https://sdk-forum.dji.net/hc/en-us/articles/8818033368857-What-is-the-plan-for-the-consumer-level-aircraft-)
