### ISSUE TITLE
DJI Air 2S Support wifi ?

### ISSUE THREAD

**Issue by dineshkandan** [dji-sdk/Mobile-SDK-Android#1217]
I have bought DJI Air 2S https://www.dji.com/air-2s?site=brandsite&from=nav . Kindly help me connect without RC .i need to connect with WIFI directly to smartphone and access SDK

**Comment by DJI-William** [comment]
You cannot use smarphone to direcly control the aircraft. The WiFi connection only exists in ancient models such as Mavic Air.
