### ISSUE TITLE
getPrimaryVideoFeed / provideTranscodedVideoFeed listeners don't return data

### ISSUE THREAD

**Issue by lmarz** [dji-sdk/Mobile-SDK-Android#1226]
After connecting to the M2EA drone, I call:
```java
VideoFeeder.getInstance().getPrimaryVideoFeed().addVideoDataListener((data, size) -> {
    Log.i("video feed", "received " + String.valueOf(size) + " bytes of data");
    ...
});
```
but this callback never gets called. I don't do anything else with the camera or the video feed. Is there any setup I have to do, before I can receive the video feed?

**Comment by DJI-William** [comment]
For Mavic 2 series, you need to use provideTranscodedVideoFeed instead of the getPrimaryVideoFeed.

**Comment by DJI-William** [comment]
Could you try the sample on this github? What is the result?

**Comment by lmarz** [comment]
The sample app gives blackscreens in the live feed view. The Video Feed from the Pilot App works.
I've tried to create the most minimal test app here: https://github.com/lmarz/streamtest
The relevant code is in [MainActivity](https://github.com/lmarz/streamtest/blob/master/src/main/java/org/lmarz/streamtest/MainActivity.java)

**Comment by brien-crean** [comment]
I wonder if this is related to the Android device you are running? Some other users have had issues with some newer Android devices - Google Pixel 5A, Pixel 6A, Pixel 7(Not Pro), Samsung Tab S7 FE, Samsung A53 and Samsung S22.

What Android are you using @lmarz?

@dji-dev @DJI-William is there a planned release date for a new msdk v4 for Android to resolve the black screen issue.

Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/81348'>Zendesk ticket #81348</a>:<br><br>Can you record a video using this demo to give us further insight into this issue?
You can upload the video to this link：https://pan-sec.djicorp.com/s/St7Zz3PMGoY5nkY
<br><p><em><small>°°°</small></em></p>

**Comment by lmarz** [comment]
I have uploaded the video. I also included the log of me opening the LiveFeedView

**Comment by lmarz** [comment]
Found the issue. I just wasn't including the anti distortion library

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/81348'>Zendesk ticket #81348</a>:<br><br>You're welcome
<br><p><em><small>°°°</small></em></p>
