### ISSUE TITLE
Always got crash of the first tutorial

### ISSUE THREAD

**Issue by caucycaucy** [dji-sdk/Mobile-SDK-Android#123]
Hi Guys,

  I've realized the first tutorial of DJI SDK <<**Integrate SDK into Application**>>(https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html#android-studio-project-integration)
However, I always got crash when ImportSDKDemo started up in simulator. My dev environment lists here:
Android Studio: 2.3.3
DJI Android SDK version: Android_Mobile_SDK_4.0.2_170510
PC OS: Windows 8.1

  When I dev this tutorial in Android Studio 2.3.3, there will some compiling errors, such as: roundIcon, layout_constraint, and another problem is **buildToolsVersion** can not be lower than **25.0.0**. After fixing them one by one, I always got crash after **OnCreate** calling in MainActivity.

protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    //Initialize DJI SDK Manager
    mHandler = new Handler(Looper.getMainLooper());
    DJISDKManager.getInstance().registerApp(this, mDJISDKManagerCallback);
}
If I comment the last line DJISDKManager.getInstance().registerApp(this, mDJISDKManagerCallback);
the programe runs okay.
Any suggestion is welcome. 
(The app code has been inserted in android:value="e****7" of AndroidManifest.xml.)

Thanks in advance.

Ding

**Comment by oliverou** [comment]
Hi @caucycaucy, the [Integrate SDK into Application](https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html#android-studio-project-integration) has been updated to Android SDK 4.1.1, could you try to clone the latest version of the demo from here: <https://github.com/DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio> and try again? Also, have you try to use Android device for testing instead of Android Studio simulator?

**Comment by caucycaucy** [comment]
Hi Oliverou,

  Thank you very much for your so quick reply. I read the code from your link and copy the following code to my project.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            ActivityCompat.requestPermissions(this,
                    new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.VIBRATE,
                            Manifest.permission.INTERNET, Manifest.permission.ACCESS_WIFI_STATE,
                            Manifest.permission.WAKE_LOCK, Manifest.permission.ACCESS_COARSE_LOCATION,
                            Manifest.permission.ACCESS_NETWORK_STATE, Manifest.permission.ACCESS_FINE_LOCATION,
                            Manifest.permission.CHANGE_WIFI_STATE, Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS,
                            Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.SYSTEM_ALERT_WINDOW,
                            Manifest.permission.READ_PHONE_STATE,
                    }
                    , 1);
        }
  And after importing more packages for the code above, my app run successfully in the simulator now.
  However, if I open the project cloned from your link, and run it in the simulator, I got the same crash.
It's so werid. 
  Anywary, thanks for your information.

Ding

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already with our latest tutorial.
Please feel free to reopen if the problem still exists.
Thanks!
