### ISSUE TITLE
Will I able to land the drone using this SDK to a target area? 

### ISSUE THREAD

**Issue by BillCai06** [dji-sdk/Mobile-SDK-Android#1231]
Hi, Just a quick question,
I want to build a autonomous landing for the DJI Mavic 3 Enterprise Series and I don't know here to start. If I want to land the drone on a marked area, will I able to do it though this SDK? I'm new to android development if someone could point to some resources it would be great.

**Comment by BillCai06** [comment]
Thank you, I will try it out.

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/83328'>Zendesk ticket #83328</a>:<br><br>You're welcome. Hope you can solve the problem as soon as possible
<br><p><em><small>°°°</small></em></p>
