### ISSUE TITLE
FlightController startGoHome - Execution of this process has timed out

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android#1234]
When trying to execute `startGoHome` I get the error `Execution of this process has timed out` with a DJI Mini 2. 

I tried via the Keymanager also but got the same result. See code examples below. I also tried this with a Mavic Pro and it worked just fine. So this seems to be specific to the Mini 2?

```java
DJIKey rthKey = FlightControllerKey.create(FlightControllerKey.START_GO_HOME);
DJISDKManager.getInstance().getKeyManager().performAction(rthKey, new ActionCallback() {
    @Override
    public void onSuccess() {
        Log.d("DEBUG", "SUCCESS STARTING RTH!");
     }

    @Override
    public void onFailure(@NonNull DJIError djiError) {
        Log.d("DEBUG", "ERROR STARTING RTH! " + djiError.getDescription());
        promise.reject(new Exception(djiError.getDescription()));
    }

Aircraft aircraft = (Aircraft) DJISDKManager.getInstance().getProduct();
FlightController fc = aircraft.getFlightController();
fc.startGoHome(djiError -> {
    if (djiError != null) {
        Log.d("DEBUG", "ERROR STARTING RTH! " + djiError.getDescription());
});
```

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/85094'>Zendesk ticket #85094</a>:<br><br>Can it be assumed that the error message always appears when calling startGoHome under any circumstance? Also, does the aircraft perform the corresponding action after calling startGoHome?
<br><p><em><small>°°°</small></em></p>

**Comment by brien-crean** [comment]
Yes, the error always appears when calling startGoHome under any circumstances with the Mini 2. The error appears almost immediately too. The remote controller beeps once as if its about to start returning to home but then stops beeping, the error appears and the drone **_does not_** return home.

**Comment by brien-crean** [comment]
Ah I see, thank you for clarifying! That information is very much appreciated
