### ISSUE TITLE
Unabe to enable virtual sticks for Mavic 2 Pro when upwards infrared sensor detects obtacles

### ISSUE THREAD

**Issue by naiveHobo** [dji-sdk/Mobile-SDK-Android#1236]
I'm using the DJI Mobile SDK v4.16.4 to control a Mavic 2 Pro using virtual sticks from a custom app. After taking off, if the upward infrared sensor detects an obstacle overhead the drone, I'm unable to enable the virtual stick even after the overhead obstacle has been cleared and the drone is able to move upwards.

When the drone takes off in clear space without any overhead obstacles, the virtual sticks are enabled without an issues. Is there something I'm missing here? Is there a way to turn off the upward infrared sensor? I can see the function `setUpwardVisionObstacleAvoidanceEnabled` in the flight assistant class but it refers to the upward vision sensor.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/86305'>Zendesk ticket #86305</a>:<br><br>The infrared sensor cannot be turned off. The setUpwardVisionObstacleAvoidanceEnabled controls the visual system.

I placed the cover on the Mavic 2 Pro and was able to open the virtual joystick normally when taking off with the simulator. Could you please record a video for us to confirm how to trigger this issue? Here is the upload address.：https://pan-sec.djicorp.com/s/JjiFTr4dwMjMW5j
<br><p><em><small>°°°</small></em></p>
