### ISSUE TITLE
Previous SDK support lifespan

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#124]
How long are previous SDK versions supported?

I know there's some level of compatibility required between device firmware and software versions. 

If a developer is using SDK 3.5.X and hasn't upgraded yet
- how long will installations be compatible?
- if newer firmware updates are incompatible with older SDK versions, will we be notified when we need to update to newer versions of the SDK (such as migrating from 3.5 to 4.0?)

**Comment by oliverou** [comment]
Hi @jtuchek , we used to send an EDM email to all of our developers before, I put it here for you to check again, thanks!

![edm](https://user-images.githubusercontent.com/13310805/27619996-0efc0476-5bf9-11e7-9c54-3649449fe32e.png)

**Comment by jtuchek** [comment]
Hi @oliverou thanks for the reply, although I feel like this isn't exactly the answer needed.

Outside of activation requirements and location requirements - is there a timeline for how long new firmware released for say a DJI Phantom 4 will be compatible/controllable from an application using 3.5.x? Or all all future firmware releases exclusively supporting only 4.x SDK releases?

**Comment by oliverou** [comment]
Hi @jtuchek, firmwares released after June, will not be compatible with applications using SDK lower than 4.1 after July 1st.
