### ISSUE TITLE
 Native method not found: dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString:()Ljava/lang/String;

### ISSUE THREAD

**Issue by qqwoshiwuli** [dji-sdk/Mobile-SDK-Android#125]
java.lang.UnsatisfiedLinkError: Native method not found: dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString:()Ljava/lang/String;

I have entered key, but I can't access APP，why?

**Comment by Nitaym** [comment]
Hi,

(Not a DJI employee)
This problem usually happens when your app is compiled with a different SDK
level than the DJI SDK.
Check your build.gradle files in both the DJI SDK project and your app and
verify that compileSdkVersion, targetSdkVersion are set to the same value
in both projects.

(As a best practice, start with setting it to 22 in order to avoid
explicitly asking for permissions)

Good luck
Nitay

**Comment by oliverou** [comment]
Hi @qqwoshiwuli, please provide the following infos for us to investigate your issue:

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

Thanks!

**Comment by qqwoshiwuli** [comment]
Hi @oliverou Thanks for the answer
1.•DJI Android SDK 4.1.1.  
2.MAVIC PRO
3.android 4.4.4 API19
4.HUAWEI Che-CL10
5.android 2.2.2
 classpath 'com.android.tools.build:gradle:2.2.2'
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
        applicationId "com.dji.sdk.sample"
        minSdkVersion 17
        targetSdkVersion 23
Thanks!

**Comment by qiuyudong** [comment]
Hi @qqwoshiwuli I get the same question and try to change android SDK version,but it doesn't work.
And I try another mobile device,it works. Maybe just the problem of mobile devive.
Hope to help you

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
