### ISSUE TITLE
Drone does not respond to RC retaking control

### ISSUE THREAD

**Issue by danilofariadutra** [dji-sdk/Mobile-SDK-Android#1254]
We had a problem on a flight carried out by SDK ROS Onboard, where the drone did not give control to the RC when changing the type of flight.
In this situation, the drone's battery was depleted and the drone gradually fell, eventually crashing.
A similar situation has occurred in the past, with the firmware changing to versions above V03.00.0101.
In fact, when we updated to version V57.01.0001, available in DJI Assistant 2 (Enterprise Series), the drone's RC control itself was not synchronized with the drone.
Could you check what could have caused this problem?

Versions in DJI Assistant 2 (Entreprise Series)
![dji](https://github.com/dji-sdk/Mobile-SDK-Android/assets/48124432/66b80974-5048-4729-b972-8e1b851ff119)

Flight Graphic
![flight](https://github.com/dji-sdk/Mobile-SDK-Android/assets/48124432/eef37f25-ddaf-4b91-9c2a-18e7af1b5b7d)

Rosout (Flight Log)
[rosout1.zip](https://github.com/dji-sdk/Mobile-SDK-Android/files/13204598/rosout1.zip)

**Comment by dji-dev** [comment]
Agent comment from xiaorong.zheng in <a href='https://djisdksupport.zendesk.com/agent/tickets/93800'>Zendesk ticket #93800</a>:<br><br>Can I ask what aircraft firmware version you are using,  since the V57.01.0001 firmware needs to be used with RC Plus.
<br><p><em><small>°°°</small></em></p>

**Comment by danilofariadutra** [comment]
Firmware: 07.00.0100

**Comment by dji-dev** [comment]
Agent comment from xiaorong.zheng in <a href='https://djisdksupport.zendesk.com/agent/tickets/93800'>Zendesk ticket #93800</a>:<br><br>We noticed that you have sent us the bill of lading, and we will track the issue in the work order.
<br><p><em><small>°°°</small></em></p>

**Comment by danilofariadutra** [comment]
For those who may have faced the same problem, it has to do with Multiple Flight Mode. To avoid the problem, Multiple Flight Mode must be enabled. If the problem occurs in flight, simply enable it.
