### ISSUE TITLE
Focus values

### ISSUE THREAD

**Issue by danilofariadutra** [dji-sdk/Mobile-SDK-Android#1257]
For the Zenmuse P1 camera, is there any logic to the focus values?
By how many centimeters/meters do the values ​​vary?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/95001'>Zendesk ticket #95001</a>:<br><br>I guess you are referring to the distance the focus changes when the Focus Ring value changes during manual focusing. I apologize, but we do not have this parameter as it depends on the shooting environment.
<br><p><em><small>°°°</small></em></p>

**Comment by danilofariadutra** [comment]
According to DJI, there is no valid logic to automatically acquire the manual focus values ​​of the P1 Zenmuse camera.
So, for this problem, we did a study with captures from 1 meter to 3 meters away, capturing numbers from a measuring tape. We varied every 10 cm, and captured 2 to 3 images, with different focus values ​​between them.
Below are the values ​​with the results of the study carried out. I hope to help you

1.0m = 1740 (better) || 1707
1.1m = 1548 (better || 1436
1.2m = 1461 (better) || 1437
1.3m = 1366 (better) || 1337
1.4m = 1202 || 1256 (any value is ok)
1.5m = 1125 || 1187 (any value is ok)
1.6m = 1087 || 1143 (better)
1.7m = 983 || 1075 (better) || 1027
1.8m = 929 (bad value) || 939 || 957 (the other two, any value is ok)
1.9m = 966 || 1005 || 1058 (better)
2.0m = 1080 || 1093 || 1100 (any value is ok)
2.1m = 955 || 970 || 1008 (any value is ok)
2.2m = 946 (better) || 912 || 899
2.3m = 937 (better) || 928 || 912
2.4m = 926 (better) || 935 || 920
2.5m = 926 || 915 || 906 (any value is ok)
2.6m = 913 || 930 || 899 (any value is ok)
2.7m = 904 || 892 || 883 (any value is ok)
2.8m = 874 || 892 || 883 (any value is ok)
2.9m = 883 || 872 || 861 (any value is ok)
3.0m = 873 (bad) || 861 || 850 (the other two, any value is ok)
