### ISSUE TITLE
Capture button not working

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android#1259]
I have integrated this SDK in my project .. all the functionalities are working fine but hardware capture button not working. is there any solution?

**Comment by Vickyxdev** [comment]
DJI Mavic 2 Smart Controller
![Media (1)](https://github.com/dji-sdk/Mobile-SDK-Android/assets/40540336/08147c4f-5183-45ba-9297-d284c8e05c53)
![Media](https://github.com/dji-sdk/Mobile-SDK-Android/assets/40540336/997fa1df-ba4d-445b-861d-e78f4406683e)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99096'>Zendesk ticket #99096</a>:<br><br>You can refer to this article to learn about the solution：https://sdk-forum.dji.net/hc/en-us/articles/4404550341657
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Thanks a lot ...

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99096'>Zendesk ticket #99096</a>:<br><br>Is this method effective for you?
<br><p><em><small>°°°</small></em></p>
