### ISSUE TITLE
Remote Control signal the same as the control

### ISSUE THREAD

**Issue by danilofariadutra** [dji-sdk/Mobile-SDK-Android#1267]
How can I acquire the signal information from the remote control to the drone, just as it exists on the drone's remote control?
The drone used is the Matrice 300 RTK.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/102606'>Zendesk ticket #102606</a>:<br><br>I'm sorry, I'm having a bit of trouble understanding your question.
What is the purpose of you obtaining signal information? Are you looking to diagnose the signal quality between the remote control and the aircraft?
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
Thank you for your response. I understand what you need now. If you are using Mobile SDK V5, you can use AirLinkKey.KeyUpLinkQualityRaw to obtain the signal quality between the remote controller and the aircraft.

**Comment by danilofariadutra** [comment]
We currently use version 4.16.2. This method does not exist in this SDK version, however, I believe I managed it with the following code:

Is correct?

 AirLink airLink = DJISDKManager.getInstance().getProduct().getAirLink();
        // RC to Aircraft (predominantly control information)
        airLink.setUplinkSignalQualityCallback(new SignalQualityCallback() {
            @Override
            public void onUpdate(int intensity) {
//                showToast(String.format("RC to Aircraft: %d", intensity));
                    }
                });
            }
        });

        // Aircraft to RC (predominantly video information)
        airLink.setDownlinkSignalQualityCallback(new SignalQualityCallback() {
            @Override
            public void onUpdate(int i) {
//                showToast(String.format("Aircraft to RC: %d", i));
            }
        });

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/102606'>Zendesk ticket #102606</a>:<br><br> Your usage is correct. The `setUplinkSignalQualityCallback` is used to set up a listener for the signal quality between the remote controller and the aircraft.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/102606'>Zendesk ticket #102606</a>:<br><br>Your usage is correct. `UplinkSignalQualityCallback` can be seen as monitoring the signal quality of the remote controller, while `sDownlinkSignalQualityCallback` can be seen as monitoring the signal quality of the image transmission, that is, the signal quality of the camera video transmission channel.
<br><p><em><small>°°°</small></em></p>
