### ISSUE TITLE
Set Gimble pitch

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android#1268]
How to set gimble pitch without adding this code:
                waypoint.addAction(new WaypointAction(WaypointActionType.GIMBAL_PITCH, -90));

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/103086'>Zendesk ticket #103086</a>:<br><br>You mentioned the code is the method to set the gimbal rotation in the waypoint mission. Are you implying that you do not want to rotate the gimbal in the waypoint mission?
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Actually, i want to set my gimble -90 degree for my mission..

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/103086'>Zendesk ticket #103086</a>:<br><br>During the flight of the wayline mission, you can also use Gimbal.rotate to rotate the gimbal. However, please be careful not to conflict the gimbal rotation with waypoint actions.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
ok thanks
