### ISSUE TITLE
CRASH ANDROID 14 - One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by GiangGiang11051999** [dji-sdk/Mobile-SDK-Android#1272]
Hello team, 

I use DJI-SDK to connect aircraft. But my app was crashed when it register app in class DJISDKManager. Issue detail in logcat below as: 

![Screenshot 2024-03-28 at 09 39 17](https://github.com/dji-sdk/Mobile-SDK-Android/assets/121371676/94476cf2-3ef3-4659-9807-436d84adcddc)
![Screenshot 2024-03-28 at 09 38 58](https://github.com/dji-sdk/Mobile-SDK-Android/assets/121371676/c283ce87-94c5-4ded-a688-7f57ed006a10)

I think DJI-SDK not compatible with Android 14. I wish DJI-SDK can support smooth for us app. Please check context.registerReceiver and update your code. 

Thank team so much! I hope receive answer from your team early.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103762'>Zendesk ticket #103762</a>:<br><br>The Mobile SDK is indeed not compatible with Android 14.
Could you please confirm if changing the TargetSDKVersion to 33 will still result in a crash?
<br><p><em><small>°°°</small></em></p>

**Comment by letsmeetutsav** [comment]
yes even i have downgraded my target to Android 11 its crashes in Android 14 Devices.

**Comment by GiangGiang11051999** [comment]
Thank you team supported!
