### ISSUE TITLE
[Support] Advanced Pilot Assistance System (APAS)

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1274]
How to implement function: Advanced Pilot Assistance System (APAS)?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103864'>Zendesk ticket #103864</a>:<br><br>The FlightController.setMaxFlightHeight function can be used to define the maximum flight height of the aircraft. Typically, the maximum height for the aircraft is set at 500 meters.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103864'>Zendesk ticket #103864</a>:<br><br>You can also set the maximum horizontal distance. However, the horizontal distance limit feature can be turned off. After turning it off, the aircraft will move horizontally up to the maximum transmission distance between the remote controller and the aircraft in the current environment.
https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_FlightController_FlightControllerKey.html?search=keydistancelimitenabled&i=0&#key_flightcontroller_distancelimitenabled_inline
https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_FlightController_FlightControllerKey.html?search=keydistancelimitenabled&i=0&#key_flightcontroller_distancelimitenabled_inline
https://developer.dji.com/api-reference-v5/android-api/Components/IKeyManager/Key_FlightController_FlightControllerKey.html?search=keydistancelimitenabled&i=0&#key_flightcontroller_distancelimit_inline
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev thank you so much, but I used SDK V4

**Comment by dji-lyt** [comment]
Here is the corresponding interface for MSDK V4:https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html#djiflightlimitation_setmaxflightheight_inline
![image](https://github.com/dji-sdk/Mobile-SDK-Android/assets/104296295/e4c5c01c-2a91-4293-9221-992ec9baf9b6)
