### ISSUE TITLE
Get radar from BaseProduct is null

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1278]
![Screenshot 2024-04-01 at 15 14 29](https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/1a1e4e9c-6701-4f7e-b9e9-36196a7f5b94)
I used to update radar obstacle avoidance status, but radar variable returned null.
Please help me check it

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104011'>Zendesk ticket #104011</a>:<br><br>Could you provide the model of the drone you are using and confirm if it is equipped with a radar?
Would you be able to take a photo for us?
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104011'>Zendesk ticket #104011</a>:<br><br>If you cannot get the radar instance, it means that the aircraft's current state does not support the Radar. The radar usually refers to the millimeter-wave radar installed on the M300 RTK.
If you need to obtain obstacle data detected by the sensor, you can use the interface provided in this article to retrieve it：https://sdk-forum.dji.net/hc/en-us/articles/4418315942169-How-to-get-the-visual-obstacle-avoidance-data
<br><p><em><small>°°°</small></em></p>
