### ISSUE TITLE
Spotlight / object selection support

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1281]
![Screenshot 2024-04-04 at 16 32 56](https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/df9ecc34-b811-40ae-8701-411401448864)
Any widget to support spotlight focus?
When I select an object on screen (by drawing on the screen) so drone camera will move like the object move.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104275'>Zendesk ticket #104275</a>:<br><br>There is no similar widget in UXSDK now. It requires you to develop and implement it based on the Mobile SDK.
<br><p><em><small>°°°</small></em></p>
