### ISSUE TITLE
Gimbal mode

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1283]
```
val gimbal = DJISDKManager.getInstance().product?.gimbal
// Check if Gimbal is available
if (gimbal != null) {
    val gimbalMode = GimbalMode.FPV // Set the desired gimbal mode
    // Set the mode of the gimbal
    gimbal.setMode(gimbalMode){}
}
```
I used the above code to implement update gimbal mode.
But how to check the current gimbal mode for the next time open the application?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104489'>Zendesk ticket #104489</a>:<br><br>The setStateCallback can be used to set up a status listener for the gimbal. The listener will continuously push updates on the gimbal status, which includes the gimbal mode.
https://developer.dji.com/api-reference/android-api/Components/Gimbal/DJIGimbal_GimbalState.html#djigimbal_gimbalstate_workmode_inline
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
I got error when set gimbal mode: Execution of this process has timed out

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104489'>Zendesk ticket #104489</a>:<br><br>Could this error occur consistently? Under what circumstances does this error typically occur?
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
![Screenshot 2024-04-26 at 11 46 10](https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/9c534f23-ab03-4a9f-9a98-9a851cb3f960)
This is the code I implemented this feature, please help me check it.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104489'>Zendesk ticket #104489</a>:<br><br>The code is not error, but the gimbal mode may vary for different aircraft.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
How to check the gimbal mode for each aircraft?
My drone is: Air 2s

**Comment by dji-lyt** [comment]
Most aircraft support FPV and Yaw_Follow modes, with enterprise series drones also offering Free mode as an additional feature.The DJI Air 2s you are using supports FPV and Yaw_Follow modes.
Do you encounter the same issue with your aircraft in the sample code as well?
![image](https://github.com/dji-sdk/Mobile-SDK-Android/assets/104296295/58335022-08e0-49ae-9289-075e11184c3c)

**Comment by huongta157** [comment]
@dji-lyt I run the sample code, but still show error message is: Execution of this process has timed out

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104489'>Zendesk ticket #104489</a>:<br><br>When you set the gimbal mode to YAW_FOLLOW, what is the current gimbal mode being used by the camera? Can you retrieve it using getMode? If the camera's current mode is YAW_FOLLOW, will setting it to FPV also result in the same error?

Could you please inform us of the MSDK version you are using?
<br><p><em><small>°°°</small></em></p>
