### ISSUE TITLE
Gimbal

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1284]
How to Allow Upward Gimbal Rotation and check if it is allowed or not? (get/set)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104490'>Zendesk ticket #104490</a>:<br><br>If you detect a upward  gimbal using the SDK, you can use the SDK to control its movement. The position of it can be obtained by using Gimbal.getIndex:https://developer.dji.com/api-reference/android-api/Components/BaseComponent/DJIBaseComponent.html#djibasecomponent_index_inline
<br><p><em><small>°°°</small></em></p>
