### ISSUE TITLE
Unit type

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1285]
I used UnitTypeWidget, but not support Metric (km)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104498'>Zendesk ticket #104498</a>:<br><br>UnitTypeWidget should support the meter unit. If it is not supported in your usage environment, could you please provide a screenshot?

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
<img width="474" alt="Screenshot 2024-04-09 at 18 38 56" src="https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/7db551b6-552d-4aab-908b-3d969e859340">
I want used kilometre (km) unit

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104498'>Zendesk ticket #104498</a>:<br><br>The UnitTypeWidget does not support the kilometer unit, and it cannot be modified again. Have you considered implementing your own unit widget? We have an open-source widget repository that offers the UnitModeListItemWidget, which has similar functionality to the UnitTypeWidget and can be modified based on it.
https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android
<br><p><em><small>°°°</small></em></p>
