### ISSUE TITLE
Aspect ratio can’t be change

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1288]
I can't change camera aspect ratio from 16:9 to 4:3
- Message error: Param Illegal
- Drone Model: Air 2s
Any idea? Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104584'>Zendesk ticket #104584</a>:<br><br>Could you please confirm if it is possible to set the camera aspect ratio to 4:3 on DJI Fly? I found information stating that Air 2s does not support 4:3. If DJI Fly does support setting the aspect ratio to 4:3, could you kindly provide us with an image showing how to do so?

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev Thank your for reply
How to check aspect ratio supported for each model?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104584'>Zendesk ticket #104584</a>:<br><br>The CameraKey.PHOTO_ASPECT_RATIO_RANGE can be used to retrieve the range of aspect ratios supported by the camera.
https://developer.dji.com/api-reference/android-api/Components/KeyManager/DJICameraKey.html#camerakey_photo_aspect_ratio_range_key
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev thank you so much

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104584'>Zendesk ticket #104584</a>:<br><br>I am glad to help you.
<br><p><em><small>°°°</small></em></p>
