### ISSUE TITLE
Delete media file

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1290]
<img width="633" alt="Screenshot 2024-04-12 at 16 37 10" src="https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/7decec53-c007-456e-aa0f-0f00500772b3">

I used this code to delete media files, response is success but the media not deleted the next time open app.
Please help me!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104952'>Zendesk ticket #104952</a>:<br><br>Could you please try switching the delete interface to execute on the main thread? If you still cannot delete the file, could you provide us with a method to reproduce this issue in the sample code?

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev I switched to IO thread and worked for me. Thank you so much.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104952'>Zendesk ticket #104952</a>:<br><br>I am glad that my response was helpful to you.
<br><p><em><small>°°°</small></em></p>
