### ISSUE TITLE
Safety assistance mode

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1291]
How to enable/disable Safety assistance mode?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104977'>Zendesk ticket #104977</a>:<br><br>What is the safety assistance mode you are referring to? Is it the mode where the drone can stop when encountering obstacles?
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
![2024-04-22 19 56 08](https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/a48b8110-d3cd-4d91-bf6c-c9a5a477a1e1)
I used official ios app, this is feature I want to implement

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104977'>Zendesk ticket #104977</a>:<br><br>Thank you for providing the screenshot. setForbidSideFlyEnable can be used to enable or disable side flying.
<br><p><em><small>°°°</small></em></p>
