### ISSUE TITLE
Total fight distance & fight time

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1292]
Have a function to support getting total fight distance and flight time?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105256'>Zendesk ticket #105256</a>:<br><br>Some models can get time and distance. You can refer to this article；https://sdk-forum.dji.net/hc/en-us/articles/7753552666649-How-to-get-the-flight-distance-flight-times-and-total-flight-time

The data obtained from this interface may differ from the data displayed on the official app.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev thank you so much

**Comment by huongta157** [comment]
@dji-dev I have a question
Have a function to support getting activated days?

**Comment by huongta157** [comment]
```
 val flightDistanceKey: DJIKey =
                FlightControllerKey.createFlightAssistantKey(FlightControllerKey.AIRCRAFT_TOTAL_FLIGHT_DISTANCE)
            val value = KeyManager.getInstance().getValue(flightDistanceKey)
```
Sorry @dji-dev  I used this code but the value returned to null. Can you help me?

**Comment by huongta157** [comment]
@dji-dev thanks
I try to call it on Main and IO thread but the result is still null.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105256'>Zendesk ticket #105256</a>:<br><br>Could you confirm if the model you are using supports obtaining AIRCRAFT_TOTAL_FLIGHT_DISTANCE? We mentioned in our previous communication that this key only works on the M300 and Mavic 2 Enterprise Advanced.

Thank you.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105256'>Zendesk ticket #105256</a>:<br><br>I am glad that I could help you.
<br><p><em><small>°°°</small></em></p>
