### ISSUE TITLE
[Help] State FetchMediaTaskScheduler is UNKNOWN 

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1293]
```
val task = FetchMediaTask(mediaFile, FetchMediaTaskContent.PREVIEW) { media, content, _ ->
            lifecycleScope.launch(Dispatchers.Main) {
                Glide.with(requireContext())
                    .load(media?.preview)
                    .into(binding.photoView)
                scheduler?.removeTask(media, content)
            }
        }
        Log.i(TAG, "handleDisplayPhotoView state: ${scheduler?.state}")
        scheduler?.moveTaskToEnd(task)
```
I used this code to get preview of photo, but scheduler state is UNKNOWN and not return result.
Please help me!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105552'>Zendesk ticket #105552</a>:<br><br>Could you provide me with a method to reproduce the scheduler state as UNKNOWN? Also, what is the model of the drone you are using?

Do you encounter the same issue when using the MSDK sample code?
<br><p><em><small>°°°</small></em></p>
