### ISSUE TITLE
FPVWidget issue

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1294]
I used FPVWidget to play a video media with landscape screen, video is playing normally but screen displayed is black  with the error:
`videoWidth=2240, videoHeight=1260, videoType=Ratio16X9, screenType=Ratio16X9`

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105554'>Zendesk ticket #105554</a>:<br><br>"videoWidth=2240, videoHeight=1260, videoType=Ratio16X9, screenType=Ratio16X9" does not seem to be an error message. If the screen is displaying black, have you confirmed if the camera is in playback mode? The FPVWidget needs to be set to display the main video channel's image.
<br><p><em><small>°°°</small></em></p>
