### ISSUE TITLE
Find my drone

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1296]
Any interface to support finding my drone?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105583'>Zendesk ticket #105583</a>:<br><br>What situation did you find your drone in? If the remote controller is properly connected to the aircraft, the SDK can retrieve the aircraft's location information and even make the drone emit sound.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
> the SDK can retrieve the aircraft's location information and even make the drone emit sound.

What is the interface or document to implement this?

**Comment by danilofariadutra** [comment]
If I'm right, you could use "
setESCBeepEnabled" by an object Flight Controller 

```
DJISampleApplication.getAircraftInstance().getFlightController().setESCBeepEnabled(true, djiError -> {
                // If you need to use a callback
            });
```

![image](https://github.com/dji-sdk/Mobile-SDK-Android/assets/48124432/f214bc5a-4745-466c-afd8-278c090e28c5)

For more instructions, you could use this page:

https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html?search=esc&i=6&#djiflightcontroller_setescbeepenabled_inline

**Comment by dji-lyt** [comment]
@danilofariadutra You are correct. This interface is used to make the drone emit sound.

The getAircraftLocation can get the location of drone.
https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController_DJIFlightControllerCurrentState.html#djiflightcontroller_djiflightcontrollercurrentstate_aircraftlocation_inline

**Comment by huongta157** [comment]
![photo_2024-04-24 08 43 29](https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/72f58d54-bf4f-446b-9147-825a4e24a572)
@dji-lyt @danilofariadutra 
This feature I want to implement.
So, how to get the aircraft location when not connected?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105583'>Zendesk ticket #105583</a>:<br><br>The SDK is unable to retrieve the aircraft's position when not connected to the aircraft. If Pilot 2 can display the aircraft icon without being connected to the aircraft, then Pilot 2 may have cached the location information from the last time it was connected to the aircraft.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev I think so, too. Thank you
