### ISSUE TITLE
[Help] Restricted Zone

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1298]
![2024-04-24 09 20 30](https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/c43438a1-6cba-49c4-b937-bcfede4b9be2)
I want to implement restricted zone feature (image from the official iOS app and no device to connected)
So, how to get Restricted zone data when device is not connected?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/105837'>Zendesk ticket #105837</a>:<br><br>MSDK V4 cannot obtain the flight zone function when the aircraft is not connected. You can check this on the official Flight Zone website.

Thank you.
<br><p><em><small>°°°</small></em></p>
