### ISSUE TITLE
Camera's setFlatMode fails with error

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1299]
I'm trying to setFlatMode through the SDK, and found that I need to set the camera's flat mode to:

- PHOTO_EHDR
- PHOTO_HDR
- PHOTO_SUPER_RESOLUTION
- PHOTO_HIGH_RESOLUTION
- INTERNAL_AI_SPOT_CHECKING 
- PHOTO_HYPER_LIGHT 
- PHOTO_PANORAMA 
- PHOTO_TIME_LAPSE. 

The code (Kotlin) I'm using to do this is:

```
val product = ProductManager.getInstance(requireContext())?.getProductInstance()
        (product as? Aircraft)?.camera?.setFlatMode(mode) { error ->
            if (error != null) {
                setResultToToast(error.description)
            }
            Log.i(TAG, "set camera mode to: $mode -- ${error?.description}")
 }
```

Making this call returns an error: **Camera received invalid parameters.**

 Any help is appreciated.

Device: DJI Air 2
Firmware: 01.05.0000
SDK Version: 4.17

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106586'>Zendesk ticket #106586</a>:<br><br>The AIR 2 can be used with setFlatMode. Is the mode you are passing supported by AIR 2? The mode PHOTO_HDR listed above is not supported by AIR 2. If you need the photo to be HDR type, you should set the camera mode to PHOTO_SMART.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev thank you so much.
How about with another device that does not support setFlatMode? 
Which function to change the camera mode?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106586'>Zendesk ticket #106586</a>:<br><br>If the value returned by isFlatCameraModeSupported is false, it means that FlatMode is not supported. You can set it using setMode.
<br><p><em><small>°°°</small></em></p>
