### ISSUE TITLE
write failed: ENODEV (No such device)

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#13]
With SDK 2.4.1, I often get the following "caught exception" in my logcat:

    java.io.IOException: write failed: ENODEV (No such device)
      at libcore.io.IoBridge.write(IoBridge.java:455)
     at java.io.FileOutputStream.write(FileOutputStream.java:187)
     at dji.midware.usb.P3.UsbAccessoryService$1.run(Unknown Source)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:841)

Then, the RC is not seen as a USB accessory anymore. I need to kill the App using the SDK, unplug the RC and replug it in order to get it to be recognized as a USB accessory again.

**Comment by SilverChangjian** [comment]
Thanks for your report, this bug has been listed into our bug list. We will try to reproduce it and fix it if existed as soon as possible.

**Comment by JonasVautherin** [comment]
What do you mean, "if existed"?

**Comment by wenqianqiao** [comment]
Sometimes it is hard for us to reproduce it. So we need to reproduce it first. and then fix them. Sorry for the confusion.

**Comment by JonasVautherin** [comment]
I can consistently reproduce that: when I get this message, I need to quit the App, unplug the RC controller, replug it and restart the App. Might have something to do with `DJIDrone.disconnectToDrone()` (that you don't really test in your demo App, BTW).

**Comment by wenqianqiao** [comment]
Got it. Our Engineer is already working on that. I will get back to you if we need more information for solving this problem. Thanks.

**Comment by aalmada** [comment]
Hi,
Is the connection made using AOA (Android Open Accessory)? If so, it's a know issue with Android: http://stackoverflow.com/questions/18583555/android-adk-io-exception-enodev
I'm banging my head because of this issue on a tottaly unrelated project and a search brought me here...
Antao

**Comment by SilverChangjian** [comment]
Yes, we are using AOA for building up the connection between RC and the android device. Thanks for your information!
