### ISSUE TITLE
[Help] Gimbal rotate auto reverses

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1300]
The aircraft automatically reverses when turning to the right, how to disable auto reverses?

https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/47f26594-96e5-43fd-aed5-86f67ab81052

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106740'>Zendesk ticket #106740</a>:<br><br>Could you please let us know what model of device you are using? And could you also inform us about how you are controlling it?

If you are requesting the gimbal to rotate to a specific angle, it should not automatically reverse.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
My drone is: DJI Air 2s

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/106740'>Zendesk ticket #106740</a>:<br><br>Is it possible for me to reproduce the issue you are experiencing on the AIR 2S? If so, could you please provide me with a method to do so?
<br><p><em><small>°°°</small></em></p>
