### ISSUE TITLE
DJI Air 2S Intelligent Flight Modes (ActiveTrack, Spotlight, POI)

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1304]
I want to implement 3 features: ActiveTrack, Spotlight, POI
- ActiveTrack: I used ActiveTrackOperator
How about Spotlight and POI? 
Please give me some documents for it.
![Screenshot 2024-05-22 at 17 07 13](https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/a03c30f1-d635-447f-9776-6f2aec750f36)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107990'>Zendesk ticket #107990</a>:<br><br>Spotlight and POI are also implemented using ActiveTrackOperator, corresponding to Circle and Spotlight modes respectively.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev I got it, thank you so much.
So, what is ActiveTrackMode to support `Parallel`?
![Screenshot 2024-05-24 at 09 47 43](https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/e0c1b2f0-6c4d-4022-9248-4031b5a99c35)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107990'>Zendesk ticket #107990</a>:<br><br>I think it refers to the PROFILE mode.https://developer.dji.com/api-reference/android-api/Components/Missions/DJIActiveTrackMission.html#djiactivetrackmission_djiactivetrackmode_inline
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev thank you so much

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/107990'>Zendesk ticket #107990</a>:<br><br>I'm glad I could help you.
<br><p><em><small>°°°</small></em></p>
