### ISSUE TITLE
The execution could not be executed

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1305]
```
activeTrackOperator?.getCircularSpeed(object : CompletionCallbackWith<Float?> {
                    override fun onSuccess(speed: Float?) {
                        Log.i(TAG, "getCircularSpeed:success $speed")
                    }

                    override fun onFailure(error: DJIError?) {
                        Log.e(TAG, "getCircularSpeed:error ${error?.description}")
                    }
                })
```
I use this code to get circular speed and I got error message: The execution could not be executed
Please help me check it.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108592'>Zendesk ticket #108592</a>:<br><br>Could you please let us know which drone you are using?
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
My drone is DJI Air 2S

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108592'>Zendesk ticket #108592</a>:<br><br>getCircularSpeed is an interface that can only be used when the aircraft is in circular mode following a target. Is the aircraft in this state when you are testing it?
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev I changed to Circle mode and it worked for me. Thank you so much
