### ISSUE TITLE
How to get a distance value to the .jpg file?

### ISSUE THREAD

**Issue by smpark00** [dji-sdk/Mobile-SDK-Android#1306]
My drone model is the DJI Mavic Pro 2.
When my drone flies, I can get data from the controller about the distance from the starting point.
And I can get some data from xmp .json file in the photo that was taken from DJI drones.
Can I get distance data from the xmp .json file when I shoot some photos in flight time?
I can't find the data about the distance from the starting point.
If I can't, is there any way to get distance data?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108665'>Zendesk ticket #108665</a>:<br><br>The data in XMP is written directly by the camera. There should be the drone's position when taking photos in XMP. If you know the starting point's position, you can calculate the distance.
<br><p><em><small>°°°</small></em></p>

**Comment by smpark00** [comment]
You means GPS data?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108665'>Zendesk ticket #108665</a>:<br><br>Yes, I am referring to the GPS location information stored in photos.
<br><p><em><small>°°°</small></em></p>
