### ISSUE TITLE
DJI SDK V5 LRF 

### ISSUE THREAD

**Issue by hyunah96** [dji-sdk/Mobile-SDK-Android#1307]
Hello, is the LRF feature implemented in DJI SDK V5? I am using the M300 with the H20T

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108873'>Zendesk ticket #108873</a>:<br><br>Is the LRF feature you mentioned referring to video compression functionality? The Mobile SDK V5 does not have this feature.
<br><p><em><small>°°°</small></em></p>
