### ISSUE TITLE
How to get Controller battery info in dji msdk 4.16

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android#1317]
How to get Controller battery info in dji msdk 4.16

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/113378'>Zendesk ticket #113378</a>:<br><br>The setChargeRemainingCallback is the interface for obtaining the battery level.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Thanks for your information !

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/113378'>Zendesk ticket #113378</a>:<br><br>I'm glad to have been able to assist you. For specific target interfaces, you can actually refer to the API documentation and check the interfaces based on the modules. For example, to check the battery level of the remote control, you can look at the interfaces in the remote control module.
<br><p><em><small>°°°</small></em></p>
