### ISSUE TITLE
How to get verticle speed of drone in dji msdk 4.16

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android#1318]
How to get verticle speed of drone in dji msdk 4.16 while takeoff any mission?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/113379'>Zendesk ticket #113379</a>:<br><br>The getVelocityZ method retrieves the speed in the vertical direction.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Got it.

Thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/113379'>Zendesk ticket #113379</a>:<br><br>Hope you have a wonderful day.
<br><p><em><small>°°°</small></em></p>
