### ISSUE TITLE
[Feature Request] Latest available firmware

### ISSUE THREAD

**Issue by justintuchek** [dji-sdk/Mobile-SDK-Android#132]
It would be nice (maybe during SDK initialization, or later) to have a cached result of the most available firmware for the current product components.

That way if there is an important update SDK developers can use this information to prompt users that they need to update their devices.

Maybe having a severity ranking with firmware update - such as:
- critical, fixes flight or mission bug
- minimal, software performance improvements

**Comment by oliverou** [comment]
Hi @jtuchek, have you check the Release Notes for each SDK release: <http://developer.dji.com/mobile-sdk/downloads/>? It includes the **Supported Firmware** section, please check it and let me know if it can resolve your issue.

**Comment by JamesMastermanDev** [comment]
This would be a great feature. We maintain our own class to do this and copy the numbers from the release notes for each SDK into the code. It's tedious, but works for now. 

It's also never clear if the firmware versions are just recommended or if there could be serious issues from users having old firmware. Issues that could leave developers legally exposed if users are not warned. 

Ideally, the SDK itself would have an isFirmwareCompatible() or some such function that would check the connected drone is running a high enough firmware version. 

In older SDK's we found reading the firmware version was very unreliable (would often return an empty string) on some drone models, but SDK 4.1+ seems to be much better.

**Comment by jtuchek** [comment]
Thanks for the reply @oliverou 

I know that as a developer I could go and read the supported firmware sections.

My thought was that programmatically depending on the connected product components, a developer could query the SDK if there are updates needed.

In the use case that a user wants to fly their drone
We setup that connection via the SDK
Check if there are critical updates
If yes, notify them before flying

@JamesMastermanDev brings up a point about copying data from the release notes, but if an SDK developers app is an incremental or major version number behind that data is now out of date - and wouldn't reflect any newly available software. 

It would also allow firmware version numbers to be correct when firmware (that doesn't break compatibility) is released independently of SDK releases and notes.

**Comment by JamesMastermanDev** [comment]
@jtuchek good point about old code (based on older SDK's) being out of date compared to advancing firmware using our method. We are assuming that new firmware only gets better, but of course that is not always true (eg. Mavic firmware broke the onNewFile(MediaFile djiMedia) callback since about version 1.3.500 and it's still not fixed in 1.3.900!). 

 I suppose it would need to be something dynamic. Pass in your SDK version number and it returns a range of firmware versions that are compatible with the connected aircraft. Probably quite a complex piece of work to test all the possible combinations for DJI I expect, especially if we want levels of compatibility to be returned (eg. critical/non critical etc)

**Comment by cukingpro** [comment]
Is there any way to know the latest firmware of the product if the SDK doesn't support?

**Comment by Michael-DJI** [comment]
@cukingpro you could check the official website: www.dji.com

**Comment by cukingpro** [comment]
> @cukingpro you could check the official website: [www.dji.com](http://www.dji.com)

What I want is to check the latest available firmware of the drone programmatically, then compare to the current firmware and tell users to update.

**Comment by Michael-DJI** [comment]
@cukingpro Oh I see, sorry for the misunderstanding, this could be a feature request, we will record it to our list, thanks!

**Comment by kenargo** [comment]
But in order for this request to be valuable you would also need to include an SDK way to update firmware.   Otherwise the best an app would be able to do is to tell the user to run DJI GO.

⁣Get BlueMail for Android ​

**Comment by Michael-DJI** [comment]
@justintuchek 4.11 has supported this feature, please refer to UpgradeManager
