### ISSUE TITLE
Does the app need bluetooth?

### ISSUE THREAD

**Issue by tri133** [dji-sdk/Mobile-SDK-Android#1321]
I did not give bluetooth permission to the app and got this error
```
dji.midware.ble.BLE.isEnabled
java.lang.SecurityException - Need BLUETOOTH permission: Neither user 10250 nor current process has android.permission.BLUETOOTH.
```

I don't know when the app uses bluetooth. I looked through it but I don't know which function uses bluetooth.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/117272'>Zendesk ticket #117272</a>:<br><br>Could you please let us know the model of the device you are using and the version of MSDK? Bluetooth permissions are required on some devices, but the app may not necessarily utilize Bluetooth.
<br><p><em><small>°°°</small></em></p>

**Comment by tri133** [comment]
> Agent comment from yating.liao in [Zendesk ticket #117272](https://djisdksupport.zendesk.com/agent/tickets/117272):Could you please let us know the model of the device you are using and the version of MSDK? Bluetooth permissions are required on some devices, but the app may not necessarily utilize Bluetooth.
> 
> _°°°_

I am using sdk V4.17 with Pixel 4a, android 11. Is there any way to fix it without granting bluetooth permission.
Thanks
