### ISSUE TITLE
FetchMediaTaskScheduler - Scheduled task memory leak

### ISSUE THREAD

**Issue by jcfarsight** [dji-sdk/Mobile-SDK-Android#133]
I've recently upgraded the DJI SDK to v4.2 and have been experimenting with use of the new FetchMediaTaskScheduler API in my application. The SD card on my Mavic Pro has 491 photos currently and I am iterating through trying to pull back a preview of each one such that they can be transmitted to a web service on my desktop.

Unfortunately I've noticed that a somewhat short period of time after starting the process, the application crashes with an OOM exception. Sure enough, watching the memory in Android Studio confirms that the allocated memory quickly climbs from the baseline ~40MB to ~192MB where the crash occurs in a matter of 55 seconds.

Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 0 free bytes and -1832B until OOM" (recursive case)
"recvBufferThread" prio=9 tid=27 Runnable
   | group="main" sCount=0 dsCount=0 obj=0x32c23700 self=0x72f2248e00
   | sysTid=14849 nice=-1 cgrp=default sched=0/0 handle=0x72ee6f5450
   | state=R schedstat=( 11568122043 4719804501 85051 ) utm=814 stm=341 core=2 HZ=100
   | stack=0x72ee5f3000-0x72ee5f5000 stackSize=1037KB
   | held mutexes= "mutator lock"(shared held)
     at java.nio.ByteBuffer.wrap(ByteBuffer.java:291)
     at dji.midware.util.b.a(unavailable:-1)
     at dji.midware.usb.P3.UsbAccessoryService$1.parseSecondHeader(unavailable:-1)
     at dji.midware.parser.plugins.b.c(unavailable:-1)
     at dji.midware.parser.plugins.b.a(unavailable:-1)
     at dji.midware.usb.P3.UsbAccessoryService$RecvBufferRunnable.run(unavailable:-1)
     at java.lang.Thread.run(Thread.java:761)

To ensure it is not an issue with me leaking memory inside the onUpdate delegate, I've commented out all the functional code dealing with streams, web service communication etc and the problem still exists.

Here is a snippet of my code:

```
List<MediaFile> mediaFiles = _mediaManager.getFileListSnapshot();

Log.e(TAG, "Fetch Media Success: " + (mediaFiles == null ? "no files" : mediaFiles.size()) + " items.");

if (mediaFiles != null)
{
   for (MediaFile file : mediaFiles)
   {
      if (!_processedMediaFiles.containsKey(file.getFileName()))
      {
         Log.d(TAG, "New file detected: " + file.getFileName());

         final FetchMediaTaskScheduler scheduler = _mediaManager.getScheduler();

         if (scheduler.getState() == FetchMediaTaskScheduler.FetchMediaTaskSchedulerState.SUSPENDED)
         {
            scheduler.resume(new CommonCallbacks.CompletionCallback()
            {
               @Override
               public void onResult(DJIError djiError)
               {
                  Log.d(TAG, "Scheduler resumed with error: " + (djiError == null ? "none" : djiError.getDescription()));
               }
            });
         }

         scheduler.moveTaskToEnd(new FetchMediaTask(file, FetchMediaTaskContent.PREVIEW, new FetchMediaTask.Callback()
         {
            @Override
            public void onUpdate(MediaFile mediaFile, FetchMediaTaskContent fetchMediaTaskContent, DJIError djiError)
            {
               Log.d(TAG, "On scheduler update.");

               if (djiError == null)
               {
                  // Web service/streaming code here...
               }
               else
               {
                  Log.e(TAG, "Error on scheduler update: " + djiError.getDescription());
               }

               // (Testing puposes) Remove the task from the scheduler to try and avoid memory leak/bloat.
               scheduler.removeTask(mediaFile, fetchMediaTaskContent);
            }
         }));
      }
   }
}
```

Has anyone else experienced this problem or am I doing something obviously bad here?

**DJI Android SDK Version:** 4.2
**DJI Product:** Mavic Pro w/ firmware 01.03.0900
**Android system version:** 7.1.2
**Android device:** Nexus 5X
**Android studio version:** 2.3.3

**Comment by oliverou** [comment]
Hi @jcfarsight , you should reset the cached **thumbnail**/**Preview image** to null to release the memory usage by invoking the following methods of `MediaFile`:

- [resetThumbnail](http://developer.dji.com/cn/api-reference/android-api/Components/Camera/DJIMediaManager_DJIMedia.html?search=resetm&i=10&#djimediamanager_djimedia_resetthumbnail_inline)
- [resetPreview](http://developer.dji.com/cn/api-reference/android-api/Components/Camera/DJIMediaManager_DJIMedia.html?search=resetm&i=10&#djimediamanager_djimedia_resetpreview_inline)

Take the snippet of your code for example, in the `onUpdate()` method of `moveTaskToEnd()`, you can get the cached preview image from the `mediaFile` object,  then after you finish storing this cache preview image to an array, you can invoke the `resetPreview()` method to reset the cached preview image to release the memory.

**Comment by jcfarsight** [comment]
Thanks for your help!
I can confirm that using `resetPreview()` resolves the issue nicely and all images were able to be pulled down successfully.
