### ISSUE TITLE
dji simulator class

### ISSUE THREAD

**Issue by Bestboy125** [dji-sdk/Mobile-SDK-Android#1331]
您好，我看到文档中关于Continuous Integration Simulation持续集成模拟的介绍，其中是这样说的
![image](https://github.com/user-attachments/assets/bf6dd1a5-2ae3-4b04-9425-5242021516b2)
请问这里我不需要连接遥控器和无人机就可以进行代码测试吗？
因为现在无人机和遥控器不在我身边。。，但是我写了代码想要测试。
此外，这里有一些参考代码吗？
谢谢解答，感谢！

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/121256'>Zendesk ticket #121256</a>:<br><br>SDK的模拟器只是不需要使用到电脑提供的模拟器环境，你依旧需要使用无人机和遥控器才可以测试SDK的功能。
目前无法做到没有遥控器和无人机的情况下进行仿真调试。
<br><p><em><small>°°°</small></em></p>

**Comment by Bestboy125** [comment]
您好，谢谢，那我只用遥控器可以嘛

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/121256'>Zendesk ticket #121256</a>:<br><br>只用遥控器是可以对遥控器上的功能进行调试的，无人机功能还是需要有无人机才能调试。
<br><p><em><small>°°°</small></em></p>
