### ISSUE TITLE
Feature Request: Add ability to get EXIF information of media without downloading full files

### ISSUE THREAD

**Issue by jcfarsight** [dji-sdk/Mobile-SDK-Android#134]
I'm currently looking to pull back preview images from the SD card via the newly released `FetchMediaTaskScheduler` API. Pulling back the preview images is fine however I also want to access the original image EXIF information to acquire GPS location, altitude etc.

The only way I can seem to do this without pulling the whole original file across is to access the 'custom information' of the `MediaFile`. Unfortunately this doesn't appear to be well documented and in fact some places don't reference it existing at all.

When I attempt to pull back the information via the scheduler, the scheduler correctly enters EXECUTING state but the number of pending tasks in the queue doesn't decrease and the `onUpdate` method of any task is never called.

Here is the piece of code I'm using to attempt this (note that FetchMediaTaskContent PREVIEW and THUMBNAIL work correctly):
```
scheduler.moveTaskToEnd(new FetchMediaTask(file, FetchMediaTaskContent.CUSTOM_INFORMATION, new FetchMediaTask.Callback()
{
   @Override
   public void onUpdate(MediaFile mediaFile, FetchMediaTaskContent fetchMediaTaskContent, DJIError djiError)
   {
      Log.d(TAG, "On scheduler update.");

      if (djiError == null)
      {
         Log.d(TAG, "CustomInfo: " + mediaFile.getCustomInformation());
      }
      else
      {
         Log.e(TAG, "CustomInfo: " + djiError.getDescription());
      }
   }
}));
```

Is fetching custom information actually supported in the API at the moment or is it just a future proofing stub?

**DJI Android SDK Version:** 4.2
**DJI Product:** Mavic Pro w/ firmware 01.03.0900
**Android system version:** 7.1.2
**Android device:** Nexus 5X
**Android studio version:** 2.3.3

**Comment by jcfarsight** [comment]
I see in release 4.3 that the custom information functionality has now been added but it isn't exactly what I thought it was. 

Looking at the API reference for the MediaFile getCustomInformation:
> Custom information can be stored in media file's XMP meta data using setMediaFileCustomInformation This property contains the information that was written to this media file. If this property returns null, use fetchCustomInformation to populate it. Only supported by Phantom 4 Pro, Phantom 4 Advanced and Inspire 2 with firmware versions from after May 23 2017.

It would be great if we could also just get the default EXIF information of images somehow, which hopefully would be available on a wider selection of drone/camera products.

**Comment by Michael-DJI** [comment]
@jcfarsight did you find a way to resolve your problem? currently we didn't provide the full info of EXIF.

**Comment by jcfarsight** [comment]
@Michael-DJI Unfortunately we weren't able to solve the problem with EXIF retrieval. 

The project I was working on isn't going ahead at this time however so there's no pressure to implement this feature if nobody else wants it.

**Comment by Michael-DJI** [comment]
@jcfarsight ok, I see, thanks for your reply!

**Comment by brien-crean** [comment]
@Michael-DJI is this feature request still being considered? It would be extremely useful to be able to grab the meta data from an image without having to stream a file and grab the meta data tags manually - especially since there is a bug with stopFetchingFileData #463

**Comment by Michael-DJI** [comment]
@brien-crean yes, the feature is being considered, but it will be integrated in some new drone, thanks for the advices!
