### ISSUE TITLE
Unstable connection to mobile devices (SDK 4.2.1)

### ISSUE THREAD

**Issue by Nuclominus** [dji-sdk/Mobile-SDK-Android#136]
Recently began to develop under the DJI device in the face of the problem of unstable connection with mobile devices. As a reference point, took your example from git.

SDK is registered without problems, but mobile devices behave differently. On Nexus devices, the connection to DJI devices is more stable, but still if you reconnect several times by Wi-fi then for the second or third time it already gives out :
 ```
E/wm220: ****resetSwitchFromWifiFlag
 E/DJIPackManager: pack senderType=7 cmdSet=7
 E/wm220: ****resetSwitchFromWifiFlag
 E/DJIPackManager: post DataCameraEvent.ConnectOK RC
                                                                            
 [ 07-13 14:50:55.754 14902:15028 E/         ]
 stopDaemon WIFI
 E/UsbAccessoryService: final destroy() 71
 E/UsbAccessoryService: final destroy() 72
 E/wm220: ****resetSwitchFromWifiFlag
 E/UsbAccessoryService: final destroy() 73
 E/UsbAccessoryService: final destroy() 75
 E/UsbAccessoryService: final destroy() 76
                                                                                 
         [ 07-13 14:50:55.869 14902:15028 D/         ]
         ===DJIProductManager===[WIFI]
                                                                                 
         [ 07-13 14:50:55.869 14902:15028 D/         ]
         ===rcType bylink===[null]
                                                                                 
         [ 07-13 14:50:55.869 14902:15028 D/         ]
         linkType=WIFI

  E/b: udt 连接建立 ip:192.168.1.3port:9000
  E/UDT-JNI: Connection was broken.
  E/b: udt 连接断开 recvLen=-2 ip:192.168.1.3port:9000
  E/b: socket recv thread over
```
 and "Connection was broken" repeats indefinitely. (In particular, on models other than Nexus)
**P.S.** A very interesting point is that the application does not always see Mavic Pro connected through by Wi-fi. After the registration of SDK, product is not returned to the callback.

- I use last DJI SDK 4.2.1. 
- It was test on OSMO, OSMO+, Phantom 4 and Mavic Pro. 
- For testing, i used LG Nexus 5, HTC Nexus 9,  Samsung Galaxy Note 5, Samsung J7, Meizu Pro 6.
- Android Studio version 2.3.3

You can help with this problem or explain such instability of the connection on par with the official application? Thank you in advance.

**Comment by lillogoal** [comment]
I have the same problem. i need to follow this post. sorry

**Comment by Nuclominus** [comment]
@lillogoal The problem was identified 3 weeks ago. The problem lies in the DJI GO 4 service. It takes the data stream from the device and has the highest priority by default. If the service is stopped, the device starts to issue a stable connection immediately.

**Comment by lillogoal** [comment]
So how can i solve this problem ?

**Comment by talobin** [comment]
If you have DJIGo running in the back, please force stop DJIGo.
Please try that out with our SDK 4.3.2.
Will go ahead and close the issue.
Feel free to reopen if the problem still exists.
Thanks!
