### ISSUE TITLE
Phantom 4 Advanced compatability

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#139]
Will compatibility with the Phantom 4 Advanced be coming to a future version of the Android SDK?

**Comment by jtuchek** [comment]
Does the Phantom 4 advanced identify as a different aircraft - such as a Phantom 4 Pro? 

We don't have one yet to physically test with - as far as I can tell from looking at the docs and sample project there is no `Model` entry fro the Phantom 4 Advanced.

A few customers of ours have asked about future support before purchasing new devices, so even if it will never be supported a response would be helpful and we can help them choose a compatible aircraft model.

**Comment by oliverou** [comment]
Hi @jtuchek , the DJI Android SDK has already supported Phantom 4 Advanced since v4.1, please check the **Supported Products** in the release note of the SDK download: <http://developer.dji.com/mobile-sdk/downloads/>

**Comment by jtuchek** [comment]
@oliverou thanks - my downloaded docs were out of date on 4.0, sorry!
