### ISSUE TITLE
UploadGroundStationTask breaks backward compatibility: GS_Result_Waypoint_Info_Invalid

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#14]
Using __exactly__ the same waypoints I use with SDK 2.4.0, I cannot upload my mission using SDK 2.4.1.

The SDK returns the following error: `GS_Result_Waypoint_Info_Invalid`. It would be nice if it could be a little bit more specific.

**Comment by JonasVautherin** [comment]
Looks like I get a `GS_Result_Waypoint_Info_Invalid` when I try to upload waypoints that are further than 2km away from the drone. 

Can you confirm it is a bug/feature that was added in 2.4.1? I don't see it mentioned anywhere in the changelog.

**Comment by SilverChangjian** [comment]
Please use the latest SDK for your project, we are not going to support the 2.x version of the SDK.
