### ISSUE TITLE
fetchFileDataWithOffset for 4:3 full image is extremely slow

### ISSUE THREAD

**Issue by hy9be** [dji-sdk/Mobile-SDK-Android#142]
I tested this with my Phantom 4 Advanced and the remote control with iPad mounted right next to each other. It took almost 2 minutes to transfer one 8MB image. Is that performance in the expected range? Any suggestions to improve it? Thanks!

**Comment by kwong93** [comment]
Shouldn't this be posted in the iOS repo?
https://github.com/dji-sdk/Mobile-SDK-iOS

**Comment by oliverou** [comment]
Thanks @kwong93. Hi @hy9be, please raise this issue in the iOS Repo: <https://github.com/dji-sdk/Mobile-SDK-iOS/issues>, thanks! Close this issue now.

**Comment by hy9be** [comment]
@oliverou Got it. Thanks!
