### ISSUE TITLE
getRCSwitchFlightModeMapping return wrong values

### ISSUE THREAD

**Issue by ltluc253** [dji-sdk/Mobile-SDK-Android#145]
[This method](https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html#djiflightcontroller_getremotecontrollerflightmodemapping_inline) return threre mode A, S, P. But my controller have different mode F, A, P
My Test Environment is
  + Phantom 3 Pro
  + Nexus 9 with Android 7.1
  + DJI SDK 4.2.1

Note: It work correct in SDK version 3.5.1 with method [getRemoteControllerFlightModeMappingWithCompletion](https://developer.dji.com/iframe/mobile-sdk-doc/android/reference/dji/sdk/flightcontroller/DJIFlightController.html#getRemoteControllerFlightModeMappingWithCompletion(dji.common.util.DJICommonCallbacks.DJICompletionCallbackWith<dji.common.flightcontroller.DJIFlightControllerRemoteControllerFlightMode[]>))

**Comment by talobin** [comment]
@ltluc253 This problem has been fixed in the latest SDK version (4.3.2).
We suggest to always use the latest SDK.

**Comment by ltluc253** [comment]
I got this issue again when checking on M100 and Inspire 1 series.
- DJI SDK: 4.5.1
- Test devices: M100 and Inspire 1 series.
Actual: the mode in Remote Controller is F, A, P but this method return A, S, P.
Expected: return correct value on the callback.
Please help me fix this issue. Currently, I've to cheat code for Models above when use this method.
Thanks
