### ISSUE TITLE
Unable to set quality when taking still photos

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-SDK-Android#146]
-  Description of the issue.
Unable to find a way to set quality for stills using SDK. The docs mention quality options is available to devs but I am unable to find a method to set in the SDK

https://developer.dji.com/mobile-sdk/documentation/introduction/component-guide-camera.html

> As a JPEG image is compressed increased, it's file size and image quality reduces. Quality options of Normal, Fine and Excellent are available for users and developers to choose the right balance for their application.

I see enum for `CameraPhotoQuality `defined in `SettingsDefinitions`

```
    public static enum CameraPhotoQuality {
        NORMAL(0),
        FINE(1),
        EXCELLENT(2),
        UNKNOWN(255);
```
but no such method utilizes it AFAIK

I was expecting a method such as below to be available
`public void setPhotoQuality(@NonNull CameraPhotoQuality quality, @Nullable CompletionCallback callback)`
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
4.2.1
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Phantom 4 Pro
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
6.0.1
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
S7

**Comment by oliverou** [comment]
Hi @kwong93, thanks for the feedbacks! This Enum is already deprecated, now is unable to set the photo quality using DJI Mobile SDK. Will update the documentation: <https://developer.dji.com/mobile-sdk/documentation/introduction/component-guide-camera.html> too.

**Comment by kwong93** [comment]
What was the reason to remove the ability to set photo quality in SDK?

**Comment by oliverou** [comment]
Hi @kwong93 , the camera firmware no longer support this feature now.
