### ISSUE TITLE
Firmware Update fails due to incorrectly detecting device battery lower than 50% on LG G6

### ISSUE THREAD

**Issue by eflite** [dji-sdk/Mobile-SDK-Android#147]
When my Android device (LG G6 running android 7) is connected to the Mavic Pro controller, the DJI GO 4 app notifies: "Inconsistent firmware found. Aircraft firmware and firmware of peripheral devices do not match. "

When I slide the slider to update it notifies: "Battery lower than 50%", even though my device is at 83% battery. This bug effectively prevents me from updating my Mavic Pro's firmware. 

If this bug is supposed to be reported elsewhere, please assign it to the proper entity. 

Regards, 
Eflite

**Comment by Krishtof-Korda** [comment]
I have the same issue on my Galaxy Note4 Android version 6.0.1. Have you heard how to fix this yet or where to assign it? Thanks.

**Comment by oliverou** [comment]
Hi @eflite,  you said: "Battery lower than 50%", even though my device is at 83% battery.", do you mean the battery of your mobile device, or the remote controller of RC or the Mavic Pro drone's? Could you help to specify it?  Thanks!

**Comment by Krishtof-Korda** [comment]
In my case all batteries are greater than 50%. However, I was able to do
the update using dji assistant 2.

Cheers,

Krishtof

**Comment by oliverou** [comment]
@Krishtof-Korda, thanks for your feedbacks! We have addressed the issue and will fix it.
