### ISSUE TITLE
Geofencing

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-SDK-Android#148]
Is the geofencing functionality integrated with the SDK? Would I get warnings for no fly zones?

**Comment by oliverou** [comment]
Hi @kwong93, yes, please check this tutorial for details: [DJI GEO System Tutorial](http://developer.dji.com/mobile-sdk/documentation/android-tutorials/GEODemo.html), and the sample project: <https://github.com/DJI-Mobile-SDK-Tutorials/Android-GEODemo>.

**Comment by kwong93** [comment]
@oliverou sweet thanks
