### ISSUE TITLE
The execution could not be executed.

### ISSUE THREAD

**Issue by miladehghani** [dji-sdk/Mobile-SDK-Android#149]
I have a series of action using timeline action but I got this message on GOTOACTION "The execution could not be executed", I can't tell you when I get this message sometimes on the second action sometimes there is no problem, in fact, it's unknown when the problem happens, :((((((( any suggestion? its urgent

-  Phantom 4 pro
-  Android 6
-  Lenovo TB3-850M
-  Android Studio 2.3.2
- SDK 4.2.1

**Comment by zoemcateedji** [comment]
4.3 Was just released and contains many improvements to the Timeline Mission manager. Could load that version and let us know how it goes?
https://developer.dji.com/mobile-sdk/downloads/

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
