### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by alexwang3322** [dji-sdk/Mobile-SDK-Android#15]
Nexus6
Android version 5.1.1
with com.android.tools.build:gradle:1.3.0

description : crashed when I just start the demo.

java.lang.UnsatisfiedLinkError: No implementation found for long dji.midware.natives.GroudStation.native_hashFromString(byte[]) (tried Java_dji_midware_natives_GroudStation_native_1hashFromString and Java_dji_midware_natives_GroudStation_native_1hashFromString___3B)
12-01 10:47:26.818 26552-26579/? E/AndroidRuntime:     at dji.midware.natives.GroudStation.native_hashFromString(Native Method)
12-01 10:47:26.818 26552-26579/? E/AndroidRuntime:     at dji.midware.data.params.P3.ParamInfoBean.getParamInfo(Unknown Source)
12-01 10:47:26.818 26552-26579/? E/AndroidRuntime:     at dji.midware.data.manager.P3.c.a(Unknown Source)
12-01 10:47:26.818 26552-26579/? E/AndroidRuntime:     at dji.midware.data.manager.P3.c.a(Unknown Source)
12-01 10:47:26.818 26552-26579/? E/AndroidRuntime:     at dji.midware.data.manager.P3.d.run(Unknown Source)
12-01 10:47:26.818 26552-26579/? E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)

**Comment by VicV** [comment]
Move the two armeabi folders to src/main/jnilibs (will need to create the jnilibs folder), then try again.

**Comment by SilverChangjian** [comment]
Please make sure the compile version to lower than 23 and make sure involve all the so files in your lib file..

**Comment by VicV** [comment]
Well that's hardly fair, any plans on actually fixing the problem?

**Comment by SilverChangjian** [comment]
Reopen this issue for tracking this issue. Has tracked it on our bugs system.

**Comment by oliverou** [comment]
Since the issue was resolved, close it now.
