### ISSUE TITLE
Unable to generate signed APK due to duplicate entry gson

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-SDK-Android#150]
-  Description of the issue.
Cannot build signed APK because of duplicate entry. I can run the app fine in debug.

-  Crash logs (If you can find it, it would be very helpful)
```
Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/gson/annotations/Expose.class
```

Here are my gradle dependencies

I verified that I can build the signed APK when I commented out the DJI dependencies
```
    compile project(':dji-uilibrary')
    compile project(':dji-sdk')
```

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.github.bumptech.glide:glide:3.8.0'
    compile 'com.google.android.gms:play-services-maps:10.2.4'
    compile 'com.github.chrisbanes:PhotoView:2.0.0'
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-s3:2.2.+'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.onesignal:OneSignal:[3.5.3,4.0.0)'
    compile 'com.google.maps.android:android-maps-utils:0.5+'
    compile 'com.squareup.okhttp3:okhttp:3.8.0'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.0'
    compile 'com.google.android.gms:play-services-location:10.2.6'
    compile 'com.library.tangxiaolv:telegramgallery:1.0.3'
    compile 'com.github.barteksc:android-pdf-viewer:2.6.0'
    compile project(':dji-uilibrary')
    compile project(':dji-sdk')
}
```
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
4.2.1
-  Android Studio version you are using (Like Android Studio 2.2, etc)
2.3.3

**Comment by kwong93** [comment]
I opened the dji-sdk.aar file and I see the gson dependency
dji-sdk.aar\classes.jar\com\google\gson\

and also I see another module dji.thirdparty.gson.

Question is which one is being used? I did a brief scan and I don't see any references to com.google.json
I would like to remove the com.google.gson completely from classes.jar and remake the aar to see if will solve the conflict

**Comment by oliverou** [comment]
Hi @kwong93, please try the [logIntoDJIUserAccount](http://developer.dji.com/api-reference/android-api/Components/UserAccountManager/DJIUserAccountManager.html?search=loginto&i=0&#djiuseraccountmanager_logintodjiuseraccountwithauthorizationrequired_inline) interface to test if it works, if so, you are good to go.

For the gson dependency **dji-sdk.aar\classes.jar\com\google\gson\**, currently, we don't plan to remove it in our SDK.

**Comment by kwong93** [comment]
@oliverou Is logging in required to use drone capabilities? What is the difference for a logged in user and and an anonymous user using my app with dji integration?

**Comment by oliverou** [comment]
Hi @kwong93, the login and application activation is required for users in China, please check the **introduction** section of this tutorial: [Application Activation and Aircraft Binding](http://developer.dji.com/mobile-sdk/documentation/android-tutorials/ActivationAndBinding.html).

**Comment by jtuchek** [comment]
@kwong93 I believe the build issue you're having is a transitive dependency conflict between the version of Gson being used by `com.squareup.retrofit2:converter-gson` and the version being used by ':dji-uilibrary'

You could look into using a Gradle command to exclude the command package under - documented here `25.4.7. Excluding transitive dependencies` https://docs.gradle.org/3.3/userguide/dependency_management.html

Maybe the UI Library should use a Gradle `provided` scope to rely on compile time dependencies from the mobile SDK - otherwise a user using both the SDK and the UI library will ship 2 versions of Gson.

It's also not very friendly to people just getting started as multiple namespace paths for the same library can be confusing and if not stripped out it may push them into having to maintain a multidex application which is a significantly slower experience.

**Comment by kwong93** [comment]
Now that DJI has the sdks availabe via gradle, this is no longer an issue for me

```
    compile 'com.dji:dji-sdk:4.3.2'
    compile 'com.dji:dji-uilibrary:4.3.2'
```
