### ISSUE TITLE
Again not needed log which spams a lot and some exception occur!

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#151]
Within the 4.2.1 SDK again a lot of not needed logging is spamming my application log:

+++++++++++++++++++++++++++++++++++++++++++
"I/n: ConnectivityManager says we are online" 
"E/Playback: send success"
"D/UsbAccessoryService: rate 920,32 KB"

are written really often, but i cannot assign it to an explicit class because no class is mentioned.

+++++++++++++++++++++++++++++++++++++++++++
`08-02 20:58:24.469  W/System.err: javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
08-02 20:58:24.478  W/System.err:     at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:853)
08-02 20:58:24.478  W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:1502)
08-02 20:58:24.478  W/System.err:     at dji.midware.a.a.a.b(Unknown Source)
08-02 20:58:24.478  W/System.err:     at dji.internal.useraccount.LoginVerifyController.a(Unknown Source)
08-02 20:58:24.478  W/System.err:     at dji.internal.useraccount.LoginVerifyController.g(Unknown Source)
08-02 20:58:24.478  W/System.err:     at dji.internal.useraccount.LoginVerifyController.f(Unknown Source)
08-02 20:58:24.478  W/System.err:     at dji.internal.useraccount.LoginVerifyController.b(Unknown Source)
08-02 20:58:24.478  W/System.err:     at dji.internal.useraccount.LoginVerifyController$1.handleMessage(Unknown Source)
08-02 20:58:24.478  W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-02 20:58:24.478  W/System.err:     at android.os.Looper.loop(Looper.java:148)
08-02 20:58:24.478  W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
08-02 20:58:24.536  I/onLoad: loaded onLoad.cpp :JNI_OnLoad() go to end
08-02 20:58:24.536  D/FlyForbid: load lib success
08-02 20:58:26.207  W/System.err: java.io.FileNotFoundException: flysafe/flysafe_polygon_1860.db
08-02 20:58:26.208  W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
08-02 20:58:26.208  W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
08-02 20:58:26.208  W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
08-02 20:58:26.208  W/System.err:     at dji.midware.data.forbid.util.FlyforbidUtils.copyDatabaseFromAsset(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.getDb(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.midware.data.forbid.db.FlyfrbBaseDbManager.<init>(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.<init>(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.midware.data.forbid.db.FlyfrbPolygonSubDbManager.init(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.midware.data.forbid.DJIFlyForbidController.<init>(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.midware.data.forbid.DJIFlyForbidController.getInstance(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.sdk.sdkmanager.GeoSyncFileService.init(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.initParams(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.initSDKManager(Unknown Source)
08-02 20:58:26.208  W/System.err:     at dji.sdk.sdkmanager.DJISDKManager.registerApp(Unknown Source)
08-02 20:58:26.208  W/System.err:     at d.initDjiSdk(SkyveoApplication.java:70)
08-02 20:58:26.208  W/System.err:     at Activity$2.run(LoadingScreenActivity.java:53)
08-02 20:58:26.208  W/System.err:     at android.os.Handler.handleCallback(Handler.java:746)
08-02 20:58:26.208  W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
08-02 20:58:26.208  W/System.err:     at android.os.Looper.loop(Looper.java:148)
08-02 20:58:26.208  W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5443)
08-02 20:58:26.208  W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-02 20:58:26.208  W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
08-02 20:58:26.208  W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`
+++++++++++++++++++++++++++++++++++++++++++

`08-02 20:58:21.815  W/System.err: java.lang.ClassNotFoundException: dji.pilot.reflect.AppPublicReflect
08-02 20:58:21.815  W/System.err:     at java.lang.Class.classForName(Native Method)
08-02 20:58:21.815  W/System.err:     at java.lang.Class.forName(Class.java:324)
08-02 20:58:21.815  W/System.err:     at java.lang.Class.forName(Class.java:285)
08-02 20:58:21.815  W/System.err:     at dji.midware.data.manager.a.b.e(Unknown Source)
08-02 20:58:21.815  W/System.err:     at dji.midware.data.manager.a.b.f(Unknown Source)
08-02 20:58:21.815  W/System.err:     at dji.midware.data.manager.a.b.<init>(Unknown Source)
08-02 20:58:21.815  W/System.err:     at dji.midware.data.manager.a.b.<clinit>(Unknown Source)
08-02 20:58:21.815  W/System.err:     at dji.midware.data.manager.a.b.getInstance(Unknown Source)
08-02 20:58:21.815  W/System.err:     at dji.midware.usbhost.P3.NativeRcController.<clinit>(Unknown Source)
08-02 20:58:21.815  W/System.err:     at dji.midware.usbhost.P3.NativeRcController.getIsP4pPAD(Unknown Source)
08-02 20:58:21.815  W/System.err:     at dji.midware.link.a.a(Unknown Source)
08-02 20:58:21.815  W/System.err:     at dji.midware.link.a$1.handleMessage(Unknown Source)
08-02 20:58:21.815  W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
08-02 20:58:21.815  W/System.err:     at android.os.Looper.loop(Looper.java:148)
08-02 20:58:21.815  W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
08-02 20:58:21.815  W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.pilot.reflect.AppPublicReflect" on path: DexPathList[[zip file "/data/app/-2/base.apk", zip file "/data/app/-2/split_lib_dependencies_apk.apk", zip file "/data/app/-2/split_lib_slice_0_apk.apk", zip file "/data/app/-2/split_lib_slice_1_apk.apk", zip file "/data/app/-2/split_lib_slice_2_apk.apk", zip file "/data/app/-2/split_lib_slice_3_apk.apk", zip file "/data/app/-2/split_lib_slice_4_apk.apk", zip file "/data/app/-2/split_lib_slice_5_apk.apk", zip file "/data/app/-2/split_lib_slice_6_apk.apk", zip file "/data/app/-2/split_lib_slice_7_apk.apk", zip file "/data/app/-2/split_lib_slice_8_apk.apk", zip file "/data/app/-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/-2/lib/arm, /data/app/-2/base.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
08-02 20:58:21.816  W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-02 20:58:21.816  W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
08-02 20:58:21.816  W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
08-02 20:58:21.816  W/System.err: 	... 15 more
08-02 20:58:21.816  W/System.err: 	Suppressed: java.lang.ClassNotFoundException: dji.pilot.reflect.AppPublicReflect
08-02 20:58:21.816  W/System.err:     at java.lang.Class.classForName(Native Method)
08-02 20:58:21.816  W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
08-02 20:58:21.816  W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
08-02 20:58:21.816  W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
08-02 20:58:21.816  W/System.err: 		... 16 more
08-02 20:58:21.816  W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

Can you check what of these is really needed??

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by xxmaestroxx** [comment]
With the new SDK 4.3.2 the log from above is gone, but other log is available which is logged all the time:

`
10-29 11:25:34.576 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:34.577 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:36.578 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:36.579 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:38.578 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:38.578 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:40.576 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:40.576 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:42.578 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:42.579 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:44.578 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:44.578 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:46.577 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:46.577 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:48.580 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:48.581 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:50.580 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:50.581 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:52.579 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:52.580 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:54.580 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:54.580 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:56.578 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:56.578 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:25:58.580 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:25:58.581 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:00.579 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:00.579 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:02.578 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:02.578 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:04.578 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:04.578 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:06.578 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:06.578 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:08.581 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:08.581 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:10.582 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:10.582 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:12.583 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:12.583 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:14.583 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:14.584 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:16.584 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:16.584 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:18.582 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:18.582 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:20.585 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:20.586 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
10-29 11:26:22.586 2281-2409/d.v.s.d E/swudp-jni: SW_Pro_Gnd_Entry already start
10-29 11:26:22.586 2281-2409/d.v.s.d E/SwUdpService: SwUdpConnect ...
`
