### ISSUE TITLE
App crashes hard on Motorola G3

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#152]
When i connect my P4 to a Motorola G3 with android 6.0.1 my app crashes hard without any Exception!

The only thing the log is mention is this:

`
08-02 21:27:09.359 x.y.z.dbg I/n: ConnectivityManager says we are online
08-02 21:27:09.431 x.y.z.dbg I/n: ConnectivityManager says we are online
08-02 21:27:09.495 x.y.z.dbg I/n: ConnectivityManager says we are online
08-02 21:27:09.561 x.y.z.dbg I/n: ConnectivityManager says we are online
08-02 21:27:09.616 x.y.z.dbg I/n: ConnectivityManager says we are online
08-02 21:27:09.673 x.y.z.dbg I/n: ConnectivityManager says we are online
08-02 21:27:09.723 x.y.z.dbg I/n: ConnectivityManager says we are online
08-02 21:27:09.796 x.y.z.dbg I/n: ConnectivityManager says we are online
                                                   
                                                   --------- beginning of crash
08-02 21:27:09.803 x.y.z.dbg A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x991a3f38 in tid 21168 (Thread-10007)
08-02 21:27:09.851 x.y.z.dbg I/n: ConnectivityManager says we are online
08-02 21:27:09.908 ? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-02 21:27:09.908 ? A/DEBUG: Build fingerprint: 'motorola/osprey_reteu/osprey_umts:6.0.1/MPIS24.107-55-2-17/14:user/release-keys'
08-02 21:27:09.908 ? A/DEBUG: Revision: 'p2b0'
08-02 21:27:09.908 ? A/DEBUG: ABI: 'arm'
08-02 21:27:09.908 ? A/DEBUG: pid: 20862, tid: 21168, name: Thread-10007  >>> x.y.z.dbg <<<
08-02 21:27:09.908 ? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x991a3f38
08-02 21:27:09.935 ? A/DEBUG:     r0 a16a1fab  r1 00000000  r2 00000014  r3 a16a2044
08-02 21:27:09.936 ? A/DEBUG:     r4 991a3f38  r5 a16a1fab  r6 00102fa3  r7 992a80b4
08-02 21:27:09.936 ? A/DEBUG:     r8 00000099  r9 b87a4270  sl 992a812c  fp b889c7b8
08-02 21:27:09.936 ? A/DEBUG:     ip 00000000  sp 992a80a8  lr 9dd97859  pc 9dd97858  cpsr 400f0030
08-02 21:27:09.940 ? A/DEBUG: backtrace:
08-02 21:27:09.940 ? A/DEBUG:     #00 pc 000d6858  /data/app/x.y.z.dbg-2/lib/arm/libsqlcipher.so (_ZN9sqlcipher12CursorWindow8allocRowEv+49)
08-02 21:27:09.940 ? A/DEBUG:     #01 pc 000d53e9  /data/app/x.y.z.dbg-2/lib/arm/libsqlcipher.so
08-02 21:27:09.940 ? A/DEBUG:     #02 pc 000ea989  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
08-02 21:27:09.940 ? A/DEBUG:     #03 pc 000e6291  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
08-02 21:27:09.940 ? A/DEBUG:     #04 pc 003ebc6b  /system/lib/libart.so (art_quick_invoke_stub+170)
08-02 21:27:09.940 ? A/DEBUG:     #05 pc 000fe26c  [stack:21168]
08-02 21:27:11.567 ? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_02
08-02 21:27:11.567 ? E/DEBUG: AM write failed: Broken pipe
`

So what i see is that the libsqlcipher.so is creating some system leak and the app will stop working directly!

Regards
xxmaestroxx

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
