### ISSUE TITLE
ProGuard obfuscation issue: UnsatisfiedLinkError: No implementation found for ...

### ISSUE THREAD

**Issue by GIS-HowardZhang** [dji-sdk/Mobile-SDK-Android#154]
My app worked well if  generated signed APK without obfuscation. But after I added the provided [ProGuard rules](https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/proguard-project.txt) and _-dontwarn dji.**_, I got a code-obfuscated apk. Error occurred while I run the app. Here are some logs found:

   **java.lang.UnsatisfiedLinkError: No implementation found for int dji.midware.natives.FPVController.native_init**(java.lang.Object) (tried Java_dji_midware_natives_FPVController_native_1init and Java_dji_midware_natives_FPVController_native_1init__Ljava_lang_Object_2)
       at dji.midware.natives.FPVController.native_init(Native Method)
       at dji.midware.data.manager.P3.b.a(Unknown Source)
       at dji.midware.b.a(Unknown Source)
       at dji.sdksharedlib.b.a(Unknown Source)
       at dji.sdk.sdkmanager.b.initParams(Unknown Source)
       at dji.sdk.sdkmanager.b.initSDKManager(Unknown Source)
       at dji.sdk.sdkmanager.b.registerApp(Unknown Source)
       **at cn.***.***.MyApplication.onCreate(MyApplication.java:258)**
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5658)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

And "MyApplication.java:258" points to the code below:
            DJISDKManager.getInstance().registerApp(this, mDJISDKManagerCallback);

I can ensure that this error is related to DJI SDK since I just succeeded in 
testing my app in a version without dji-sdk.aar. So what is the solution of this issue? 

Hope your response soon!

**Comment by Michael-DJI** [comment]
try to add "abiFilters" in defaultConfig  (defaultConfig is located inside your build.gradle file)  like following:
    defaultConfig {
        ......
        ndk {
            abiFilters 'armeabi-v7a'
        }
    }

**Comment by GIS-HowardZhang** [comment]
hi @Michael-DJI ,

Thanks for your advice, but it didn't work for me either. I wonder if the proguard-rules provided by DJI has forgotten to keep some important class.

**Comment by Michael-DJI** [comment]
Hi @GIS-HowardZhang, Could you please provide your device information? like which drone and which  phone or pad you were testing with, normally our proguard file is tested by our testing team, it shouldn't be the problem, but still you could try to use our AAR package and use the following rule:
"-libraryjars ./PATH_TO_THIS_FILE/dji_android_sdk.aar", then you could ignore the proguard file we mentioned.

**Comment by Michael-DJI** [comment]
@GIS-HowardZhang we hame a template:

#### Is this issue about bugs or crash issues of DJI Android SDK and Sample Code?

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

-  Description of the issue.
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

**Comment by GIS-HowardZhang** [comment]
@Michael-DJI  
Of cause I am using the latest `dji-sdk.aar` . I have already solved this problem just by simply adding ``-keep class dji.midware.** {*;}`` to the proguard-rules. But still thanks a lot!

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
