### ISSUE TITLE
Keep remote controller running when activating virtual stick

### ISSUE THREAD

**Issue by amirfarazmand** [dji-sdk/Mobile-SDK-Android#155]
I am using the Android sample code for Phantom 3. This code works fine; however, it disables the remote controller and only allows the virtual stick control aircraft. I dont see any method disabling the remote. How can I keep the remote controller in charge when calling this method? It is actually quite dangerous as the mobile crashed and the aircraft was hanging up in the air until I restarted the mobile.

            case R.id.btn_enable_virtual_stick:
                DJISampleApplication.getAircraftInstance().
                        getFlightController().enableVirtualStickControlMode(
                        new DJICompletionCallback() {
                            @Override
                            public void onResult(DJIError djiError) {
                                Utils.showDialogBasedOnError(getContext(), djiError);
                            }
                        }
                );

**Comment by Michael-DJI** [comment]
if you are using 3.5 version of Mobile SDK, you could use "disableVirtualStickControlMode()" to disable it,  but for later version the method changed to "setVirtualStickModeEnabled()" you could use this to enable or disable it

**Comment by talobin** [comment]
@amirfarazmand 
Using VirtualStick and RC are mutually exclusive.
Like @Michael-DJI said, if you want to disable VirtualStick please use the suggested interfaces.
Another way to quickly turn off VirtualStick is to switch the FlightMode switch of the RC. That will also immediately turn off VS, hence enable the RC.
