### ISSUE TITLE
Errors received in automatic waypoint missions. Mobile SDK DJI.

### ISSUE THREAD

**Issue by filthros** [dji-sdk/Mobile-SDK-Android#156]
Hello,

 I'm having problems when creating automatic missions with mobile DJI sdk, sometimes it works perfectly, but other times I receive messages like:

"The execution could not be executed"
"The system is too busy to execute the action"

I do not understand why I am getting these messages, when in reality nothing in my code changes from one execution to another.

Is there a way to get the drone out of this situation and execute the mission commands correctly?

My frame is a matrice 600 pro with the latest firmware.

Thank you very much.

Regards

**Comment by rohitrameshrao** [comment]
Same here. Keep getting "The execution could not be executed". And it is random. Some times, when I try to re upload the mission, it goes though successfully.

**Comment by nextfullstorm** [comment]
You need to manually check if mission uploaded successfully. For example, `WaypointMissionOperator.uploadMission` callback returns not after mission **uploaded**, but after mission **started** to upload. And if you have long enough mission and call `WaypointMissionOperator.startMission` inside `uploadMission` callback you will receive exactly this message - "The execution could not be executed". So you need to wait while `WaypointMissionOperator().getCurrentState() == WaypointMissionState.UPLOADING` and after that check if `WaypointMissionOperator().getCurrentState() == WaypointMissionState.READY_TO_EXECUTE` before call `WaypointMissionOperator.startMission`.

**Comment by oliverou** [comment]
Thanks @nextfullstorm for the detail explanation! @filthros, you will get these warning messages if you don't follow the correct way of using `WaypointMissionOperator` and `DJIWaypointMission`. Please check the followings:

1. Firstly, you should invoke the [loadMission()](http://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=loadmission&i=0&#djiwaypointmissionoperator_loadmission_inline) method to load the WaypointMission into device memory and then invoke [uploadMission()](http://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=uploadmission&i=0&#djiwaypointmissionoperator_uploadmission_inline) method if there is no error.
2. After you invoke the  [uploadMission()](http://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=uploadmission&i=0&#djiwaypointmissionoperator_uploadmission_inline) method, you should check if there is any error in the completion block, and invoke the [getCurrentState()](http://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html#djiwaypointmissionoperator_currentstate_inline) method of `WaypointMissionOperator` to check if the current state is `READY_TO_EXECUTE`  
3. Lastly, invoke the [startMission](http://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html#djiwaypointmissionoperator_startmission_inline) method to start the execution of the uploaded mission.

For more details, please check the [Creating a MapView and Waypoint Application](http://developer.dji.com/mobile-sdk/documentation/android-tutorials/GSDemo-Google-Map.html) tutorial.

**Comment by jiyangyang0319** [comment]
Hello,
   I encountered the same problem，and invoke the getCurrentState() method of WaypointMissionOperator,the current state is READY_TO_UPLOAD because of MissionState is NOT_READY. I don't konw why？ I will be grateful for your help @oliverou 
and I rewrite the method of adding waypointList.
 private void addPath(){
        List<LatLng> pathPoint=addPointsToPath();
        for(int i=0;i<pathPoint.size();i++){
            markWaypoint(pathPoint.get(i));
            Waypoint mWaypoint = new Waypoint(pathPoint.get(i).latitude,pathPoint.get(i).longitude, altitude);
            if (waypointMissionBuilder != null) {
                waypointList.add(mWaypoint);
                waypointMissionBuilder.waypointList(waypointList).waypointCount(waypointList.size());
            } else {
                waypointMissionBuilder = new WaypointMission.Builder();
                waypointList.add(mWaypoint);
                waypointMissionBuilder.waypointList(waypointList).waypointCount(waypointList.size());
            }
        }
       
    }

**Comment by jiyangyang0319** [comment]
Hello,
     I encountered the same problem，and invoke the getCurrentState() method of WaypointMissionOperator,the current state is READY_TO_UPLOAD because of MissionState is NOT_READY. I don't konw why？ I will be grateful for your help @oliverou 
and I rewrite the method of adding waypointList.

    private void addPath(){
          List pathPoint=addPointsToPath();
         for(int i=0;i<pathPoint.size();i++){
         markWaypoint(pathPoint.get(i));
        Waypoint mWaypoint = new Waypoint(pathPoint.get(i).latitude,pathPoint.get(i).longitude, altitude);
        if (waypointMissionBuilder != null) {
                 waypointList.add(mWaypoint);
                 waypointMissionBuilder.waypointList(waypointList).waypointCount(waypointList.size());
         } else { 
                 waypointMissionBuilder = new WaypointMission.Builder();
                 waypointList.add(mWaypoint);
                 waypointMissionBuilder.waypointList(waypointList).waypointCount(waypointList.size());
         }
        }

    }

**Comment by oliverou** [comment]
Hi @jiyangyang0319 , how do you get the `NOT_READY` of MissionState? Please try to upgrade your aircraft's firmware and use the latest Android SDK 4.3 and test it again.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by rangerzhou** [comment]
> You need to manually check if mission uploaded successfully. For example, `WaypointMissionOperator.uploadMission` callback returns not after mission **uploaded**, but after mission **started** to upload. And if you have long enough mission and call `WaypointMissionOperator.startMission` inside `uploadMission` callback you will receive exactly this message - "The execution could not be executed". So you need to wait while `WaypointMissionOperator().getCurrentState() == WaypointMissionState.UPLOADING` and after that check if `WaypointMissionOperator().getCurrentState() == WaypointMissionState.READY_TO_EXECUTE` before call `WaypointMissionOperator.startMission`.

Thanks very much!!!
