### ISSUE TITLE
Cannot set targetSDK to 23 and also build to a 6.0 device due to .so file text moves. ( java.lang.UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by VicV** [dji-sdk/Mobile-SDK-Android#16]
If you attempt to do this, you will see:

`12-01 15:53:25.657 18600-18600/com.jarone.litterary W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/.../arm/libDJICam.so: has text relocations`

See here:

http://stackoverflow.com/questions/32346402/libavcodec-so-has-text-relocations

If you are seeing this, set your targetSDK of your project to 22 until DJI fixes this.

**Comment by SilverChangjian** [comment]
Thanks  for your reporting, we will try to reproduce it and then fix it ASAP.

**Comment by SilverChangjian** [comment]
Please set the compile version to lower than 23 (Android 6.0).

**Comment by VicV** [comment]
Well that's hardly fair, any plans on actually fixing the problem?
