### ISSUE TITLE
Waypoint Mission upload succes, but can't start with a Common Error

### ISSUE THREAD

**Issue by ltluc253** [dji-sdk/Mobile-SDK-Android#160]
I've created a mission fly across No-Fly Zone, but when prepare mission the SDK don't throw any error. Then, I start mission it throw a [common error](https://developer.dji.com/api-reference/android-api/Components/SDKError/DJIError_DJISDKError.html#djierror_djisdkerror_commandexecutionfailed_inline), it is difficult to investigate the cause of error.  I've test on iOS app, it throw [this error](https://developer.dji.com/api-reference/android-api/Components/SDKError/DJIError_DJIMissionManagerError.html#djierror_djimissionmanagererror_mission_result_mission_across_noflyzone_inline) when prepare mission, and we can handle this case.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
