### ISSUE TITLE
DJI GEO System Tutorial problems

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-SDK-Android#161]
-  Description of the issue.
http://developer.dji.com/mobile-sdk/documentation/android-tutorials/GEODemo.html
Documentation for GEO system has incorrect declaration for flight controller, `DJIFlightController ` does not exist it should be `FlightController`

**Comment by oliverou** [comment]
Hi @kwong93 , thanks for your feedbacks! The tutorial has been updated, please check it again.
