### ISSUE TITLE
Timeline Mission Unable to execute all actions

### ISSUE THREAD

**Issue by fred-aims** [dji-sdk/Mobile-SDK-Android#162]
Hi,

I have a timeline mission with a TakeOffAction and a series of GoToActions. When I run code, after the TakeOffAction and the first GoToAction have been executed, the mission calls the finished event and the remain go to actions are not executed. I have been try to fix this error for about 3 days now and it looks like the error is not coming from my end. Could this be a bug in the sdk?

**Comment by oliverou** [comment]
Hi @fred-aims, could you help to check the distance between the GoToActions? The distance should not be less than 0.5 meter.

**Comment by fred-aims** [comment]
Hi @oliverou please the minimum distance between the two successive points is about 10 meters

**Comment by oliverou** [comment]
Hi @fred-aims, got you. Please provide the following info for us to investigate the issue:

1. Your test case or source code of using the Timeline Mission
2. The error or crash logs of the issue (If you can find it, it would be very helpful)
3. The GPS coordinates of the home point and different GoToActions 
4. The steps to reproduce the issue (It would be great if you can provide this)
5. DJI Android SDK version you are using (Like Android SDK 3.4, etc)
6. DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
7. Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
8. Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
9. Android Studio version you are using (Like Android Studio 2.2, etc)

Thanks!

**Comment by fred-aims** [comment]
Hello @oliverou,

I just tried executing the mission and it worked and I did not change anything in the code.
Question 1-4
I am sorry I won't be able to upload my entire code how ever I can provide the relevant part

double homeLatitude = 5.560346
double homeLongitude = -0.297047
MissionControl birdControl = MissionControl.getInstance();
MissionControl.Listener elements = new ArrayList<>();
List<TimelineElement> birdListener = new MissionControl.Listener() {
            @Override
            public void onEvent(@Nullable TimelineElement timelineElement, TimelineEvent 
            timelineEvent, @Nullable DJIError djiError) {
                updateTimelineStatus(timelineElement, timelineEvent, djiError);
            }

        };

// I add the TakeOffAction
TakeOffAction takeOff = new TakeOffAction();
elements.add(takeOff);

// I add a GoToAction that lifts the drone 50m above the home location
GoToAction set_altitude = new GoToAction(new LocationCoordinate2D(homeLatitude, homeLongitude), (float) 50);
elements.add(set_altitude);

// I add another GoToAction
GoToAction go_to_1 = new GoToAction(new LocationCoordinate2D(5.560303, -0.296570), (float) 50);
elements.add(go_to_1);

// I add another GoToAction
GoToAction go_to_2 = new GoToAction(new LocationCoordinate2D(5.559919, -0.296463), (float) 50);
elements.add(go_to_2);

// I add another GoToAction
GoToAction go_to_3 = new GoToAction(new LocationCoordinate2D(5.560050, -0.297037), (float) 50);
elements.add(go_to_3);

// finally I add a GoHomeAction
GoHomeAction goHome = new GoHomeAction();
elements.add(goHome);

// this is to run the mission
MissionControl.getInstance().startTimeline();

On a click of a button, this code should be implemented

The issue was that, when the button is clicked, the drone takes off, moves to a heigh of 50 meters above the home point and then displays Timeline event is finished fails to execute the remaining actions;

Question 5: I am using the SDK 4.2.1

Question 6: I am using a Mavic Pro

Question 7, 8: The android version is 5.0.2 and the device name is samsung S6 edge

Question 9: The android android studio version is 2.3.3

Thank you

**Comment by fred-aims** [comment]
Hi @oliverou ,

Please have you been able to replicate the problem and solve it.
The problem has come up again

**Comment by zoemcateedji** [comment]
4.3 Was just released and contains many improvements to the Timeline Mission manager.  Could load that version and let us know how it goes?
https://developer.dji.com/mobile-sdk/downloads/

**Comment by fred-aims** [comment]
Thanks @zoemcateedji, I will do that and get back to you.
