### ISSUE TITLE
setOnboardSDKDeviceDataCallback not firing

### ISSUE THREAD

**Issue by buckaroo68** [dji-sdk/Mobile-SDK-Android#163]
Matrice 100 FW: 1.3.1
Onboard SDK: 3.3.1
Mobile SDK: 4.2
Device: Nexus 6 (7.1.1)

After sending data from the OnboardSDK using sendDataToMSDK just like in the example [here](https://github.com/dji-sdk/Onboard-SDK/tree/3.3/sample/linux/mobile), I setup the callback on the mobile side using setOnboardSDKDeviceDataCallback. The callback is never getting fired after sending the data. I built the OnboardSDK with debug mode and verified that it is allocating the message and should be sending correctly. For whatever reason the callback is never fired, could this be a bug in the Mobile SDK or maybe some version incompatibilities?

-buck

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Also, please remember you have to connect aircraft to DJIGO first to activate OnboardSDK
Thanks!
