### ISSUE TITLE
What is the acceleration of the Phantom 4 Pro when accelerating and braking?

### ISSUE THREAD

**Issue by GIS-HowardZhang** [dji-sdk/Mobile-SDK-Android#166]
I want to know the acceleration of  Phantom 4 Pro when braking and accelerating at a waypoint, so that I can get the accurate time needed to fly and the max velocity aircraft can accelerate between two waypoints.

**Comment by oliverou** [comment]
Hi @GIS-HowardZhang, currently, DJI Android SDK doesn't provide such acceleration data.
