### ISSUE TITLE
Create folders / custom naming format in SD card

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-SDK-Android#168]
-  Description of the issue.
Is there a way to set the output location of the photos and change filenames in the SD card taken by the camera? Currently all photos taken by the camera are in one folder. I would like them categorized into different folders on the SD card.

**Comment by Michael-DJI** [comment]
it's not supported by current firmware

**Comment by StiflerJj** [comment]
Is this issue supported in M200 now?@Michael-DJI

**Comment by Michael-DJI** [comment]
@StiflerJj I don't think so
