### ISSUE TITLE
Leaked IntentReceiver

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#17]
Hello, 

When exiting, I receive the following error:

> Service has leaked IntentReceiver dji.internal.version.c@4309fc40 that was originally registered here. Are you missing a call to unregisterReceiver()?

It says that the IntentReceiver has been registered somewhere in "initParams", called by "DJISDKManager.initSDKManager()".

Could you tell me which IntentReceiver is registered by "initSDKManager()" and how to unregister it?

Thanks in advance!

**Comment by SilverChangjian** [comment]
Thanks for report it. I have recorded in our tracking list. Will provide the result soon.

**Comment by JonasVautherin** [comment]
Do you have any news about that?

**Comment by JonasVautherin** [comment]
Is it the right place to ask this question?

**Comment by SilverChangjian** [comment]
Thanks for your report. That is the aoa accessory receiver. Will fix it in the coming version.

**Comment by kenargo** [comment]
http://forum.dev.dji.com/forum-90-1.html would be better.

 

In fact this email goes to developers and is quickly turning into a spam overload (IMO).

**Comment by talobin** [comment]
Will go ahead and close this issue since its been too long.
@JonasVautherin please feel free to reopen if you find version 4.3.2 still has this problem.
Thank you!
