### ISSUE TITLE
First call of DJISDKManager.getInstance().registerApp() fails (DJI SDK 4.3.2)

### ISSUE THREAD

**Issue by rusakovam** [dji-sdk/Mobile-SDK-Android#171]
Hi,

I am using Android DJI SDK 4.3.2. Android 7.0.

I found that _on fresh app installation_, the following code snippet never actually hooks a callback:
```
DJISDKManager.getInstance().registerApp(context, sdkManagerCallback);
```

I found some solution to this:
By previously calling `DJISDKManager.getInstance()` several seconds earlier, for instance: 
```
Log.d(TAG, "DJI sdk version: " + DJISDKManager.getInstance().getSDKVersion());
```
I get this line in log output:
```
D/SDKRelativeJNI: load lib suc
```
And the sdkManagerCallback is ok then.

So, DJISDKManager.getInstance() does some async work on the background, like loading libs. 

Is there a proper way to know, when DJISDKManager instance is actually ready?

Thank you.

**Comment by talobin** [comment]
Hi @rusakovam .
Can you repo this in our Sample app?
Which Android device are you using?

**Comment by talobin** [comment]
@rusakovam Will close this ticket for now.
If you can give us a repo with our Sample App, please feel free to reopen.
