### ISSUE TITLE
setMode fails with not support

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-SDK-Android#173]
-  Description of the issue.
calling `camera.setMode(SettingsDefinitions.CameraMode.MEDIA_DOWNLOAD...` fails sometimes with not support when using P4, but using a P4 PRO I don't get this error
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
```
        if (camera != null) {
            mediaManager = camera.getMediaManager();

            if (mediaManager != null) {
                camera.setMode(SettingsDefinitions.CameraMode.MEDIA_DOWNLOAD, new CommonCallbacks.CompletionCallback() {
                    @Override
                    public void onResult(DJIError djiError) {
                        if (djiError == null) {
                            mediaManager = camera.getMediaManager();
                            mediaManager.refreshFileList(new CommonCallbacks.CompletionCallback() {
                                @Override
                                public void onResult(DJIError djiError) {
...

                                }
                            });
                        } else {
// fails here with not support
                        }
                    }
                });
            } else {
...

            }
        } else {
...

        }
```

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
```
        minSdkVersion 19
        targetSdkVersion 26
```
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Phantom 4
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
6.0.1
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
Samsung Galaxy S7 and Verizon Ellipsis 10 Tablet
-  Android Studio version you are using (Like Android Studio 2.2, etc)
2.3.3

**Comment by zoemcateedji** [comment]
Thanks for reporting this!  A developer will look into this as we were able to reproduce the issue.

**Comment by zoemcateedji** [comment]
Seems like a firmware issue: On one P4 with camera firmware with new **01.20**.55.81 we CAN"T repro the problem. (On the older camera firmware **01.19**.52.66 we can reproduce it.)  Please do a firmware check  - DJI Go 4 should prompt you to take a firmware upgrade.

Hope that helps!
