### ISSUE TITLE
Poor connection of app and dji-sdk.

### ISSUE THREAD

**Issue by tubipham** [dji-sdk/Mobile-SDK-Android#178]
1. It seems the software did not receive the signal when I unplugged the connection cable and plugged it back.
2. Sometimes the display software is connected, then turned off immediately.
3. Sometimes when I plug in the cable, the software does not receive the signal from the controller, I have to clean it in the background, reopen it, unplug it, and attach the cable to get the signal.

Please check this video https://www.dropbox.com/s/4rgcl9q3xy77ym6/Screencast_2017-10-25-08-50-02.mp4?dl=0

P/S: In the video, when the N icon appears and 66% is when I attach the cable to my phone.

DJI Android SDK: 4.3
DJI Product: P3P
Android system version: 7.1.1
Android device: Sky a900
Android Studio version: 2.3.3

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
