### ISSUE TITLE
Fix manifest merge during Gradle Build (unknown element <receiver> found in the merged manifest)

### ISSUE THREAD

**Issue by ZeroCool2u** [dji-sdk/Mobile-SDK-Android#179]
The receiver is getting merged before the application tag in the build AndroidManifest.xml file. This issue was referenced in #167 but the poster closed the issue prior to its resolution. A temporary work around can be used by setting `android.enableAapt2=false` in the gradle.properties file, but this is not a permanent fix and breaks all existing DJI tutorials. The build errors out with the merged file looking like this: 

`    <uses-permission android:name="dji.permission.broadcast" /> 
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />

    <receiver
        android:name="dji.logic.receiver.DJIPilotStartupReceiver"
        android:exported="true"
        android:permission="dji.permission.sdk.wifi" >
        <intent-filter>
            <action android:name="dji.pilot.STARTUP" />
            <action android:name="dji.go3.STARTUP" />
            <action android:name="dji.go4.STARTUP" />
        </intent-filter>
    </receiver> 
    <application
        android:allowBackup="true"
        android:debuggable="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme" >

        
        <uses-library android:name="com.android.future.usb.accessory" />`

This effects all users using Android Studio 3.0 and above, because AAPT2 is enabled by default. 
@oliverou @talobin Is there any news on a fix for this?

**Comment by ZeroCool2u** [comment]
@oliverou @talobin [This](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#aapt2_element_hierarchy) and [this](https://developer.android.com/guide/topics/manifest/manifest-intro.html#filestruct) might be helpful in fixing the issue. Perhaps this would fix some other bugs as well, because if it's still happening when we enable the work around, it's just being ignored, it likely still breaks other things.

**Comment by talobin** [comment]
@ZeroCool2u ,
Thank you for reporting this issue.
We are aware of this problem and has fixed this in our current development code.
The next SDK release will come with this permanent fix.
I hope the `android.enableAapt2=false` work around is fine with you for now.

**Comment by ZeroCool2u** [comment]
@talobin Thanks, that's great to hear. Do you have any kind of time estimate for the next release that includes the fix? I'm not looking for an exact timeline, just if it's imminent, like sometime in the next week or two, or much farther off.

**Comment by talobin** [comment]
Hi @ZeroCool2u ,
It is still early to say the estimate release date. I can only tell you right now that it is within 2 months.
Definitely won't be able to release in "the next week or two".

**Comment by ZeroCool2u** [comment]
@talobin No problem, we've mitigated the issue in our project for now. I just wanted to make sure it wasn't something that we'd need to deal with reverting very soon. Thanks!

**Comment by kosmelnikov** [comment]
Hi @talobin 
Any updates as for this issue?

**Comment by jtuchek** [comment]
disabling aapt2 does seem to resolve the issue if you're migrating to Gradle 3+

**Comment by kosmelnikov** [comment]
Hi @talobin
Any updates as for this issue?
When you are going to release updated SDK?

**Comment by talobin** [comment]
@ZeroCool2u @kosmelnikov 
This should be fixed with the release of SDK 4.4.1.
Please check it out.
Thanks!

**Comment by ZeroCool2u** [comment]
Awesome, will take a look! Thanks!
