### ISSUE TITLE
WaypointMissionOperator removeListener() does not remove the listener

### ISSUE THREAD

**Issue by JamesMasterman** [dji-sdk/Mobile-SDK-Android#180]
I have a class that implements WaypointMissionOperatorListener and registers for WaypointMissionOperator updates using MissionControl.getInstance().getWaypointMissionOperator().addListener(this);

When I am done with listening for updates I call  MissionControl.getInstance().getWaypointMissionOperator().removeListener(this); 

However, the class continues to receive updates through the WaypointMissionOperatorListener methods (Eg. onExecutionUpdate continues to be called).

This leads to unintended behaviour as well as a potential memory leak.

- I am using DJI Android SDK 4.3.2
- Devices are Samsung S7, S2, Nexus 6P, Huawei media pad M3 (it's not device dependent, happens on all devices)
- Drones are Mavic Pro, Phantom 4 Pro, Phantom 4 (happens on all drones).
- Android studio 2.3.3

**Comment by kenargo** [comment]
My first guess would be that the this pointer is different.  Are you perhaps calling one or the other from a callback or other method where the this pointer maybe different?

**Comment by JamesMasterman** [comment]
Thanks kenargo, I thought that might be the case, but then I added some debug that prints the id of the pointer being added and removed. It appears to be the same object in my tests. eg. I add an object @d7ba823 then remove the same object @d7ba823 later on. 

However on a subsequent mission, onExecutionUpdate messages are still being sent to that object. 

I've added a flag as a workaround to ignore any messages from onExecutionUpdate in dead objects, but it seems a bit of a hack.

**Comment by talobin** [comment]
@JamesMasterman 
We will try to reproduce this and keep you posted.

**Comment by DJI-RobertLiu** [comment]
Hi James, can you double check if the waypointMissionOperator object you got in these two statements are same? 
MissionControl.getInstance().getWaypointMissionOperator().addListener(this);
...
MissionControl.getInstance().getWaypointMissionOperator().removeListener(this);

They might be different that depends on the actions you did between these two statements.

**Comment by JamesMasterman** [comment]
My sincere apologies. You are absolutely correct, the result of MissionControl.getInstance().getWaypointMissionOperator() was a different pointer when I was making the removeListener call to when I was calling addListener(). 

I had assumed (wrongly) that the WaypointMissionOperators was some kind of singleton or immutable object, but it's not. 

I have a fixed my code and removed that assumption and it works ok now.

This can be closed
