### ISSUE TITLE
I really need to find out，please help

### ISSUE THREAD

**Issue by Minhom** [dji-sdk/Mobile-SDK-Android#181]
How can the aircraft  continue its wayPointMission after the aircraft and remote control have lost their connection. I aleady set setExitMissionOnRCSignalLostEnabled(false). plz help.

**Comment by zoemcateedji** [comment]
What aircraft are you seeing this on, and what version of the SDK?

When you test with the simulator connected to the aircraft, and turn off the remote controller when the aircraft is on it's way to the first waypoint (after upload and take off) can you reproduce the issue?  We are seeing that even with the remote controller off, the aircraft runs the mission as expected with the remote controller off (I am using 4.3.2 and the M210)

**Comment by oliverou** [comment]
Hi @Minhom, you use the correct method, it's a bug and is resolved in our latest Android SDK 4.3.2, please download it on our developer website and try agian: http://developer.dji.com/mobile-sdk/downloads/

**Comment by talobin** [comment]
Will close this ticket.
@Minhom if 4.3.2 still has this problem, please feel free to reopen the issue.
