### ISSUE TITLE
How I can download the lastest sdk zip not by Maven and Gradle, I can not find the way to download

### ISSUE THREAD

**Issue by Minhom** [dji-sdk/Mobile-SDK-Android#182]
#### Is this issue about bugs or crash issues of DJI Android SDK and Sample Code?

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

-  Description of the issue.
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

#### Is this issue about DJI iOS SDK and Sample Code?

Then this is the wrong place, please refer to the Mobile-SDK-iOS Github: <https://github.com/dji-sdk/Mobile-SDK-iOS/issues>

**Comment by oliverou** [comment]
Hi @Minhom , currently, we don't provide Android SDK AAR file for developers to download directly. Please use Maven to get the latest Android SDK. You can check this tutorial: [Import Maven Dependency](http://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html#import-maven-dependency) to learn how to import DJI Android SDK to your Android Studio project by using Maven.

**Comment by Minhom** [comment]
So I don't need to import djiSDKLIB Module anymore?

**Comment by Minhom** [comment]
Like tutorial shown in view: http://developer.dji.com/mobile-sdk/documentation/android-tutorials/ImportAndActivateSDKInAndroidStudio.html

**Comment by oliverou** [comment]
Yes, please follow the tutorial to import the Android SDK.

**Comment by oliverou** [comment]
Close this ticket now. If you have any questions, please feel free to reopen it.

**Comment by Minhom** [comment]
I already fixed my problem，thanks！
