### ISSUE TITLE
Missing photos on waypoint mission

### ISSUE THREAD

**Issue by tomerdaniel** [dji-sdk/Mobile-SDK-Android#184]
Recently, we've started to get complaints from several pilots using either P3A, Inspire 1 or P4P for missing photos on waypoint mission. That is, some photos are missing at the end of mission. All of those missions are collecting around 90 photos per mission. Most missions are simple 90 waypoints task with a single action on each waypoint to take a photo. At the end of the mission, some photos (~3-9) are missing at random. There are no reported errors. 

We've reproduced the same scenario on DJI Assistant 2 simulator using P4P and a simple 90 points mission with single action.  Same results - random photos missing. No signal interference, no wind. Nothing physical to prevent the drone from taking the picture.

We are currently using latest DJI Android SDK v4.3.2
Android tablet brand: Galaxy Tab A, Model: SM-T280
Phantom 4 Pro Aircraft Firmware: V01.04.0602 (Reported by SDK: 03.02.35.05), RC Firmware: 01.04.01.00

**Comment by oliverou** [comment]
Hi @tomerdaniel, thanks for the feedbacks! We have addressed this issue and are investigating it now. For the P4P, this issue will be fixed in the upcoming version of firmware. For P3A and Inspire 1, we will inform you if there is any progress on it.

**Comment by JamesMasterman** [comment]
That's wonderful news. I've seen the same thing on all models of DJI aircraft I've used for the last 2 years. Exactly as tomerdaniel described. It's great that a fix is coming out for this!

**Comment by martindroneharmony** [comment]
We also have similar reports from our userbase to what tomerdaniel is describing. Good to know that there is a bug fix on the way. Thanks!

**Comment by ITCCodeDev** [comment]
We have seen the same issue with our Inspire 1 flights and M100 flights with a waypoint mission that has a start_shoot_photos with intervalometer command only in the beginning of the waypoint mission. A fix will be greatly appreciated! Thanks!

**Comment by trofunenko** [comment]
Has there been any progress with this issue?

**Comment by martindroneharmony** [comment]
Unfortunately, apart from the message of oliverou on 9th of November none that I know of. Meanwhile reports of missing images are steadily coming in from our user base, all leading back to this issue.

Let's hope they find the problem at some point.

**Comment by tomerdaniel** [comment]
I've updated to latest SDK 4.4.0 and ran a simulator test for 215 waypoints. Sadly, the drone only took 211 photos. Looking at the release notes this issue is not in the _bugfix_ neither it is in the _known issues_.
@oliverou can you please update on this issue status?

**Comment by Michael-DJI** [comment]
hi @tomerdaniel, we also found the issue, but I think it' s not only associated with software and we need do more investigation, will try to fix it ASAP, thanks for your feedback!

**Comment by tomerdaniel** [comment]
Hi @Michael-DJI , @oliverou 3 months has passed, and I'm curious if you guys are having any progress?
Obviously we are still having those issues...

**Comment by t-o-o-m** [comment]
Are there any news in this regard? I (am trying to) use my P3A professionally, which isn't possible at all while this error persists.

**Comment by Michael-DJI** [comment]
it has been fixed in latest  P4P firmware.

**Comment by Michael-DJI** [comment]
update:
it's fixed in v01.06.0800 of P4P but this version of firmware is not visible to all users, if you need update to 01.06.0800 for the fixing of "Missing photos on waypoint mission" issue, please send email to dev@dji.com

**Comment by tomerdaniel** [comment]
Thanks @Michael-DJI !
Since our customers are using our software with their own drones, they would need to have access to fixed firmware. Are you expecting to release this firmware fix for general availability anytime soon?

**Comment by Michael-DJI** [comment]
@tomerdaniel you're welcome! it will not be released soon, my suggestion is letting your customer contact the dev@dji.com, and provide their DJI account, then use DJI Assistant 2 to upgrade the firmware to v01.06.0800.

**Comment by tomerdaniel** [comment]
Thanks @Michael-DJI 
Here's the response I got when I asked dev@dji.com for the FW version. Can you please assist?

> Thank you for contacting DJI Developer Support with this request.  Currently this firmware version is not yet public and so I have added you to a list for the engineers to provide you with the firmware.  There is not yet an estimate of when this can be released but I will reach back out to you where there is an update.  If you have any other developers or customers who also want to be put on the list please have them also reach out to us directly!

**Comment by dji-lisafedane** [comment]
@tomerdaniel - your DJI Developer account has been updated to receive the firmware update.  Please  login to DJI Assistant 2 for Phantom software connect the P4P to it - the beta firmware will appear in the firmware list.
