### ISSUE TITLE
To finish waypointMission，can I use my own map(by geoserver)，or local offline map

### ISSUE THREAD

**Issue by Minhom** [dji-sdk/Mobile-SDK-Android#185]
When used in rural areas, Google Maps can not provide HD maps，so I need to know if I can use the map I released , to create a waypointMisson,and upload,start the waypointMission

**Comment by talobin** [comment]
Hi @Minhom the SDK doesn't care which map you use for the WaypointMission.
What it cares is the coordinate you give for each Waypoint.
You can use any Maps solution that works for you, get the coordinates, and pass it in to the SDK.

Please refer to our API reference if you want to explore more about waypoint:
https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypointMissionOperator.html?search=waypoint&i=20&
Our SDK Sample code also shows you how to use WaypointMissionOperator
https://github.com/dji-sdk/Mobile-SDK-Android/tree/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/missionoperator
