### ISSUE TITLE
Flight controller serial number string is cropped for M200 and Inspire 2 aircraft

### ISSUE THREAD

**Issue by JamesMasterman** [dji-sdk/Mobile-SDK-Android#186]
I'm using FlightController.getSerialNumber() to get the flight controller serial number from the drone that my software is currently connected to. For most models of drones this works fine, however for Inspire 2 and M200/M210 aircraft, the serial number is missing the last 4 digits compared with what is reported in DJI GO. 

For example, on an Inspire 2 it returns 095XE16002, when the real serial number from DJI GO is 095XE16002**1234**

SDK version: 4.3.2
Aircraft: Inspire 2, M200, M210 are the aircraft that have the issue.  I've tested on P4, P4 Pro and Mavic Pro and they work ok, the full serial number is returned.
Android studio: 2.3.3
Devices: Samsung S7, S2, Huawei M3 tablet, Nexus 6P phone (it's not device dependent)

**Comment by talobin** [comment]
Hi @JamesMasterman 
Thanks for reporting the bug.
We will try to reproduce this and keep you posted.

**Comment by talobin** [comment]
@JamesMasterman 
We were able to confirm this was a bug in 4.3.2.
It will be fixed with 4.4 release.

**Comment by talobin** [comment]
@JamesMasterman This has been fixed with the release of SDK 4.4.1.
Please check it out.
Thanks!

**Comment by KahWeing** [comment]
Hi, May i know on the dji sdk can i get the serial number of the drone?
