### ISSUE TITLE
Simple Data Transmission App - Android

### ISSUE THREAD

**Issue by dienstagfpv** [dji-sdk/Mobile-SDK-Android#187]
hi,

i got the sample and example apps running and now wanted to implement a super simple android-application to show data on my android device that i get from my A3 / M100 via Data Transparent Protocoll.

Im using the ActivationAndBinding-Demo App (app itself is working) as my starting point and tried to implement the code ( 
https://developer.dji.com/onboard-sdk/documentation/M100-Docs/application-development-guides/data-transparent-transmission.html ) to my app by simply copying it to the end of my MainActivity. But i cant get it to work properly. Am i missing something?

I get all kinds of errors, mostly "Cannot resolve Symbol" - See image below. As im quite new to Android development i hoped to find a easy solution for my problem. I think my problem is kind of essential but i cant find a solution.. any kind of help is very appreciated! Thanks!

I use Android Studio 3.0 (auto import activated) and Mobile SDK 4.3.2. 

![grafik](https://user-images.githubusercontent.com/22576193/32856650-a928914e-ca45-11e7-940c-355074aae39b.png)

**Comment by jtuchek** [comment]
@dienstagfpv that sample project may be out of date (using SDK v3.5.x)

New documentation for SDK 4.0+ will show some class name changes such as "DJIAircraft" -> "Aircraft", "DJIFlightController" -> "FlightController", etc.

You cannot import those objects for use as they no longer exist in the SDK under that name.

**Comment by oliverou** [comment]
Hi @jtuchek, thanks for pointing it out! @dienstagfpv, sorry for the confusion, we have updated the documentation to the latest SDK APIs, please check it agian: https://developer.dji.com/onboard-sdk/documentation/M100-Docs/application-development-guides/data-transparent-transmission.html

**Comment by dienstagfpv** [comment]
thanks @jtuchek and @oliverou! i somehow had figured it out before, but wasnt 100% sure ;) 
now it seems to work, thank you!

**Comment by oliverou** [comment]
No problem. Close this issue now, if you have any questions, please feel free to reopen it.

**Comment by dienstagfpv** [comment]
just noticed that the page: https://developer.dji.com/onboard-sdk/documentation/M100-Docs/application-development-guides/data-transparent-transmission.html seems to be back-dated again with wrong examples: 
![image](https://user-images.githubusercontent.com/22576193/33174443-5de5758a-d058-11e7-951b-4c038cd184c5.png)

**Comment by oliverou** [comment]
Hi @dienstagfpv , thanks for informing us and sorry for the inconvenience. The documentation is updated now. Please help to check it again.
