### ISSUE TITLE
Timeline errors just after takeoff but waypoint mission proceeds anyway

### ISSUE THREAD

**Issue by JamesMasterman** [dji-sdk/Mobile-SDK-Android#188]
I am seeing occasional errors reported through the timeline onEvent() listener. I have not found a way to reproduce it reliably, but it happens in probably 1 in 10 times using exactly the same mission, mainly on the Mavic Pro although I have seen it on other aircraft.

I have a Timeline that contains a GimbalAttitudeAction command, then a Waypoint mission with ~10 waypoints in it. After executing the GimbalAttitudeAction, the waypoints are uploaded then the aircraft takes off. About 5 seconds after takeoff, I get an error "The system is too busy to execute the action" or sometimes "The execution could not be executed". However, the waypoint mission still proceeds as normal with no issues.

This is very confusing for our users.

What I think is happening is the Timeline itself has timed out/stopped, but the uploaded waypoint mission is now on the aircraft and is executing as if it was just a normal waypoint mission, not part of a Timeline. I still get callbacks from the Waypoint mission operator, but not from the Timeline, until another Timeline is uploaded later. Sometimes I need to restart the App, RC and Drone to make another Timeline work 

- DJI Android SDK 4.3.2
- Most often occurs on Mavic Pro but have also seen it on the Phantom 4 and Phantom 4 Pro
- Android 7 and 8 on Samsung S7, S2, Nexus 6P, Huawei Media Pad M3
- Android Studio 3.0 and 2.3.3

**Comment by talobin** [comment]
Hi @JamesMasterman 
Can you reproduce this using our sample app?
https://github.com/dji-sdk/Mobile-SDK-Android/tree/master/Sample%20Code
If so please provide me a gist of your personal code inside our sample app for us to reproduce.

Thank you.

**Comment by JamesMasterman** [comment]
Sure, I will give that a try and report back
