### ISSUE TITLE
Data Transmission - M100 vs A3

### ISSUE THREAD

**Issue by dienstagfpv** [dji-sdk/Mobile-SDK-Android#189]
Hi,

are there any differences M100 vs A3 regarding Data Transmission?
This "Data Transparent Transmission" page is located in "M100 Protocol Documents", which suggests that its a M100-only feature: https://developer.dji.com/onboard-sdk/documentation/M100-Docs/application-development-guides/data-transparent-transmission.html

Also see here (ok, this is not up to date): http://download.dji-innovations.com/downloads/dev/OnboardSDK/Data_Transparent_Transport_Introduction_v1.0.0_en.pdf 
it says: 
![grafik](https://user-images.githubusercontent.com/22576193/33134294-a52bf41e-cf9f-11e7-8700-71d1ddc5c818.png)

But then on this site, it seems to be a general OSDK / MSDK feature:
https://developer.dji.com/onboard-sdk/documentation/guides/component-guide-mobile-communication.html

Can you tell me if there are any differences in the latest OSDK / MSDK-Versions? 
Thanks!

**Comment by rohitsantdji** [comment]
To answer your question - there is no difference between A3 and M100 regarding Data transparent transmission, they should both work exactly the same. The [component guide](https://developer.dji.com/onboard-sdk/documentation/guides/component-guide-mobile-communication.html) page is up to date, and so is the protocol document page you linked to within the M100 docs section. It is kept within the M100 docs section for legacy reasons, and we intend to deprecate that section soon and move the useful information in there to relevant parts of the website.

**Comment by dienstagfpv** [comment]
Thanks!
