### ISSUE TITLE
无法链接控制器

### ISSUE THREAD

**Issue by smellok** [dji-sdk/Mobile-SDK-Android#19]
配置好app的密钥后，打包到手机上运行此app
连接好usb线（可以通过sdk校验），显示Status:No Product Connected.
环境信息：
手机：samsung note5, Android 5.1.1
机器：经纬100
机器固件：V1.5.8
SDK版本：V3.1，刚才拉的最新，没有修改任何代码（除了app密码配置外）。

**Comment by SilverChangjian** [comment]
Thanks for your reply, could you please check your application has registered successfully?

**Comment by smellok** [comment]
yes, it's registered successed.
if not , a message like 'SDK Registration Failed.' shown.

**Comment by smellok** [comment]
1, int file DjiSampleApplication.java , line 40,  "mProduct" will return null.
2, method getDJIProduct() in DJISDKManager class
`return SDK_LEVEL >= 1?this.mBaseProduct:null;`
what is SDK_LEVLE? why my app sdk_level < 1?. how to check sdk_level??

**Comment by SilverChangjian** [comment]
The SDK_LEVEL should be 2 if you could successfully register the application. Could you please delete your application and then re-install it again and see toast message.

**Comment by SilverChangjian** [comment]
Hi @smellok , we found that the connectivity of the server might not be stable in past couple of hours. Could you please test it again now.?

**Comment by smellok** [comment]
i reinstall it.
i got a toast message : SDK 注册失败。but app key is correct.

**Comment by smellok** [comment]
@SilverChangjian 
now i reinstall it again.
internet connection is ok.
there is no sdk failed toast. just can't connect to my remote control.

**Comment by smellok** [comment]
@SilverChangjian 
in DJISKDManager.class file. i found code 
`boolean var1 = WifiStateUtil.ping(STAT_TEST_URL, 3000);`
is there any problem with STAT_TEST_URL ?
it's from SDKRelativeJNI.navive_getStatTestUrl()
`private static final String STAT_TEST_URL = SDKRelativeJNI.native_getStatTestUrl();`
maybe can not connect url that sdk provided.

checkPermission method can change 'SDK_LEVEL' value , is it fully tested?!

thank you .

**Comment by SilverChangjian** [comment]
I test it with the latest firmware in the website, it could register successfully and get the product. One thing i want to confirm with you is when the device connects to the remote controller, could you see a dialog for selecting the application you want to launch? If not, please upgrade the remote controller firmware.

**Comment by smellok** [comment]
yes, i can see a dialog let me to choose a default application.
and i have upgrade my remote control to the latest firmware V1.5.8 with dji assitant2 yesterday.
are you test it with this version.

**Comment by SilverChangjian** [comment]
Hi, i saw you closed the issues. Could you please share how do you do with this issue? Thank you in advance.

**Comment by smellok** [comment]
固件问题（曾经用dji go升级到最新固件的时候，40%左右失败了，然后就出问题了。）。
说来话长，直接去去换了一个新的遥控器，然后重新升级到了最新的固件。重新连接搞定了。
PS:
1，你们开发支持没有电话支持（社区支持不够）
2，给你们的dev@jdi.com发邮件，发了好几封，到现在还没有回复我。
3，你们的服务器是在是太不稳定了（经常SDK校验失败或者固件有时看是最新的，有时看又有更新）。
4，API文档太过于简洁了。还有很多API接口是abstract的，如果没有必要可以暂时不要放出来。等功能实现之后在放出来。

PSS：@SilverChangjian 您回答问题很有耐心，谢谢！

**Comment by SilverChangjian** [comment]
1. We do not provide that kind of service right now.
2. Our customer support will contact you soon.
3. We found several developers report this issue, we are investigating now.
4. About the abstract methods, all of the methods are implemented in the subclasses (We only provide the base class for developers). SDK Will help you to assign different components to the Product object automatically based on the connected products.

Thanks.

**Comment by FreemanX** [comment]
英文社区支持会好一点，有几个国外的developer在里面解答问题，不过有时候要等几天可能。也会有DJI support在里面解答，也非常不及时。
文档简洁得也确实有点过分了, 经常就是把function name 或者 enum values name 中间加个空格就是解释了。 但developer并不明白其含义， 例如：
public static final DJIFlightControllerDataType.DJIFlightControllerFlightMode Hover

Hover mode.
public static final DJIFlightControllerDataType.DJIFlightControllerFlightMode Joystick

Joystick mode.
public static final DJIFlightControllerDataType.DJIFlightControllerFlightMode Manual

Manual mode.
