### ISSUE TITLE
How to set the "App Output Mode" to EXT with SDK

### ISSUE THREAD

**Issue by chenxiaojin** [dji-sdk/Mobile-SDK-Android#191]
DJI Android SDK version : 4.0.1
DJI Product : LightBridge2,
Android system version: Android 6.0.1
Android device: XIAOMI 4
Android Studio version : 2.2.3

Use SDK 4.0.1 to connect LightBridge2, the connection is successful but can not see the video.
Use DJI GO App to connect , the video can be display, but the “APP Output Mode“ is EXT。
![image](https://user-images.githubusercontent.com/9512516/33364927-76b2c482-d521-11e7-82f7-5db102ff4267.png)

How can I set "App Output Mode" to EXT with SDK ？

**Comment by DJI-RobertLiu** [comment]
Please download the latest SDK version:DJI Android SDK version : 4.3.2
The sample app in this version has the demo on how to switch the live videos between cameras. 
The demo file is VideoFeederView.java.  In this file, you will see how to enable the EXT mode and how to set bandwidth for each camera.  Let me know if you have any problem with it.

**Comment by chenxiaojin** [comment]
@DJI-RobertLiu Thanks~ The problem has been solved
