### ISSUE TITLE
error "The waypoint request is running" on start WaypointMissionOperator 

### ISSUE THREAD

**Issue by trofunenko** [dji-sdk/Mobile-SDK-Android#192]
Sometimes, after start mission with WaypointMissionOperator.startMission, callback function return error - "The waypoint request is running". 
This case reproduce on simulator and yard, but never reproduce on Phantom 4. I cannot programatically interact anymore and forces me to restart the drone.  
The bug to reproduce during sequentially running mission with a lot of way points. 

-  DJI Android SDK version - 4.3.2
-  DJI Product - Phantom 3 Professional, firmware : 3P_FW_V01.11.0020 
-  Android system version - 5.0
-  Android device you are using - Samsung Note 3
-  Android Studio version - Android Studio 2.3.3

2017-11-29_055135_UTC_0a9c5cf8-9bc6-45d7-8218-28721af19ff5.zip - log created by archiveLog method. 

[2017-11-29_055135_UTC_0a9c5cf8-9bc6-45d7-8218-28721af19ff5.zip](https://github.com/dji-sdk/Mobile-SDK-Android/files/1513196/2017-11-29_055135_UTC_0a9c5cf8-9bc6-45d7-8218-28721af19ff5.zip)
[app_req.txt](https://github.com/dji-sdk/Mobile-SDK-Android/files/1513211/app_req.txt)

**Comment by DJI-RobertLiu** [comment]
Thanks for the report on this issue.  May I get more info:
1.  How frequently do you see this error "The waypoint request is running"?  When this error happens, did you try to call WaypointMissionOperator.stopMission? If yes, is there any additional error info? 
2. Btw, how many waypoints do you have in your mission?

**Comment by trofunenko** [comment]
1. How frequently do you see this error "The waypoint request is running"?  
approximately one in 3. 
2. When this error happens, did you try to call WaypointMissionOperator.stopMission? 
no i didn't. Drone states changed this way  READY_TO_UPLOAD -> UPLOADING (GPS_ATTI, LEVEL_4). 
3. Btw, how many waypoints do you have in your mission?
~70-80 points. Problem occurs also with 25 points.

**Comment by DJI-RobertLiu** [comment]
Thanks for the answer! It is very helpful in the issue investigation to us.  
Btw, please try to call the stopMission in such situation to see whether it can avoid restarting the drone?

**Comment by nextfullstorm** [comment]
(Didn't read logs, sorry)
Did you wait for READY_TO_EXECUTE state before calling WaypointMissionOperator.startMission? If not, try this. This not solves drone hang, but it avoids such hang. Right sequence to start mission is WaypointMissionOperator.uploadMission -> wait for READY_TO_EXECUTE -> WaypointMissionOperator.startMission.

**Comment by talobin** [comment]
@trofunenko SDK 4.4.1 has been released and Waypoint should be more stable.
Please try that out and reopen the ticket if the problem still occurs.
