### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void dji.internal.e.a.a()' on a null object reference

### ISSUE THREAD

**Issue by flyanra** [dji-sdk/Mobile-SDK-Android#193]
-  SDK throws a null pointer exception randomly when you start the app. The Exception occurs in the first minute after starting. Not always. only 5% chances when running and rerunning the app. 

-  Steps to reproduce - Create an app which includes DJI SDK, After sdk registration is done and then go to any activity,say go to main activity, it will crash after several tries. Drone need not be connected
-  Crash logs - STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'void dji.internal.e.a.a()' on a null object reference
at dji.sdk.sdkmanager.DJISDKManager$4.run(Unknown Source)
at java.lang.Thread.run(Thread.java:818)

-  DJI Android SDK version 4.3.2
-  Phantom 3 advance and Phantom 4 pro - More chances of crashing on phantom 3 Advance
-  Android system version - 6.0, 7.0
-  Android device - Motorola Moto g3, Moto g5, Samsung Tab 4
-  Android Studio version - 2.2.3

**Comment by talobin** [comment]
@flyanra Please make sure you only access SDK after registration has been done successfully.
If after that, the bug still reproduce, please let us know.

**Comment by thucld** [comment]
@talobin I am sure the application has registered successfully. But the error still arises (product is not connected)
DJI Android SDK version 4.3.2
Android Studio version 2.2.3
Device - Samsung Galaxy A5 2017 (SM-A520F)
Android version - 7.0
