### ISSUE TITLE
Gimbal yaw action in WaypointMission

### ISSUE THREAD

**Issue by puffosauro** [dji-sdk/Mobile-SDK-Android#194]
I have a suggestion for mobile SDK

In waypoint missions I can add an action to the waypoint to set the pitch of the gimbal (WaypointActionType.GIMBAL_PITCH). Unfortunately, there is no way to set the gimbal yaw too.
I know that I can rotate the aircraft (and it's what I'm doing at the moment), but I do NOT want to rotate the aircraft, firstly because I think is slower (for long missions the time is critical). Also, if I can't control the gimbal yaw, the 2 axis gimbal is useless.
I want the aircraft flying turned in the direction of the path. I think is more intuitive, and I can take advantage of the anti-collision sensors.

So, please, add a WaypointActionType.GIMBAL_YAW like the WaypointActionType.GIMBAL_PITCH

**Comment by talobin** [comment]
Hi @puffosauro ,
Thanks for the suggestion.
Unfortunately our Aircraft firmware does not allow to rotate gimbal_yaw in waypoint so the SDK can't do anything about it.
However, we are working on bring this feature to OnBoardSDK with the Mission feature of OnBoardSDK.

Thanks.
