### ISSUE TITLE
Peak Focus

### ISSUE THREAD

**Issue by Djacob502** [dji-sdk/Mobile-SDK-Android#196]
This is not a bug but just an enhancement to the android mobile sdk. 

I would like to use the Peak Focusing with the android mobile sdk. This is the option which puts red lines on the video stream to help with focusing. 

If this option is already present - then I apologize in advance but I cannot find it in the sdk. 

Thanks

**Comment by jtuchek** [comment]
That would be a cool feature to see for photography purposes.

Although just to expand on that, it doesn't have to be exclusively red. For example on Sony camera firmware you can adjust between white, yellow, or red to indicate the areas of focus in the case that your subject makes it hard to distinguish between focus peaking outlines.

**Comment by Michael-DJI** [comment]
it will be supported in next version of UXSDK.
