### ISSUE TITLE
Cendence RC battery status updated too rarely

### ISSUE THREAD

**Issue by nextfullstorm** [dji-sdk/Mobile-SDK-Android#197]
Setup: Matrice 210 RTK, Cendence GL-800A, Lenovo TAB 3, Android 6.0, latest firmware on every DJI hw, DJI SDK 4.3.2.

Description: Cendence battery status received via ChargeRemaining.Callback, ChargeRemaining.getRemainingChargeInPercent(). Returning value changes not on every percent, but one time per 8-10 min. If connection to Cendence restarted with cable remove and insert, then callback receives right battery level, but doesn't updates it next 8-10 min.

**Comment by Michael-DJI** [comment]
pls try 4.4.0 or later version.

**Comment by Michael-DJI** [comment]
@nextfullstorm
