### ISSUE TITLE
 I want to get GPS latitude and longitude of the aircraft, how to operate it, request help!

### ISSUE THREAD

**Issue by hongyang-li** [dji-sdk/Mobile-SDK-Android#198]
I need to GPS real-time data sent to the remote server by mobile phone, and now I do not know how to get GPS latitude and longitude data in the aircraft!

**Comment by trofunenko** [comment]
[http://forum.dev.dji.com/thread-32181-1-1.html](url)

**Comment by Michael-DJI** [comment]
`mFlightController.setStateCallback(new FlightControllerState.Callback() {
                    @Override
                    public void onUpdate(FlightControllerState state) {
                        mAircraftLat = state.getAircraftLocation().getLatitude();
                        mAircraftLng = state.getAircraftLocation().getLongitude();
...
`
