### ISSUE TITLE
DJI Mobile SDK Issues Submit Guide

### ISSUE THREAD

**Issue by oliverou** [dji-sdk/Mobile-SDK-Android#2]
# Workflow

If an issue/bug is found in our source code, developers are welcome to submit an issue on Github. If the issues are valid, the DJI SDK staffs will check and respond to your issues as soon as possible.

Issues that do not follow this guide will not be accepted.

### Please provide the following info for us to help fix bugs:
-  Android device type you are using (Like Nexus 5, Samsung Galaxy Tab 4 WIFI, etc)
-  Android Studio or Eclipse version you are using (Like Android Studio 1.3.2, Eclipse 3.6, etc)
-  Android system version you are using (Like Android 6.0, Android 5.1.1, etc)

### Please provide the following info for us to help fix crash issues:
-  Crash logs(If you can find it, it would be very helpful)
-  Android device type you are using (Like Nexus 5, Samsung Galaxy Tab 4 WIFI, etc)
-  Android Studio or Eclipse version you are using (Like Android Studio 1.3.2, Eclipse 3.6, etc)
-  Android system version you are using (Like Android 6.0, Android 5.1.1, etc)

**Comment by jtuchek** [comment]
Hey @oliverou I made a wiki page for submission guidelines https://github.com/dji-sdk/Mobile-SDK-Android/wiki/Issue-Submission-Guide if you want to close this issue.

**Comment by dji-dev** [comment]
Hi @jtuchek thanks for your help to create the wiki page, already update the wiki and will close this issue now.
