### ISSUE TITLE
SDK3.1 连接状态

### ISSUE THREAD

**Issue by smellok** [dji-sdk/Mobile-SDK-Android#20]
在sdk3.0中，如果只连接遥控器（主机没开），如下代码：

`DJISDKManager.getInstance().getDJIProduct();
`
貌似返回的不是null，可以通过这个返回值来判断是否连接了遥控器。

而在SDK3.1中，即使连接了遥控器，这段代码返回为null。

如果判断只有遥控器连接的状态？

**Comment by SilverChangjian** [comment]
For checking whether the remote controller is connected or not, you should check the connect in serval callbacks.

`onProductChanged()`, `onComponentChanged()`, `onProductConnectivityChanged()` and in `ComponentListener`. If `DJISDKManager.getInstance.getDJIProduct()` is not null, the product is instance of `DJIAircraft` and the `isConnected` in RemoteController is `true`. The the RC connected.
