### ISSUE TITLE
MediaFile.fetchFileData unable to download files larger than 700MB

### ISSUE THREAD

**Issue by Appleman1234** [dji-sdk/Mobile-SDK-Android#200]
###  Description of the issue

I am using an application based on https://github.com/DJI-Mobile-SDK-Tutorials/Android-MediaManagerDemo . It is able to download files that are less than 700MB succesfully, but downloading files larger than 700MB results in a 0 length file instead of the complete file. The complete file is downloaded to DJI/packagename/CACHE_IMAGE/ directory successfully, but is then deleted and not moved successfully, with a 0 length file being moved the download directory instead.

This outcome is the same as the problem described byhttps://github.com/dji-sdk/Mobile-SDK-Android/issues/9#issuecomment-160635637 , but the issue I see only occurs with files larger than 700MB.

### Expected outcome 

Able to download file larger than 700MB successfully.

### Actual outcome

File download of file larger than 700MB results in a 0 length file.

### Steps to reproduce the bug or crash issues

1. Turn on Light Bridge 2 Remote Controller
2. Plug Light Bridge 2 Remote Controller into Tablet using USB cable
3. Start MediaDownload application
4. Click Open button after Register Success and Product Information says A3
5. Click on MediaManager icon in the bottom right hand corner.
6. Select file that is larger than 700MB, click download button
7. Wait until download progress is 100% completed and Downloaded file successfully message displays in Toast.
8. Browse to download directory using Files file browser, confirm that selected file is listed and has file size of 0 bytes.

### Crash logs 
There is no crash.
### DJI Android SDK version you are using 
DJI Android SDK 4.3.2
### DJI Product you are using 
A3 and Lightbridge 2
### Android system version you are using
Android 6.0
### Android device you are using 
Huawei MediaPad T3
### Android Studio version you are using 
Android Studio 3.0.1

**Comment by Michael-DJI** [comment]
it's fixed, pls try 4.4.0 or later version

**Comment by Michael-DJI** [comment]
4.4.1 is released, you could try with this version.
