### ISSUE TITLE
Method onExecutionStart of WaypointMissionOperatorListener was not called occasionally

### ISSUE THREAD

**Issue by zzhall** [dji-sdk/Mobile-SDK-Android#202]
Method `onExecutionStart` of `WaypointMissionOperatorListener` was not called occasionally when the waypoint mission started to execute.  And another small problem is that this method is usually called more than once.

This makes my app unstable if I need to do something important at the beginning of the execution.  Can you just let it called absolutely only once? 

-  Method `onExecutionStart` of `WaypointMissionOperatorListener` was not called occasionally when the waypoint mission started to execute.  
-  Steps to reproduce the bug or crash issues - it just occurs occasionally
-  DJI Android SDK version you are using -  Android SDK v4.3.2
-  DJI Product you are using -Phantom 4 Pro
-  Android system version you are using - Android 7.0
-  Android device you are using - Huawei M3 Tablet
-  Android Studio version you are using - Android Studio 3.0.1

**Comment by MAX-POLKOVNIK** [comment]
Same problem
Using SDK 4.4.1
Mavic Pro
