### ISSUE TITLE
SDK 4.4: HotpointMission.angularVelocity has been changed from float -> int

### ISSUE THREAD

**Issue by rickyhopper** [dji-sdk/Mobile-SDK-Android#204]
In SDK 4.4 on Android, the type of angularVelocity in HotpointMission has been changed to an **int** (formerly a **float** in previous SDK versions). This sacrifices accuracy that we rely on for reliable execution of HotpointMissions, especially at lower speeds. Can this be changed back to a float? 

I have also noticed that the iOS SDK stored angularVelocity as an integer before 4.4, and has now changed it to a float in the latest release. We have seen great results executing HotpointMissions in our 4.4 iOS testing today, and in previous Android SDK testing before 4.4 as well.

Relevant info:
-  DJI Android SDK version: 4.4.0
-  DJI Product: all
-  Android system version you are using: 8.1, 7.0
-  Android device: Google Pixel 5.0", Samsung Galaxy Tab S3
-  Android Studio version: 3.0

**Comment by Michael-DJI** [comment]
4.4.1 is released, pls use this version.
