### ISSUE TITLE
There is a serious conflict between DJI SDK v4.4.0 and AMap SDK! Please give me some solution!

### ISSUE THREAD

**Issue by zzhall** [dji-sdk/Mobile-SDK-Android#205]
-  There is a serious conflict between DJI SDK v4.40 and AMap SDK while I change the 
`compile 'com.dji:dji-sdk:4.3.2'` to      `compile 'com.dji:dji-sdk:4.4.0'` and `    provided 'com.dji:dji-sdk-provided:4.4.0'` . 
Thousands of red error about AMap SDK occurred after I upgrade the DJI SDK version.  And I just checked the structure of  _dji-sdk-provided-4.4.0.jar_ file from Android Studio External Libraries. Found that there were two packages named _amap.api_ and _autonavi_, which belonged to AMap SDK absolutely.

-  Steps to reproduce the bug or crash issues: 
just`compile 'com.amap.api:3dmap:5.6.0'`and `compile 'com.amap.api:location:3.6.1'` with the DJI SDK new version,  then you will see that  lots of methods from AMap SDK API turn red.
-  Crash logs:
It is all about **method not found** crash log.
-  DJI Android SDK version you are using :
Android SDK 4.4.0
-  DJI Product you are using :
Phantom 4 Pro
-  Android system version you are using :
 Android 7.0
-  Android device you are using :
Huawei M3 Tablet3.0

**Comment by Djacob502** [comment]
I don't have a solution for the conflicts between sdk 4.4 and AMap sdk. I'm using mapBox and there is no conflict with dji sdk 4.4. However I would request that the future dji mobile sdks be tested with the major mapping options including here maps, mapbox, AMap, and google maps to avoid possible issues in the future.

**Comment by GIS-HowardZhang** [comment]
@Djacob502 Thanks still. These are supplementary facts below.

Structure of dji-sdk-provided-4.4.0.jar file:
```
▾📁com.dji:dji-sdk-provided:4.4.0@jar
  ▾📁dji-sdk-provided-4.4.0.jar
    ▸📁assets
    ▾📁com
      ▸📁a
      ▸📁amap.api
      ▸📁autonavi
      ▸📁dji
    ▸📁dji
    ▸📁META-INF
```

Structure of dji-sdk-provided-4.4.0.jar file:
```
▾📁com.amap.api:3dmap:5.6.0@jar
  ▾📁3dmap-5.6.0.jar
    ▸📁assets
    ▾📁com
      ▸📁amap.api
      ▸📁autonavi
    ▸📁lib
    ▸📁META-INF
```

They just have the same package structure, so that classes from AMap SDK are all imported from DJI SDK now. And DJI SDK has also obfuscate all the methods from package _com.amap.api_ to 'a()','b()',etc., which makes my code all wrong.

We urge you to fix this issue asap so that we can upgrade the sdk version to the newest! 

Thanks!

**Comment by Michael-DJI** [comment]
hi, we have found this issue, will release a new version ASAP, thank you for the feedback.

**Comment by Michael-DJI** [comment]
hi @GIS-HowardZhang pls replace the jar files so files of AMAP with this kind of dependancies:
compile 'com.amap.api:navi-3dmap:latest.integration'
compile 'com.amap.api:search:latest.integration'
compile 'com.amap.api:location:latest.integration'

**Comment by GIS-HowardZhang** [comment]
@Michael-DJI 
OK, I'll try it immediately. Thanks!

**Comment by GIS-HowardZhang** [comment]
Hi, @Michael-DJI, the solution you provide still doesn't work. 
![Uploading WX20171228-165020.png…]()
![Uploading WX20171228-165020.png…]()

**Comment by GIS-HowardZhang** [comment]
Hi, @Michael-DJI, the solution you provide still doesn't work.
Methods from AMapSDK classes remain obfuscated.

**Comment by Michael-DJI** [comment]
@GIS-HowardZhang ok, we will release a new version to fix it.

**Comment by Michael-DJI** [comment]
@GIS-HowardZhang 4.4.1 released, pls test the issue with this version.
