### ISSUE TITLE
DJI Phantom 2 Vision Plus (Pre SDK 3) Video feed freezes when looking at trees or grass.

### ISSUE THREAD

**Issue by VicV** [dji-sdk/Mobile-SDK-Android#21]
The video callback works perfectly fine, but when at the highest resolution at highest framerate, the renderer just completely freezes and takes forever to get back to normal. Makes developing a nightmare.

**Comment by talobin** [comment]
Will go ahead and close this issue since its been too long.
@VicV  please feel free to reopen if you find version 4.3.2 still has this problem.
As of now, to get video feed, please use the VideoFeeder class.
Thank you!
