### ISSUE TITLE
"isLandingConfirmationNeeded" is not working on disconnect and reconnect android device.

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#215]
Drone used: Phantom 4

Preconditions to reproduce: 
- Keep a button in android app to check the value of key "IS_LANDING_CONFORMATION_NEEDED"

Steps:
- Connect the Android device and fly around.
- Keep the aircraft in a state that requires landing confirmation [Do not confirm Landing]
- Click on the button that gives the value of key "IS_LANDING_CONFORMATION_NEEDED". It works fine and returns true.
- Disconnect the android device and reconnect it.
- Now click on the same button that gives the value of key "IS_LANDING_CONFORMATION_NEEDED". It returns "The feature is unsupported". This is the issue.

But once landing is confirmed, the key "IS_LANDING_CONFORMATION_NEEDED" starts giving proper values. 

We want know if landing confirmation is needed as soon as we connect the Android device, which is not working.

However, this works fine in DJI GO 4. Let us know if I am doing anything wrong.

Device used:
Moto G3, 6.0.1
DJI sdk : 4.4.1

Android studio version : 2.2.2

**Comment by Michael-DJI** [comment]
@Abhishek284 we will fix it in next version, thanks for the feedback!

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by twissmueller** [comment]
@Abhishek284 How do you "Keep the aircraft in a state that requires landing confirmation"?

When I test this in the simulator, isLandingConfirmationNeeded becomes true, but in GPS (outside) or OPTI (indoors) mode the drone just lands without requiring any confirmation.

**Comment by Abhishek284** [comment]
@twissmueller I am sorry as I don't have an answer, It is been two years since I am not working on this anymore. I believe we during landing outside, it actually waits for a moment 1 meter above ground and when you move the joystick down, it acts like you have confirmed landing and it will land.
