### ISSUE TITLE
Inconsistent behavior between FlightControllerState's aircraft location and FlightControllerKey.AIRCRAFT_LOCATION

### ISSUE THREAD

**Issue by reddigfabian** [dji-sdk/Mobile-SDK-Android#219]
This issue happens when the drone does not have GPS location fix.

When listening to value changes in aircraft location via a Keylistener with FlightControllerKey.AIRCRAFT_LOCATION a valid LocationCoordinate3D with all its values set to 0 is returned. This causes our app to think the drone is in the middle of the Atlantic ocean.

When listening to FlightControllerState callbacks, the LocationCoordinate3D's doubles are set to Double.NaN so I can properly validate the location.

I don't understand why these two behave differently since they should, in theory, be pulling the LocationCoordinate3D from the same place. I would rather get aircraft location with a keylistener so that it only updates when the value actually changes.

DJI SDK Version 4.3.2

**Comment by Michael-DJI** [comment]
pls try 4.4.1

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
