### ISSUE TITLE
Error in SDK 3.1.0: Could not dispatch event

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#22]
> Could not dispatch event: class dji.midware.data.model.P3.DataOsdGetPushCommon to subscribing class class dji.sdk.MissionManager.DJIMissionManager$InnerEventBus
>                                                                  java.lang.NullPointerException
>                                                                      at dji.sdk.MissionManager.DJIMissionManager$InnerEventBus.onEventBackgroundThread(Unknown Source)
>                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                      at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:569)
>                                                                      at de.greenrobot.event.EventBus.postToSubscription(EventBus.java:513)
>                                                                      at de.greenrobot.event.EventBus.postSingleEvent(EventBus.java:475)
>                                                                      at de.greenrobot.event.EventBus.post(EventBus.java:365)
>                                                                      at dji.midware.data.manager.P3.t.setPushRecData(Unknown Source)
>                                                                      at dji.midware.data.model.P3.DataOsdGetPushCommon.setPushRecData(Unknown Source)
>                                                                      at dji.midware.data.manager.P3.t.setPushRecPack(Unknown Source)
>                                                                      at dji.midware.data.manager.P3.l.b(Unknown Source)
>                                                                      at dji.midware.data.manager.P3.l.a(Unknown Source)
>                                                                      at dji.midware.data.manager.P3.l.a(Unknown Source)
>                                                                      at dji.midware.usb.P3.UsbAccessoryService$1.onGetBody(Unknown Source)
>                                                                      at dji.midware.f.a.d.b(Unknown Source)
>                                                                      at dji.midware.f.a.d.a(Unknown Source)
>                                                                      at dji.midware.usb.P3.UsbAccessoryService$RecvBufferRunnable.run(Unknown Source)
>                                                                      at java.lang.Thread.run(Thread.java:841)

**Comment by kenargo** [comment]
When do you get this error; I just ported to 3.1 (from 3.0.1) and ran a waypoint mission, no problems?

**Comment by JonasVautherin** [comment]
I ran a mission, and then it went into a state where that happened repeatedly.

**Comment by kenargo** [comment]
Interesting, I’ve not seen in in many waypoint missions.  I was flying the Phantom 3 Pro under simulator but running 3.1 SDK.

 

Sorry, I can’t help.

**Comment by SilverChangjian** [comment]
Hi, thanks for providing the information, we have already investigated on it. Will provide the feedback soon.

**Comment by talobin** [comment]
Will go ahead and close this issue since its been too long.
@JonasVautherin please feel free to reopen if you find version 4.3.2 still has this problem.
Thank you!
