### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by VolodymyrCj** [dji-sdk/Mobile-SDK-Android#220]
when open my app in debug mode(without proguard), the following error occurs:
```java
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString() (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString and Java_dji_midware_natives_SDKRelativeJNI_native_1getUsbAccessoryAttachedString__)
                      at dji.midware.natives.SDKRelativeJNI.native_getUsbAccessoryAttachedString(Native Method)
                      at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source)
                      at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source)
````
-  DJI Android SDK version: 4.4.1
-  Android system version: 7.0
-  Android device: MI 5
-  Android Studio version: 3.0.1

**Comment by VolodymyrCj** [comment]
I decompile the apk my app generated, find the libSDKRelativeJNI exists, so I am confused about the error

**Comment by Michael-DJI** [comment]
could you pls try the Mobile sdk sample with your tablet?

**Comment by VolodymyrCj** [comment]
the sample can run without error

**Comment by VolodymyrCj** [comment]
and I change dji sdk in my project to version 4.3.2, the error is gone

**Comment by Michael-DJI** [comment]
Please make sure you don't miss the following steps:

In your project's build.gradle file, please add the packagingOptions to avoid unexpected crashes, and also add the compile and provided dependencies to to import the DJI Android SDK maven dependency as shown in this Integrate SDK into Application tutorial.

Create a new MApplication class and invoke the install() method of Helper class to load the SDK classes before using any SDK functionality. Failing to do so will result in unexpected crashes. Also, you should initialize SDK class objects (Like BaseProduct.BaseProductListener, BaseComponent.ComponentListener and DJISDKManager.SDKManagerCallback) inside the onCreate() method. For more details, please check the Creating a Camera Application tutorial.

https://developer.dji.com/mobile-sdk/documentation/faq/index.html#after-upgrading-to-dji-android-sdk-4-4-1-my-android-project-crashes-with-java-lang-noclassdeffounderror-error-how-to-fix-it

**Comment by VolodymyrCj** [comment]
yes, I do all of the things in the document.
actually, I have a release version that use 4.4.0, which can run without error.
when the error happens, I try to reset to that commit, but it can not run correctly suddenly

**Comment by Michael-DJI** [comment]
try to add abiFilters in your build.gradle of app like following:
defaultConfig {
        ndk {
            abiFilters 'armeabi-v7a', 'x86', 'arm64-v8a'
        }
      .....
      .....
    }

**Comment by VolodymyrCj** [comment]
I have add the abiFilters already

**Comment by Michael-DJI** [comment]
how about only support v7a architechture
ndk {
abiFilters 'armeabi-v7a'
}

**Comment by aijie1712** [comment]
i have the same problem, it's no problem when running the sample code,But when I move the code to module, it occurs, How should I use it in module?

**Comment by Michael-DJI** [comment]
@aijie1712 if possible, could you pls provide your project in github?

**Comment by aijie1712** [comment]
the demo code link is [demo](https://github.com/aijie1712/DjDemo)

**Comment by Michael-DJI** [comment]
@aijie1712 I fixed your issue, there are two steps:
1.add the doNotStrip tag in build.gradle under app folder:

`diff --git a/app/build.gradle b/app/build.gradle
index 23ad8a5..2dbc9a4 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -20,6 +20,17 @@ android {
             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
         }
     }
+    packagingOptions{
+        doNotStrip "*/*/libdjivideo.so"
+        doNotStrip "*/*/libSDKRelativeJNI.so"
+        doNotStrip "*/*/libFlyForbid.so"
+        doNotStrip "*/*/libduml_vision_bokeh.so"
+        doNotStrip "*/*/libyuv2.so"
+        doNotStrip "*/*/libGroudStation.so"
+        doNotStrip "*/*/libFRCorkscrew.so"
+        doNotStrip "*/*/libUpgradeVerify.so"
+        doNotStrip "*/*/libFR.so"
+    }
`

2.

**Comment by Michael-DJI** [comment]
@VolodymyrCj pls make sure that in your build.gradle of app module, add the doNotStrip tag just like our sample

**Comment by aijie1712** [comment]
@Michael-DJI  thx for your reply, This solved my problem.

**Comment by williamjiangweiming** [comment]
@Michael-DJI  I had the same issure, can you help me ? my proplem is               Process: com.huawei.droneplan.droneplan, PID: 23105
                                                   java.lang.VerifyError: Verifier rejected class dji.sdk.sdkmanager.DJISDKManager: void dji.sdk.sdkmanager.DJISDKManager.<init>() failed to verify: void dji.sdk.sdkmanager.DJISDKManager.<init>(): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.sdk.sdkmanager.DJISDKManager' appears in /data/app/com.huawei.droneplan.droneplan-2/split_lib_dependencies_apk.apk)
                                                       at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source)
                                                       at com.huawei.droneplan.droneplan.DJIApplication.onCreate(DJIApplication.java:142)
                                                       at com.huawei.droneplan.droneplan.DronePlanApplication.onCreate(DronePlanApplication.java:92)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5658)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by milkywayriver** [comment]
> @Michael-DJI I had the same issure, can you help me ? my proplem is Process: com.huawei.droneplan.droneplan, PID: 23105
> java.lang.VerifyError: Verifier rejected class dji.sdk.sdkmanager.DJISDKManager: void dji.sdk.sdkmanager.DJISDKManager.() failed to verify: void dji.sdk.sdkmanager.DJISDKManager.(): [0x0] Constructor returning without calling superclass constructor (declaration of 'dji.sdk.sdkmanager.DJISDKManager' appears in /data/app/com.huawei.droneplan.droneplan-2/split_lib_dependencies_apk.apk)
> at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source)
> at com.huawei.droneplan.droneplan.DJIApplication.onCreate(DJIApplication.java:142)
> at com.huawei.droneplan.droneplan.DronePlanApplication.onCreate(DronePlanApplication.java:92)
> at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5658)
> at android.app.ActivityThread.-wrap2(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
> at android.os.Handler.dispatchMessage(Handler.java:105)
> at android.os.Looper.loop(Looper.java:156)
> at android.app.ActivityThread.main(ActivityThread.java:6523)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

maybe you use: 
> `implementation 'com.dji:dji-sdk-provided:4.10'`
other than
>`compileOnly 'com.dji:dji-sdk-provided:4.10'`
check it.

**Comment by Michael-DJI** [comment]
@milkywayriver you should use 
    implementation ('com.dji:dji-sdk:4.10', {
//             Uncomment the following line if your app does not need Anti Distortion for
//             Mavic 2 Pro and Mavic 2 Zoom. It will greatly reducing the size of the APK:
             exclude module: 'library-anti-distortion'
//             Uncomment the following line if your APP does not need network RTK
             exclude module: 'library-networkrtk-helper'
        })
    compileOnly 'com.dji:dji-sdk-provided:4.10'
