### ISSUE TITLE
Entire app hangs when using both the DJI and Mapbox SDK's

### ISSUE THREAD

**Issue by vanshg** [dji-sdk/Mobile-SDK-Android#222]
When using both the DJI Mobile SDK and Mapbox SDK within an app, there is some conflict between the two which causes the entire app to hang/freeze on initialization and causes an ANR. When this happens, there is no error or stacktrace that shows up in Logcat. However, it is very easy to reproduce:

- Take the sample app, and add `compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.3.1')` to the dependencies
- Modify `activity_main.xml` to look like this:
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/framelayout_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center"
        android:visibility="gone">
        <include layout="@layout/content_main"/>
    </FrameLayout>

    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/map"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</FrameLayout>
```
- Setup Mapbox MapView in MainActivity
    - Add `private MapView mapView;` class variable declaration
    - Add the following to the end of the `onCreate` method:
```
mapView = findViewById(R.id.map);
mapView.onCreate(savedInstanceState);
mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                System.out.println("Ready");
            }
}); 
```
- Override onStart, onStop, onPause, onResume, onDestroy, onLowMemory, and onSaveInstanceState and call the respective super and mapView methods
```
@Override
    protected void onDestroy() {
        DJISampleApplication.getEventBus().unregister(this);
        mapView.onDestroy();
        super.onDestroy();
    }

@Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

    @Override
    protected void onStart() {
        super.onStart();
        mapView.onStart();
    }

    @Override
    protected void onStop() {
        super.onStop();
        mapView.onStop();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }
```
- Add this to the end of `DJISampleApplication` file
```
@Override
    public void onCreate() {
        super.onCreate();
        Mapbox.getInstance(this, "");
    }
```
- Run the app. It will launch and show a white screen. After a couple seconds, you will get an ANR dialog. (If there were to be content that you could interact with on the screen, nothing would be responsive)

Android Studio version: 3.0.1
Device: Pixel 2
OS: 8.1
DJI SDK version: 4.4.1
Mapbox SDK version: 5.3.1

I believe the issue is occurring as a result of some type of clash over native libraries.

**Comment by Michael-DJI** [comment]
thanks for your feedback, we will look into this issue!

**Comment by Djacob502** [comment]
I'm also getting mapbox to cause ANR - however in my case only on one particular device: T71 - an rugged android device sold specifically for outdoor use. On other android devices mapbox works correctly including the crystal sky tablets.

**Comment by reddigfabian** [comment]
We've found that removing some of the abiFilters in the build.gradle will resolve these issues. @Djacob502 @vanshg Can you try running your apps with only the following:

`defaultConfig {
        ndk {
            abiFilters 'armeabi-v7a'
        }`

We're still unsure about the implications of this exactly, but for now it has served as a stop gap while we test things like thermal with the new SDK. Hopefully multiple voices on this issue will get us some feedback. I know we would appreciate some greater detail on both this and the inclusion of SecNeo's security library in the new SDK.

**Comment by Djacob502** [comment]
@reddigfabian  - thank you for the advice to remove the abiFilters! The mapbox maps work correctly on the T71. 
I'll continue to do additional testing to see if there are errors with removing the abiFilters.

**Comment by vanshg** [comment]
Thanks for that @reddigfabian, it's working on Pixel 2 now. However, will this not prevent the SDK from working on devices with other architectures?

**Comment by reddigfabian** [comment]
@vanshg We believe that other architectures have a translation layer to support arm v7, but at a potential cost of performance. We're working on procurring some test devices to figure this out and I will try to update here with what we figure out.

**Comment by rickyhopper** [comment]
Hey all, we've been doing some research on this (building off @reddigfabian's comment). When only supporting the armeabi-v7a architecture, the app crashes on x86 devices (it cannot resolve DJI SDK classes). I have tested today that the x86 abiFilter can also be included, and the app will run on all devices that the DJI SDK is supposed to support. 

We have excluded *arm64-v8a* from our abiFilters, since this causes ANRs in activities that include a MapView - this happens in all ARM-based Android devices we've tested. (Please note that this code will still work on 64-bit ARM devices, but it will not be able to utilize the 64-bit architecture.)

For clarification, here is our fix for this issue:

```
defaultConfig { 
    ndk { 
        abiFilters 'armeabi-v7a', 'x86' 
    }
    ...
}
```

@Michael-DJI - we believe the above should be the recommended configuration in DJI sample code until these conflicts are resolved. It seems the issues come from the 64-bit ARM libraries only.

**Comment by Michael-DJI** [comment]
@rickyhopper got u! thanks for that, actually we are resolving the arm64 issue now!

**Comment by rickyhopper** [comment]
@Michael-DJI Awesome, thanks for the heads up! Please let us know when we can expect a fix to be published :)

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
