### ISSUE TITLE
enum DJIDiagnosticsError garble

### ISSUE THREAD

**Issue by lemonL** [dji-sdk/Mobile-SDK-Android#223]
public static enum DJIDiagnosticsError {
        a(1001),
        b(1002),
        c(1003),
        d(1004),
        e(1005),
        f(1006),
        g(1007),
        h(1008),
        i(1009),
        j(1010),
        k(2001),
        l(2002),
        m(2003),
        n(2004),
        o(2005),
        p(3001),
        q(3002),
        r(3003),
        s(3004),
        t(3005),
        u(3006),
        v(3007),
        w(3008),
        x(4001),
        y(4002),
        z(4003),
        A(4004),
        B(4005),
        C(4006),
        D(4007),
        E(4008),
        F(4009),
        G(4010),
        H(5001),
        I(5002),
        J(5003),
        K(6001),
        L(6002),
        M(7001),
        N(7002),
        O(8001),
        P(8002),
        Q(8003),
        R(8004),
        S(8005),
        T(8006),
        U(8007),
        V(8008),
        W(8009),
        X(8010),
        Y(8011),
        Z(8012),
        aa(8013),
        ab(8014),
        ac(8015),
        ad(8016),
        ae(8017),
        af(9001),
        ag(9002),
        ah(9003),
        ai(9004),
        aj(9005);

        private int value;

        private DJIDiagnosticsError(int var3) {
        }

        public int a() {
            return 0;
        }

        private boolean a(int var1) {
            return false;
        }

        public static DiagnosticsBaseHandler.DJIDiagnosticsError find(int var0) {
            return null;
        }
    }

DJIDiagnosticsError  encryption ，Can not get it  enum

Android SDK 4.4.1

Android Studio .3.0

**Comment by Michael-DJI** [comment]
hi @lemonL , you need care about the name of each enum

**Comment by ITCCodeDev** [comment]
Hi @Michael-DJI 
I'm trying to filter out the codes received using the `DiagnosticsInformationCallback` and only display certain codes on the screen that are relevant to the user using the `enum DJIDiagnosticsError` as listed [here](https://developer.dji.com/api-reference/android-api/Components/Diagnostics/DJIDiagnostics.html#djidiagnostics_djidiagnosticserror_inline).
How can I compare the error codes to the names listed in the enum to filter them out?
I am unable to find and access these anywhere.

**Comment by Michael-DJI** [comment]
ok, we will fix it in next version, thanks for your feedback!
