### ISSUE TITLE
FIVE_D_BUTTON in remote controller key class does on listen to key callbacks

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#226]
When listener is added to FIVE_D_BUTTON form Remote controller key class , callback are not getting received. However , by setting hardware state callback , we can getFiveDButton() and use it. 

CUSTOM_BUTTON_1 and CUSTOM_BUTTON_2 works fine by adding listeners.

**Comment by wocoltd** [comment]
We've also noticed this in SDK version 4.4.1. We also noticed that although the CUSTOM_BUTTON_1 and 2 listeners work, they are called multiple times per press?

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
