### ISSUE TITLE
The sign in dialog shows blank white screen.

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#227]
We are using  **UserAccountManager.getInstance().logIntoDJIUserAccount(....)**  for sign in purpose.

- While having internet connectivity issues login dialog shows blank white screen. 

As the dialog is not upto customisation for developers, please add a message in order to connect to the internet for the user.

**Comment by Michael-DJI** [comment]
pls provide more details about the version of sdk, which drone, which device you are using etc.

**Comment by Abhishek284** [comment]
DJI SDK : 4.4.1
This issue is independent of drone. [We are using mavic pro] 
Device: Epson android glasses BT-300 and BT-350

This can also be replicated in any android device by switching off the internet and calling 
**UserAccountManager.getInstance().logIntoDJIUserAccount(....)**

**Comment by yakovchang** [comment]
Has this problem been solved? I also have this problem.

**Comment by radjkarl** [comment]
Possible duplicate: https://github.com/dji-sdk/Mobile-SDK-Android/issues/410
