### ISSUE TITLE
Mediafile from onNewFile dateCreated is different from the mediafile in getFileListSnapshot

### ISSUE THREAD

**Issue by kwong93** [dji-sdk/Mobile-SDK-Android#228]
Here are some logs I printed

getFileListSnapshot MediaFile dateCreated: 2018-02-05 11:21:03
getFileListSnapshot MediaFile sizeInBytes: 8497267
getFileListSnapshot MediaFile getFileName: DJI_0083.jpeg

onNewFile MediaFile  dateCreated: 2018-02-05 11:21:06
onNewFile MediaFile  sizeInBytes: 8497267
onNewFile MediaFile  getFileName: DJI_0083.jpeg

I have some logic that compares the date equality but on DJI SDK 4.4.1 it is breaking

Android 6.0.1
Galaxy S7
DJI Phantom 4 PRO

**Comment by zoemcateedji** [comment]
Could you try with 4.4.1?  IIRC that was something that was looked at.

**Comment by kwong93** [comment]
@zoemcateedji 
My bad it was one 4.4.1 but 4.3.2 its fine

**Comment by Michael-DJI** [comment]
@kwong93 thanks for your feedback, we will fix it in next version

**Comment by reddigfabian** [comment]
@Michael-DJI please also note that the filename in the new media callback has a ".jpeg" extension when in fact the file has a ".jpg" extension. We're doing some string matching on file names and this causes the matching to fail.

**Comment by Michael-DJI** [comment]
@reddigfabian which drone?

**Comment by reddigfabian** [comment]
Phantom 4 Advanced

**Comment by reddigfabian** [comment]
@Michael-DJI please see the info provided in this issue: 
https://github.com/dji-sdk/Mobile-SDK-Android/issues/264
it shows the jpeg -> jpg difference in action

**Comment by Michael-DJI** [comment]
@reddigfabian ok, we will fix it in next version, thanks for the feedback.

**Comment by Michael-DJI** [comment]
I think you have resolved your issue with new version, right?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
