### ISSUE TITLE
Duplication of dependencies

### ISSUE THREAD

**Issue by lemonL** [dji-sdk/Mobile-SDK-Android#230]
I use the third-party framework found dependencies are duplicates, such as okio, Dji SDK version 1.8, the third party is using the 1.12 version, so how to solve? AAR package official website provides the connection is to jump to github, but there is no aar file

SDK： 4.4.1 

Problems：  Bmob  SDK  and  DJI Mobile SDK

![qq 20180206175322](https://user-images.githubusercontent.com/5005866/35852793-c2e5e76e-0b66-11e8-85d0-d4d6cd64cf74.png)
![qq 20180206175351](https://user-images.githubusercontent.com/5005866/35852800-c713b956-0b66-11e8-9bf7-4eefba561742.png)

**Comment by lemonL** [comment]
Many frameworks are duplicates

**Comment by Michael-DJI** [comment]
Hi @lemonL you could exclude gson and okio like following:
compile ('com.dji:dji-uilibrary:4.4.1') {
        exclude group: 'com.google.code.gson', module: 'gson'
        exclude group: 'com.squareup.okio', module: 'okie'
    }

**Comment by lemonL** [comment]
@Michael-DJI The problem has been solved, thanks
