### ISSUE TITLE
CameraKey.ISO, CameraKey.SHUTTER_SPEED and CameraKey.APERTURE won't work for PUSH or GET.

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#233]
DJI SDK: 4.4.1
Device: Mavic pro and Phantom 4

We are not able get values from the following keys,
-CameraKey.ISO
-CameraKey.SHUTTER_SPEED 
-CameraKey.APERTURE
We do not receive any callbacks by adding listeners too. 

But we can get the respective values in **onUpdate(...)** by setting exposure settings state callback [ExposureSettings.Callback].

**Comment by Michael-DJI** [comment]
can you show some pieces of your code?

**Comment by Abhishek284** [comment]
`DJIKey cameraKey = CameraKey.create(CameraKey.ISO);
        KeyManager.getInstance().addListener(cameraKey, new KeyListener() {
            @Override
            public void onValueChange(final Object oldValue, final Object newValue) {
                handler.post(new Runnable() {
                    @Override
                    public void run() {
                        showMessage("Old value = " + oldValue + "New Value = " + newValue);
                    }
                });
            }
        });`

**Comment by Michael-DJI** [comment]
@Abhishek284 when calling addListener you can't get updating immediately, you could try to change the ISO then you could get the updating.

**Comment by Abhishek284** [comment]
@Michael-DJI 
Thank you for your feedback.
