### ISSUE TITLE
call sendVirtualStickFlightControlData method with Param Illegal error

### ISSUE THREAD

**Issue by smellok** [dji-sdk/Mobile-SDK-Android#24]
in the Sample code.
VirtualStickView class has two setJoystickListener method.
when i test it, but get **Param Illegal** error.

DJIFlightControllerDataType.DJIVirtualStickFlightControlData(
                                mPitch, mRoll, mYaw, mThrottle
                        )

what's four params value range??

**Comment by kenargo** [comment]
The information is in the documentation and depends on the modes you set for control.

 

Refer to https://developer.dji.com/mobile-sdk/get-started/Virtual-Stick-User-Guide/

 

You really need to start using the forum for questions (http://forum.dev.dji.com/en), the SDK GIT isn’t for questions and spams all developers.  There is a lot of information in the docs and on the developer website.

**Comment by smellok** [comment]
@kenargo , thanks for your answer.
btw: 
1,the forum http://forum.dev.dji.com/en is not easy to visit, too slow.
2,the question i asked in here is because i think the code in this git is not work well
   the fragment i provided is from com.dji.sdk.sample.flightcontroller.VirtualStickView.java file.
3, i installed the apk file(DJI SDK Sample) to my phone, when i use virtual joystick function, it's not work fine.

**Comment by almeidapaulooliveira** [comment]
In the Air 2S aircraft. I can confirm that the MAX **mThrottle is 15**.

 Anything higher than that will throw `Param Illegal`.

Using these settings for the flight controller:
``` Java
flightController.setRollPitchCoordinateSystem(FlightCoordinateSystem.BODY);
flightController.setRollPitchControlMode(RollPitchControlMode.VELOCITY);
flightController.setYawControlMode(YawControlMode.ANGLE);
flightController.setVerticalControlMode(VerticalControlMode.POSITION);
```
