### ISSUE TITLE
The key "TRANSMISSION_MODE" in AirlinkKey results unsupported when fetched for values. 

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#241]
SDK: 4.4.1
Device: Mavic pro
Platform: Android

We are trying to set and get values for TRANSMISSION_MODE key from Airlink key. 
It always results in unsupported error.

We tried by changing channel selection between MANUAL and AUTO. It is not working.

**Comment by wenqianqiao** [comment]
https://developer.dji.com/api-reference/android-api/Components/LBAirLink/DJILBAirLink.html?search=setchannel&i=0&#djilbairlink_setchannelselectionmode_inline

I think you could use the above API for setting the Manual and Auto mode.

**Comment by Abhishek284** [comment]
We are actually trying to change TRANSMISSION_MODE.

`DJIKey djiKey = AirLinkKey.createLightbridgeLinkKey(AirLinkKey.TRANSMISSION_MODE);
                KeyManager.getInstance().setValue(djiKey, LightbridgeTransmissionMode.HIGH_QUALITY, new SetCallback() {
                    @Override
                    public void onSuccess() {
                        handler.post(new Runnable() {
                            @Override
                            public void run() {
                                showMessage("Successful");
                            }
                        });

                    }

                    @Override
                    public void onFailure(final DJIError djiError) {
                          handler.post(new Runnable() {
                            @Override
                            public void run() {
                                showMessage(djiError.getDescription());
                            }
                        });

                    }
                });`

Please refer the link below.
[https://developer.dji.com/api-reference/android-api/Components/LBAirLink/DJILBAirLink.html#djilbairlink_djilbairlinkfpvvideoqualitylatency_inline](https://developer.dji.com/api-reference/android-api/Components/LBAirLink/DJILBAirLink.html#djilbairlink_djilbairlinkfpvvideoqualitylatency_inline)

**Comment by Michael-DJI** [comment]
pls try this method "setHDLiveViewEnabled"

https://developer.dji.com/api-reference/android-api/Components/Camera/DJICamera.html?search=sethdliveviewenabled&i=0&#djicamera_camerasettings_sethighdefinitionliveviewenabled_inline

**Comment by Michael-DJI** [comment]
@Abhishek284 did you resolve the problem?
