### ISSUE TITLE
The Key INTELLIGENT_FLIGHT_ASSISTANT_GHAVOID_ENABLED is not working.

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#242]
SDK: 4.4.1
Device: Mavic Pro
Platform: Android

We are trying to get/set values for the key INTELLIGENT_FLIGHT_ASSISTANT_GHAVOID_ENABLED. It is resulting in unsupported error.

We also tried by enabling "SMART_RETURN_TO_HOME_ENABLED" key before getting/setting values for INTELLIGENT_FLIGHT_ASSISTANT_GHAVOID_ENABLED key.

**Comment by Michael-DJI** [comment]
could u show some pieces of your code please?

**Comment by Kishan003** [comment]
@Michael-DJI 
Thank you so much for resolution, We were using FlightControllerKey.create() for creating DJIKey so it was throwing "Feature not supported" error, when we tried using FlightControllerKey.createFlightAssistantKey() for creating DJIKey as you suggested, it is working fine.

**Comment by Michael-DJI** [comment]
@Kishan003 you are very welcome, and could you pls close this issue:)?

**Comment by Abhishek284** [comment]
@Michael-DJI Sure. Thank you.
