### ISSUE TITLE
The getValue for VISION_DETECTION_STATE_KEY returns null.

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#243]
Device: mavic pro
SDK: 4.4.1
Platform: Android

We are trying to getValue for the VISION_DETECTION_STATE_KEY. But it always returns null.

**Comment by Michael-DJI** [comment]
are u try to use FlightControllerKey.VISION_DETECTION_STATE, this key?

**Comment by Abhishek284** [comment]
It was a typo error. Used the key FlightControllerKey.VISION_DETECTION_STATE itself , it returns null.
We are using something like this below.

 DJIKey djiKey = FlightControllerKey.create(FlightControllerKey.VISION_DETECTION_STATE);
        KeyManager.getInstance().getValue(djiKey, new GetCallback() {
            @Override
            public void onSuccess(Object o) {
                //do something
            }

            @Override
            public void onFailure(DJIError djiError) {

            }
        });
        
        KeyManager.getInstance().addListener(djiKey, new KeyListener() {
            @Override
            public void onValueChange(Object o, Object o1) {
                //do something
            }
        });

**Comment by Michael-DJI** [comment]
@Abhishek284 
`DJIKey djiKey = FlightControllerKey.createFlightAssistantKey(FlightControllerKey.VISION_DETECTION_STATE);`

**Comment by Abhishek284** [comment]
- What is the difference between FlightControllerKey.create(...) and FlightControllerKey.createFlightAssistantKey(....); ?  
- Which one should be generically used for FlightControllerKeys?

I have tried using 
`DJIKey djiKey = FlightControllerKey.createFlightAssistantKey(FlightControllerKey.VISION_DETECTION_STATE);`
From the resultant object of VisionDetectionState, 
getObstacleDetectionInMeters() always returns 0.0
getVisionDetectionSectors() always returns null.

I have connected to aircraft and tried flying it too.

**Comment by Michael-DJI** [comment]
pls check the developer page:
https://developer.dji.com/api-reference/android-api/Components/VisionDetectionState/DJIVisionDetectionState.html?search=getobstacledistanceinmeters&i=0&#djivisiondetectionstate_obstacledistanceinmeters_inline

getObstacleDetectionInMeters() is only valid in P4P otherwise it just return 0;

**Comment by Abhishek284** [comment]
We are actually trying to get the VPS value like in DJI GO 4. ScreenShot attached below. And we were advised to use FlightControllerKey.VISION_DETECTION_STATE for it.

![screenshot_20180316-151816](https://user-images.githubusercontent.com/17245095/37514578-94b6b3ce-28c5-11e8-99be-ccc6188f8c59.png)

Please let us know which key to be used to get the VPS value.

**Comment by Michael-DJI** [comment]
you could use FlightControllerKey.ULTRASONIC_HEIGHT_IN_METERS 
DJIKey djiKey = FlightControllerKey.create(FlightControllerKey.ULTRASONIC_HEIGHT_IN_METERS);

**Comment by Abhishek284** [comment]
Thank you @Michael-DJI 
It was very much helpful.
