### ISSUE TITLE
Spark connection to android application via OTG.

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#245]
SDK: 4.4.1
Platform: Android
Device: Spark

If spark is connected to android application via wifi, then everything works fine.

But if spark if connected to android app via a OTG cable, I am able to see live view and camera related details. The model is detected as an UNKNOWN_AIRCRAFT though.  

Does spark support cable connection to android app?

**Comment by simonhock** [comment]
Same here,

Sdk 4.5.1
Android 8.1
Device spark 

Tried to use the uxsdk but nothing either.

**Comment by Michael-DJI** [comment]
please use the latest version.
