### ISSUE TITLE
虚拟杆控制权获取

### ISSUE THREAD

**Issue by suffrajet** [dji-sdk/Mobile-SDK-Android#25]
调用 API
`enableVirtualStickControlMode `
获取虚拟杆的控制权时SDK返回了错误，
错误是：the condition of mission is not satisfied

请问这是怎么回事？调用前需要做什么操作

**Comment by SilverChangjian** [comment]
Have you updated your aircraft with latest firmware? Normally, you should change to F mode in remote controller for the products. Especially, for P4, you should put the mode into P mode.

**Comment by suffrajet** [comment]
非常感谢，这个问题已经解决，我更新了SDK版本到最新的3.1，测试的时候直接从P档切到F档，虚拟杆控制权获取成功。

**Comment by SilverChangjian** [comment]
That's great. I am going to close this issue. Thank you for supporting DJI Mobile SDK.
