### ISSUE TITLE
What video stream format is returned by VideoFeeder.VideoDataCallback.onReceive

### ISSUE THREAD

**Issue by chenxiaojin** [dji-sdk/Mobile-SDK-Android#251]
Hi, i want to ask what the detailed format of the video data of the byte[] returned by VideoFeeder.VideoDataCallback.onReceive？

I use the example of Android-VideoStreamDecodingSample to decode the video data returned by onReceive, and the result is not playable, so I want to know more about the details of the video format.

**Comment by RocketRider** [comment]
How did you resolve this issue?

**Comment by chenxiaojin** [comment]
@RocketRider Android-VideoStreamDecodingSample can decode the video data. the video data of the byte[] returned by VideoFeeder.VideoDataCallback.onReceive is H264 raw
