### ISSUE TITLE
Unable to debug application after Helper.install function call

### ISSUE THREAD

**Issue by negativ** [dji-sdk/Mobile-SDK-Android#254]
I'm developing an app that using DJI Android SDK and i found that debuging is imposible after calling Helper.install(MApplication.this) function - Android Studio debugger loses connection with target. The only message i get from debugger is: 

Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'

I'm using DJI Android SDK 4.4.1
Android version is 5.1

**Comment by Michael-DJI** [comment]
@negativ thanks for your feedback, this will be fixed in next version.

**Comment by negativ** [comment]
Now it's ok. Thank you!
