### ISSUE TITLE
Unable to get Compass bias state  

### ISSUE THREAD

**Issue by Kishan003** [dji-sdk/Mobile-SDK-Android#257]
I am not able to find any method or key to get the value of compass calibration state which provide information about interference.  Can you please guid me in how to get this value?
Note: I am referring to Compass calibration page of DJI-GO4 app where progress bar is used to indicate the interference for compass

**Comment by Michael-DJI** [comment]
`mFlightController.setIMUStateCallback(new IMUState.Callback() {

                    @Override
                    public void onUpdate(IMUState state) {
                        StringBuffer sb = new StringBuffer();
                        if (state.isMultiSideCalibrationType()) {
                            Tools.addLineToSB(sb, "Whole Calibration progress", state.getCalibrationProgress());
                            Tools.addLineToSB(sb, "Whole Calibration status", state.getCalibrationState().name());
                            Iterator<CalibrationOrientation> iterator =
                                state.getMultipleOrientationCalibrationHint().getOrientationsCalibrated().iterator();
                            while (iterator.hasNext()) {
                                CalibrationOrientation value = iterator.next();
                                Tools.addLineToSB(sb, "finish=", value.name());
                            }
                        }
                        //different index for different IMU
                        if (state.getIndex() == 0) {
                            Helper.showText(FlightControllerTestingActivity.this, textViewIMU1, sb.toString());
                        } else if (state.getIndex() == 1) {
                            Helper.showText(FlightControllerTestingActivity.this, textViewIMU2, sb.toString());
                        } else if (state.getIndex() == 2) {
                            Helper.showText(FlightControllerTestingActivity.this, textViewIMU3, sb.toString());
                        } else {
                            Helper.showText(FlightControllerTestingActivity.this, textViewInfo, sb.toString());
                        }
                    }
                });`

**Comment by Kishan003** [comment]
@Michael-DJI  
Thanks for reply, sorry for ambiguity, The issue is not with IMU state, My question was about the bias values of the compass, I am referring to following screen of DJI-Go4 app.

![screen shot 2018-03-30 at 3 42 23 pm](https://user-images.githubusercontent.com/24645572/38134577-3ec2977c-3431-11e8-84cb-a61d5538f24d.png)

**Comment by Abhishek284** [comment]
Its neither available in the SDK nor in the documentation.(sdk: 4.8.1)

**Comment by Michael-DJI** [comment]
in Compass class it's a hidden method
