### ISSUE TITLE
搜索蓝牙接口

### ISSUE THREAD

**Issue by shanyaodan** [dji-sdk/Mobile-SDK-Android#259]
小米6,  miui 9,     7.1.1安卓系统 ，as3.0.1
搜索蓝牙接口
设备是自拍杆2
searchBluetoothProducts 刷新调用，setBluetoothDevicesListCallback返回的list里面的设备是重复的，而且每刷新一次重复增加一个设备。这个sdk为什么会返回重复设备呢

引用sdk版本
compile 'com.dji:dji-sdk:4.4.1'
provided 'com.dji:dji-sdk-provided:4.4.1'

**Comment by shanyaodan** [comment]
connector.setBluetoothDevicesListCallback(new BluetoothProductConnector.BluetoothDevicesListCallback() {
                @Override
                public void onUpdate(List<BluetoothDevice> list) {
                    if (null != djBlutoothListener) {

                        djBlutoothListener.onUpdate(list);
                        connector.setBluetoothDevicesListCallback(null);
                        LogUtils.e(getClass(), "startScan Onupdate:"+(null==list?"":list.toString()));
                    }
                }
            });

            connector.searchBluetoothProducts(new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError djiError) {
                    if (null != djBlutoothListener) {
                        djBlutoothListener.callback(djiError);
                    }
                }
            });

代码是这样的

**Comment by shanyaodan** [comment]
connector.setBluetoothDevicesListCallback(new BluetoothProductConnector.BluetoothDevicesListCallback() {
                @Override
                public void onUpdate(List<BluetoothDevice> list) {
                    if (null != djBlutoothListener) {

                        djBlutoothListener.onUpdate(list);
                        connector.setBluetoothDevicesListCallback(null);
                        LogUtils.e(getClass(), "startScan Onupdate:"+(null==list?"":list.toString()));
                    }
                }
            });

            connector.searchBluetoothProducts(new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError djiError) {
                    if (null != djBlutoothListener) {
                        djBlutoothListener.callback(djiError);
                    }
                }
            });

**Comment by shanyaodan** [comment]
有时候手机已经连接上蓝牙，但是搜索到到的蓝牙状态却是未连接

**Comment by shanyaodan** [comment]
搜索要怎么停止呢

**Comment by shanyaodan** [comment]
调用官方demo也是一样，有时候可以搜的到蓝牙，有时候搜不到

**Comment by shanyaodan** [comment]
小米6, miui 9, 7.1.1安卓系统 ，调用官方demo，有时候能搜索不到蓝牙，有时候搜不到，而且有时候手机已经连接上蓝牙，但是搜索到到的蓝牙状态却是未连接，有时候已经断开，其实返回的状态是已连接

**Comment by Michael-DJI** [comment]
we don't have stopSearch interface, the searching will be stopped in 20 seconds after startSearch.

**Comment by shanyaodan** [comment]
thanks your answer, but,
searchBluetoothProducts 刷新调用，setBluetoothDevicesListCallback返回的list里面的设备是重复的，而且每刷新一次重复增加一个设备。这个sdk为什么会返回重复设备呢,有时候还搜索不到蓝牙设备，不知道为什么

**Comment by Michael-DJI** [comment]
pls use latest version of MSDK 4.8.1, you could call the stopSearch() method
