### ISSUE TITLE
Segmentation fault in libdjivideo.so

### ISSUE THREAD

**Issue by bradhoekstra** [dji-sdk/Mobile-SDK-Android#26]
When connecting my app, using SDK 3.1, to a P3S the app will crash trying to display the FPV. This usually happens in less than 10 seconds. This doesn't happen for P3A, P3P, or I1.

03-30 10:27:20.201 15830-20615/com.vertical.dji.tracker3 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9be80000 in tid 20615 (Thread-30438)
03-30 10:27:20.293 5661-5661/? W/debuggerd: type=1400 audit(0.0:15683): avc: denied { search } for name="com.google.android.gms" dev="mmcblk0p28" ino=81492 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
03-30 10:27:20.303 5661-5661/? A/DEBUG: **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
03-30 10:27:20.303 5661-5661/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MMB29V/2554798:user/release-keys'
03-30 10:27:20.303 5661-5661/? A/DEBUG: Revision: '0'
03-30 10:27:20.303 5661-5661/? A/DEBUG: ABI: 'arm'
03-30 10:27:20.303 5661-5661/? A/DEBUG: pid: 15830, tid: 20615, name: Thread-30438  >>> com.vertical.dji.tracker3 <<<
03-30 10:27:20.303 5661-5661/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9be80000
03-30 10:27:20.341 5661-5661/? A/DEBUG:     r0 00000294  r1 00000297  r2 9be7fffd  r3 9be7fd69
03-30 10:27:20.341 5661-5661/? A/DEBUG:     r4 00000303  r5 aa94238b  r6 9be7fffd  r7 9f4c0010
03-30 10:27:20.341 5661-5661/? A/DEBUG:     r8 9be7f000  r9 00000d69  sl 9f54962c  fp 9f549630
03-30 10:27:20.341 5661-5661/? A/DEBUG:     ip 00000024  sp 8e997194  lr a00a24b1  pc a015ce06  cpsr 20050030
03-30 10:27:20.343 5661-5661/? A/DEBUG:     #00 pc 0020de06  /data/app/com.vertical.dji.tracker3-1/lib/arm/libdjivideo.so (ff_startcode_find_candidate_c+29)

**Comment by SilverChangjian** [comment]
Thanks for your report we will investigate it.

**Comment by bradhoekstra** [comment]
Let me know if any other information would be helpful, it is very repeatable.

**Comment by bradhoekstra** [comment]
I also get this same issue with an unmodified DJI SDK Sample application:

04-06 10:08:40.755 194-194/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-06 10:08:40.755 194-194/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MMB29V/2554798:user/release-keys'
04-06 10:08:40.755 194-194/? A/DEBUG: Revision: '0'
04-06 10:08:40.755 194-194/? A/DEBUG: ABI: 'arm'
04-06 10:08:40.755 194-194/? A/DEBUG: pid: 11584, tid: 12638, name: Thread-11026  >>> com.dji.sdkdemo <<<
04-06 10:08:40.755 194-194/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x97c00000
04-06 10:08:40.787 194-194/? A/DEBUG:     r0 000000e8  r1 000000ea  r2 97bffffe  r3 97bfff16
04-06 10:08:40.787 194-194/? A/DEBUG:     r4 007f0000  r5 f47f3650  r6 97bffffe  r7 aec40010
04-06 10:08:40.788 194-194/? A/DEBUG:     r8 97bff000  r9 00000f16  sl aecc962c  fp aecc9630
04-06 10:08:40.788 194-194/? A/DEBUG:     ip 00000780  sp 9ac3a234  lr a0bf14b1  pc a0cabe06  cpsr 20010030
04-06 10:08:40.790 194-194/? A/DEBUG:     #00 pc 0020de06  /data/app/com.dji.sdkdemo-2/lib/arm/libdjivideo.so (ff_startcode_find_candidate_c+29)

**Comment by SilverChangjian** [comment]
Thanks for your report. This is issue which happens when the native methods allocate memories. We are investigating it now.

**Comment by talobin** [comment]
We have had many fixes in JNI level since then.
Will go ahead and close this issue since its been too long.
@bradhoekstra  please feel free to reopen if you find version 4.3.2 still has this problem.
Thank you!
