### ISSUE TITLE
android 调用destory 崩溃

### ISSUE THREAD

**Issue by shanyaodan** [dji-sdk/Mobile-SDK-Android#260]
djisdkManager.destroy();
错误码
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.Map.clear()' on a null object reference

**Comment by wenqianqiao** [comment]
你好，

有没有错误的crash  log  发给我们一下 ，这样我们好方便定位问题

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by Michael-DJI** [comment]
fixed in 4.9
