### ISSUE TITLE
上传完航点后，执行startMisssion指令，但是返回“ the execution could not be executed” 错误

### ISSUE THREAD

**Issue by crazyMing** [dji-sdk/Mobile-SDK-Android#263]
问题：如题
SDK版本：android sdk 4.4.1

**Comment by Michael-DJI** [comment]
pls provide some details, which drone and which phone were you using, and which version of sdk?

**Comment by crazyMing** [comment]
Drone:精灵4
SDK:DJI Android SDK 4.4.1

已经登录大疆账号
使用GS PRO正常飞行，但使用sdk不行

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version 4.8.1?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
