### ISSUE TITLE
java.lang.VerifyError v4.5

### ISSUE THREAD

**Issue by YandexWillKillYou** [dji-sdk/Mobile-SDK-Android#274]
Verifier rejected class dji.sdk.sdkmanager.DJISDKManager due to bad method void dji.sdk.sdkmanager.DJISDKManager.<init>() (declaration of 'dji.sdk.sdkmanager.DJISDKManager' appears in /data/app/ru.degeneration.empty"-1/split_lib_dependencies_apk.apk:classes2.dex)

Empty app made in Android studio 3.1 with gradle v3.1.0, ran at android 5.1.1
build.gradle

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "ru.degeneration.empty"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    implementation 'com.dji:dji-uxsdk:4.5'
    implementation 'com.dji:dji-sdk:4.5'
    implementation 'com.dji:dji-sdk-provided:4.5'
}
```

```
public class RelativelyEmptyActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_relatively_empty);            
        DJISDKManager.getInstance().registerApp(this, null);
    }
}
```

**Comment by Michael-DJI** [comment]
implementation 'com.dji:dji-sdk-provided:4.5' need be changed  to compileOnly

**Comment by YandexWillKillYou** [comment]
It solves the problem. TY for fast response.

**Comment by lbx2015** [comment]
Following solve my problem   

 implementation ('com.dji:dji-uxsdk:4.16.2', {
        /**
         * Uncomment the following line to exclude amap from the app.
         * Note that Google Play Store does not allow APKs that include this library.
         */
        // AMAP: Do not include if publishing to Google Play Store. you should exclude it
        // exclude group: 'com.amap.api'
    })

    compileOnly ('com.dji:dji-sdk-provided:4.16.2')

if you are using uxsdk, you can avoid to add following:
 implementation ('com.dji:dji-uxsdk:4.16.2', {
        *//**
         * Uncomment the following line to exclude amap from the app.
         * Note that Google Play Store does not allow APKs that include this library.
         *//*
        // AMAP: Do not include if publishing to Google Play Store. you should exclude it
        // exclude group: 'com.amap.api'
    })
