### ISSUE TITLE
Stick throws not reversing when using Custom Gimbal Mapping

### ISSUE THREAD

**Issue by jmoore3274** [dji-sdk/Mobile-SDK-Android#276]
**-  Description of the issue.**
 
       When trying to set custom gimbal stick mapping the controls will not reverse when using 
       isReversed. However I do have normal movement direction as if the style was set to default.
       I do have toast messages displaying text to let me know the code executed correctly.
            
**-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)**
      
      Make a new instance of the GimbalMapping object and set properties. Call the 
       setGimbalMappingStyle method and set it to CUSTOM. Call the setCustomGimbalMapping method 
       and pass it the new GimbalMapping object then give it a new common call back. I'm not entirely 
       sure this is a bug or if I'm just not calling the isReversed correctly. My code is below.

      `if(app.getInvertVideoSwitchState()== true) {

            final GimbalMapping newCustomGimbalMapping = new GimbalMapping();
            newCustomGimbalMapping.leftHorizontal.isReversed();
            newCustomGimbalMapping.rightVertical.isReversed();

            mVideoSurface.setRotation(180.0f);
            ((Aircraft)FPVApplication.getProductInstance()).getRemoteController().setGimbalMappingStyle(GimbalMappingStyle.CUSTOM, new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError djiError) {

                }
            });
            ((Aircraft)FPVApplication.getProductInstance()).getRemoteController().setCustomGimbalMapping(newCustomGimbalMapping, new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError djiError) {

                    showToast("Custom Mapping Set");

                }
            });

        }else{

            mVideoSurface.setRotation(0.0f);
            ((Aircraft)FPVApplication.getProductInstance()).getRemoteController().setGimbalMappingStyle(GimbalMappingStyle.DEFAULT, new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError djiError) {

                    showToast("Default Mapping Set");

                }
            });
        }`

**-  Crash logs (If you can find it, it would be very helpful)**

      APP is not crashing

**-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)**
   
     Android Mobile 4.5 and Android UX 4.5

**-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)**

      DJI Inspire 1 and the DJI A3 with LB2. Both of these systems mount the following cameras that all 
     exhibit the same behavior. X3,Z3, XT640 Advanced Radiometry

**-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)**
    
     Android 7.0 on Samsung Galaxy S2 Tablet
     Android 7.1.1 on Samsung Galaxy Note 8

**-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)**

     Samsung Galaxy S2 Tablet and the Samsung Note 8    

**-  Android Studio version you are using (Like Android Studio 2.2, etc)**

      Android Studio 3.0.1

**Comment by ligongzixing** [comment]
@jmoore3274 It is a bug and will fix the next version.

**Comment by Michael-DJI** [comment]
@jmoore3274 if you have fix the issue with latest version of MSDK, please help to close the issue.

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
