### ISSUE TITLE
DJI SDK sample doesn't work

### ISSUE THREAD

**Issue by edancain** [dji-sdk/Mobile-SDK-Android#28]
Android Studio 2.0 (installed April 7th 2016). You guys are missing the ic_launch.png out of drawable. Finally able to compile it and launch it onto a Samsung SM-G920A smart phone. I have connected a Matrice RC controller to it, a Phantom 3 Professional and Phantom 4. In all cases baring none, the app main page status reads: Status: No Product Connected. Model not Available. So I can't open it. 
DJI SDK Version 3.1.

**Comment by SilverChangjian** [comment]
Hi thanks for your report. We will update the support for the Android Studio 2.0 in couple of days. For the sample, have you put the App key in the AndroidManifest.xml? What is the registration result?

**Comment by edancain** [comment]
Yes I put my App-Key into the AndroidManifest.xml file. Where is this registration result you write of? I have looked through a lot of the MainActivity java file and others trying to discover where this might be with no luck. Sorry for my ignorance, I don't code for Android often.

**Comment by edancain** [comment]
I think I see it in DJISampleApplication.java ::OnCreate method:
/**
         * handles SDK Registration using the API_KEY
         */
        DJISDKManager.getInstance().initSDKManager(this, mDJISDKManagerCallback);

**Comment by edancain** [comment]
onGetRegisteredResult(DJIError error) returns false. Ideas?

**Comment by edancain** [comment]
Your documentation is horribly out of date: This explanation does not reference the current downloadable sample. https://dji-dev.gitbooks.io/mobile-sdk-tutorials/content/en/Android/AndroidStudioMigration/Android_Studio_Migration_Tutorial_en.html

**Comment by SilverChangjian** [comment]
What's the error returned? If it returns success, then it should work.

**Comment by oliverou** [comment]
Hi all, we have updated the Android SDK Sample Project Readme.m file, please follow the process to run the Sample Code again. Also, we provide a new tutorial to teach you how to import DJI Android SDK to a new Android Studio project from scratch, please check this [Link](https://github.com/DJI-Mobile-SDK/Android-ImportSDKToAndroidStudio) for details.

**Comment by jtuchek** [comment]
@edancain the initialization callback requires an active internet connection as well - which isn't totally obvious from the documentation unless if you read the source for `DJIError`.

As for the documentation - pages hosted basically anywhere on DJIs official pages are still out of date, however docs that are bundles with the project under `API Reference/index.html` do appear to be current for v3.3 (as far as I've seen.)

**Comment by dji-dev** [comment]
Hi @edancain @jtuchek, currently, all the documentations hosted on DJI Mobile SDK Website are revamped and updated to DJI Mobile SDK 3.3, as well as the tutorials and sample projects on Github. The [DJI Mobile SDK Gitbook](https://dji-dev.gitbooks.io/mobile-sdk-tutorials) is now deprecated, please check the related tutorials on DJI Mobile SDK Website for details: <https://developer.dji.com/mobile-sdk/documentation/introduction/index.html>

BTW, @edancain the SDK activation process requires internet connection, please check this documentation for details: <https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-run.html#Internet-Connectivity> 

Please let us know if you find any documentations on DJI Developer Website or SDK Github Page are still out of date, we will do our best to update them as soon as possible. Thanks!

**Comment by talobin** [comment]
Will go ahead and close this issue since it has been a long time.
@edancain  Please help to create a separate issue if you still have problem with current version SDK 4.3.2
Thanks!
