### ISSUE TITLE
DJISampleApplication.getAircraftInstance()).getMobileRemoteController()获取的为null

### ISSUE THREAD

**Issue by firefecker** [dji-sdk/Mobile-SDK-Android#280]
请问一下，我在使用dji mobile sdk 4.5版本的sdk的时候用 DJISampleApplication.getAircraftInstance()).getMobileRemoteController()语句来获取MobileRemoteController对象时，始终都是获取的空值。使用手机控制飞机的飞行状态需要其他条件吗

**Comment by jacobsenmd** [comment]
I am having what I presume is the same problem with SDK v4.5. Periodically, after the DJI SDK detects an aircraft connected, all the components return null values. This includes at least the remote controller, flight controller, airline, and battery. I have validated with both a Pixel 2 (Android 8.1) and Samsung S7 (Android 7.0). Terminating and restarting the app does not seem to solve the problem. The only solution is to reinstall the app.

I have seen the problem with the Mavic Pro, and it seems to occur every time with the Mavic Air and Spark.

**Comment by Michael-DJI** [comment]
did you connect the drone directly with your phone? if the drone is not in direct-wifi mode, the MobileRemoteController will be null

**Comment by Michael-DJI** [comment]
did you resolve your issue?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
