### ISSUE TITLE
How to define events for buttons c1, c2 and listen for click events for buttons c1, c2 in dji mobile sdk

### ISSUE THREAD

**Issue by firefecker** [dji-sdk/Mobile-SDK-Android#286]
#### Is this issue about bugs or crash issues of DJI Android SDK and Sample Code?

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

-  Description of the issue.
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

#### Is this issue about DJI iOS SDK and Sample Code?

Then this is the wrong place, please refer to the Mobile-SDK-iOS Github: <https://github.com/dji-sdk/Mobile-SDK-iOS/issues>

**Comment by wocoltd** [comment]
Hi,

Have you tried creating a listener for RemoteControllerKey.CUSTOM_BUTTON_1?

The alternative if that isn't working is to use the RemoteController.setHardwareStateCallback, which is what we do.

Otherwise, please post more information about what you are trying to do?

wocoltd

**Comment by firefecker** [comment]
Execute me,
I listened by applying the RemoteController.setHardwareStateCallback, which can be implemented on the simulator, but it cannot be implemented in the actual situation.

**Comment by wocoltd** [comment]
I don't know why something would work on the simulator but not on an actual device. The following code works well for me on a Mavic Pro:
        
RemoteControllerKey keyC1 = RemoteControllerKey.create(RemoteControllerKey.CUSTOM_BUTTON_1);
KeyManager.getInstance().addListener(keyC1, (oldValue, newValue) -> {
   if( newValue != null ) {
      if( (HardwareState.Button)newValue).isClicked() ){
         // Do something
      }             
});

Hope that helps!

**Comment by fernando-s97** [comment]
Hi! 

With this approach can I configure the button action? I mean... If I create a C1 listener to disable the front LED and a C2 listener to enable them, these "settings" will be saved in the remote controller?

If not, you guys know can I achieve this?

**Comment by kenargo** [comment]
I do not believe they are saved in the RC because the listener fires for every RC button press.  If they where saved then there would be no need for a listener to fire.

 

It’s easy enough to verify; configure the button action, connect the app to the drone, verify the listeners perform the action.  Then disconnect the device from the RC and try the buttons again; my bet is they don’t do anything because the app is no longer responding to the buttons.
