### ISSUE TITLE
Changing video standard giving error even though it succeeds.

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#287]
Platform: Android 
SDK: 4.4.1
Drone: Mavic Pro

I am trying to set the video standard by the following code
```

        videoStandard = SettingsDefinitions.VideoStandard.NTSC;
OR
        videoStandard = SettingsDefinitions.VideoStandard.PAL;

```
```
public void setVideoStandard(final SettingsDefinitions.VideoStandard videoStandard) {
        Aircraft aircraft = AircraftManager.getAircraft();
        if (aircraft != null && aircraft.getCamera() != null) {
            aircraft.getCamera().setVideoStandard(videoStandard, new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError djiError) {
                            if (djiError != null) {
showMessage(djiError.getDescription());
                            }
                }
            });
        }
    }

```
I am getting the djierror as "Camera failed to set the parameters it received". But in reality it is actually getting set. If I call the **getVideoStandard()** method in a similar way, I am able to see that the video standard has been set.

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
