### ISSUE TITLE
How to upload real-time data to external servers?

### ISSUE THREAD

**Issue by QAKill** [dji-sdk/Mobile-SDK-Android#288]
hello everybody.
I want upload real-time data from drone to external servers by RTMP Protocol.
How to do it?
I need some help.
the platform is Android.

**Comment by EXEShirley** [comment]
Sorry, We don't provide such interfaces.

**Comment by kenargo** [comment]
This functionality is not directly supported but the SDK but you can write code that will capture the flight data and send RTMP.You might be able to find an RTMP library or you might need to write one, I don't know what's available. On May 3, 2018 9:04 AM, LIU SIQI <notifications@github.com> wrote:hello everybody.
I want upload real-time data from drone to external servers by RTMP Protocol.
How to do it?
I need some help.
the platform is Android.
