### ISSUE TITLE
SDK - smal and big problem

### ISSUE THREAD

**Issue by AlexanderMaydorf** [dji-sdk/Mobile-SDK-Android#29]
getShutterSpeed()

APP will crash if getShutterSpeed is used in ExposureMode "P"rogram or "A"perture Priority

Someone said, this is correct, because shutter speed can not be SET in this modes - so there is also no GET.
This must be wrong. First: Aperture would be the same - You can't SET Aperture in "P"rogram or "S"hutter Priority - but this value you can GET all the time.
Also - even in "P" or "A" - it's important to see, which value the camera will be use for shutter Speed. So I can decide to go to a manual mode or use the program mode.

upper and lower case in constants

Not all the time I use auto complete - but this can bring a lot of Syntax error search - like:

Resolution_2704X1520  - Video resolutions are have a smal "x" - only 2704X1520.
There are also some constants -only- in upper case...

**Comment by SilverChangjian** [comment]
Thanks for your report. This problem has already reported to the developers. Will provide the feedback, when i get the result from the developers.

**Comment by talobin** [comment]
Will go ahead and close this issue since it has been a long time.
@AlexanderMaydorf Please help to create a separate issue if you still have problem with current version SDK 4.3.2
Thanks!
