### ISSUE TITLE
Feature request: pull SRT file from medialist

### ISSUE THREAD

**Issue by hblanken** [dji-sdk/Mobile-SDK-Android#291]
Has anyone been able to pull the video caption SRT file via the SDK or via other means from drone to android device? 

In the code it currently says:
>The information is updated at 1Hz. Currently the .srt file can only be downloaded directly from the SD card.

@oliverou Can the mobile SDK please enable downloading this file along the mp4 file in the Media call.

**Comment by XietongLU** [comment]
No. There is no plan for this yet.

**Comment by hblanken** [comment]
@Michael-DJI  - if you closed this - do you mind pointing us to the implementation of this in the latest SDK? I cannot find it easily. Thanks!

**Comment by Michael-DJI** [comment]
@hblanken sorry about it, currently we don't have this kind of interface, but I have collected your idea as a feature request, we will do some investigation and discussion to decide if it's necessary to implement this feature.
