### ISSUE TITLE
How to get channel selection mode for Wifi link ?

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#295]
SDK: 4.4.1
Platform: Android
Mode: Spark

There is no way to get channel selection mode for Wifi link. But there are methods to get channelSelectionMode in  LightBridgeLink and OcusyncLink.

I tried with AirLinkKey.CHANNEL_SELECTION_MODE, which returns "Feature unsupported"

DJIKey djiKey = AirLinkKey.createWiFiLinkKey(AirLinkKey.CHANNEL_SELECTION_MODE);
        KeyManager.getInstance().getValue(djiKey, new GetCallback() {
            @Override
            public void onSuccess(final Object o) {
              
            }

            @Override
            public void onFailure(final DJIError djiError) {
              
            }
        });

**Comment by Michael-DJI** [comment]
will add it in next version, thanks for your feedback.

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
