### ISSUE TITLE
Can not use PWM(Pulse width modulation)

### ISSUE THREAD

**Issue by Minhom** [dji-sdk/Mobile-SDK-Android#297]
Pulse width modulation is available when I use the remote control to take photos,but when I using SDK to take photos, it will not work.
So I'd like to know how to open the PWM of the f channel. I cant find the answer in API document.
thanks a lot.

**Comment by Michael-DJI** [comment]
pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
