### ISSUE TITLE
The pitch and roll has something wrong when sendVirtualStickFlightControlData.

### ISSUE THREAD

**Issue by hopeful0** [dji-sdk/Mobile-SDK-Android#30]
I met a strange problem when I developer a Mobile APP using this SDK.
When I used the sendVirtualStickFlightControlData in this APP, I found that the **pitch** in the Data make the aircraft move right and the **roll** in the Data make the aircraft move ahead.
I checked the code and try the Sample,then I found the problem appeared again.
In fact,it is not allways wrong.Only the ** RollPitchControlMode** is "velocity",the problem will appear.If it is "angle",the program is nromal.
Poor English,so sorry.
Devices:Any Devices
IDE:Android Studio2.0

**Comment by dji-dev** [comment]
Hi, I think the following tutorial would explain why the right direction value would cause the moving ahead.  https://developer.dji.com/mobile-sdk/get-started/Virtual-Stick-User-Guide/.

**Comment by hopeful0** [comment]
I think you don't understand my issue.I meant that when I use "angle" mode the pitch make aircraft go ahead and back(it is right according your guide),but in "velocity" mode the pitch make the aircraft move left and right.I don't know why it is so different in this two modes,I had read the guide before,but it didn't told me the why this happend.

**Comment by hopeful0** [comment]
Oh,I find it.Thanks!

**Comment by chenxiaojin** [comment]
@dji-dev the url “https://developer.dji.com/mobile-sdk/get-started/Virtual-Stick-User-Guide“ is not found。 Can you give me the newest url？ I have the same problem， thanks
