### ISSUE TITLE
Feature Request: Skip Waypoint in Mission

### ISSUE THREAD

**Issue by Stevenhua03** [dji-sdk/Mobile-SDK-Android#300]
Are you guys planning on adding the ability to skip a waypoint during a mission? 

Its a bit of a niche idea but it could help speed up missions if the user only wants to perform a portion of a mission. We would have use for this particular feature and would like to see it included in the SDK if possible.

**Comment by Michael-DJI** [comment]
pls use getWaypointList() method in Builder to get the list and then you could remove one waypoint as you like, then rebuild the waypoint mission and re-upload it.

**Comment by Stevenhua03** [comment]
Right, this would allow the user to perform a part of the mission but is it possible to skip waypoints while the mission is running without having to re-upload the rest of the waypoints?

**Comment by Michael-DJI** [comment]
@Stevenhua03  it's not allowed to change the waypoint in running state.

**Comment by Stevenhua03** [comment]
Thanks for answering!
