### ISSUE TITLE
Waypoint.shootPhotoDistanceInterval

### ISSUE THREAD

**Issue by Minhom** [dji-sdk/Mobile-SDK-Android#301]
Is it possible to use the PWM(Pulse width modulation) in the  WaypointMisson 
 Waypoint.shootPhotoDistanceInterval().
I cannot find the answer in the sdk document,and I really need to find out the answer.
thanks a lot!!

**Comment by kenargo** [comment]
I don't understand the request; use PWM for what purpose?  It sounds like you are asking to use some external trigger to alter the photo shoot???

**Comment by wenqianqiao** [comment]
Could you please give more descriptions so we could help you on that.

**Comment by Minhom** [comment]
We use the m600 and the plug-in camera. We now need to trigger the plug-in camera to take a picture by PWM when the shootpointByDistance of waypointMission is triggered. So I want to know if the PWM trigger is controlled in the SDK.

**Comment by igala** [comment]
We could not make shootPhotoDistanceInterval not shootPhotoTimeInterval feature work. The mission upload got stuck during uploading mission to aircraft.
Can anyone acknowledge that this feature works? is there a sample code available ?

**Comment by Michael-DJI** [comment]
pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
