### ISSUE TITLE
Sometimes, Phantom 4 PRO don't reach last points of WayPoint mission - fly only part of route.

### ISSUE THREAD

**Issue by trofunenko** [dji-sdk/Mobile-SDK-Android#304]
This issue did't reproduce with simulator, only in the field.  Approx one time in a ten. Drone API upload, execute and completed mission without any errors, but aircraft fly only part of route. 

09:16:17  Drone state = EXECUTING, stateDelay = 15091
09:16:17 case WAIT_END_EXECUTE, state delay = 15091, limit=36000, GPS_WAYPOINT, LEVEL_5
09:16:17 Listener onExecutionFinish: Success!
09:16:17 Drone state = READY_TO_UPLOAD, stateDelay = 15092
09:16:17 case WAIT_END_EXECUTE, state delay = 15092, limit=36000, GPS_WAYPOINT, LEVEL_5

-  DJI Android SDK version you are using  - 4.3.2
-  DJI Product you are using - Phantom 4 Pro
-  Android 5.0
-  Samsung Galaxy Note 3
-  Android Studio 3.1.0 

Firmware version is : 
![img_20180424_160613-2](https://user-images.githubusercontent.com/8773523/40702370-3b0496ce-63ea-11e8-9479-3f17108a5a90.jpg)
![img_20180424_160620-2](https://user-images.githubusercontent.com/8773523/40702371-3b258d02-63ea-11e8-85be-8d2fa9f6c95d.jpg)

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
