### ISSUE TITLE
Code not building

### ISSUE THREAD

**Issue by mihirbala** [dji-sdk/Mobile-SDK-Android#305]
Code does not build unmodified in Android Studio 3.1.2.  Works when the following code is commented out in the build.gradle file:
`plugins {
    id "me.tatarka.retrolambda" version "3.5.0"
}`

**Comment by railsGod** [comment]
had the same issue, same solution

**Comment by Jai-GAY** [comment]
i believe the [details explanation is here](https://developer.android.com/studio/write/java8-support). got the warning already before build.

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
