### ISSUE TITLE
Spark: The live view in FPVWidget keeps shifting on changing the size the widget programatically

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#307]
SDK : 4.5.1
Platform: Android
Drone: Spark

The spark has a 4:3 live view display in FPVWidget. 
Steps Followed:
1. Show live view in a screen with hardcoded width and height[For e.g.: 100dp].
2. On clicking the live view, I am updating the width and height of the Fpvwidget to full screen. Observe:
Result : The live view in full screen is not center aligned.

Sometimes putting app in background and launching will refresh the Fpvwidget and automatically aligns live view to centre.

Note: This issue is not observed for 4:3 aspect ratio in Mavic and Phantom.

**Comment by Abhishek284** [comment]
This also happens in Phantom 4 Advanced for 4:3 live view aspect ratio.

**Comment by Abhishek284** [comment]
I tried the adding the following code in the official GitHub project to resize the FPV widget and it was not resizing properly.
https://github.com/dji-sdk/Mobile-UXSDK-Android

 ```
button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (!isFull) {
                    isFull = true;
                    RelativeLayout.LayoutParams fpvWidgetParams = (RelativeLayout.LayoutParams) fpvWidget.getLayoutParams();
                    Point screenSize = getScreenSize(MainActivity.this);
                    fpvWidgetParams.height = screenSize.y;
                    fpvWidgetParams.width = screenSize.x;
                } else {
                    isFull = false;
                    RelativeLayout.LayoutParams fpvWidgetParams = (RelativeLayout.LayoutParams) fpvWidget.getLayoutParams();
                    fpvWidgetParams.width = (int) getResources().getDimension(R.dimen.width);
                    fpvWidgetParams.height = (int) getResources().getDimension(R.dimen.width);
                }
            }
        });
```

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by Abhishek284** [comment]
This issue is still present in the SDK. It can be observed by setting 4:3 aspect ration for camera view in Mavic Air, Spark , Phantom 4 Advanced.

**Comment by KPN-DJI** [comment]
@Abhishek284 This was working as expected with the latest sample app on v4.9 of the UXSDK using "Resize" in the `CustomizedWidgetsActivity`. Something to note - in the XML file the FPVWidget's centerInParent parameter must be set to true in this manner - `android:layout_centerInParent="true"`if you would like it to be centered at all times.
