### ISSUE TITLE
DJICrashHandler handled my RuntimeException and gave no useful instruction to solve it.

### ISSUE THREAD

**Issue by zzhall** [dji-sdk/Mobile-SDK-Android#308]
App crashes and DJICrashHandler just handle the exception, showing these useful logs at logical below:

![image](https://user-images.githubusercontent.com/26140321/41029382-1b91c374-69ae-11e8-8fdf-1d2abbe46ab2.png)

I just can't get any useful information (such as RuntimeException type, position in code) from those logs! It is so awful that I have to use my own CrashHandler to generate a log file on my phone and open it to get the Exception log. And those Exceptions are none of DJI's business.

Do something, please!

**Comment by Michael-DJI** [comment]
@zzhall, firstly sorry for the problem, pls provide the MSDK version you are using, and try to use the latest version, we couldn't reproduce the issue you mentioned.
