### ISSUE TITLE
[Question] RCGps frequency

### ISSUE THREAD

**Issue by andre-nguyen** [dji-sdk/Mobile-SDK-Android#31]
Hi,

after testing DJIRemoteController.RCGpsDataUpdateCallback I noticed that the update frequency varies a lot, sometimes even with 9 satellites it took a few seconds for the callback to be triggered, at its worst it took 20 seconds between two calls.

Question: What is the criterion for the RCGps callback to be triggered, is it when there is significant motion? I also noticed that speed east and speed north was 0 while I was walking around. Do I need to move faster?

Thanks,

**Comment by kenargo** [comment]
Most of the callbacks are triggered when information changes and not by time.  The only callback I am aware of is updateSystemStateCallback (which happens every 100ms).

 

As for the RCGpsDataUpdateCallback, what aircraft are you testing with?  The callback is only used for RC controllers that have GPS modules; I think only the Inspire and likely the Matrice units have them.  None of the Phantom model’s RC units have GPS and will return 0.

**Comment by andre-nguyen** [comment]
I'm testing with the m100. The callback works and I get data. I'm mostly trying to get a better understanding of what performance I can expect.

**Comment by kenargo** [comment]
I haven’t seen documentation at that level; you will need DJI people to answer that part.

**Comment by andre-nguyen** [comment]
@SilverChangjian any ideas?

**Comment by SilverChangjian** [comment]
Hi thanks for your reporting. For all of the callbacks in the SDK, they will be fired only when the data they listened is changed. We will investigate the speed value as you mentioned. Will provide result when we get the result.

**Comment by andre-nguyen** [comment]
Thanks, for the speed being 0 it might just be that I wasn't walking fast enough. Does the RC GPS calculate speed through differentiation or through doppler effect?
