### ISSUE TITLE
Is there a way of telling if the drone has a built in FPV camera?

### ISSUE THREAD

**Issue by Nitaym** [dji-sdk/Mobile-SDK-Android#310]
-  Description of the issue.
(Unless we missed it) The SDK doesn't provide a function that tells us whether FPV is supported on a drone.

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
DJI SDK 4.5.1

**Comment by Michael-DJI** [comment]
right now only Inspire2 M200 M210 and M210rtk have build-in FPV camera
