### ISSUE TITLE
getRCSwitchFlightModeMapping return wrong values on M100 and Inspire 1 series

### ISSUE THREAD

**Issue by ltluc253** [dji-sdk/Mobile-SDK-Android#312]
This method return wrong values when I test on M100 and Inspire 1 series.

- DJI SDK: 4.5.1

- Test devices: M100 and Inspire 1 series.

Actual: the modes in Remote Controller is F, A, P but this method return A, S, P.
Expected: return correct value on the callback.

**Comment by Michael-DJI** [comment]
it will be fixed in next version.
