### ISSUE TITLE
About DJISDKManager.getInstance().destroy();

### ISSUE THREAD

**Issue by aforme** [dji-sdk/Mobile-SDK-Android#316]
-  when i call **DJISDKManager.getInstance().destroy()** in Activity's onDestory() fun , app report **java.lang.NullPointerException**
-  i'm not yet connect to DJI Product use usb line

[crash-2018-06-14-17-24-28.txt](https://github.com/dji-sdk/Mobile-SDK-Android/files/2101663/crash-2018-06-14-17-24-28.txt)

**Comment by Michael-DJI** [comment]
it has been fixed in 4.8.1
