### ISSUE TITLE
Phantom 3 Standard open nothing happens

### ISSUE THREAD

**Issue by augre** [dji-sdk/Mobile-SDK-Android#32]
Hi,

I made an .apk out of the SDK sample and ran it on my oneplus one android phone with phantom 3 standard connected, and when I hit open, it doesn't do anything. What could cause this?

Thank you!

![screenshot_20160616-144627](https://cloud.githubusercontent.com/assets/2387022/16143847/b249b3b0-346f-11e6-9c56-c8a3de629ed8.png)

**Comment by augre** [comment]
It builds with some errors:
AGPBI: {"kind":"error","text":"this warning is that reflective operations on this class will incorrectly","sources":[{}]}
AGPBI: {"kind":"error","text":"indicate that it is *not* an inner class.","sources":[{}]}
AGPBI: {"kind":"error","text":"warning: Ignoring InnerClasses attribute for an anonymous inner class","sources":[{}]}
AGPBI: {"kind":"error","text":"(dji.thirdparty.a.b.b.c.d) that doesn\u0027t come with an","sources":[{}]}
AGPBI: {"kind":"error","text":"associated EnclosingMethod attribute. This class was probably produced by a","sources":[{}]}
AGPBI: {"kind":"error","text":"compiler that did not target the modern .class file format. The recommended","sources":[{}]}
AGPBI: {"kind":"error","text":"solution is to recompile the class from source, using an up-to-date compiler","sources":[{}]}
AGPBI: {"kind":"error","text":"and without specifying any \"-target\" type options. The consequence of ignoring","sources":[{}]}
AGPBI: {"kind":"error","text":"this warning is that reflective operations on this class will incorrectly","sources":[{}]}
AGPBI: {"kind":"error","text":"indicate that it is *not* an inner class.","sources":[{}]}
AGPBI: {"kind":"error","text":"warning: Ignoring InnerClasses attribute for an anonymous inner class","sources":[{}]}
AGPBI: {"kind":"error","text":"(dji.thirdparty.a.b.b.c.e) that doesn\u0027t come with an","sources":[{}]}
AGPBI: {"kind":"error","text":"associated EnclosingMethod attribute. This class was probably produced by a","sources":[{}]}
AGPBI: {"kind":"error","text":"compiler that did not target the modern .class file format. The recommended","sources":[{}]}
AGPBI: {"kind":"error","text":"solution is to recompile the class from source, using an up-to-date compiler","sources":[{}]}
AGPBI: {"kind":"error","text":"and without specifying any \"-target\" type options. The consequence of ignoring","sources":[{}]}
AGPBI: {"kind":"error","text":"this warning is that reflective operations on this class will incorrectly","sources":[{}]}
AGPBI: {"kind":"error","text":"indicate that it is *not* an inner class.","sources":[{}]}

:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug
:dJISDKLIB:preDebugBuild UP-TO-DATE
:dJISDKLIB:compileDebugNdk UP-TO-DATE
:dJISDKLIB:copyDebugLint UP-TO-DATE
:dJISDKLIB:mergeDebugProguardFiles UP-TO-DATE
:dJISDKLIB:packageDebugRenderscript UP-TO-DATE
:dJISDKLIB:checkDebugManifest
:dJISDKLIB:prepareDebugDependencies
:dJISDKLIB:compileDebugRenderscript UP-TO-DATE
:dJISDKLIB:generateDebugResValues UP-TO-DATE
:dJISDKLIB:generateDebugResources UP-TO-DATE
:dJISDKLIB:packageDebugResources UP-TO-DATE
:dJISDKLIB:compileDebugAidl UP-TO-DATE
:dJISDKLIB:generateDebugBuildConfig UP-TO-DATE
:dJISDKLIB:mergeDebugShaders UP-TO-DATE
:dJISDKLIB:compileDebugShaders UP-TO-DATE
:dJISDKLIB:generateDebugAssets UP-TO-DATE
:dJISDKLIB:mergeDebugAssets UP-TO-DATE
:dJISDKLIB:processDebugManifest UP-TO-DATE
:dJISDKLIB:processDebugResources UP-TO-DATE
:dJISDKLIB:generateDebugSources UP-TO-DATE
:dJISDKLIB:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:dJISDKLIB:compileDebugJavaWithJavac UP-TO-DATE
:dJISDKLIB:processDebugJavaRes UP-TO-DATE
:dJISDKLIB:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:dJISDKLIB:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:dJISDKLIB:mergeDebugJniLibFolders UP-TO-DATE
:dJISDKLIB:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:dJISDKLIB:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:dJISDKLIB:bundleDebug UP-TO-DATE
:dJISDKLIB:compileDebugSources UP-TO-DATE
:dJISDKLIB:assembleDebug UP-TO-DATE

BUILD SUCCESSFUL

Total time: 23.037 secs

**Comment by jtuchek** [comment]
Hi @augre - if you check out the `MainContent` there's something similar to this:
`        mBtnOpen.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (Utils.isFastDoubleClick()) return;
                EventBus.getDefault().post(new SetViewWrapper(R.layout.content_component_list, R.string.activity_component_list, getContext()));
            }
        });`

You could try adding a breakpoint here and debugging it. Either the touch event is being interpreted as a double click or the event being posted isn't being received.

**Comment by talobin** [comment]
Will go ahead and close this issue since it has been a long time.
@augre  Please help to create a separate issue if you still have problem with current version SDK 4.3.2
Thanks!
