### ISSUE TITLE
WaypointMissionOperatorListener callbacks is not firing 

### ISSUE THREAD

**Issue by AdamKraif** [dji-sdk/Mobile-SDK-Android#323]
Hi,

I use SDK version 4.5.1.
And I doesn't get any callbacks when the mission is being executed
 (the mission is going according to plan except the callbacks part).
Please Help.

 Here's my code:

  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // When the compile and target version is higher than 22, please request the
        // following permissions at runtime to ensure the
        // SDK work well.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            ActivityCompat.requestPermissions(this,
                    new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.VIBRATE,
                            Manifest.permission.INTERNET, Manifest.permission.ACCESS_WIFI_STATE,
                            Manifest.permission.WAKE_LOCK, Manifest.permission.ACCESS_COARSE_LOCATION,
                            Manifest.permission.ACCESS_NETWORK_STATE, Manifest.permission.ACCESS_FINE_LOCATION,
                            Manifest.permission.CHANGE_WIFI_STATE, Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS,
                            Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.SYSTEM_ALERT_WINDOW,
                            Manifest.permission.READ_PHONE_STATE,
                    }
                    , 1);
        }

        setContentView(R.layout.activity_main);

        initUI();

        addListener();

        poller = new Runnable() {
            private long time = 0;

            @Override
            public void run() {
                // do stuff then
                // can call h again after work!
                time += 1000;
                reportCheckpoint(null);
            }
        };

        missionHanlderPoller = new Runnable() {

            @Override
            public void run() {
                sendToServer("control", "manageDrone", null, new HttpUtils.OnSucccess() {
                    @Override
                    public void OnResult(JSONObject result) {
                        try {
                            if (controlActions != null) {
                                if (!controlActions.getString("startMission").equalsIgnoreCase(result.getString("startMission"))) {
                                    if (controlActions.getString("startMission").equalsIgnoreCase("") && !result.getString("startMission").equalsIgnoreCase("")) {
                                        // starting new mission
                                        final String missionId = result.getString("startMission");
                                        loadSettings(missionId, new CommonCallbacks.CompletionCallback() {
                                            @Override
                                            public void onResult(DJIError djiError) {
                                                new Timer().schedule(
                                                        new TimerTask() {
                                                        @Override
                                                        public void run() {
                                                            startWaypointMission(new CommonCallbacks.CompletionCallback() {
                                                                @Override
                                                                public void onResult(DJIError djiError) {
                                                                    setResultToToast("Mission " + missionId + " triggered from control center", true);
                                                                }
                                                            });
                                                        }
                                                    },
                                                    1000
                                                );
                                            }
                                        });
                                    } else if (!controlActions.getString("startMission").equalsIgnoreCase("") && result.getString("startMission").equalsIgnoreCase("")) {
                                        // stopping mission execution
                                        stopWaypointMission(new CommonCallbacks.CompletionCallback() {
                                            @Override
                                            public void onResult(DJIError djiError) {
                                                setResultToToast("Mission stopped from control center", true);
                                            }
                                        });
                                    }
                                }
                            }
                        } catch(JSONException jex) {

                        }

                        controlActions = result;
                    }
                }, new HttpUtils.OnFailure() {
                    @Override
                    public void OnResult(Exception error) {

                    }
                });
            }
        };

  private void addListener() {
        if (getWaypointMissionOperator() != null){

            getWaypointMissionOperator().addListener(eventNotificationListener);
        }
    }

 private WaypointMissionOperatorListener eventNotificationListener = new WaypointMissionOperatorListener() {
        @Override
        public void onDownloadUpdate(WaypointMissionDownloadEvent downloadEvent) {
            setResultToToast("onDownloadUpdate", false);

        }

        @Override
        public void onUploadUpdate(WaypointMissionUploadEvent uploadEvent) {
            setResultToToast("onUploadUpdate", false);
      
        }

        @Override
        public void onExecutionUpdate(WaypointMissionExecutionEvent executionEvent) {
            setResultToToast("onExecutionUpdate", false);
        }

        @Override
        public void onExecutionStart() {
            setResultToToast("onExecutionStart", false);

        }

        @Override
        public void onExecutionFinish(@Nullable final DJIError error) {
            setResultToToast("onExecutionFinish", false);     
        
        }
    };

public WaypointMissionOperator getWaypointMissionOperator() {

        if (instance == null) {
            if (DJISDKManager.getInstance().getMissionControl() != null){
                setResultToToast("getWaypointMissionOperator start", false);
                instance = DJISDKManager.getInstance().getMissionControl().getWaypointMissionOperator();
            }

        }
        return instance;
    }

**Comment by kenargo** [comment]
The SDK suggests a different way to get the MissionOperator as I’ve shown below.

public WaypointMissionOperator getWaypointMissionOperator() {
	if (instance == null) {
        instance = MissionControl.getInstance().getWaypointMissionOperator()
	}

return instance;
}

Another thing I notice missing (maybe you didn’t include the code) is the call to instance.loadMission and instance.uploadMission.  loadMission is called to load the mission into the SDK like this:

Instance.loadMission(mission) is called to load the mission into the SDK memory and validate the mission instance.uploadMission moves the mission into the UAV.

Note:  You should NOT call instance.StartMission until the callback onUploadUpdate completed uploading all points and the call to getCurrentState() == WaypointMissionState.READY_TO_EXECUTE otherwise the mission will be partially uploaded.  You maynot see this failure in small missions but once you get more than a few waypoint I think you will start seeing an error.

**Comment by kenargo** [comment]
The SDK suggests a different way to get the MissionOperator as I’ve shown below.

 

public WaypointMissionOperator getWaypointMissionOperator() {

        if (instance == null) {

        instance = MissionControl.getInstance().getWaypointMissionOperator()

  }

return instance;

}

 

Another thing I notice missing (maybe you didn’t include the code) is the call to instance.loadMission and instance.uploadMission.  loadMission is called to load the mission into the SDK like this:

 

Instance.loadMission(mission) is called to load the mission into the SDK memory and validate the mission instance.uploadMission moves the mission into the UAV.

 

Note:  You should NOT call instance.StartMission until the callback onUploadUpdate completed uploading all points and the call to getCurrentState() == WaypointMissionState.READY_TO_EXECUTE otherwise the mission will be partially uploaded.  You maynot see this failure in small missions but once you get more than a few waypoint I think you will start seeing an error.
 

 

Hope this helps.

**Comment by Michael-DJI** [comment]
@AdamKraif accroding @kenargo 's advice, did you resolve your issue?

**Comment by AdamKraif** [comment]
@kenargo  yes we switched to IOS SDK ;)

**Comment by Michael-DJI** [comment]
@AdamKraif well, I think latest Android SDK also could work now, anyway you have resolved it, in future you could report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
