### ISSUE TITLE
Failed to build after update to 4.6

### ISSUE THREAD

**Issue by Chickinnick** [dji-sdk/Mobile-SDK-Android#325]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForProdDebug'.
> More than one file was found with OS independent path 'lib/x86/libRoadLineRebuildAPI.so'

```
I tried to add 
` packagingOptions{
        doNotStrip "*/*/libRoadLineRebuildAPI.so"
      }
 `
but this doesn't helps

**Comment by Chickinnick** [comment]
Helped downgrade 
`   implementation 'com.dji:dji-uxsdk:4.5.1'`
but the issue is still present for 4.6

**Comment by kenargo** [comment]
Look at the updated sample,  there are new so files,  fix the gradle file and build will work. 

⁣Sent from BlueMail ​

**Comment by Chickinnick** [comment]
@kenargo  thank you!  
` packagingOptions {       pickFirst 'lib/*/libstlport_shared.so'
        pickFirst 'lib/*/libRoadLineRebuildAPI.so'
        pickFirst 'lib/*/libGNaviUtils.so'
        pickFirst 'lib/*/libGNaviMapex.so'
        pickFirst 'lib/*/libGNaviData.so'
        pickFirst 'lib/*/libGNaviMap.so'
        pickFirst 'lib/*/libGNaviSearch.so'
     }  ` makes it built

**Comment by kenargo** [comment]
The sample shws this:

 

packagingOptions {
    doNotStrip "*/*/libdjivideo.so"
    doNotStrip "*/*/libSDKRelativeJNI.so"
    doNotStrip "*/*/libFlyForbid.so"
    doNotStrip "*/*/libduml_vision_bokeh.so"
    doNotStrip "*/*/libyuv2.so"
    doNotStrip "*/*/libGroudStation.so"
    doNotStrip "*/*/libFRCorkscrew.so"
    doNotStrip "*/*/libUpgradeVerify.so"
    doNotStrip "*/*/libFR.so"

    pickFirst 'lib/*/libstlport_shared.so'
    pickFirst 'lib/*/libRoadLineRebuildAPI.so'
    pickFirst 'lib/*/libGNaviUtils.so'
    pickFirst 'lib/*/libGNaviMapex.so'
    pickFirst 'lib/*/libGNaviData.so'
    pickFirst 'lib/*/libGNaviMap.so'
    pickFirst 'lib/*/libGNaviSearch.so'
    exclude 'META-INF/rxjava.properties'
}
