### ISSUE TITLE
Random app crash - could be when cell connection is weak (guess based on observation)

### ISSUE THREAD

**Issue by kenargo** [dji-sdk/Mobile-SDK-Android#326]
Android SDK - apps built with the SDK randomly crash with the below crash stack.

-  Run SDK based app; register SDK
-  4.6 SDK for Android
-  Various (the attached was Phantom 4
-  Android 8 on Samsung Tab 
-  Android Studio version 3.2 but happened with 3.1

Crash Stack files below:

[crash-2018-07-06-10-18-15.txt](https://github.com/dji-sdk/Mobile-SDK-Android/files/2171594/crash-2018-07-06-10-18-15.txt)
[crash-2018-07-06-10-23-35.txt](https://github.com/dji-sdk/Mobile-SDK-Android/files/2171595/crash-2018-07-06-10-23-35.txt)
[crash-2018-07-06-10-49-21.txt](https://github.com/dji-sdk/Mobile-SDK-Android/files/2171596/crash-2018-07-06-10-49-21.txt)

**Comment by Michael-DJI** [comment]
it will be fixed in next version. BTW you could report the issue in Stackoverflow using "dji-sdk" tag, it will attract more attention of our supporting team.
