### ISSUE TITLE
5840 error(s)

### ISSUE THREAD

**Issue by alexblack** [dji-sdk/Mobile-SDK-Android#33]
Hi, I'm just getting started with the Android Mobile SDK, I cloned it from the repo, and I'm trying to build the sample app.  I'm using Android Studio 2.1.2, and gradle plugin 2.1.2.  

I get this message when I build:

1:18:30 PM Gradle build finished with 5840 error(s) in 3m 16s 855ms

You can see the full build output here: https://gist.github.com/alexblack/70a2414a4ce6013df886a26a25e7206f
Here is a sample of some errors, how do I fix this?

AGPBI: {"kind":"error","text":"warning: Ignoring InnerClasses attribute for an anonymous inner class","sources":[{}]}
AGPBI: {"kind":"error","text":"(org.bouncycastle.asn1.ASN1InputStream$1) that doesn\u0027t come with an","sources":[{}]}
AGPBI: {"kind":"error","text":"associated EnclosingMethod attribute. This class was probably produced by a","sources":[{}]}
AGPBI: {"kind":"error","text":"compiler that did not target the modern .class file format. The recommended","sources":[{}]}
AGPBI: {"kind":"error","text":"solution is to recompile the class from source, using an up-to-date compiler","sources":[{}]}
AGPBI: {"kind":"error","text":"and without specifying any \"-target\" type options. The consequence of ignoring","sources":[{}]}
AGPBI: {"kind":"error","text":"this warning is that reflective operations on this class will incorrectly","sources":[{}]}
AGPBI: {"kind":"error","text":"indicate that it is _not_ an inner class.","sources":[{}]}
AGPBI: {"kind":"error","text":"warning: Ignoring InnerClasses attribute for an anonymous inner class","sources":[{}]}

**Comment by kenargo** [comment]
The link doesn’t work.

 

Did you follow the instructions on how to obtain and add an SDK license code into the app?

**Comment by alexblack** [comment]
Fixed the link.  Yes, I have put a license key in the AndroidManifest.xml file.

**Comment by kenargo** [comment]
What is the link?  The email clipped the URL.

**Comment by alexblack** [comment]
https://gist.github.com/alexblack/70a2414a4ce6013df886a26a25e7206f

**Comment by arstk8** [comment]
I'm also seeing very similar errors (except I have 12059 errors).  I'm using the DJI Android Mobile SDK 3.4.1 with Android Studio 2.2.2 on OSX.  I've tried tweaking my proguard rules, but no luck so far.

**Comment by xxmaestroxx** [comment]
Hey DJI,

what is the status of this issue?

Regards
Maestro

**Comment by talobin** [comment]
Will go ahead and close this issue since it has been a long time.
@alexblack Please help to create a separate issue if you still have problem with current version SDK 4.3.2
Thanks!
