### ISSUE TITLE
GimbalKey.YAW_ANGLE_WITH_AIRCRAFT_IN_DEGREE returns null

### ISSUE THREAD

**Issue by Lloyd2205** [dji-sdk/Mobile-SDK-Android#335]
Platform: Android
Dji Mobile Sdk : 4.5.1

 ` DJIKey gimbalHeadingKey = FlightControllerKey.create(GimbalKey.YAW_ANGLE_WITH_AIRCRAFT_IN_DEGREE);`

The value of gimbalHeadingKey returns null.
Also the method  getYawRelativeToAircraftHeading( ) is not found.

**Comment by EXEShirley** [comment]
Please do not use "FlightControllerKey.create" to create a GimbalKey.
