### ISSUE TITLE
MediaFile fetchFileData() much slower than DJI GO App download

### ISSUE THREAD

**Issue by hanming-nls** [dji-sdk/Mobile-SDK-Android#337]
-  Description of the issue.
Following the code of MediaManager Demo, the downloading of photo from the aircraft is successful but much slower than the DJI GO App.
Downloading a 7mb photo from aircraft using DJI GO App takes ~7 secs.
Downloading the same photo from aircraft using SDK code takes ~70 secs

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
Please refer to the attached animated gif
![dji](https://user-images.githubusercontent.com/33014397/43753635-58201b86-9a39-11e8-9e67-d5f95a749db6.gif)

The code used is adapted from 
https://developer.dji.com/mobile-sdk/documentation/android-tutorials/MediaManagerDemo.html

The additional code that is required is that the MediaManager need to issue a refreshFileList() before downloading the photo.
Else the app will crash. (The same behavior is observed even from a build directly pull from Android-MediaManagerDemo GitHub repo)

-  Crash logs (If you can find it, it would be very helpful)
N.A.

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
DJI SDK 4.6
DJI GO App 4.2.21

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Phantom 4 Pro

-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
Android 7.0

-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
XiaoMi Mi Max

-  Android Studio version you are using (Like Android Studio 2.2, etc)
Android Studio 2.3.3

**Comment by hanming-nls** [comment]
The camera needs to be set in media_download mode and use a faster phone so that it won't encounter a timeout process.

https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/camera/FetchMediaView.java

**Comment by agising** [comment]
The behaviour is the same for IOS SDK version 2.5 years later. The download speed is also significantly reduced when flying, huge difference between prior to take off and directly after.

Are there any tricks for optimising the download speed of media?
