### ISSUE TITLE
DJISDKManager.getInstance().getAircraftRealTimeFlightData NOT return right data

### ISSUE THREAD

**Issue by yiyihome** [dji-sdk/Mobile-SDK-Android#338]
I login my account and  use  DJISDKManager.getInstance().getAircraftRealTimeFlightData api to get data , it always return error message like this :  Authorization information has expired , please authorize again ."             
 sometimes the message is "execute can not execute"

when i login my account the status is NOT-AUTHORIZED

how can i get the flight data?

-  DJI Android SDK version  using 4.6
-  DJI Product  using (GL100A)
-  Android system version using Android 7.0

**Comment by Michael-DJI** [comment]
pls use setStateCallback() in FlightController to get the flight state.
