### ISSUE TITLE
stopMission and pauseMission keep WaypointMissionState as "executing"

### ISSUE THREAD

**Issue by SerjTech** [dji-sdk/Mobile-SDK-Android#339]
When stopMission or pauseMission methods are executed on a WaypointMissionOperator object, the state doesn't update and still shows as "Executing".
Happens all the time just by starting a Waypoint mission and calling Stop or Pause mission using a button. Both methods execute onResult with djiError=null. 
No crashes cause of this, but if i try to start another mission i get "The execution could not be executed" as an error when executing loadMission()

-  DJI Android SDK version: 4.6
-  DJI Product: Matrice 210 RTK
-  Using CrystalSky (latest firmware)
-  Android Studio version: Android 3.1.3

**Comment by agrognetti** [comment]
I am getting the same error, what was the solution to this? @SerjTech
