### ISSUE TITLE
Cannot grab IMU data from Mavic Air on Android 

### ISSUE THREAD

**Issue by MoBaT** [dji-sdk/Mobile-SDK-Android#340]
Hey!

I'm trying to grab the IMU Data such as ACCELEROMETER and GYROSCOPE from my Mavic Air but whenever I add a listener to the KeyManager, I don't get any values on the "onValueUpdate".

I'm having similar issues as this guy: https://github.com/dji-sdk/Mobile-SDK-Android/issues/248

Android Studio 3.1.2
Android Oreo: 8.0 x86 using the Android Emulator
MAVIC AIR
DJI SDK 4.6

```
protected dji.keysdk.callback.KeyListener mAccelCallback = null;
private static FlightControllerKey imuStateKey = FlightControllerKey.create(FlightControllerKey.IMU_STATE);
mImuStateCallback = new dji.keysdk.callback.KeyListener() {
    @Override
    public void onValueChange(@Nullable Object o, @Nullable Object o1) {
        Log.i("IMU STATE", o1.toString());
    }
};
 KeyManager.getInstance().addListener(imuKey, mImuStateCallback);
```

The IMU_STATE key only outputs information when the drone is not IN_MOTION, when the drone starts moving and its state becomes IN_MOTION, no data gets outputted.

I never get data from IMU_STATE_ACCELEROMETER_STATE, IMU_STATE_GYROSCOPE_STATE, or any of the velocitys VELOCITY_*.

**Comment by MoBaT** [comment]
Hey @kenargo , That was a typo on my part! I was trying different keys so I must've copied the key wrong one. I have actually tried using the IMU_STATE_ACCELEROMETER_STATE key and the IMU_STATE key. 

The IMU_STATE key only outputs information when the drone is not IN_MOTION, when the drone starts moving and its state becomes IN_MOTION, no data gets outputted.

I cannot even get data from the VELOCITY_X, VELOCITY_Y and VELOCITY_Z keys also.

**Comment by kenargo** [comment]
I don't have a different drone and it works correctly. 

Have you tried running the same and see if the keys work?

I could post an android activity showing working code if you think that will help

⁣Sent from BlueMail ​

**Comment by MoBaT** [comment]
@kenargo Yes! Can you please do that. I'm pretty sure I'm doing everything correctly, but I would love to see your code.

**Comment by kenargo** [comment]
I've confirmed the following works with the Phantom 4 (I don't have a Mavic Air):

`
public class FlightModeTest extends Fragment {

    FlightControllerKey flightModeKeyVELOCITY_X;
    FlightControllerKey flightModeKeyVELOCITY_Y;
    FlightControllerKey flightModeKeyVELOCITY_Z;

…

    @Override
    public void onViewCreated(@NonNull View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        flightModeKeyVELOCITY_X = FlightControllerKey.create(FlightControllerKey.VELOCITY_X);
        flightModeKeyVELOCITY_XListener.onValueChange(null, KeyManager.getInstance().getValue(flightModeKeyVELOCITY_X));

        flightModeKeyVELOCITY_Y = FlightControllerKey.create(FlightControllerKey.VELOCITY_Y);
        flightModeKeyVELOCITY_YListener.onValueChange(null, KeyManager.getInstance().getValue(flightModeKeyVELOCITY_Y));

        flightModeKeyVELOCITY_Z = FlightControllerKey.create(FlightControllerKey.VELOCITY_Z);
        flightModeKeyVELOCITZ_ZListener.onValueChange(null, KeyManager.getInstance().getValue(flightModeKeyVELOCITY_Z));
    }

    @Override
    public void onStart() {
        super.onStart();

        KeyManager.getInstance().addListener(flightModeKeyVELOCITY_X, flightModeKeyVELOCITY_XListener);
        KeyManager.getInstance().addListener(flightModeKeyVELOCITY_Y, flightModeKeyVELOCITY_YListener);
        KeyManager.getInstance().addListener(flightModeKeyVELOCITY_Y, flightModeKeyVELOCITY_YListener);
    }


    private dji.keysdk.callback.KeyListener flightModeKeyVELOCITY_XListener = new dji.keysdk.callback.KeyListener() {
        @Override
        public void onValueChange(@Nullable Object o, @Nullable Object o1) {
            if (o1 instanceof Float) {
                Log.d("ASDF", "VELOCITY_X: " + o1);
            }
        }
    };

    private dji.keysdk.callback.KeyListener flightModeKeyVELOCITY_YListener = new dji.keysdk.callback.KeyListener() {
        @Override
        public void onValueChange(@Nullable Object o, @Nullable Object o1) {
            if (o1 instanceof Float) {
                Log.d("ASDF", "VELOCITY_Y: " + o1);
            }
        }
    };

    private dji.keysdk.callback.KeyListener flightModeKeyVELOCITZ_ZListener = new dji.keysdk.callback.KeyListener() {
        @Override
        public void onValueChange(@Nullable Object o, @Nullable Object o1) {
            if (o1 instanceof Float) {
                Log.d("ASDF", "VELOCITY_Y: " + o1);
            }
        }
    };

`

**Comment by MoBaT** [comment]
Hey @kenargo  !

I finally got it to work!! It was not on my part. DJI just released the SDK 4.7 and it fixed my issues when I upgraded.

**Comment by Michael-DJI** [comment]
pls use setIMUStateCallback() method to get the value like following:

```mFlightController.setIMUStateCallback(new IMUState.Callback() {

                    @Override
                    public void onUpdate(IMUState state) {
                        StringBuffer sb = new StringBuffer();
                            Tools.addLineToSB(sb, "IMU ID", state.getIndex());
                            Tools.addLineToSB(sb, "Is connected", state.isConnected());
                            Tools.addLineToSB(sb, "AccelerometerState", state.getAccelerometerState());
                            Tools.addLineToSB(sb, "AccelerometerValue", state.getAccelerometerValue());
                            Tools.addLineToSB(sb, "getGyroscopeState", state.getGyroscopeState());
                            Tools.addLineToSB(sb, "getGyroscopeValue", state.getGyroscopeValue());
                            
                        }
                        if (state.getIndex() == 0) {
                            Helper.showText(FlightControllerTestingActivity.this, mImu0PushTv,sb.toString());
                        } else if (state.getIndex() == 1) {
                            Helper.showText(FlightControllerTestingActivity.this, mImu1PushTv, sb.toString());
                        } else if (state.getIndex() == 2) {
                            Helper.showText(FlightControllerTestingActivity.this, mImu2PushTv,sb.toString());
                        } else {
                            Helper.showText(FlightControllerTestingActivity.this, mImuAllPushTv, sb.toString());
                        }
                    }
                });```

**Comment by MoBaT** [comment]
> pls use setIMUStateCallback() method to get the value like following:
> 
> ```
> mFlightController.setIMUStateCallback(new IMUState.Callback() {
> 
>                     @Override
>                     public void onUpdate(IMUState state) {
>                         StringBuffer sb = new StringBuffer();
>                             Tools.addLineToSB(sb, "IMU ID", state.getIndex());
>                             Tools.addLineToSB(sb, "Is connected", state.isConnected());
>                             Tools.addLineToSB(sb, "AccelerometerState", state.getAccelerometerState());
>                             Tools.addLineToSB(sb, "AccelerometerValue", state.getAccelerometerValue());
>                             Tools.addLineToSB(sb, "getGyroscopeState", state.getGyroscopeState());
>                             Tools.addLineToSB(sb, "getGyroscopeValue", state.getGyroscopeValue());
>                             
>                         }
>                         if (state.getIndex() == 0) {
>                             Helper.showText(FlightControllerTestingActivity.this, mImuIndex0PushTv,sb.toString());
>                         } else if (state.getIndex() == 1) {
>                             Helper.showText(FlightControllerTestingActivity.this, mImuIndex1PushTv, sb.toString());
>                         } else if (state.getIndex() == 2) {
>                             Helper.showText(FlightControllerTestingActivity.this, mImuIndex2PushTv,sb.toString());
>                         } 
>                     }
>                 });
> ```
> BTW, you could report the issue in Stackoverflow using "dji-sdk" tag, it will attract more attention of our supporting team.

Hey Michael,
I've actually tried the setImuCallback approach. The ImuCallback is getting data only when the drone is not moving. When the drone starts moving, the IMUCallback stops outputting data.

My theory is that there is something wrong with DJI's SDK.

**Comment by Michael-DJI** [comment]
it's not blocked by SDK you could see that in DJI GO it's same

**Comment by MoBaT** [comment]
> it's not blocked by SDK you could see that in DJI GO it's same

@Michael-DJI , I don't think I'm crazy or writing my code incorrectly. I seriously have tried for days to get the IMU data to no avail. The DJI Mobile SDK is not hard to use at all.

As I said above, I get IMUStates only when the drone is not in motion. If you can write me a quick app showing me that you can get IMU data off the drone and the output of said data in your own IDE while the drone is **FLYING**, then I will admit that I'm doing something wrong. But with all the information presented to me above and everything I have tried between August 13 (When I wrote this post) until now, it's leading me to believe that there is something wrong going on, whether it be in my code (which I have checked many times) or in the SDK.

**Comment by Michael-DJI** [comment]
@MoBaT I believe that your code is correct, what I mean is the phenomenon in DJI Go is same as in your app: when the drone is moving, it just stop the pushing of IMU data so no app could get the data to display. I think it's the firmware issue, I will try to talk with the firmware team about it, then come back to you, thanks for the feedback and sorry for the inconvenience.

**Comment by MoBaT** [comment]
@Michael-DJI Awesome thanks. I'm starting to believe that DJI does not want us to get the RAW IMU data from the drone. Their documentation for IMUState says[ "Called when the flight controller pushes an IMU state update. The callback method would not be called if the aircraft is flying." ](https://developer.dji.com/api-reference/android-api/Components/IMUState/DJIIMUState.html#djiflightcontroller_updateimustate_inline). 
Also in the newest SDK that was released a week or two ago, they got rid of two FlightControllerKeys, the " IMU_STATE_ACCELEROMETER_STATE" and the "IMU_STATE_GYROSCOPE_STATE".

Thanks for the support @Michael-DJI and I'm hoping that the firmware team will allow us to grab the IMU data soon.

**Comment by Michael-DJI** [comment]
@MoBaT you're welcome.  and could you please close this issue? I think you have got a very clear answer now :)

**Comment by wagenaartje** [comment]
> I think it's the firmware issue, I will try to talk with the firmware team about it, then come back to you, thanks for the feedback and sorry for the inconvenience.

Has this been fixed @Michael-DJI ?
