### ISSUE TITLE
Unable to Get Drone's Home Coordinates

### ISSUE THREAD

**Issue by fred-aims** [dji-sdk/Mobile-SDK-Android#345]
Hello, I am try to get the home coordinates of the drone (Mavic Pro) using the code below
flightController.getHomeLocation(new CommonCallbacks.CompletionCallbackWith<LocationCoordinate2D>() {

                @Override
                public void onSuccess(LocationCoordinate2D locationCoordinate2D) {

                    homeLatitude = locationCoordinate2D.getLatitude();
                    homeLongitude = locationCoordinate2D.getLongitude();
                    
                    drone_home_set = true;
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                setTimelinePlanToText("home latitude: " + homeLatitude + " | home longitude: " + homeLongitude);
                            }
                        });

                }

                @Override
                public void onFailure(final DJIError djiError) {

                    drone_home_set = false;
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            Toast.makeText(getApplicationContext(), "Failed to get home coordinates: " + djiError.getDescription(), Toast.LENGTH_SHORT).show();
                        }
                    });

                }

            });

and I am getting 4.5836E7 for both the latitude and longitude.

The android SDK version I am using is 4.6

**Comment by kenargo** [comment]
Just to confirm; the home location is set once the motors turn on for the first time.  Are you making the call before that?

**Comment by zoemcateedji** [comment]
You might want to check out the Sample Code - it has things like a Timeline mission
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/timeline/TimelineMissionControlView.java
 //Step 3: Go 10 meters from home point
        setTimelinePlanToText("Step 3: Go 10 meters from home point");
        elements.add(new GoToAction(new LocationCoordinate2D(homeLatitude, homeLongitude), 10));

as well as Waypoint samples
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/missionoperator/WaypointMissionOperatorView.java

**Comment by kenargo** [comment]
I wouldn't mess with time line, it's overkill and comes with some challenge. 

What I would do is to insert a waypoint at the drone location at the altitude you want. 

Let the user define the mission however they want but when it's time to build the real mission insert a point at index 0 and this becomes the mission uploaded. 

Make sense?

⁣Sent from BlueMail ​

**Comment by fred-aims** [comment]
yeah it makes sense
