### ISSUE TITLE
Cannot get raw video data from Mavic 2

### ISSUE THREAD

**Issue by fukuchidaisuke** [dji-sdk/Mobile-SDK-Android#346]
VideoDataCallback is never called with Mavic 2.
I tested in [VideoStreamDecodingSample](https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample). 
But DJICodecManager seems to display preview without sendDataToDecoder.
Special behavior for Mavic 2?

- Mobile SDK 4.7
- Mavic 2 Pro, Mavic 2 Zoom

**Comment by Michael-DJI** [comment]
yes,  it's a special logic for Mavic2, if you want to get the video data, pls try to use provideTranscodedVideoFeed() in VideoFeeder

**Comment by fukuchidaisuke** [comment]
If so, can I detect whether getPrimaryVideoFeed().setCallback() is useless? How?

**Comment by fukuchidaisuke** [comment]
OK. Thank you.
