### ISSUE TITLE
'onNewFile' doesn't work when using the second camera (Matrice 200 + z30)

### ISSUE THREAD

**Issue by tubipham** [dji-sdk/Mobile-SDK-Android#349]
I'm using "onNewFile" to get the picture information when it's taken, it works fine with "phantom3 pro + primary camera", but when I use Matrice 200 + z30 I get no response  from function "onNewFile"

To be able to display directly from "z30" I use "FPVWidget" and change "VideoSource" to "SECONDARY".
https://github.com/dji-sdk/Mobile-UXSDK-Android/blob/master/sample/app/src/main/java/com/dji/ux/sample/CustomizedWidgetsActivity.java

//Code

` Camera camera = getCameraInstance();
        if (camera != null){
        camera.setMediaFileCallback(this);
    }`

`    @Override
    public void onNewFile(@NonNull MediaFile mediaFile) {
        Toast.makeText(CustomizedWidgetsActivity.this, "mediaFile", Toast.LENGTH_LONG).show();
    }`

-  DJI Android SDK: 4.7.1
-  DJI Product: Phantom 3 Pro and Matrice 200 + z30
-  OS: Android 8.0, Android 7.1
-  Android device: Galaxy Note 8
-  Android Studio version: 3.1.4

**Comment by tubipham** [comment]
@dji-dev

**Comment by Michael-DJI** [comment]
it's not supported in firmware of Z30.

**Comment by tubipham** [comment]
Thank you for the reply, I wonder that is there any way to get medias when shooting from the z30?

**Comment by Michael-DJI** [comment]
@tubipham it's hard to say, we need collect more feedbacks about it, then might provide this feature in new firmware, but I can't say for sure this will happen in future.

**Comment by gitnarqt** [comment]
@tubipham @Michael-DJI we're facing the same issue. Any updates on that feature? It is vital for our clients to have such a feature.

**Comment by Michael-DJI** [comment]
@gitnarqt could you use X5s camera instead? Z30 still doesn't support this feature.

**Comment by gitnarqt** [comment]
@Michael-DJI I wish, but some of our clients use Z30 and requires this feature. Any timeline on that?

**Comment by Michael-DJI** [comment]
@tubipham Z30 don't have firmware upgrading plan, please use Zenmuse-H20
