### ISSUE TITLE
DJICompletionCallback onResult "Error" for non-errors

### ISSUE THREAD

**Issue by GitPlz** [dji-sdk/Mobile-SDK-Android#35]
Some of the DJIErrors that are returned to DJIBaseComponent.DJICompletionCallback are not errors, they are messages. I expect an error returned to the onResult method to be an error, which indicates to me that the command didn't work. 

For example, I paused a DJIHotPointMission and got the following error returned: "The homepoint is paused". 

The drone paused the mission, and could resume the mission... no error occurred. This causes a bug in my code, since I believe the drone is still performing the hot point mission, when in fact it has paused correctly.

**Comment by SilverChangjian** [comment]
Thanks for reporting this. We would rethink about the naming of the DJIError.

**Comment by xxmaestroxx** [comment]
Hey DJI,

what is the status of this issue?

Regards
Maestro

**Comment by talobin** [comment]
We have had a big revamp in Mission.
Please check out the class MissionControl.
Will go ahead and close this issue since it has been a long time.
@edancain Please help to create a separate issue if you still have problem with current version SDK 4.3.2
Thanks!
