### ISSUE TITLE
Can not run importSDKDemo

### ISSUE THREAD

**Issue by meteaydn** [dji-sdk/Mobile-SDK-Android#350]
Hi
I am using dji sdk 4.7.1 and android studio 3.1.4. I imported this project https://github.com/DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio to Android Studio, it is built without any errors but when I run it in Android Emulator, it crashes and says "ImportSDKDemo has stopped" then i got these errors in android studio.

E/zygote: No implementation found for byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String) (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX and Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX__Ljava_lang_String_2)
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.dji.importSDKDemo, PID: 5364
                  java.lang.UnsatisfiedLinkError: No implementation found for byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String) (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX and Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX__Ljava_lang_String_2)
                      at dji.midware.natives.SDKRelativeJNI.native_getXXXX(Native Method)
                      at com.dji.g.a.a.b.a(Unknown Source:24)
                      at com.dji.g.a.a.b.a(Unknown Source:5)
                      at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
                      at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
                      at com.dji.importSDKDemo.MainActivity$1.run(MainActivity.java:123)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                      at java.lang.Thread.run(Thread.java:764)
D/EGL_emulation: eglMakeCurrent: 0xaa8074a0: ver 3 0 (tinfo 0xb258e7d0)

I am new in Android and could not solve this problem for two days, can u help me to solve?

**Comment by luoyuzhao** [comment]
also encountered this problem

**Comment by meteaydn** [comment]
I have fixed this problem by using dji sdk 4.6, i think dji sdk 4.7.1 has bugs.

**Comment by kenargo** [comment]
4.7 has many issues.   It also breaks active track. 

I'm hopeful there is a refresh soon as I'd prefer to use 4.7 in order to get support for mavic 2

⁣Sent from BlueMail ​

**Comment by Michael-DJI** [comment]
@meteaydn 
Moble SDK 4.7 includes FFMpeg lib to provide the transcoded video feed, but FFMpeg x86 so files will lead to the runtime crash when the target Api of APP is larger than 23(included).

PS. you could report the issue in Stackoverflow using "dji-sdk" tag, it will attract more attention of our supporting team.

**Comment by AdinhLux** [comment]
> 
> 
> I have fixed this problem by using dji sdk 4.6, i think dji sdk 4.7.1 has bugs.

In my case I've got this message : 

09-14 05:26:56.972 3108-3108/? I/m.importsdkdem: Not late-enabling -Xcheck:jni (already on)
09-14 05:26:57.032 3108-3108/? W/m.importsdkdem: Unexpected CPU variant for X86 using defaults: x86
09-14 05:26:57.595 3108-3108/dji.com.importsdkdemo W/m.importsdkdem: Accessing hidden field Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList; (light greylist, reflection)
    Accessing hidden method Ldalvik/system/DexPathList;->makePathElements(Ljava/util/List;Ljava/io/File;Ljava/util/List;)[Ldalvik/system/DexPathList$Element; (light greylist, reflection)
    
    --------- beginning of crash
09-14 05:26:57.596 3108-3108/dji.com.importsdkdemo A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 3108 (m.importsdkdemo), pid 3108 (m.importsdkdemo)

**Comment by tubipham** [comment]
@Michael-DJI 
I have a similar situation.
I cannot edit the target to 22 because the play-store requires the target to be equal to 26.

**Comment by kenargo** [comment]
I'm using SDK target 28 for my app and the SDK works perfect.   You cannot use androidX libraries but other than that, no issues. 

What error are you seeing?

⁣Sent from BlueMail ​

**Comment by tubipham** [comment]
@kenargo This happens when I install the app from playstore. App from hockeyapp works normally.


01-23 23:57:38.095 16154-16282/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.ins8.los, PID: 16154
    java.lang.UnsatisfiedLinkError: No implementation found for byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String) (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX and Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX__Ljava_lang_String_2)
        at dji.midware.natives.SDKRelativeJNI.native_getXXXX(Native Method)
        at com.dji.g.a.a.c.b(Unknown Source)
        at dji.midware.d.b(Unknown Source)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source)
        at com.ins8.los.ui.main.MainActivity$15.run(MainActivity.java:1633)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by eyalmnm** [comment]
I am using SDK 4.11 (I need androidx support) and i got the same error 
`No implementation found for void dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.setFirmwareStoreDirectory(java.lang.String) (tried Java_dji_upgrade_internal_csdk_upgradeadapter_UpgradeAdapterManager_setFirmwareStoreDirectory and Java_dji_upgrade_internal_csdk_upgradeadapter_UpgradeAdapterManager_setFirmwareStoreDirectory__Ljava_lang_String_2)`
When trying to register the application using 
`DJISDKManager.getInstance()
                        .registerApp(applicationContext, object : DJISDKManager.SDKManagerCallback {..}`
How it can be solved?

**Comment by Hujunjob** [comment]
> I am using SDK 4.11 (I need androidx support) and i got the same error
> 
> `No implementation found for void dji.upgrade.internal.csdk.upgradeadapter.UpgradeAdapterManager.setFirmwareStoreDirectory(java.lang.String) (tried Java_dji_upgrade_internal_csdk_upgradeadapter_UpgradeAdapterManager_setFirmwareStoreDirectory and Java_dji_upgrade_internal_csdk_upgradeadapter_UpgradeAdapterManager_setFirmwareStoreDirectory__Ljava_lang_String_2)`
> 
> When trying to register the application using
> 
> `DJISDKManager.getInstance() .registerApp(applicationContext, object : DJISDKManager.SDKManagerCallback {..}`
> 
> and using the following .so files in my build.gradle
> ` packagingOptions{
> doNotStrip "_/_/libdjivideo.so"
> doNotStrip "_/_/libSDKRelativeJNI.so"
> doNotStrip "_/_/libFlyForbid.so"
> doNotStrip "_/_/libduml_vision_bokeh.so"
> doNotStrip "_/_/libyuv2.so"
> doNotStrip "_/_/libGroudStation.so"
> doNotStrip "_/_/libFRCorkscrew.so"
> doNotStrip "_/_/libUpgradeVerify.so"
> doNotStrip "_/_/libFR.so"
> 
> ```
>     // Add the new so
>     doNotStrip "*/*/libDJIFlySafeCore.so"
>     doNotStrip "*/*/libdjifs_jni.so"
>     doNotStrip "*/*/libsfjni.so"
> 
>     exclude 'META-INF/rxjava.properties'
> }
> ```
> 
> `
> How it can be solved?

I have same problem

**Comment by Ray-DJI** [comment]
@Hujunjob @Asendo316 
Hi, 4.11 add some new so files needed to be kept in build.gradle, please check
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle
It is better to check the sample app when upgrade the sdk version.

> packagingOptions {
> 
>         doNotStrip "*/*/libdjivideo.so"
>         doNotStrip "*/*/libSDKRelativeJNI.so"
>         doNotStrip "*/*/libFlyForbid.so"
>         doNotStrip "*/*/libduml_vision_bokeh.so"
>         doNotStrip "*/*/libyuv2.so"
>         doNotStrip "*/*/libGroudStation.so"
>         doNotStrip "*/*/libFRCorkscrew.so"
>         doNotStrip "*/*/libUpgradeVerify.so"
>         doNotStrip "*/*/libFR.so"
>         doNotStrip "*/*/libDJIFlySafeCore.so"
>         doNotStrip "*/*/libdjifs_jni.so"
>         doNotStrip "*/*/libsfjni.so"
>         doNotStrip "*/*/libDJICommonJNI.so"
>         doNotStrip "*/*/libDJICSDKCommon.so"
>         doNotStrip "*/*/libDJIUpgradeCore.so"
>         doNotStrip "*/*/libDJIUpgradeJNI.so"
>         exclude 'META-INF/rxjava.properties'
>    }
