### ISSUE TITLE
Does Mavic 2 support digital zoom?

### ISSUE THREAD

**Issue by fukuchidaisuke** [dji-sdk/Mobile-SDK-Android#351]
Keyed interface returns true for IS_DIGITAL_ZOOM_SUPPORTED.
But, setting DIGITAL_ZOOM_FACTOR fails with "Camera received invalid parameters".

-  DJI SDK 4.7.1
-  Mavic 2 Pro, Mavic 2 Zoom
-  Android 7.1.1
-  Moto G5s PLUS
-  Android Studio 3.1.4

**Comment by GGPENG** [comment]
Same problem here. Still looking for a solution.

**Comment by Michael-DJI** [comment]
thanks for your feedback it will be fixed in next version.
BTW, you could report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by Jim-DJI** [comment]
@fukuchidaisuke Hi, Could you give me more details?
Such as:
- Product Type
- DIGITAL_ZOOM_FACTOR parameter which you give 

Thanks, BTW, you could report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by Jim-DJI** [comment]
@fukuchidaisuke Hi. I have fixed the issue now. Please update the next version. Thanks.
BTW, you could report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by Jim-DJI** [comment]
@fukuchidaisuke Mavic 2 does not support digital zoom. It only supports optical zoom, you can learn more at DJI.com. Thanks for your feedback.

**Comment by Soulblighter47** [comment]
I'm concerned about the topic started by @fukuchidaisuke :

Mavic 2 Pro does not have digital zoom feature, so there is no point on this one (but it SHOULD be able to digital zoom like Mavic Pro 1...).

**Mavic 2 Zoom and Enterprise** does have digital zoom feature. When in 1080p camera mode in DJI GO 4, you can optical zoom 2X, **and then digital zoom to 2X more (Zoom) up to 3X more (Enterprise).**

However, in the DJI SDK API reference, none of the Mavic's 2 are notified having the digital zoom feature: https://developer.dji.com/api-reference/android-api/Components/Camera/DJICamera.html?search=digital&i=3&#djicamera_camerasettings_isdigitalzoomscalesupported_inline

I'm about to get a Mavic 2 Enterprise JUST for this combined extra zoom (compared to Mavic 2 Pro), for a specific industry purpose, using a custom Android app I'm developing. What a disapointment if the digital zoom is not usable with DJI SDK!!! And for sure not understandable!
Just reported the issue to dev@dji.com, will give you news.
Anybody with a Mavic 2 Zoom or Enterprise can test the function?

**Comment by Michael-DJI** [comment]
@Soulblighter47 hey, thank you for the feedback! MSDK will add a new zoom interface to support the digital zoom in next version which will be released soon, actually in MSDK 4.10, digital zoom is supported by using optical zoom interface.

**Comment by Soulblighter47** [comment]
Thanks for your answer, i will test this once i get my Mavic 2 Enterprise, and can't wait for the next version as well.

**Comment by Soulblighter47** [comment]
@fukuchidaisuke @GGPENG  @Michael-DJI 
Just tested the workaround on my Mavic 2 Enterprise, optical and digital zoom are working great with the optical zoom interface on SDK 4.10. Thanks @Michael-DJI !
You can use the get and setOpticalZoomFocalLength to get or set a focal length within the entire optical and digital zoom factors seamlessly (up to 6X on Mavic 2 Enterprise Zoom).
