### ISSUE TITLE
FPVDemo not connecting to Inspire 1

### ISSUE THREAD

**Issue by Squrrli** [dji-sdk/Mobile-SDK-Android#355]
I have been trying to run the FPVDemo on a Huawei P20 Lite (Android 8.0, API 26) but it seems as though after the application registers no other methods are called.
```
DJISDKManager.getInstance().registerApp(getApplicationContext(), new DJISDKManager.SDKManagerCallback() {
                        @Override
                        public void onRegister(DJIError djiError) {
                            Log.d("sdkErrDebug", djiError.getDescription());

                            if (djiError == DJISDKError.REGISTRATION_SUCCESS) {
                                DJILog.e("App registration", DJISDKError.REGISTRATION_SUCCESS.getDescription());
                                DJISDKManager.getInstance().startConnectionToProduct();
                                showToast("Register Success");
                            } else {
                                Log.d("sdkErrDebug", djiError.getDescription());
                                showToast( "Register sdk fails, check network is available");
                            }
                            Log.v(TAG, djiError.getDescription());
                        }

                        @Override
                        public void onProductDisconnect() {
                            Log.d(TAG, "onProductDisconnect");
                            showToast("Product Disconnected");

                        }
                        @Override
                        public void onProductConnect(BaseProduct baseProduct) {
                            Log.d(TAG, String.format("onProductConnect newProduct:%s", baseProduct));
                            showToast("Product Connected");

                        }
                        @Override
                        public void onComponentChange(BaseProduct.ComponentKey componentKey, BaseComponent oldComponent,
                                                      BaseComponent newComponent) {

                            if (newComponent != null) {
                                newComponent.setComponentListener(new BaseComponent.ComponentListener() {

                                    @Override
                                    public void onConnectivityChange(boolean isConnected) {
                                        Log.d(TAG, "onComponentConnectivityChanged: " + isConnected);
                                    }
                                });
                            }else {
                                Log.d(TAG, "component is null");
                            }
                            Log.d(TAG,
                                    String.format("onComponentChange key:%s, oldComponent:%s, newComponent:%s",
                                            componentKey,
                                            oldComponent,
                                            newComponent));

                        }
                    });
```
I have added debug logs to onComponentChange() but this is not being called.
Any information on why this is happening and how I might fix it would be greatly appreciated, cheers.

**Comment by Squrrli** [comment]
The problem was solved with help of the Dev email.

When bringing the project into android studio I updated the build tools when prompted to, causing the applicaton not to work with my phone. Re downloading and not updating build tools solved this problem.

**Comment by ibrahimsalgin** [comment]
I m facing the same problem. I can't connect any product (I have Phantom/4 product). I can see "Register Success" toast and that is all. What should I do to connect my tablet to my product?

**Comment by Michael-DJI** [comment]
@ibrahimsalgin please make sure internet connection is accessible and in your app, the correct com.dji.sdk.API_KEY is filled in AndroidManifest.xml file, and be careful with the API_KEY you get if it's for Android platform

**Comment by ibrahimsalgin** [comment]
@Michael-DJI I have tried either for Android or IOS platform. I use correct API_KEY for both. As I sad I'm not having trouble with app activation (registration). My problem is to connect my dji product (Phantom 4 pro) to my mobile device. I have tried almost all sample projects in your dji github. Please give me a help. When I connect my mobile device to the remote controller, the remote controller can only see media pictures on my mobile.

**Comment by ibrahimsalgin** [comment]
I have also tried your DJI GO 4 mobile application on both IOS and Android. Still I can't see my dji product as connected

**Comment by Squrrli** [comment]
As per my comment when I closed this issue, what solved it for me was __NOT__ updating the build tools when prompted to by android studio on first launch of a demo application. Try a fresh installation of android studio and/ or a fresh demo application and do not update build tools when prompted to.
Hope this helps.
