### ISSUE TITLE
How do I put compile ('com.dji:dji-sdk:4.7') dependent files into the local libs folder

### ISSUE THREAD

**Issue by misshsj** [dji-sdk/Mobile-SDK-Android#356]
How do I get this dependent source file?

**Comment by kenargo** [comment]
Standard Maven method work best. 

Look at the manifest file of the sample,  copy and paste the SDK lines into your manifest. 

No need to place individual files using this method.  There is very little reason to place files in the new sdk.

⁣Sent from BlueMail ​

**Comment by Michael-DJI** [comment]
@misshsj pls avoid to use the original files, because Maven will also tell the Android studio the 3rd-part dependencies, if you directly depend on the aar file, you will miss the 3rd-part dependencies info.
