### ISSUE TITLE
DJI Mobile SDK, Android

### ISSUE THREAD

**Issue by benchen99999** [dji-sdk/Mobile-SDK-Android#359]
Hi,

I am a student developer, Benedict Chen, my group and I are currently doing on an industry project on DJI Phantom 4 Pro and the drone is required to fly inside a warehouse autonomously (without GPS/waypoints) with just an activation of a button on the mobile app. 

We're currently stuck in deciphering which are the lines of code for the primary movement of the drone, fly forward, backward, roll left and right. We kindly seek your advices!

Cheers!
Benedict Chen

**Comment by wocoltd** [comment]
Hi Benedict,

I suggest you start by looking at the Virtual Stick interfaces, which are accessed via the FlightController?

I also found this link useful: https://developer.dji.com/mobile-sdk/documentation/introduction/flightController_concepts.html

You may find it quite challenging without GPS, as you can only specify speeds or angles, and not distances!

Good luck,

William

**Comment by Michael-DJI** [comment]
@benchen99999 did you resolve the problem? if you get other issue please report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
