### ISSUE TITLE
2.4 version arm64-v8a

### ISSUE THREAD

**Issue by zhuzhibo0** [dji-sdk/Mobile-SDK-Android#36]
arm64-v8a

**Comment by SilverChangjian** [comment]
Sorry, we did not provide the arm64-v8a for 2.4 version. We highly recommend that you could pick the SDK 3.0 as your dependency since it is well documented and higher quality compared with 2.4 version.

**Comment by talobin** [comment]
4.3.2 should fix v8a issue already.
Will go ahead and close this ticket.
Please feel free to reopen if the problem still exists.
Thanks!
