### ISSUE TITLE
How to get relative altitude of the aircraft location relative to sea level?

### ISSUE THREAD

**Issue by tubipham** [dji-sdk/Mobile-SDK-Android#360]
Does anyone have any way to get altitude of drone relative to sea level?

-  DJI Android SDK version: 4.7.1

**Comment by Michael-DJI** [comment]
thanks for your feedback, android side is missing the key, it will be added in the next version, with this name: FlightControllerKey. TAKEOFF_LOCATION_ALTITUDE 
note that:
by this key we could only get the above-sea altitude value before the taking off, after the taking off the drone will stop updating the value.

**Comment by tubipham** [comment]
@Michael-DJI  Thank you so much

**Comment by kenargo** [comment]
Altitude is always relative to takeoff.   You can use the home pint location,  look up elevation and calculate using services like Google location service.   Is not very accurate but the are some services that are like USGS.


⁣Sent from BlueMail ​

**Comment by Michael-DJI** [comment]
@tubipham pls use 4.8.1 version.

**Comment by kenargo** [comment]
FlightControllerKey. TAKEOFF_LOCATION_ALTITUDE has been added to SDK 4.8.1 !!!
