### ISSUE TITLE
HotpointMission keeps rotating forever

### ISSUE THREAD

**Issue by mcorner** [dji-sdk/Mobile-SDK-Android#362]
-  Description of the issue.

Using a hotpointmission and hotpointaction and missioncontrol often (about 50%) the aircraft gets stuck going around and around and never finishes.  It should only go angle degrees.  At that point it it is very, very hard to control the aircraft to get it to land etc.  I have almost crashed because of this.  It happens in the simulator and in a Mavic Air.

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)

This is a piece of my code:

            HotpointMission hotpointMission = new HotpointMission();
            hotpointMission.setHotpoint(new LocationCoordinate2D(centerPoint.latitude, centerPoint.longitude));
            hotpointMission.setAltitude(altitude);
            hotpointMission.setRadius(outerradius);
            hotpointMission.setAngularVelocity(10);
            hotpointMission.setStartPoint(HotpointStartPoint.NEAREST);
            hotpointMission.setHeading(HotpointHeading.TOWARDS_HOT_POINT);
            hotpointMission.setClockwise(true);
            elements.add(new HotpointAction(hotpointMission, angle));

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
4.7.1

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)

Mavic Air

-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)

8.0
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)

-  Android Studio version you are using (Like Android Studio 2.2, etc)
3.1.4

**Comment by mcorner** [comment]
When it fails I get a STARTED event but no PROGRESSED event from the missioncontrol listener.

**Comment by mcorner** [comment]
Just to follow up, I gave up on the official HotpointAction and wrote my own.  This is bare bones and you have to adapt it to use the official flightcontroller state (I wrote my own listener/broadcaster for that).  But the accuracy on angles is better (at least for the MavicAir I used) and it doesn't get stuck.

https://gist.github.com/mcorner/6a37a1c74b2f1258ca7d7a4626f84348

**Comment by KalaiSelvanG** [comment]
@mcorner I have problem in POI. When I tried the sample code, my drone only takes off but it won't rotate in 360 degree and it won't even stop when I try to stop it. Can you please help me with this

**Comment by mcorner** [comment]
@KalaiSelvanG What sample code?  The ones from DJI or the gist I posted?  The one I posted needs to be adapted a bit to receive the lat/lng from the aircraft state.  I just posted it to give people some idea about how to work around the bug.

**Comment by KalaiSelvanG** [comment]
@mcorner The one from DJI. It started to work went I set for 5m radius. So by default the minimum radius to be 5m? Is it possible to set to 2m radius?

**Comment by mcorner** [comment]
I had problems with it getting stuck at 5m and at 10m.  I don't think the radius is the issue, I think it just has a bug in it that prevents it from detecting how many degrees it went.

**Comment by Michael-DJI** [comment]
@mcorner we will try to fix it in next version, thanks for your feedback.
BTW, you could also report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by thanhtd1987** [comment]
@Jim-DJI please help me to check my issue, https://github.com/dji-sdk/Mobile-SDK-Android/issues/435 look like it stuck at STARTED also, but I updated to 4.10
