### ISSUE TITLE
Events not triggering with Time line and Hot point Mission not working

### ISSUE THREAD

**Issue by KalaiSelvanG** [dji-sdk/Mobile-SDK-Android#363]
Recently I have downloaded the sample and did a play around Timeline event in Android sdk. I can able to get home location and initiate the flow. When I start the mission the drone has taken off and keeps flying there without completing successive actions.

**Comment by Michael-DJI** [comment]
which drone and which version of MSDK were you using? 
please report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
