### ISSUE TITLE
Circular dependency between the following tasks

### ISSUE THREAD

**Issue by hangtianfeige** [dji-sdk/Mobile-SDK-Android#364]
Circular dependency between the following tasks:
:app:checkManifestChangesDebug
\--- :app:instantRunMainApkResourcesDebug
     \--- :app:transformClassesAndDexWithShrinkResForDebug
          \--- :app:transformDexArchiveWithDexMergerForDebug
               +--- :app:preColdswapDebug
               |    \--- :app:incrementalDebugTasks
               |         +--- :app:transformClassesAndClassesEnhancedWithInstantReloadDexForDebug
               |         |    \--- :app:transformClassesWithInstantRunForDebug
               |         |         \--- :app:checkManifestChangesDebug (*)
               |         \--- :app:transformClassesWithInstantRunForDebug (*)
               \--- :app:transformClassesWithDexBuilderForDebug
                    +--- :app:preColdswapDebug (*)
                    \--- :app:transformClassesWithInstantRunForDebug (*)

(*) - details omitted (listed previously)

**Comment by sharvashish** [comment]
Any idea on how to fix this?

**Comment by hangtianfeige** [comment]
sorry,i have not know how to fix this.

**Comment by Michael-DJI** [comment]
could you please test the build configuration in our Sample in your IDE, if it's ok, please upgrade your IDE. btw you could report the issue in Stackoverflow using "dji-sdk" tag, it will attract more attention of our supporting team, thanks.

**Comment by hangtianfeige** [comment]
this is your sample

**Comment by hangtianfeige** [comment]
更改build.gradle为如下即可解决问题   （ shrinkResources false）

buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            shrinkResources false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

**Comment by anilgorthy** [comment]
I was able to get the sample app w/ ```dji-sdk:4.8.1``` launch fine. Here is my environment:

```
Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 8, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```

Can you share yours?

**Comment by Michael-DJI** [comment]
@hangtianfeige well, it may related with the version of the gradle or AS you were using.

**Comment by AliGhIO** [comment]
Hi @hangtianfeige 
I have the same issue and I fix it by disabling instant run.

**Comment by xrnd** [comment]
> Hi @hangtianfeige @sharvashish
> I have the same issue and I fix it by disabling instant run.

Yes disabling Instant Run worked for me too.

**Comment by MikeAlvarado** [comment]
Works for current version.

**Comment by BayoKwendo** [comment]
> Does anyone has update on this issue for Android Studio 4.0 . As it does not have instant run option. In Android Studio - > preferences there is no setting for instant run.

Go to Run --> Edit Configurations --> and disable "Allow parallel run"
