### ISSUE TITLE
Build fails in SDK 4.8 if proguard minify is enabled

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#368]
Android MSDK: 4.8.1

The android app in sdk 4.7 was working fine. After upgrading to 4.8.1, the build is failing due to proguard rules.  I have noticed that the pro guard rules have not been updated in GitHub sample
 [Link to github](https://github.com/dji-sdk/Mobile-SDK-Android/tree/master/Sample%20Code/app)

**Comment by Michael-DJI** [comment]
@Abhishek284 could you please show me the error message?

**Comment by Lloyd2205** [comment]
Even I have the same issue , error logs are shown below:

Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.amap.provider.AMapProvider'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.Mapkit'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.MapkitOptions'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.MapkitOptions$Builder'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.a.e'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.callback.MapScreenShotListener'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.callback.OnCameraChangeListener'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.camera.DJICameraUpdate'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.camera.DJICameraUpdateFactory'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.exceptions.MapkitInitializerException'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMap'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMap$InfoWindowAdapter'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMap$MapType'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMap$OnInfoWindowClickListener'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMap$OnMapClickListener'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMap$OnMapLongClickListener'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMap$OnMarkerClickListener'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMap$OnMarkerDragListener'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMapView'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMapView$OnDJIMapReadyCallback'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.DJIMapViewInternal'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.c'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.maps.d'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.BasePointCollection'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.DJIBitmapDescriptor'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.DJIBitmapDescriptor$Type'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.DJIBitmapDescriptorFactory'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.DJICameraPosition'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.DJICameraPosition$Builder'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.DJILatLng'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.DJILatLngBounds'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.annotations.DJICircle'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.annotations.DJICircleOptions'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.annotations.DJIMarker'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.annotations.DJIMarkerOptions'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.annotations.DJIPolygon'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.annotations.DJIPolygonOptions'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.annotations.DJIPolyline'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.models.annotations.DJIPolylineOptions'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.core.providers.MapProvider'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.google.provider.GoogleProvider'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.here.provider.HereProvider'
Note: the configuration explicitly specifies 'com.dji.**' to keep library class 'com.dji.mapkit.mapbox.provider.MapboxProvider'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioAttributes'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioAttributes$Builder'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioDeviceCallback'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioDeviceInfo'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioFocusRequest'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioFormat'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioManager'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioManager$AudioPlaybackCallback'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioManager$AudioRecordingCallback'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioManager$OnAudioFocusChangeListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioRecord'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioRecord$OnRecordPositionUpdateListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioRecord$OnRoutingChangedListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioRouting'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioRouting$OnRoutingChangedListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.AudioTimestamp'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.CamcorderProfile'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaDataSource'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaDescription'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaDescription$Builder'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaDrm$KeyRequest'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaFormat'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaMetadata'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaMetadata$Builder'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaMetadataEditor'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$DrmInfo'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnBufferingUpdateListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnCompletionListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnDrmConfigHelper'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnDrmInfoListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnDrmPreparedListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnErrorListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnInfoListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnPreparedListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnSeekCompleteListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnTimedMetaDataAvailableListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnTimedTextListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$OnVideoSizeChangedListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaPlayer$TrackInfo'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaRecorder'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaRecorder$AudioEncoder'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaRecorder$AudioSource'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaRecorder$OnErrorListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaRecorder$OnInfoListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaRecorder$OutputFormat'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaRecorder$VideoEncoder'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaRecorder$VideoSource'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaScannerConnection'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaScannerConnection$MediaScannerConnectionClient'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaScannerConnection$OnScanCompletedListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaSyncEvent'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.MediaTimestamp'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.PlaybackParams'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.Rating'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.RemoteControlClient'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.RemoteControlClient$MetadataEditor'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.RemoteControlClient$OnGetPlaybackPositionListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.RemoteControlClient$OnMetadataUpdateListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.RemoteControlClient$OnPlaybackPositionUpdateListener'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.RemoteController'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.SyncParams'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.VolumeAutomation'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.VolumeProvider'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.VolumeShaper'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.VolumeShaper$Configuration'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.browse.MediaBrowser'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.browse.MediaBrowser$ConnectionCallback'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.browse.MediaBrowser$ItemCallback'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.browse.MediaBrowser$MediaItem'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.browse.MediaBrowser$SubscriptionCallback'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.MediaController'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.MediaController$Callback'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.MediaController$PlaybackInfo'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.MediaController$TransportControls'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.MediaSession'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.MediaSession$Callback'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.MediaSession$QueueItem'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.MediaSession$Token'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.PlaybackState'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.PlaybackState$Builder'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.PlaybackState$CustomAction'
Note: the configuration explicitly specifies 'android.media.**' to keep library class 'android.media.session.PlaybackState$CustomAction$Builder'
Note: the configuration explicitly specifies 'dji.midware.media.colors.ColorOscilloscopeDisplayView' to keep library class 'dji.midware.media.colors.ColorOscilloscopeDisplayView'
Note: there were 4 references to unknown classes.
      You should check your configuration for typos.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
Note: there were 1 references to unknown class members.
      You should check your configuration for typos.
Note: there were 51 unkept descriptor classes in kept class members.
      You should consider explicitly keeping the mentioned classes
      (using '-keep').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 127 library classes explicitly being kept.
      You don't need to keep library classes; they are already left unchanged.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#libraryclass)
Note: there were 8 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Warning: there were 28 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 6 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Thread(Tasks limiter_11): destruction

**Comment by Abhishek284** [comment]
The DJI SDK 4.8.1 uses Mapbox SDK internally with the Mapbox SDK version 5.5.1.

We are trying to use the latest version of Mapbox SDK i.e. **6.7.0** in our gradle.

I am assuming that the proguard conflict is arising due to this. When proguard is disabled , things work fine.

**Comment by Abhishek284** [comment]
@Michael-DJI  Sorry the issue was related to mapbox SDK, resolved the issue by adding the following rules in pro guard. 
`-dontwarn com.mapbox.services.android.location.LostLocationEngine
-dontwarn com.mapbox.services.android.location.MockLocationEngine
`
These were not found in mapbox github tutorial. This issue can be closed.

**Comment by Michael-DJI** [comment]
@Abhishek284 got you, thanks for your wonderful job, we will investigate on this and update the proguard file if necessary!
