### ISSUE TITLE
VideoFeeder.VideoDataCallback is not called on dji spark when connected via wifi

### ISSUE THREAD

**Issue by Consti10** [dji-sdk/Mobile-SDK-Android#369]
**Description:** 
When connecting my android phone via **usb** to my dji spark controller's, everything **works fine**.
That is I receive video data via the `VideoFeeder.VideoDataCallback` and telemetry data accordingly.
But when connecting to the **wifi** of my controller, the VideoFeeder.VideoDataCallback **stops working** (it is never called, no data whatsoever) while telemetry and other stuff continues working.

Note that creating a instance of `DJICodecManager ` makes the Callback being called again - but thats not a solution for me, since I mustn't use it.

**Comment by Michael-DJI** [comment]
@Consti10 can you please try to use the sample app to retest it? and I also want to know if "kill app and restart" could resolve the issue?

**Comment by Consti10** [comment]
Hello Michael,
The app already restarts itself because of the new established usb connection when connecting via usb. But I manually restarted it also a couple of times, same behaviour.
It is also present in the sample app: https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample/issues/43
Besides from that, the only variable that I have to change when reproducing the issue is the physical connection to the controller - no changes in the app code or flow.


Note that when connecting via wifi I have to 'enable airplane mode'  for the sdk to recognize the spark ( but that is also needed when using the official DJI GO app ).

**Comment by Consti10** [comment]
@Michael-DJI 
Adding a fake DJICodecManager like in #352, https://github.com/dji-sdk/Mobile-SDK-Android/issues/352#issuecomment-444892468
Makes the callback being called in wifi mode.
But as pointed out by raphael, this is not a good solution and also results in application crashes when creating a real SurfaceTexture.

Please either implement a functionality that triggers the VideoFeeder.Callback reliable or make it enabled by default for both usb and wifi.

**Comment by Michael-DJI** [comment]
which version of MSDK were you using, we tested with the latest sample, can't reproduce the issue.
BTW, you could report the issue to  `dev@dji.com`  it's the official channel to request DJI SDK support now.

**Comment by Consti10** [comment]
Hello Michael,
Thanks for your feedback, I was using v4.8 of the mobile sdk.
When testing ( I am assuming you were using the Android-VideoStreamDecodingSample ),
did you make sure not to create a instance of DJICodecManager anywhere ? Because in this example there is no option without creating it.

I will also update to v4.8.1 and tell you if that fixes anything.

**Comment by Michael-DJI** [comment]
@Consti10 actually I was testing it with the Mobile-SDK-Android sample app, please check the listener in VideoFeedView class:
`videoDataListener = new VideoFeeder.VideoDataListener() {

            @Override
            public void onReceive(byte[] videoBuffer, int size) {

                lastReceivedFrameTime.set(System.currentTimeMillis());
                printRate(size);
                if (codecManager != null) {
                    codecManager.sendDataToDecoder(videoBuffer,
                                                   size,
                                                   isPrimaryVideoFeed
                                                   ? UsbAccessoryService.VideoStreamSource.Camera.getIndex()
                                                   : UsbAccessoryService.VideoStreamSource.Fpv.getIndex());
                }
            }
        };`

**Comment by Consti10** [comment]
Hello Michael,
did you disable the DJICodecManager ? I was able to reproduce the issue with the VideoFeedView class, and both when connecting my smartphone to dji spark directly via wifi and when connecting to rc via wifi.

I just added a print in the VideoDataListener()  ( like you did) and uncommented the DJIVideoReceiver:

`@Override
    public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
        if (codecManager == null) {
            /*codecManager = new DJICodecManager(this.getContext(),
                                               surface,
                                               width,
                                               height,
                                               isPrimaryVideoFeed
                                               ? UsbAccessoryService.VideoStreamSource.Camera
                                               : UsbAccessoryService.VideoStreamSource.Fpv);*/
        }
    }`

No data on the callback without DJIVideoReceiver.

**Comment by Michael-DJI** [comment]
@Consti10 can you please provide me your code in github with a public branch? so that I can clone it and test it

**Comment by Consti10** [comment]
Hello Michael,

Isn't it easier for you to do the changes to the original code yourself, it is 1 line of code and 1 'uncomment' :)
All changes are in internals/utils/videoFeedView.java

1) add `Log.d("XXX","DATA in callback arrived");` or `printRate(size);//I added this line to test the received video Buffer` like you did

2) uncomment the instantiation of DJICodecManager in `onSurfaceTextureAvailable` (line 104)

Then, check the android studio console for output.
