### ISSUE TITLE
Transparent Transmission with Android

### ISSUE THREAD

**Issue by alexandrubichis** [dji-sdk/Mobile-SDK-Android#37]
I am trying to send data from the mobile device to the onboard device and everything works fine on iPhone but on Android it does NOT work. I am using A3 and LB2.  Please note that on iPhone it works.

**Android: returns "Error on upstream from Mobile Device to OES. Description:Unsupport"**
_DJIAircraft mAircraft = (DJIAircraft)DJISDKManager.getInstance().getDJIProduct();
DJIFlightController mFlightController = mAircraft.getFlightController();                                
String message = "Hello, World!";
mFlightController.sendDataToOnboardSDKDevice(message.getBytes(),
new DJIBaseComponent.DJICompletionCallback() {
				@Override
				public void onResult(DJIError pError) {
								if (pError == null) {
												DJIDialog.showDialog(getContext(),"Success upstream from Mobile Device to OES");
								} else {
												DJIDialog.showDialog(getContext(), "Error on upstream from Mobile Device to OES. Description:" + pError.getDescription());
								}
				}
});_

**Also please note that when calling the isOnboardSDKDeviceAvailable() method it returns false**
                        _DJIAircraft mAircraft = (DJIAircraft)DJISDKManager.getInstance().getDJIProduct();
                        DJIFlightController mFlightController = mAircraft.getFlightController();                                       
                        String message;
                        if(mFlightController.isOnboardSDKDeviceAvailable()) {
                                message = "OnboardSDK device is available!";
                        }
                        else{
                                message = "OnboardSDK device is not available!";
                        }
                        DJIDialog.showDialog(getContext(), message);_

**Comment by alexandrubichis** [comment]
Hello, can anybody help me with this issue?

**Comment by dji-dev** [comment]
Hi @alexandrubichis, thanks for your feedback! We are investigating this issue, will get back to you once we have made any progress.

**Comment by dji-dev** [comment]
@alexandrubichis, after testing using the latest Android SDK 3.3, it works well. Please make sure that you are using the latest Android SDK 3.3, which you can download from our [DJI Developer Website](https://developer.dji.com/mobile-sdk/downloads/).

If you still have this issue, please let us know, thanks!

**Comment by alexandrubichis** [comment]
Hi,

I've checked using the latest Android SDK 3.3 and is working now.

Thank you!
