### ISSUE TITLE
 Tripod mode is not supported for Phantom 4 in DJI SDK

### ISSUE THREAD

**Issue by Abhishek284** [dji-sdk/Mobile-SDK-Android#371]
DJI SDK version: 4.7.1

While trying to enable the Tripod mode in Phantom 4 using the API "**setTripodModeEnabled**", we get the error "This feature is unsupported". We can enable the same in Mavic pro without any issues. This is in a sample app that I am working on. But the DJI GO 4 app supports Tripod mode in Phantom 4.

Is there anything that has to be done to make tripod mode work in phantom 4 in the sample app?

**Comment by kenargo** [comment]
Th 4.8.1, it fixes some functionality that was regressed in 4.7 but I don't know specifically about tripod mode. 

I know tracking mode on p4 is broken in 4.7 and 4.8.1.  I have not tested all other modes.


⁣Sent from BlueMail ​

**Comment by Abhishek284** [comment]
@kenargo I verified Tripod mode for Phantom 4 in the latest SDK **4.8.1** and it sill throws "Feature unsupported" error.  Is it an SDK issue?

**Comment by Michael-DJI** [comment]
sorry for the inconvenience, it will be fixed in next version.
BTW, you could report the issue in Stackoverflow using "dji-sdk" tag, it will attract more attention of our supporting team or send email to  `dev@dji.com`  it's the official channel to request DJI SDK support now.
