### ISSUE TITLE
importSDKDemo fails to load ffmepg 

### ISSUE THREAD

**Issue by rfsch** [dji-sdk/Mobile-SDK-Android#372]
Hi 

I am unable to run ImportSDKDemo it fails to load ffmepg.

D/EGL_emulation: eglCreateContext: 0xe47855a0: maj 2 min 0 rcv 2
E/EGL_emulation: tid 2708: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xd2fbede0, error=EGL_BAD_MATCH
E/EGL_emulation: tid 2708: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcfa24420, error=EGL_BAD_MATCH
E/linker: "/data/app/com.dji.importSDKDemo-vcSjhfUhuwILP8WpWu0Qjg==/lib/x86/libffmpeg.so" has text relocations
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.dji.importSDKDemo-vcSjhfUhuwILP8WpWu0Qjg==/lib/x86/libffmpeg.so" has text relocations
W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
W/System.err:     at dji.midware.natives.SDKRelativeJNI.<clinit>(Unknown Source:2)
        at dji.midware.natives.SDKRelativeJNI.native_getXXXX(Native Method)
        at com.dji.g.a.a.c.b(Unknown Source:22)
W/System.err:     at dji.midware.d.b(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
W/System.err:     at com.dji.importSDKDemo.MainActivity$1.run(MainActivity.java:122)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
D/SDKRelativeJNI: Couldn't load lib
E/zygote: No implementation found for byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String) (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX and Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX__Ljava_lang_String_2)
W/zygote: Got a deoptimization request on un-deoptimizable method byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String)
    Got a deoptimization request on un-deoptimizable method dji.sdk.sdkmanager.DJISDKManager dji.sdk.sdkmanager.DJISDKManager.getInstance()
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 2705 (AsyncTask #1)

Please help 

Thanks

**Comment by rfsch** [comment]
Hi 

I am unable to run ImportSDKDemo it fails to load ffmepg.

D/EGL_emulation: eglCreateContext: 0xe47855a0: maj 2 min 0 rcv 2
E/EGL_emulation: tid 2708: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xd2fbede0, error=EGL_BAD_MATCH
E/EGL_emulation: tid 2708: eglSurfaceAttrib(1210): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcfa24420, error=EGL_BAD_MATCH
E/linker: "/data/app/com.dji.importSDKDemo-vcSjhfUhuwILP8WpWu0Qjg==/lib/x86/libffmpeg.so" has text relocations
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.dji.importSDKDemo-vcSjhfUhuwILP8WpWu0Qjg==/lib/x86/libffmpeg.so" has text relocations
W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
W/System.err:     at dji.midware.natives.SDKRelativeJNI.<clinit>(Unknown Source:2)
        at dji.midware.natives.SDKRelativeJNI.native_getXXXX(Native Method)
        at com.dji.g.a.a.c.b(Unknown Source:22)
W/System.err:     at dji.midware.d.b(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
W/System.err:     at com.dji.importSDKDemo.MainActivity$1.run(MainActivity.java:122)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
D/SDKRelativeJNI: Couldn't load lib
E/zygote: No implementation found for byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String) (tried Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX and Java_dji_midware_natives_SDKRelativeJNI_native_1getXXXX__Ljava_lang_String_2)
W/zygote: Got a deoptimization request on un-deoptimizable method byte[] dji.midware.natives.SDKRelativeJNI.native_getXXXX(java.lang.String)
    Got a deoptimization request on un-deoptimizable method dji.sdk.sdkmanager.DJISDKManager dji.sdk.sdkmanager.DJISDKManager.getInstance()
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 2705 (AsyncTask #1)


Please help 

Thanks

**Comment by Michael-DJI** [comment]
Please check the Release Notes of 4.7 version, it's a known issue:
`On x86 devices that run Android API 23 or above, if the application is targeted with API 23 or above, FFmpeg lib might lead to runtime crashes or warnings.`
pls retarget your sdk to 22.
you could report the issue in Stackoverflow using "dji-sdk" tag, it will attract more attention of our supporting team or send email to  `dev@dji.com`  it's the official channel to request DJI SDK support now.

**Comment by chenerlich** [comment]
@Michael-DJI Were there any fixes? I'm stuck on this problem also..

**Comment by Michael-DJI** [comment]
@chenerlich this issue could not be fixed by DJI, it's caused by the ffmpeg, but you could retarget your app's targetSdkVersion to 22 (in your build.gradle file)to replace the crash with a google's warning message

**Comment by MarkinYuriy** [comment]
@Michael-DJI 
that is not solve
android studio don't want to compile it
Inspection info:As of the second half of 2018, Google Play requires that new apps and app updates target API level 26 or higher.

how to solve it?

**Comment by Michael-DJI** [comment]
@MarkinYuriy as I mentioned  this issue could not be fixed by DJI, yes we already know that:  Google Play requires that new apps and app updates target API level 26 or higher, so currently x86 so files only suitable for some company who has their own customized Android Rom.

**Comment by AdamKraif** [comment]
Any news ?
