### ISSUE TITLE
Feature request: Add api to get date of the drone

### ISSUE THREAD

**Issue by brozot** [dji-sdk/Mobile-SDK-Android#376]
Before starting a mission, we would need to determine if the time of the drone is synced with the time of the phone. I took a look to the SDK and I only found a way to get GSP time from the controller but nothing from the drone.

I would like to know if there is any way to get the current time of the drone ( the same time as the one used by getTimeCreated for mediaFile) from a call on the SDK and if not if there are any plan to add it ?

**Comment by Michael-DJI** [comment]
Currently we don't have this kind of interface, actually sdk will sync the phone's time to the drone when the app get connected.

BTW, you could report the issue in Stackoverflow using "dji-sdk" tag, it will attract more attention of our supporting team or send email to  `dev@dji.com`  it's the official channel to request DJI SDK support now.
