### ISSUE TITLE
How to get roll, pitch, yawn of drone? 

### ISSUE THREAD

**Issue by lordofprograms** [dji-sdk/Mobile-SDK-Android#379]
#### I have stucked with getting pitch, roll and yawn metrics on Android. 
Unfortunately, I didn`t find code or class with method of metrics that I need. I found only [description about this metrics](https://developer.dji.com/mobile-sdk/documentation/introduction/flightController_concepts.html) on official DJI developer website.
I will be so gladful, if you help me.

Best wishes, 
Michael

**Comment by kenargo** [comment]
There are many ways to get pitch, roll and yaw information.  FlightController.getState() will return an instatnce of FlightControllerState that includes the information you are looking for.  You could also use FlightController.setStateCallback (to receive information in real-time)  or you could use the key interfaces and get the information using the FlightControllerKey.VELOCITY_X, FlightControllerKey.VELOCITY_Y and FlightControllerKey.VELOCITY_Z.

If you want current attitude information (and not flight movement information) you can use the values in the FlightControllerState.getAttitude() call which will return an instance of Attitude

**Comment by lordofprograms** [comment]
Thank you for your answer it helped me a lot)
