### ISSUE TITLE
您好，使用4.9版本sdk推流延迟很高

### ISSUE THREAD

**Issue by Qiaoxinghua** [dji-sdk/Mobile-SDK-Android#395]
您好，运行sample code，测试推流延迟在2s左右，但是把LiveStreamView移植到自己的项目中去，推流的延迟达到15s左右，请问有可能是哪方面的问题，能否指点一下，非常感谢，期待您的回复。

**Comment by Qiaoxinghua** [comment]
非常感谢您的回复，我的是Manifest.permission.RECORD_AUDIO权限没有申请，加上就好了，再次感谢！

**Comment by coolmaye** [comment]
帮了我大忙，我花了一天多的时间都没找到原因..
