### ISSUE TITLE
XT2 and M2E Dual camera switching

### ISSUE THREAD

**Issue by coptercam** [dji-sdk/Mobile-SDK-Android#397]
-  Can't locate any sample code to show how to implement switching between IR and VL cameras on the XT2 and the M2E Dual cameras

**Comment by Michael-DJI** [comment]
setDisplayMode() in Camera class

**Comment by coptercam** [comment]
Thank.  That worked, however you have to select the IR camera instead of the RGB camera and then call the setDisplayMode() method.
