### ISSUE TITLE
UsbAccessoryService is obfuscated.

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#4]
We use UsbAccessoryService.getInstance().isConnected(), which is a public function. In SDK 2.4, it is obfuscated. I think it should not be.

**Comment by SilverChangjian** [comment]
Hi, the UsbAccessoryService is the internal class for our SDK and we have obfuscated this as well as other internal interface. If you want to check the connection, we suggest that you could use DJIDrone.getDjiCamera.getCameraConnectionIsOk()

**Comment by JonasVautherin** [comment]
Hello! We use it to detect if the connection to the remote controller is established or not. `getCameraConnectionIsOk()` will tell if the connection to the camera is established or not. It is different.

Since `UsbAccessoryService.registerAoaReceiver()` is public, why wouldn't it be the same for `UsbAccessoryService.isConnected()`?

**Comment by JonasVautherin** [comment]
Do you happen to have any news about that problem?

**Comment by SilverChangjian** [comment]
I have ask the team to add a method for getting the connection status between app and rc. And the methods in `UsbAccessoryService` would be scrambled.

**Comment by JonasVautherin** [comment]
Whatever you do, it would be nice to document it here once it is deployed. Thanks!

**Comment by JonasVautherin** [comment]
`isConnected` is apparently not obfuscated anymore in SDK 2.4.1. Looks like it is fixed for now.
