### ISSUE TITLE
DJI simulator callbacks not received from cold start.

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#40]
when calling DJISimulator.startSimulator(...) the first time it will never return the callback.

If I call it a second time it will start.

**Comment by SilverChangjian** [comment]
Do you mind to name the product you are using and which firmware version it is?

**Comment by jtuchek** [comment]
Sorry, I forgot the standard details on the post.

Android Devices: Nexus 9, Nexus 6P
Android Studio: v2.2
Android Version: 7.0
DJI SDK Version: 3.3
DJI Product: P3 Controller and Phantom 3 Professional
Flight Controller Firmware: 02.04.15.05
Remote Controller Firmware: 1.6.0

**Comment by SilverChangjian** [comment]
Thank you for reporting the bugs. We will investigate it in the following days.

**Comment by dji-dev** [comment]
Hi @jtuchek, after investigating, we cannot reproduce this issue, the callback works well. Are you sure you can reproduce this issue everytime? Have you tried others phones and see if the issue occurs again?

**Comment by jtuchek** [comment]
@dji-dev I can try a different device later this week.

It has been highly consistent. Where `DJIFlightController`->`startSimulator(...)` will be called, and never invoke the callback.

I can query if it has started with `DJIFlightController`->`hasSimulatorStarted(...)` and it will return `true`, but the result is not delivered. When it is called a second time, after a cold start, it will return a result.

**Comment by oliverou** [comment]
Hi @jtuchek, we have just launched the new Android SDK 3.4.1, please try it and check if the issue still exists. Thanks!
