### ISSUE TITLE
Helper.install() failed with AndroidX

### ISSUE THREAD

**Issue by Hujunjob** [dji-sdk/Mobile-SDK-Android#405]
#### Is this issue about bugs or crash issues of DJI Android SDK and Sample Code?

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

-  Description of the issue.
-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

#### Is this issue about DJI iOS SDK and Sample Code?

Then this is the wrong place, please refer to the Mobile-SDK-iOS Github: <https://github.com/dji-sdk/Mobile-SDK-iOS/issues>

DJI-SDK version 4.9
when i use AndroidX in my project, it will crash

**Comment by codeversed** [comment]
@Hujunjob I currently have an open support ticket with DJI about this and they did confirm that it has been passed to Engineering. 

There is really nothing we can do but to wait. DJI Support said it would be addressed in a future SDK release. I am sad not to see it in today's 4.10 SDK update.

**Comment by Ezorrio** [comment]
It's most probably related to Jetifier.
Sadly we're forced to wait for now

**Comment by Hujunjob** [comment]
@codeversed it's a sad story that 4.10 SDK has not fixed this bug

**Comment by cwbsl** [comment]
Apparently they are finally working on the issue:
https://github.com/dji-sdk/Mobile-SDK-Android/issues/377#issuecomment-523082981
But we don't know how long it will take to finish yet...

**Comment by eyalmnm** [comment]
Can anybody can update us about this bug and what are the alternatives? 
I am using:
implementation 'com.dji:dji-sdk:4.10'
compileOnly 'com.dji:dji-sdk-provided:4.10'

**Comment by kenargo** [comment]
Easy fix,  use older support libraries and not Android X

⁣Get BlueMail for Android ​

**Comment by mnabilurrehman** [comment]
Any update on this? Is the issue resolved?

**Comment by kenargo** [comment]
There is no ETA for Android X support.

⁣Get BlueMail for Android ​

**Comment by Michael-DJI** [comment]
@mnabilurrehman @Hujunjob pls update to 4.11

**Comment by eyalmnm** [comment]
Does com.dji:dji-sdk:4.11 supports androidX?

**Comment by neilyoung** [comment]
It is supposed to support it. Expect surprises.

**Comment by dji-lisafedane** [comment]
I can confirm MSDK 4.11 does support AndroidX - please see the release notes for more information on other highlights: https://developer.dji.com/mobile-sdk/downloads/

![image](https://user-images.githubusercontent.com/39347132/65900940-f997ed00-e36b-11e9-8295-6f42c424f478.png)

**Comment by kenargo** [comment]
Yes,  I build the app, Android X is now supported and required.   No more support libraries,  yea!

⁣Get BlueMail for Android ​
