### ISSUE TITLE
直播延迟和什么有直接关系呢

### ISSUE THREAD

**Issue by coolmaye** [dji-sdk/Mobile-SDK-Android#414]
demo的推流延迟测试大概是1秒多一点，同样的设备在我写的app上竟变成了12秒，我多次对比过各项设置，发现都没有问题，但就是延迟莫名其妙高了很多，在同样的设备同样的网络环境 gz#24500

**Comment by coolmaye** [comment]
没有加 的原因 感谢前人Manifest.permission.RECORD_AUDIO

**Comment by dji-dev** [comment]
> Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/24500'>Zendesk ticket #24500</a>:<br><br>尊敬的用户，<br><br> 您好！感谢您联系DJI 大疆创新。<br>很高兴您已经自行解决了问题，如果有任何SDK问题，可以再次联系我们。<br><br>非常感谢您的理解与配合，祝您生活愉快！<br><br>Best Regards,<br><br>DJI 大疆创新SDK技术支持
