### ISSUE TITLE
Add Osmo Pocket and Osmo Action support 

### ISSUE THREAD

**Issue by kibermaks** [dji-sdk/Mobile-SDK-Android#415]
Guys, please add support of Osmo Pocket and Osmo Action. Many of our customers request the support for this software! gz#24604

**Comment by dji-dev** [comment]
> Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/24604'>Zendesk ticket #24604</a>:<br><br>Thanks for reaching out to DJI Developer Support. I will pass on the request about providing SDK support for DJI Action and as for the OSMO Pocket, DJI is targeting support in the next couple of release cycles.<br><br>Lisa Fedane<br>DJI Developer Support

**Comment by Michael-DJI** [comment]
@kibermaks we thanks for feedbacks, we have got your request email.

**Comment by neilyoung** [comment]
Has the status changed meanwhile? Is the Osmo Pocket supported by the SDK?

**Comment by ygbr** [comment]
Is this possible already?

**Comment by demiantres** [comment]
Is there any news on this?

**Comment by markvdean** [comment]
Still no news on this?

**Comment by tuyaliang** [comment]
I successed to get stream and control osmo pocket & pocket2 through usb !
https://www.youtube.com/watch?v=A-PpPbcsgoo

**Comment by ikthreeo** [comment]
Hey guys also looking for a way to motion control the pocket osmo. Any update on this or atleast make the SDK available.

**Comment by markvdean** [comment]
> I successed to get stream and control osmo pocket & pocket2 through usb !
> https://www.youtube.com/watch?v=A-PpPbcsgoo

That's so cool!  So looking at your first video on it you're using a Jetson and controlling it through the micro USB port for the phone - could you go over how you got the Osmo to see inputs from it?  I'd love to find out more about this since I have a few ideas that would require control over the Osmo's gimbal.  Thank you

**Comment by zsinba** [comment]
How do you do that? Beautiful

**Comment by zsinba** [comment]
> I successed to get stream and control osmo pocket & pocket2 through usb !
> https://www.youtube.com/watch?v=A-PpPbcsgoo

How do you do that? Beautiful

**Comment by darvin** [comment]
?

**Comment by darvin** [comment]
That’s extremely regrettable - to find the way to control thing and not share it with community. Although it’s more shamable on the DJI side to make a good device completely worthless for humanity by closing up even its SDK

**Comment by frippe75** [comment]
The Drones have the Gimbal API. Couldn't the same be extended to support the DJI Osmo 2 ??
At least API wise. Just transport it via Bluethooth instead (overly simplifying,,,) ....

**Comment by pursual** [comment]
Any news on this front? The action series needs an api like the GoPros have.
