### ISSUE TITLE
Website error android mobile SDK V4.10 download button mislinked to github instead

### ISSUE THREAD

**Issue by hotelzululima** [dji-sdk/Mobile-SDK-Android#417]
the download android mobile sdk V4.10 button at https://developer.dji.com/mobile-sdk/downloads/<br>points to   https://github.com/dji-sdk/Mobile-SDK-Android  not to any mobile SDK for android..<br><br> gz#25433

**Comment by dji-dev** [comment]
> Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/25433'>Zendesk ticket #25433</a>:<br><br>Hi there,<br><br>Thank you for posting about your issue - this is Lisa from DJI Developer Support and I'm sorry to hear that the re-route has caused some confusion.  The link from the DJI Developer website does reroute you to DJI's github site but this is where you can download or clone the SDK - I have attached a screenshot to show you where.  In addition DJI has a tutorial called "Run Sample Application​" that gives you step by step instructions on how to do this.<br><br> ![](https://djisdksupport.zendesk.com/attachments/token/XF2gL0dJYvrtVh7FLUNv6Qtyx/?name=Screen+Shot+2019-06-26+at+5.44.36+AM.png)​<br><br>Please let me know if you run into any issues - we're happy to continue to help!<br><br>Warm Regards,<br><br>Lisa Fedane<br>DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/XF2gL0dJYvrtVh7FLUNv6Qtyx' target='zd_attach'>Screen Shot 2019-06-26 at 5.44.36 AM.png</a>

**Comment by dji-dev** [comment]
> Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/25433'>Zendesk ticket #25433</a>:<br><br>The link to the Run Sample App did not come through in the previous reply - here it is now: https://developer.dji.com/mobile-sdk/documentation/quick-start/index.html<br><br>Lisa Fedane<br>DJI Developer Support

**Comment by Michael-DJI** [comment]
@hotelzululima yes, we route to the GitHub page intentionally, you could download the package file from any Maven server like: https://mvnrepository.com/artifact/com.dji/dji-sdk
