### ISSUE TITLE
DJI SDK is WAY too big

### ISSUE THREAD

**Issue by reddigfabian** [dji-sdk/Mobile-SDK-Android#418]
The Android SDK from DJI has grown significantly over the last several months and has now reached a point where it is almost impossible to deploy an application that includes the SDK to the Google Play store due to the store's 100mb apk size limit.<br><br>Kittyhawk wants to provide its customers the most up to date and safe flight experience with their DJI aircraft but we are struggling to find ways to trim our apk in order to compensate for the size of the DJI sdk. I have attached a screenshot of apks compiled from DJIs own Sample Code repository with incrementing versions of the sdk. Please note that the latest sdk revision puts even this very small sample application OVER the 100mb limit set by the Google Play store.<br><br>Any advice on ways to trim unnecessary modules or assets in the sdk would be greatly appreciated.<br><br>![Alt Text](https://i.imgur.com/wBi9Cl0.png) gz#25641

**Comment by dji-dev** [comment]
> Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/25641'>Zendesk ticket #25641</a>:<br><br>Please see this MSDK Tutorial: Android-VideoStreamDecodingSample.  At the bottom you can see instructions on how to exclude the library-anti-distortion module and comment out a line if you do not need network RTK.<br><br>Lisa Fedane<br>DJI Developer Support

**Comment by dji-lisafedane** [comment]
https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample/blob/master/android-videostreamdecodingsample/app/build.gradle

**Comment by fishstix-dronedeploy** [comment]
The inclusion or exclusion of the RTK `library-networkrtk-helper` does little to the size of the APK.  And what if we *do* want to support the Mavic 2 series of drones in the application?  The exclusion `library-anti-distortion` does indeed reduce the size of the app significantly, but I'm not sure that is something we can afford to exclude.

**Comment by kenargo** [comment]
Have you thought about using expansion apk?

The other option would be to use bundles,  which allow for 150 MB but I've found that due to issues with the way DJI packages the SDK you might set failures on a few android device types. 



⁣Get BlueMail for Android ​

**Comment by reddigfabian** [comment]
Yea bundles would be the way to go except that the dji sdks setup causes them to fail on all the devices we tested.

**Comment by kenargo** [comment]
Yea, I found that out after I updated an app to use bundles (and there is no going back to apks).

 

I believe the issues with the DJI SDK failing with bundles is how they package the .SO files; for some devices the .SOs are not getting delivered.

 

If DJI would fix support for Google bundles it would certainly make things easier and solve so many problems, especially apk size!

**Comment by brien-crean** [comment]
We're having the same issue and also using the dji-uxsdk so our APK size is 182.8MB before looking at expansion apk but I don't see it going down to < 100MB unless anyone has a suggestion?

Also tried using a bundle but got the same issue as everyone else. Soon after the app loads it stops responding.

Has anyone managed to get their app that uses the latest sdk to work with an android bundle?

**Comment by Michael-DJI** [comment]
Please upgrade to 4.11 which is smaller than older version, meanwhile in next version we will continue to decrease the size of package.

**Comment by dji-lisafedane** [comment]
The Android Appbundle bug has been fixed with MSDK V4.11.1.  Please see the following links for more information: 

	•	Sample Code for Bundle: https://github.com/DJI-Mobile-SDK-Tutorials/DJI-Android-SDK-Bundle-Sample
	•	MSDK Release Notes: https://developer.dji.com/mobile-sdk/downloads/
	•	UXSDK Release Notes: https://developer.dji.com/ux-sdk/

Please reach out to DJI Developer Support if you have any issues.  We have a form that you can now use to generate tickets found here: https://formcrafts.com/a/dji-developer-feedback-en or email dev@dji.com

**Comment by jeryini** [comment]
Hello @dji-dev @dji-lisafedane !

Can someone at DJI check out this issue https://github.com/DJI-Mobile-SDK-Tutorials/DJI-Android-SDK-Bundle-Sample/issues/1 for above mentioned sample code for bundles. Thank you!
