### ISSUE TITLE
MediaFile.fetchFileData is not correctly writing larger files

### ISSUE THREAD

**Issue by ericwarden** [dji-sdk/Mobile-SDK-Android#419]
I have a Mavic 2 Enterprise Dual with a file around 3.5GB (according to the DJI Go app) that I'm trying to download using v4.10. This is a video recorded at 1080p and is 13:51 minutes long.<br><br>The onSuccess callback from the fetchFileData is being called and the file is being saved to the directory that I specified. However, once try to access that file using the Java File class, it is giving me a length that is much smaller than the size of the MediaFile object from the DJI SDK.<br><br>MediaFile.fileSize=3758589565<br>File.length=2147479552<br><br>I have tested on both the DJI Smart Controller and a Samsung Tab A running Android 8.1.0 and get the same result. gz#25689

**Comment by Michael-DJI** [comment]
@ericwarden Hey, thanks for the feedback, did you play the video and check the duration? if it's 13:51 ?

**Comment by ericwarden** [comment]
Yes, it's showing the correct duration of 13:51 and I can play the file from our app just fine. The only issue is that trying to access the file after it is download is showing a smaller file than it should.

Additionally, I tried downloading the file with the DJI Pilot app. Likewise, it also downloaded successfully however I was unable to find the downloaded file in the filesystem and the app crashes when I try to watch the download video.

**Comment by Michael-DJI** [comment]
@ericwarden did you check the size of file on a computer?  insert the sd card into the computer

**Comment by ericwarden** [comment]
Connecting the drone to the computer appears to show the correct file size of 3.76GB.

**Comment by ericwarden** [comment]
I tried to upload another slightly smaller file and got the following:
Java file length: 2147479552
MediaFile fileSize: 2716564413

I noticed that the file length was the same in both cases. After doing a little searching I found the following snippet from `man write` which seems relevant.

> On Linux, write() (and similar system calls) will transfer at most 0x7ffff000 (2,147,479,552) bytes, returning the number of bytes actually transferred. (This is true on both 32-bit and 64-bit systems.)
