### ISSUE TITLE
Product connecction with usb cable

### ISSUE THREAD

**Issue by ibrahimsalgin** [dji-sdk/Mobile-SDK-Android#423]
I have been trying almost all samples (either android or ios) but couldn't connect my dji product (phantom 4 pro+ V2.0) to my app. I can successfully register my app by using my api key, but when I connect dji product to the phone with usb cable I cannot see any connection. How can I make a successful connection?

**Comment by kenargo** [comment]
The samples work,  I can confirm that because I use them on occasion for testing. 

I understand your frustration but because of a lack of details it's going to be difficult to help you. 

For example, you only say the SDK authorizes correctly.   I assume you know this never you see the toast?

When you connect the usb to the android,  do you see your app start or another app?

What about app permissions,  are they enabled?

⁣Get BlueMail for Android ​

**Comment by dji-dev** [comment]
> Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/26080'>Zendesk ticket #26080</a>:<br><br>Can you test product connection with the DJI GO 4 app?  If your P4P doesn't connect then there maybe something wrong with your drone and please contact the DJI After Sales team at Support@DJI.com.<br><br>When you say "I have been trying almost all samples (either android or ios) but couldn't connect my dji product (phantom 4 pro) to **_my app_**"  are you trying to connect unmodified DJI Sample Apps to your P4P or are the DJI Samples integrated into your app?  If it's the later, I would suggest running the sample apps without your code first to test if the drone will connect.<br><br>It's also possible that your RC and aircraft just need to be paired which can be done through the GO 4 app.  If you are able to connect DJI GO 4 but still not able to connect to any of DJI's Sample Apps, then please post screenshots of the splash page for the Android UXSDK or MSDK Sample App so I can better see what might be going on.<br><br>Lisa Fedane<br>DJI Developer Support

**Comment by ibrahimsalgin** [comment]
Thanks for the responses. I have also tried DJI GO 4 app but i couldn't see any connected device. I m connecting my tablet to my controller with usb cable. I can understand now the problem is my controller has also it's own tablet on it. Should I use a controller without a tablet? I have uploaded an image that you can see my tablet is connected to the controller with cable. The DJI product is connected to the controller but not connected on samsung tablet.
![IMG_5531](https://user-images.githubusercontent.com/6638258/61368661-0a6db200-a897-11e9-9f11-3691e23d5651.jpg)

**Comment by Michael-DJI** [comment]
@ibrahimsalgin yes, pls use the remote controller without the screen

**Comment by ibrahimsalgin** [comment]
Is there any guide to remove the screen from the controller? Because it seems impossible to remove it.

**Comment by Michael-DJI** [comment]
@ibrahimsalgin I'm sorry, I think you need to get a new remote controller or try to install your app directly to the build-in screen( it's actually a android system)

**Comment by ibrahimsalgin** [comment]
is it possible to connect "phantom 4 pro+ V2.0" via a custom app by using dji sdk? In some forums it s mentioned that "phantom 4 pro+ V2.0" does not support to be connected by another app or device. @Michael-DJI

**Comment by Michael-DJI** [comment]
@ibrahimsalgin MSDK started to support p4p v2 from v4.6, please read the release notes for accessing of such information from following link:
 https://developer.dji.com/mobile-sdk/downloads/
(need login first)
