### ISSUE TITLE
LiveStreamManager State is pushing flow.Actual state has stopped pushing flow

### ISSUE THREAD

**Issue by boosan** [dji-sdk/Mobile-SDK-Android#424]
Using a video streaming LiveStreamManager push, I reply some broken network, frame rate obtained through getLiveVideoBitRate still close to 30 frames per second, but it has stopped pushing flow.I try to use djigo4 and djipilot will, too.I use is model is the P4P, analog network broken network: 4 g wifi off open or close the wifi and open wifi.I think it's about LiveStreamManager bug gz#26117

**Comment by dji-dev** [comment]
> Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/26117'>Zendesk ticket #26117</a>:<br><br>Dear Customer,<br><br>Thank you for contacting DJI.<br>Sorry that this is a known issue in the MSDK v4.10. There is no MSDK method to monitor the status of the internet.<br>So it's recommended to monitor them in a real-time for the being time.<br><br>We will try to fix it in the later MSDK version, and please pay attention to the future MSDK release.<br><br>Thanks,<br><br>Luce Luo<br>DJI Dev Team

**Comment by boosan** [comment]
> > Public comment from Luce Luo in [Zendesk ticket #26117](https://djisdksupport.zendesk.com/agent/tickets/26117):Dear Customer,Thank you for contacting DJI.Sorry that this is a known issue in the MSDK v4.10. There is no MSDK method to monitor the status of the internet.So it's recommended to monitor them in a real-time for the being time.We will try to fix it in the later MSDK version, and please pay attention to the future MSDK release.Thanks,Luce LuoDJI Dev Team
Ok, looking forward to the new release

**Comment by boosan** [comment]
Ok, looking forward to the new release

**Comment by neilyoung** [comment]
You could consider using a more modern WebRTC based approach using this

https://github.com/accuware/djistreamerlib

Demo video:

https://youtu.be/B1reiM7oCmM
