### ISSUE TITLE
请问实时如何获取航点任务拍照的照片（我知道不应该在这问非bug问题，但希望有人能回答我一下）

### ISSUE THREAD

**Issue by pzy2253999075** [dji-sdk/Mobile-SDK-Android#429]
我这边需要实现一个功能，就是航点拍照的时候把照片的存储路径和航点编号对应起来，方便快速找到航点编号对应的照片。我已经阅读了Camera类下面的各种功能，但是好像没找到实时获取每次拍照图片的存储路径或名字的API，只看到这个setMediaFileCustomInformation函数勉强相关，但是不知道怎么用，有大神可以告诉我一下吗，谢谢（我英文不太好，就不写英文了），如果我发的内容不符合板块要求，把我的贴子删了，但希望大疆的开发者告诉我一下有没有这个功能，或者怎么实现。

**Comment by Michael-DJI** [comment]
你用的哪几个型号的飞机？

**Comment by pzy2253999075** [comment]
不好意思，我来晚了，我的飞机型号是inspire pro1 和inpire 2  ，云台是禅思X5 @Michael-DJI

**Comment by Michael-DJI** [comment]
@pzy2253999075 建议用Inspire 2 + x5s或者x4s相机，
https://developer.dji.com/api-reference/android-api/Components/Camera/DJICamera.html?search=camera&i=2&#djicamera_setdjicamerageneratednewmediafilecallback_inline
setMediaFileCallback（） 这个接口客户获取到拍摄的照片的文件名，但是获取不到存储路径

**Comment by pzy2253999075** [comment]
@Michael-DJI 好的，谢谢，我试试
