### ISSUE TITLE
DJIMissionManager.pauseMissionExecution hangs...

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-Android#43]
DJI Android SDK version - 3.4
DJI Product: Phantom 4
Android version: 6.0.1
Android device: Samsung Galaxy Tab S2
Android Studio version: 2.2.2

If you call DJIMissionManager.pauseMissionExecution when a mission is not running, rather than calling back the callback with an error, the call goes off into the ether and NEVER calls the callback.  This can be an issue because a mission MAY be running when the call to pause is initiated, and then will complete shortly after (within milliseconds).  This issue is reproducible at any time simply by calling DJIMissionManager.pauseMissionExecution when a mission has been stopped or before one is started.

The expected behavior would be that the callback will ALWAYS get called (similar to the way the iOS SDK works), and if there is no mission running (or the mission finishes execution after the call to pause is initiated but before it completes) then an appropriate error gets returned.  In iOS, that is error code -5016 (No mission is running).

**Comment by oliverou** [comment]
Hi @jgrantr, thanks for your feedbacks, we will investigate this issue and get back to you once we make progress.

**Comment by oliverou** [comment]
Hi @jgrantr, we have just launched the new Android SDK 3.4.1, please try it and check if the issue still exist. Thanks!

**Comment by jtuchek** [comment]
I am also experiencing this in SDK 3.4.0 with the Inspire 1.

**Comment by oliverou** [comment]
Hi @jtuchek, please try the latest Android SDK 3.4.1 and check if the issue still exists.

**Comment by xxmaestroxx** [comment]
Hey DJI,

what is the status of this issue?

Regards
Maestro

**Comment by talobin** [comment]
We have had a big revamp in Mission.
Please check out the class MissionControl.
Will go ahead and close this issue since it has been a long time.
@edancain Please help to create a separate issue if you still have problem with current version SDK 4.3.2
Thanks!
