### ISSUE TITLE
PHANTOM 4 RTK掉固定解

### ISSUE THREAD

**Issue by Mc-mo** [dji-sdk/Mobile-SDK-Android#431]
飞机没起飞时可以获取到固定解，航点任务起飞后会掉出固定解，networkServiceState.getChannelState()直接变成DISCONNECTED，但getError()为空。
当前机型 PHANTOM 4 RTK
固件版本 最新
SDK版本 4.10

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/26917'>Zendesk ticket #26917</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by Michael-DJI** [comment]
请用表格反馈，多谢
https://formcrafts.com/a/dji-developer-feedback-cn
