### ISSUE TITLE
Mavic 2 pro support in android sdk

### ISSUE THREAD

**Issue by aRealBanana** [dji-sdk/Mobile-SDK-Android#436]
So, I searched the website and the internet for an answer but i couldnt, is Mavic 2 pro supported in android sdk? if yes why is it not stated in the dji [website](https://developer.dji.com/products/#!/)? also, for testing does DJI Assistant 2 support mavic 2 pro as it is not mentioned in the [website](https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-testing.html)?

**Comment by kenargo** [comment]
According to the readme; the Mavic 2 Pro  is supported.  Is there some issue that you are seeing?
