### ISSUE TITLE
DJIMissionManager.stopMissionExecution returns the wrong errors...

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-Android#44]
DJI Android SDK version - 3.4
DJI Product: Phantom 4
Android version: 6.0.1
Android device: Samsung Galaxy Tab S2
Android Studio version: 2.2.2

There are two cases where calling DJIMissionManager.stopMissionExecution returns errors that are unexpected or just plain wrong.

Case 1:

When calling DJIMissionManager.stopMissionExecution when a mission has already been stopped, the error that is sent to the callback is "DJIMissionManagerError.MISSION_RESULT_WAYPOINT_REQUEST_IS_RUNNING" but the actual error to return SHOULD be "DJIMissionManagerError.MISSION_RESULT_WAYPOINT_NOT_RUNNING" because no mission is actually executing, correct?  This is 100% reproducible:

1) Start a waypoint mission
2) After the mission starts (and before it finished) call DJIMissionManager.stopMissionExecution
3) Call it a second time, and the 2nd time (and every time thereafter), the error result sent to the callback is DJIMissionManagerError.MISSION_RESULT_WAYPOINT_REQUEST_IS_RUNNING.

Please see below for a suggestion on what the new error should be called.

Case 2

When calling DJIMissionManager.stopMissionExecution when no mission has ever been started, the error that is sent to the callback is "DJIError.COMMON_UNKNOWN" (whose message says "Server error, please contact <dev@dji.com> for help.").  Calls to this method SHOULD be consistent.  If there is no mission running (regardless of whether one has run before or not), the returned value should always indicate that no mission is running.  The only current error that seems to indicate that is:  

DJIMissionManagerError.MISSION_RESULT_WAYPOINT_NOT_RUNNING

However, since more than one type of mission can be run, it should probably be a more generic error, something along the lines of:

DJIMissionManagerError.MISSION_RESULT_NO_MISSION_RUNNING

This would more closely follow what the iOS SDK is doing, which returns a consistent error from pause/resume/stop if there is not a mission that is currently executing (in the case of iOS it is error code -5016, whose enum name is DJISDKMissionErrorAircraftNoRunningMission).

**Comment by oliverou** [comment]
Hi @jgrantr, thanks for the detailed feedbacks! We have found and fixed this issue in the Android SDK, will update it in the next SDK release soon.

**Comment by oliverou** [comment]
Hi @jgrantr, we have just launched the new Android SDK 3.4.1, please try it and check if the issue still exists. Thanks!
