### ISSUE TITLE
Does DJI SDK support Android 10 (Android Q)?

### ISSUE THREAD

**Issue by vivekvinodh** [dji-sdk/Mobile-SDK-Android#440]

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/28135'>Zendesk ticket #28135</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry to tell you that the current SDK v4.10 doesn't support the Android Q.
Please pay attention to the later version.

Thanks,

Luce Luo
DJI Dev Team
