### ISSUE TITLE
AMAP SDK Google Play issue

### ISSUE THREAD

**Issue by cwbsl** [dji-sdk/Mobile-SDK-Android#444]
Hello

I just received an e-mail from Google Play Support with the following content:

We're writing to let you know that your app, *MYAPPNAME*, with package name my.package.name is in violation of Google Play Developer Program Policies. 
Issue: Violation of the Malicious Behavior policy
An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism. Likewise, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play.
We found that your app is using a non-compliant version of the AMAP SDK which contains code to download executable code (e.g. dex, JAR, .so files) from a source other than Google Play. If necessary, you can consult your SDK provider(s) for further information.
Action required: Please bring your app into compliance within 7 days of the issuance of this notification, or your app will be removed from Google Play.

I'm not using any AMAP SDK and I'm pretty sure that this SDK is included in the DJI SDK.

What can we do about this? 7 days won't be enough for DJI to fix this I think and Google Play will remove all apps with the DJI SDK included in them?

**Comment by kenargo** [comment]
What SDK version?  

⁣Get BlueMail for Android ​

**Comment by kenargo** [comment]
Never mind,  I received the same email for my apps, they've been in the store for months with no issue.

This is bad. 

⁣Get BlueMail for Android ​

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/28404'>Zendesk ticket #28404</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team

**Comment by smaorus** [comment]
Any solutions yet?
This is an emergency for all users of this sdk.

**Comment by kenargo** [comment]
If you don't need AMap then you can exclude it from the package. 

implementation ('com.dji:dji-uxsdk:4.11',
{ exclude group: 'com.amap.api' }
)

⁣Get BlueMail for Android ​

**Comment by cwbsl** [comment]
> If you don't need AMap then you can exclude it from the package. implementation ('com.dji:dji-uxsdk:4.11', { exclude group: 'com.amap.api' } ) ⁣Get BlueMail for Android ​
> […](#)
> On Sep 29, 2019, 3:31 AM, at 3:31 AM, smaorus ***@***.***> wrote: Any solutions yet? This is an emergency for all users of this sdk. -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#444 (comment)](https://github.com/dji-sdk/Mobile-SDK-Android/issues/444#issuecomment-536280973)

Thanks! I will try that since I use Google Maps for my app...

**Comment by kenargo** [comment]
Google just confirmed it worked!

⁣Get BlueMail for Android ​

**Comment by smaorus** [comment]
> Google just confirmed it worked! ⁣Get BlueMail for Android ​
> […](#)
> On Sep 30, 2019, 12:33 AM, at 12:33 AM, cwbsl ***@***.***> wrote: > If you don't need AMap then you can exclude it from the package. implementation ('com.dji:dji-uxsdk:4.11', { exclude group: 'com.amap.api' } ) ⁣Get BlueMail for Android ​> […](#) > On Sep 29, 2019, 3:31 AM, at 3:31 AM, smaorus ***@***.***> wrote: Any solutions yet? This is an emergency for all users of this sdk. -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#444 (comment)]([#444 (comment)](https://github.com/dji-sdk/Mobile-SDK-Android/issues/444#issuecomment-536280973)) Thanks! I will try that since I use Google Maps for my app... -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#444 (comment)](https://github.com/dji-sdk/Mobile-SDK-Android/issues/444#issuecomment-536440018)

How did they let you know?

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/28404'>Zendesk ticket #28404</a>:<br><br>I can confirm that this is a known UXSDK problem the DJI SDK engineers are working on.  In the meanwhile, if you don't need to use AMAP then we have a workaround for you to use immediately - see below:

Please use the following code in your build.gradle and re-submit your app  to Google for approval:

    implementation ('com.dji:dji-uxsdk:4.10',
    { exclude group: 'com.amap.api' }
    )



Lisa Fedane
DJI Developer Support

**Comment by cwbsl** [comment]
Thanks Lisa, I will do that as a workaround!
