### ISSUE TITLE
DJIMissionManager stalls on preparing DJICustomMission

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#45]
When attempting to upload any custom mission via the mission manager - the process will always stall on `DJIMissionManager.prepare(...)` and cannot be started.

The completion callback with `DJIMissionManager.prepare(...)` is never returned. 

If using `addMissionToTheQueue` - the mission will begin to execute, but takeoff unexpectedly and only perform a few of several points before unexpectedly returning home. *I don't intend to use this as it circumvents the mission manager, was just curious if it would work*

SDK Version: 3.3
Android Devices
- Nexus 9: API 24
- Nexus 6P: API 25
DJI Devices
- Phantom 3 Professional
--Remote Controller Firmware: 1.6.0
--Flight Controller Firmware: 2.04.14.05
--Gimbal Firmware: 01.44.00.00
--Camera Firmware: 01.30.50.36
- Inspire 1 Pro
--Remote Controller Firmware: 1.7.4.0
--Flight Controller Firmware: 2.0.4.20.18
--Gimbal Firmware: 1.29.00.92
--Camera Firmware: 1.9.1.10

**Comment by oliverou** [comment]
Hi @jtuchek, thanks for your feedbacks. I saw that you are still using Android SDK 3.3, actually, we have published the Android SDK 3.4 last week, could you try to use the SDK 3.4 and check if the issue still exists? Thanks!

**Comment by jtuchek** [comment]
@oliverou I can give it a shot and follow up with the results.

**Comment by jtuchek** [comment]
I have updated our SDK to v3.4 - from testing in the simulator on both the Phantom and the Inspire neither of them seem to work with `DJIMissionnManager.prepare(...)`.

We'll be doing a real life field test in a few hours to verify outside of the simulator.

**Comment by oliverou** [comment]
Hi @jtuchek, we have launched the Android SDK 3.4.1, please try it and check if the issue still exist. Thanks!
