### ISSUE TITLE
setPhotoTimeIntervalSettings throws "Param Illegal"

### ISSUE THREAD

**Issue by cwbsl** [dji-sdk/Mobile-SDK-Android#453]
I'm using the SDK version 4.11 and havent changed this code bit since 4.10:

```
int shootInterval = 2;
SettingsDefinitions.PhotoTimeIntervalSettings mSettings = new SettingsDefinitions.PhotoTimeIntervalSettings(255, shootInterval);
DJIApplication.getCameraInstance().setPhotoTimeIntervalSettings(mSettings, djiError -> {
    if (djiError == null) {
        Log.d(MainActivity.TAG, "Camera interval set to " + mSettings.getTimeIntervalInSeconds() + " seconds");
    } else {
        Log.e(MainActivity.TAG, "ERROR! Message: " + djiError.getDescription())
    }
});
```

The error I'm getting:

> "Param Illegal"

This seems to be a bug in the 4.11 SDK because in the 4.10 SDK it was working with the same code snippet. As a drone I'm using the Phantom 4 RTK.
I can't go back and use the 4.10 SDK though because AndroidX support was only recently added.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/29900'>Zendesk ticket #29900</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team

**Comment by cwbsl** [comment]
I have filled out the form with the bug I've encountered

**Comment by cwbsl** [comment]
Too bad the devs are not answering here to make sure everybody knows what's going on.
The problem is that the P4RTK only supports 3 second intervals. This is however documented nowhere.
