### ISSUE TITLE
OnBoardSdk callbacks not working on Matrice 210 RTK v1

### ISSUE THREAD

**Issue by SerjTech** [dji-sdk/Mobile-SDK-Android#456]
Using a Matrice 210 RTK v1, and the latest mobile SDK version, 
when trying to connect to OnBoardSdk using the Android methods, the Mobile SDK keeps receiving the error message that says "This aircraft does not support OnBoardSDK".

However, OnBoardSdk Documentation (https://developer.dji.com/onboard-sdk/documentation/introduction/homepage.html) leaves clear that Matrice 210 RTK does support OnBoardSdk. 

But, Mobile Sdk documentation says that this drone is not compatible (https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html?search=senddatato&i=4&#djiflightcontroller_senddatatoonboardsdkdevice_inline)

Which one is the true answer, OnBoard's or mobile's documentation? How can I make it work with Matrice 210?

(All SDK options available in DJI Assistant 2 for Matrice 210 RTK are correctly configured)

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30110'>Zendesk ticket #30110</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team
