### ISSUE TITLE
Broken video stream from Phantom 4 Advanced with HDMI (Part 54) module.

### ISSUE THREAD

**Issue by jknightmmcs** [dji-sdk/Mobile-SDK-Android#460]
Hello.

I receive raw H264 video through VideoFeeder from PrimaryVideoFeed and send it to DJICodecManager.
With DJI Phantom 4 YuvDataCallback receives correct video frames with HD (1280x720) resolution. With DJI Phantom 4 Advanced coupled with HDMI (Part 54) module it receives broken Full HD (1920x1080) video frames instead. Here's how it looks:

[screenshot](https://i.stack.imgur.com/jl1p7.png)

Speaking from image processing experience, such stuff happens when binary data isn't of the declared format, but that doesn't help much anyway.

So, two questions arise:
1. Is it possible to choose resolution of the incoming video stream? If so, how?
2. What exactly happens to the video frame with P4 Advanced? What's its actual format? How to fix it?

Here is the video stream initialization source code:

```
DJICodecManager  mCodecManager_ = new DJICodecManager(workContext, null, 0, 0, UsbAccessoryService.VideoStreamSource.Camera);
VideoFeeder.getInstance().getPrimaryVideoFeed().addVideoDataListener((bytes, size) ->  mCodecManager_.sendDataToDecoder(bytes, size));
mCodecManager_.enabledYuvData(true);
mCodecManager_.setYuvDataCallback(yuv_handler_); 
```

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30291'>Zendesk ticket #30291</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
For Phantom 4, it's impossible to choose the resolution of the video stream, always 720P/30FPS.
And the video stream is not standard H264 data, missing the I frame.
So you need to insert the I frame and then decode it with a customized decoder.
Here is a documentation about how to insert the I frame, hope this can help you.
https://developer.dji.com/mobile-sdk/documentation/sample-code/index.html

Thanks,

Luce Luo
DJI Dev Team

**Comment by jknightmmcs** [comment]
Stream being broken issue fixed, this was problem with the code on our side.
