### ISSUE TITLE
DJI Matrice 600 Pro YuvData video stream doesn't work

### ISSUE THREAD

**Issue by jknightmmcs** [dji-sdk/Mobile-SDK-Android#461]
Hello.

I'm trying to receive video stream from DJI Matrice 600 Pro (+Zenmuse Z3). It seems that VideoFeeder correctly outputs raw H264 from SecondaryVideoFeed, but DJICodecManager's isDecodeOk == false, and YuvDataCallback isn't called at all. 

Here is the video stream initialization source code:

```
DJICodecManager  mCodecManager_ = new DJICodecManager(workContext, null, 0, 0, UsbAccessoryService.VideoStreamSource.Camera);
VideoFeeder.getInstance().getPrimaryVideoFeed().addVideoDataListener((bytes, size) ->  mCodecManager_.sendDataToDecoder(bytes, size));
mCodecManager_.enabledYuvData(true);
mCodecManager_.setYuvDataCallback(yuv_handler_); 
```

What could I be doing wrong?

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30292'>Zendesk ticket #30292</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Yes, for the M600Pro + z3, the video stream comes from the second video feed.
So you need to replace your code from getPrimaryVideoFeed to getSecondaryVideoFeed.

Thanks,

Luce Luo
DJI Dev Team

**Comment by jknightmmcs** [comment]
Thanks, fixed now.
