### ISSUE TITLE
storageState.getStorageLocation() always returns NULL

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android#462]
SDK Version: 4.11.1
Drone: Mavic Pro

Calling `getStorageLocation` within the `setStorageStateCallBack` function always returns `NULL`. I should be receiving an enum value of StorageLocation -> `SDCARD` as there is one installed in the drone (this drone does not support internal storage).
```
Camera camera = DJISDKManager.getInstance().getProduct().getCamera();
camera.setStorageStateCallBack(storageState -> {
    return storageState.getStorageLocation(); // Always NULL
});
```

I can get the storage location via another callback.
```
camera.getStorageLocation(new CommonCallbacks.CompletionCallbackWith<SettingsDefinitions.StorageLocation>() {
            @Override
            public void onSuccess(SettingsDefinitions.StorageLocation storageLocation) {
                return storageLocation.name(); // returns "SDCARD"
            }
```

However being able to obtain the storageLocation during `setStorageStateCallBack` is extremely useful.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30331'>Zendesk ticket #30331</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry for this issue, we will investigate it further.
Please pay attention to the later MSDK release.

Thanks,

Luce Luo
DJI Dev Team

**Comment by brien-crean** [comment]
@dji-dev thanks. I fixed my issue with a workaround for now by wrapping `setStorageStateCallBack` around `getStorageLocation`:

```
camera.setStorageStateCallBack(storageState -> {
  camera.getStorageLocation(new CommonCallbacks.CompletionCallbackWith<SettingsDefinitions.StorageLocation>() {
    @Override
    public void onSuccess(SettingsDefinitions.StorageLocation storageLocation) {
      GsonBuilder builder = new GsonBuilder();
      Gson gson = builder.create();
      JsonObject storageStateObject = gson.toJsonTree(storageState).getAsJsonObject();
      storageStateObject.addProperty("location", storageLocation.name());
      return storageStateObject;
    }

    @Override
    public void onFailure(DJIError djiError) {
      new Exception(djiError.getDescription());
    }
  });
});
```
