### ISSUE TITLE
stopFetchingFileData never called (class MediaFile)

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android#463]
SDK Version: 4.11.1
Drone: Mavic Pro

I have noticed no matter what condition I set in the onProgress function of fetchFileData, I cannot trigger stopFetchingFileData.

Here is a simple example:

```
//class MediaFile
mediaFile.fetchFileData(destinationFolder, fileName, new DownloadListener<String>() {   
    @Override
    public void onProgress(long total, long current) {
        if (current > 10) {
            Log.d("DEBUG", "current > 10");
            mediaFile.stopFetchingFileData(djiError -> {
                Log.d("DEBUG", "Stopping Download");
            });
        }        
    }
}

```
Logcat obviously shows the "current > 10" output but never "Stopping Download"

I am trying to download only the meta data of an image using fetchFileData and the closing tag `</x:xmpmeta>`. I am able to locate the tag in onProgress. However when I then trigger `stopFetchingFileData`, nothing happens and the entire file is downloaded making meta data retrieval very slow.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30442'>Zendesk ticket #30442</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Can you verify if any error turns back from the djiError?

Thanks,

Luce Luo
DJI Dev Team

**Comment by brien-crean** [comment]
@dji-dev thanks for your reply! I just tried and there is no error. It appears the lambda inside the call to `stopFetchingFileData` is never triggered. I tried the following code to print an error but nothing was printed except the initial debug log statement before stopFetchingFileData: `current > 10`:
```
mediaFile.fetchFileData(destinationFolder, fileName, new DownloadListener<String>() {   
    @Override
    public void onProgress(long total, long current) {
        if (current > 10) {
            Log.d("DEBUG", "current > 10");
            mediaFile.stopFetchingFileData(djiError -> {
                if(djiError != null) {
                    Log.d("DEBUG", djiError.getDescription());
                } else {
                    Log.d("DEBUG", "djiError is NULL");
                }
            });
        }        
    }
}
```

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30442'>Zendesk ticket #30442</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I see.
In fact, the download progress will be stopped after calling the stopFetchingFileData, even though there is no success or error feedback in callback function.
But you can listen to the onFailure listener, will give the fail result.

    @Override
    public void onFailure(DJIError djiError) {
     Log._d_("DEBUG","onFailure:" + djiError.getDescription());
    }

I will escalate this issue to the engineer to investigate it further.
Sorry about it.

Thanks,

Luce Luo
DJI Dev Team

**Comment by brien-crean** [comment]
@dji-dev unfortunately it does not stop the download. I monitored the output of the method `onProgress` of `fetchFileData` which takes the total and current values of the in progress download and I can see that it keeps going until current is equal to total and then triggers the `onSuccess` function of `fetchFileData`. 

This unfortunately makes it very slow to grab the meta data only from images on Android. The corresponding feature on iOS works as expected.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30442'>Zendesk ticket #30442</a>:<br><br>Dear Customer,

Thank you for your feedback.
Sorry that this issue has been escalated to the engineer.
It will cost some time and we will contact you again once any progress.

Thanks,

Luce Luo
DJI Dev Team

**Comment by brien-crean** [comment]
@dji-dev is there any update on this bug? Meta data retrieval on android is so painfully slow because of this bug

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30442'>Zendesk ticket #30442</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry, the engineer is keeping working on this issue and have no progress for the being time.
I will escalate it again for you and will contact you once any update.

Thanks,

Luce Luo
DJI Dev Team

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/30442'>Zendesk ticket #30442</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I'm here just inform you that this issue will be fixed in the next v4.12 version.
I can't give you the exact date and please pay attention to the official release.

Thanks,

Luce Luo
DJI Dev Team

**Comment by brien-crean** [comment]
@dji-dev Thanks for the update Luce, this will help a lot! I will keep an eye out for that release. Thanks again

**Comment by brien-crean** [comment]
Can confirm that stopFetchingFileData works in 4.13.1.

However the currently downloading file in the `DownloadListener` callback of `fetchFileData` is not available in `onProgress` (reads as 0 bytes), it is only available in `onSuccess`, by which point the entire file has already been downloaded making stopFetchingFileData useless for retrieving the metadata tag. Once 4.14 is stable I will try the new function `fetchFileByteData` and see if that is an alternative
