### ISSUE TITLE
Panorama support on Mavic Pro and Phantom 4 Pro

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-Android#473]
It seems to be unclear which products support the use of PanoramaMissionOperator from the documentation. When I attempt to get the state of the PanoramaMissionOperator with a Mavic Pro, I get a PanoramaMissionState of **DISCONNECTED**. Is it possible to clarify which products support PanoramaMissionOperator please?

Many thanks!

The MSDK version is 4.11.1
I am using a Mavic Pro running firmware version 01.04.0500

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/31930'>Zendesk ticket #31930</a>:<br><br>Hi. I am sorry to tell you that the PanoramaMissionOperator is only available for OSMO series. It doesn't support Mavic pro.

**Comment by brien-crean** [comment]
@dji-dev Thanks so much for your quick reply. Is there any other way of capturing a panorama? I have tried to use a waypoint mission. However with the phantom 4 pro for example it has a known issue where photos are dropped. This is in the SDK release documentation:

> [OLD]Photo shot miss during waypoint mission: Shoot photo action doesn't work when attempted
> during a waypoint mission for M200 series and Phantom 4 Pro. This issue will be addressed by the
> future firmware.

**Comment by dji-dev** [comment]
Public comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/31930'>Zendesk ticket #31930</a>:<br><br>Hi. Please refer to this iOS demo https://developer.dji.com/mobile-sdk/documentation/ios-tutorials/PanoDemo.html. It shows how to create a panorama application.

**Comment by brien-crean** [comment]
Thanks so much @dji-dev I ended up creating a timeline mission for the phantom 4 and a waypoint mission for the Mavic (as timeline had some timeout errors on the mavic for some reason) - closing this issue
