### ISSUE TITLE
DJI Flight Simulator support

### ISSUE THREAD

**Issue by elgalu** [dji-sdk/Mobile-SDK-Android#475]
Is it possible to use this SDK to control the drones running inside the DJI Flight Simulator?

**Comment by kenargo** [comment]
Yes, that is the intention of the simulator,  to test before flying for real. 

⁣Get BlueMail for Android ​

**Comment by elgalu** [comment]
With just the SDK? because the Simulator docs only seem to mention using the physical joystick to control the simulator but I'm looking for a fully autonomous flying experience that want to first train on the simulator, no human nor joystick in the loop, just software to software. Any docs?

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32040'>Zendesk ticket #32040</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that the SDK doesn't support to control the drone intention of the DJI Flight Simulator.

If you want to test before a real fly with SDK, it's recommended to use the Assistant 's simulator.
https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-testing.html#aircraft-simulator

Thanks,

Luce Luo
DJI Dev Team

**Comment by kenargo** [comment]
You can use the SDK to enter simulation mode and then use the sim.

Yes,  the DJI Assist is easier. 

⁣Get BlueMail for Android ​

**Comment by elgalu** [comment]
thanks!!
