### ISSUE TITLE
Zoom not supported on Mavic 2 Zoom

### ISSUE THREAD

**Issue by tobiasfriden** [dji-sdk/Mobile-SDK-Android#478]
Hello,

I am trying to set optical zoom on a Mavic 2 Zoom which  I recently purchased through the Mobile SDK. The optical zoom feature is very important for our usecase and is one reason why we purchased the Zoom version instead of pro.

I can set the optimal zoom through the DJI Go app in the smart controller. However, both
```java
mProduct.getCamera().isDigitalZoomSupported();
mProduct.getCamera().isOpticalZoomSupported()
```
return false. I have also tried calling 
```java
mProduct.getCamera().startContinuousOpticalZoom(
                    SettingsDefinitions.ZoomDirection.ZOOM_IN,
                    SettingsDefinitions.ZoomSpeed.NORMAL,
                    null);
```
and 
```java
mProduct.getCamera().setOpticalZoomFocalLength(420, null);
```
but nothing is happening. If i attach a callback then the error "Feature not supported" is reported in the `DJIError`.

I am using Mobile SDK version `4.11.1`. Any help or suggestions greatly appreciated!

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/32153'>Zendesk ticket #32153</a>:<br><br>In 4.11 MSDK release Hybrid Zoom was introduced for the Mavic 2 Zoom and Mavic 2 Enterprise Camera that replace the digital and optical zoom APIs

1. Release Notes: https://developer.dji.com/mobile-sdk/downloads/
2. Hybrid Zoom APIs: https://developer.dji.com/api-reference/android-api/Components/Camera/DJICamera.html#djicamera_camerasettings_ishybridzoomsupported_inline



Lisa Fedane
DJI Developer Support

**Comment by tobiasfriden** [comment]
> Public comment from Lisa Fedane in [Zendesk ticket #32153](https://djisdksupport.zendesk.com/agent/tickets/32153):
> 
> In 4.11 MSDK release Hybrid Zoom was introduced for the Mavic 2 Zoom and Mavic 2 Enterprise Camera that replace the digital and optical zoom APIs
> 
> 1. Release Notes: https://developer.dji.com/mobile-sdk/downloads/
> 2. Hybrid Zoom APIs: https://developer.dji.com/api-reference/android-api/Components/Camera/DJICamera.html#djicamera_camerasettings_ishybridzoomsupported_inline
> 
> Lisa Fedane
> DJI Developer Support

Aha, thanks for the quick reply!
