### ISSUE TITLE
A mistake in MOBILE SDK DJI Simulator Tutorial

### ISSUE THREAD

**Issue by JacobleeDJI** [dji-sdk/Mobile-SDK-Android#48]
#### Is this issue about bugs or crash issues of DJI Android SDK and Sample Code?

In MOBILE SDK DJI Simulator Tutorial - Buidling the Layouts of Activity,
step1 : Creating DJISimulatorApplication Class,
There is a mistake:"Next, Replace the code of the "FPVDemoApplication.java" file with the following.",
 I think FPVDemoApplication.java should Change to
"DJISimulatorApplication.java"

**Comment by oliverou** [comment]
Hi @JacobleeDJI , thanks for your feedback. The issue is fixed now. Please refresh the website and check again.
