### ISSUE TITLE
setUplinkSignalQualityCallback

### ISSUE THREAD

**Issue by MitchellMonaghan** [dji-sdk/Mobile-SDK-Android#480]
setUplinkSignalQualityCallback seems to not be firing events all other status data seems to work fine (battery, etc)

I get a one time single event of 100 percent and then never anything else ever again.

Not much of a java dev let me know what other info you need. As I know this isn't much to go off of.

dji sdk 4.11
Mavic Pro Platinum
Android 10
AndroidX

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32212'>Zendesk ticket #32212</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
This callback method 'setUplinkSignalQualityCallback' will be updated when the signal quality changed.
You can do a test that makes the Remote Controller be far away from the drone and it will be updated.

Thanks,

Luce Luo
DJI Dev Team

**Comment by MitchellMonaghan** [comment]
Thank you this would be great to add to the documentation as I didn't see it say when the event was fired.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32212'>Zendesk ticket #32212</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry about this and thanks for your advice.

Thanks,

Luce Luo
DJI Dev Team
