### ISSUE TITLE
Sample SDK cannot connect to Osmo mobile 3

### ISSUE THREAD

**Issue by eam38** [dji-sdk/Mobile-SDK-Android#483]
Hi,
I just built and run the Sample SDK app on Android and tried to connect to the osmo mobile 3 through Bluetooth but it doesn't appear in device list.

I tested the sample app on Galaxy s5 and Oneplus 5. same issue on both. 

I can see the osmo mobile on Dji mimo app.

Thank you for your help.

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/32280'>Zendesk ticket #32280</a>:<br><br>Unfortunately, the Mobile SDK does not currently support the Osmo Mobile 3 - for a full listing of what products are supported please navigate here: https://developer.dji.com/products/#!/mobile

Lisa Fedane
DJI Developer Support

**Comment by Flavelius** [comment]
Will that be possible in the future?

**Comment by zsinba** [comment]
the same question.
