### ISSUE TITLE
Mavic2 行业版带屏遥控器拍照按键适配

### ISSUE THREAD

**Issue by antman-s** [dji-sdk/Mobile-SDK-Android#484]
大疆的开发人员，您好：
    在适配Mavic2 行业版带屏遥控器时发现拍照、录像按钮点击无效，正常遥控器已适配两个按键事件，请问带屏遥控器如何适配？适配代码如下：
KeyListener recordListener = new KeyListener<HardwareState.Button>(){
//todo...录像实现
};
DJISDKManager.getInstance().getKeyManager().addListener(RemoteControllerKey.create(RemoteControllerKey.RECORD_BUTTON), shutterListener);

**Comment by Jim-DJI** [comment]
@johnchenn 您好，请问您这边使用的MSDK版本号是多少？能否提供一下，谢谢。
MSDK v4.11版本已经解决“Mavic2 行业版带屏遥控器时发现拍照、录像按钮点击无效”，
而且您可以在通过setShutterButtonBindingEnabled接口和setRecordButtonBindingEnabled 接口实现自定义设置遥控器拍照/录像按键是否打开。MSDK v4.11是默认打开。接口文档链接如下：https://developer.dji.com/api-reference/android-api/Components/RemoteController/DJIRemoteController.html?search=setshutterbuttonbindingenabled&i=0&#djiremotecontroller_setshutterbuttonbindingenabled_inline和https://developer.dji.com/api-reference/android-api/Components/RemoteController/DJIRemoteController.html?search=setrecordbuttonbindingenabled&i=0&#djiremotecontroller_setrecordbuttonbindingenabled_inline

**Comment by johnchenn** [comment]
@Jim-DJI MSDK 4.11.1 遥控器型号RM500，调用get、set方法报错Not supported
// DJI SDK
    implementation('com.dji:dji-uxsdk:4.11.1', {

    })
    compileOnly 'com.dji:dji-sdk-provided:4.11.1'

**Comment by PanGuangwei** [comment]
带屏控好像要在系统设置里把一个防止误操作的开关给关掉才能在piolt关掉的情况下按旁边的两个按钮

**Comment by Jim-DJI** [comment]
@johnchenn 您好，您反馈的问题已经修复，会在MSDK下个版本支持，请关注一下MSDK版本更新，谢谢

**Comment by DJI-William** [comment]
最新版本4.15的带屏控不需要设置任何函数，只需要去设置的防止误操作设置关闭，拍照和录像按键就起作用了。
