### ISSUE TITLE
在demo中的Live Stream支持rtmp推流，请问官方sdk支持rtsp推流吗？

### ISSUE THREAD

**Issue by beerjtu** [dji-sdk/Mobile-SDK-Android#487]
在demo中的Live Stream支持rtmp推流，请问官方sdk支持rtsp推流吗？

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32517'>Zendesk ticket #32517</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，MSDK暂不支持rtsp推流。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
