### ISSUE TITLE
LiveStreamManager不支持在后台推流吗？

### ISSUE THREAD

**Issue by beerjtu** [dji-sdk/Mobile-SDK-Android#493]
使用Demo中live stream来推流，按back键返回，rtmp流就断了（但是后台还是一直有日志）。使用官方的DJI Polit来推流，退出当前界面，也会使得推流中断。请问SDK能不能支持在活动跳转后，还能继续推流？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/32924'>Zendesk ticket #32924</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

非常抱歉，目前直播推流不支持后台推流。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
