### ISSUE TITLE
APP crash on SDK 4.11.2

### ISSUE THREAD

**Issue by keivanh** [dji-sdk/Mobile-SDK-Android#496]
Upgrading from 4.11.1 to 4.11.2, cause app crash on launch.

Logcat:

`java.lang.UnsatisfiedLinkError: No implementation found for void com.dji.megatronking.stringfog.StringUtilsJNI.test() (tried Java_com_dji_megatronking_stringfog_StringUtilsJNI_test and Java_com_dji_megatronking_stringfog_StringUtilsJNI_test__)
        at com.dji.megatronking.stringfog.StringUtilsJNI.test(Native Method)
        at com.dji.megatronking.stringfog.lib.Base64Fog.a(Unknown Source:3)
        at com.dji.megatronking.stringfog.lib.Base64Fog.a(Unknown Source:5)
        at dji.sdk.sdkmanager.DJISDKManager.<clinit>(Unknown Source:2)
        at dji.sdk.sdkmanager.DJISDKManager.getInstance(Unknown Source:0)
        at com.xxx.xxxx.MainActivity$6.run(MainActivity.java:401)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
`

Android target SDK 28 and 29
compileSdkVersion 29

Device:
Samsung S8 - SDK 28 - Android 9
Huawei P30 - SDK 29 - Android 10

**Comment by kenargo** [comment]
It sounds like you may have missed something in the build.gradle.

 

I made the changes in build.gradle and it worked fine.

 

Note: there are 2 places to update the DJI library version (assuming you are also using the UX library). And there is a change in the NDK, abifilters

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/33019'>Zendesk ticket #33019</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Please check and refer to the official configuration if any detail missing.
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle

Thanks,

Luce Luo
DJI Dev Team

**Comment by Jai-GAY** [comment]
why classpath 'com.android.tools.build:gradle:3.4.1' [reduced to 3.2.1](https://github.com/dji-sdk/Mobile-SDK-Android/blob/b2e23a3b96b0a9799eea752403a4ca6b4615533b/Sample%20Code/build.gradle#L9) for [4.11.2 release](https://github.com/dji-sdk/Mobile-SDK-Android/releases/tag/v4.11.2)?

**Comment by Jai-GAY** [comment]
Is this [key free for all developers](https://github.com/dji-sdk/Mobile-SDK-Android/blob/b2e23a3b96b0a9799eea752403a4ca6b4615533b/Sample%20Code/app/src/main/AndroidManifest.xml#L46) to use?

**Comment by Jai-GAY** [comment]
Why is this [line of code look](https://github.com/dji-sdk/Mobile-SDK-Android/blob/b2e23a3b96b0a9799eea752403a4ca6b4615533b/Sample%20Code/app/src/main/java/com/dji/sdk/sample/internal/controller/ExpandableListAdapter.java#L149) so funny?

**Comment by Ray-DJI** [comment]
@Jai-GAY  The key is a deprecated key used by test, it can not be used by anybody, please ignore it, and we already delete it, thanks for the feedback.

**Comment by keivanh** [comment]
Clean project was not enough, it fixed after I manually delete all Java and NDK build directories from project.

I can confirm version 4.11.2 is the very first one can work on Android 10.
