### ISSUE TITLE
Drone stops after taking off when executing timeline mission

### ISSUE THREAD

**Issue by ohaujingjing** [dji-sdk/Mobile-SDK-Android#497]
I've add TakeOffAction, then GoToAction in timeline mission, but after I start timeline mission, the drone stops after taking off and not execute goto action, anyone have met the same problem?
I seem to found a solution for this problem. That once I add listener to missioncontrol, this problem happens, but once I dont add listener, the timeline mission execute well.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/33041'>Zendesk ticket #33041</a>:<br><br>Dear Client
Thank you for contacting DJI.

Hi, we thought the problem may occur in timeline mission, please refer to our example.
Refer: https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/timeline/TimelineMissionControlView.java

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by ohaujingjing** [comment]
> Agent comment from William Wong in [Zendesk ticket #33041](https://djisdksupport.zendesk.com/agent/tickets/33041):
> 
> Dear Client
> Thank you for contacting DJI.
> 
> Hi, we thought the problem may occur in timeline mission, please refer to our example.
> Refer: https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/timeline/TimelineMissionControlView.java
> 
> Hopefully our solution can help you.
> Kindly Regards,
> DJI Developer Support

Thank you, I've solved my problem, there's something wrong with my code.
