### ISSUE TITLE
MSX_LEVEL

### ISSUE THREAD

**Issue by flythecode** [dji-sdk/Mobile-SDK-Android#498]
private void setCameraDisplayMode(SettingsDefinitions.DisplayMode displayMode) {
    KeyManager.getInstance().setValue(CameraKey.create(CameraKey.DISPLAY_MODE, THERM), displayMode, null);
    KeyManager.getInstance().setValue(CameraKey.create(CameraKey.MSX_LEVEL),100,null);
}

**Comment by Michael-DJI** [comment]
@flythecode were you using 4.11.2? and what the firmware version of your Mavic 2 Dual drone?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/33064'>Zendesk ticket #33064</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team

**Comment by flythecode** [comment]
KeyManager.getInstance().setValue(CameraKey.create(CameraKey.MSX_LEVEL),50,null);
This was promised over 4 months ago to be fixed. I have several tickets with Romeo and List. Still Nothing!

**Comment by Ray-DJI** [comment]
@flythecode We tested the interface on Mavic 2 Enterprise with firmware version 01.01.06.04, and also the remote controller version is 01.01.0401, it works well. This feature have supported for the Mavic 2 Enterprise since 4.11.2, please check again, thanks.

**Comment by Michael-DJI** [comment]
@flythecode thank you for your feedback! as Ray mentioned we have support this feature in 4.11.2, could you please double check your code? or if you need some sample code for this feature , please let me know. thanks.

**Comment by flythecode** [comment]
if you want to make a sample I'll try it. KeyManager.getInstance().setValue(CameraKey.create(CameraKey.MSX_LEVEL),100,null);

**Comment by Michael-DJI** [comment]
please refer to https://github.com/dji-sdk/Mobile-SDK-Android/issues/517#issuecomment-624983138
