### ISSUE TITLE
ClassNotFoundException: DataBatteryActiveStatus

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#5]
I keep getting the exception below, and I don't seem to find `DataBatteryActiveStatus` in the jar files coming with the SDK. Where is it supposed to be?

java.lang.ClassNotFoundException: dji.midware.data.model.P3.DataBatteryActiveStatus
W/System.err﹕ at java.lang.Class.classForName(Native Method)
W/System.err﹕ at java.lang.Class.forName(Class.java:251)
W/System.err﹕ at java.lang.Class.forName(Class.java:216)
W/System.err﹕ at dji.midware.data.manager.P3.g.a(Unknown Source)
W/System.err﹕ at dji.midware.data.manager.P3.g.d(Unknown Source)
W/System.err﹕ at
dji.midware.usb.P3.UsbAccessoryService$ParseOsdRunnable.run(Unknown Source)
W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
W/System.err﹕ Caused by: java.lang.NoClassDefFoundError:
dji/midware/data/model/P3/DataBatteryActiveStatus
W/System.err﹕ ... 7 more
W/System.err﹕ Caused by: java.lang.ClassNotFoundException: Didn't
find class "dji.midware.data.model.P3.DataBatteryActiveStatus" on path: DexPathList[[zip file
"<package>.apk", zip file
"<package>/code_cache/secondary-dexes/<package>.apk.classes2.zip"],nativeLibraryDirectories=[<package>,
/vendor/lib, /system/lib]]
W/System.err﹕ at
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
W/System.err﹕ at
java.lang.ClassLoader.loadClass(ClassLoader.java:497)
W/System.err﹕ at
java.lang.ClassLoader.loadClass(ClassLoader.java:457)
W/System.err﹕ ... 7 more

**Comment by SilverChangjian** [comment]
The DataBatteryActiveStatus class is also obfuscated. If you need this functionality, could you please provide the application scenarios for us? Our product manager will review it and this might become a new functionality for next version.

**Comment by JonasVautherin** [comment]
We don't use it __at all__. The SDK is sending us this error every few seconds. It looks like something is trying to access DataBatteryActiveStatus internally and does not find it (supposedly because it is obfuscated).

So it looks like a bug on the SDK's side.

**Comment by SilverChangjian** [comment]
Sorry, my mistake. The reason why this error occurs is that the battery is not activated and pushing data for notifying the DJi Go App to activate it. For the SDK, some internal classes (like DataBatteryActiveStatus) are obfuscated. And that's why the error type is ClassNotFoundException. For solving this problem, I suggest you could use the DJI Go App to activate the batter (just open the DJI Go App and it will do it automatically). Then there will no data for battery's activation notification.

Thanks for reporting bugs. We will go through all the corner case for using the SDK. 

Best wishes

**Comment by Dmitrij** [comment]
It didn't solved by opening DJI GO application. we still have same error occurring every second.

**Comment by JonasVautherin** [comment]
Do you happen to have any news about that problem?

**Comment by SilverChangjian** [comment]
There will be a 2.4.1 version for this problem. I will be solved in that version

**Comment by JonasVautherin** [comment]
Disappeared in 2.4.1. Thanks!
