### ISSUE TITLE
Tremendous amount of logs from the DJI SDK

### ISSUE THREAD

**Issue by Nitaym** [dji-sdk/Mobile-SDK-Android#50]
I get a million log messages when using the DJI SDK. I get that logging is important, but I'm not debugging the DJI SDK here, I'm debugging my own apps.
Also, a lot of messages do not make it into the log (chatty "expire" messages)

Could you please add a way to turn off log messages from the SDK?

Using version 3.4.1

**Comment by oliverou** [comment]
Hi @Nitaym, we have just launched the new Android SDK 3.4.1, please try it and check if the issue still exists, thanks!

**Comment by Nitaym** [comment]
Was using 3.4.1 - Edited the first comment

**Comment by oliverou** [comment]
Hi @Nitaym, thanks for your feedback! We will fix this issue in our next Android SDK version, for now, we provide a workaround for you:

Please add your own tag in your debug logs code, like this `Log.v("YourTag", "Log message")`, then type in "YourTag" in the search box as shown below:

![500k 6r u8lwz0g1hn2 re](https://cloud.githubusercontent.com/assets/13310805/20421509/59b8734a-ad9f-11e6-8d28-022b9fe597f2.png)

Then, it should filter all the SDK logs and only shows your debug logs. Hope this help!

**Comment by Nitaym** [comment]
Hi @oliverou, Thanks for taking the time to review this.

While that's a good workaround for small apps, larger apps with several components and several log tags usually need a more complicated a log filter. Also, many times you need to see android logs external to your app components (android system logs, external services, etc). So a positive filter isn't quite an option here.

For now I've used regex to filter out the SDK, but since DJI uses many tags the regex is long and complicated (and misses some things, especially the multiline messages). I'm afraid I didn't keep a copy of it but it was something along these lines:
`(^(?!.*DJIVersionBaseComponent))(^(?!.*UsbAccessoryService))(^(?!.*DJIComponentManager))(^(?!.*DJIVersionRC))`

(Just add more (^(?!.*TAG)) with the tags you want to filter out)

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
