### ISSUE TITLE
flightController.setStateCallback回调不执行

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#508]
设备：御2
msdk: 4.11.2
uxsdk: 4.11.2
手机: 安卓10, api 29
发现 
flightController.setStateCallback，
product.getBattery().setStateCallback，
product.getGimbal().setStateCallback，
remoteController.setGPSDataCallback
这几个回调都没有执行，不知道是哪里出了问题，代码是照抄msdk示例。SDK注册都是成功的。
换dji-go-4程序, 地图上能正确显示飞机位置，再换自己app还是不行，一次都没回调。

请问这是为什么，是不是还有什么开关没打开？

**Comment by Michael-DJI** [comment]
@addriumruss 状态变化才会回调，另外注意时序，必须等注册成功 且 连接到飞机之后再去调用各种setStateCallback

**Comment by addriumruss** [comment]
我是在SDK注册成功之后，开始获取flightcontroller, 注册回调，拿着小飞机也走动了，
为什么还是不行，是不是要等一段时间才行, 还是说我必须起一个守护线程定时盯着它?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/33950'>Zendesk ticket #33950</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

建议您不要拿着飞机走动测试，而是链接到Assistant 2里打开Simulator进行飞行测试。registerApp后回调函数里有onProductConnect，当这个函数回调后飞机才算是正式连上。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
原来最终是onProductConnect，我的业务启动代码放在了onRegister，难怪不行。
弄清楚了，非常感谢~

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/33950'>Zendesk ticket #33950</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

是的onRegister只是SDK联网鉴权通过，接下来就要链接飞机了，所以要等到onProductConnect。不客气，祝您开发顺利，后续还有问题欢迎来信咨询。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
