### ISSUE TITLE
请问msdk怎么悬停飞机, 怎么紧急坠毁飞机， 谢谢!

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#510]
设备：御2专业版
msdk: 4.11.2
手机: 安卓10, api29
问题：
希望通过msdk控制飞机立即悬停以及紧急坠毁。但是没找到具体接口函数。
麻烦指导，非常感谢!

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34033'>Zendesk ticket #34033</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

控制飞机悬停需要从飞控中输入新的飞行数据，并且把所有油门降为0，通过sendVirtualStickFlightControlData函数设置。如果要紧急坠毁，那么可以从空中紧急停车，也就是停止马达转动。可以通过调用setUrgentStopModeEnabled，然后把双杆打内八或者外八就可以空中停车，飞机就会坠毁了，但是这个功能只支持P4 RTK。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
@dji-dev 感谢支持！
关于悬停，还是有点模糊，请问有没有示例代码?
关于紧急坠毁，是希望完全通过msdk远程操作，最好不需要遥控器协助，麻烦再找找解决方法。
谢谢!

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34033'>Zendesk ticket #34033</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

您好，并没有示例代码。这个逻辑很简单，遥控器上有很多摇杆，不对任何摇杆进行操作，无人机就会悬停。sendVirtualStickFlightControlData函数就是发送虚拟摇杆指令。其参数为FlightControlData，在调用其构造函数的时候参数都设为0即可。
API文档链接：https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html?search=sendvirtualstickflightcontroldata&i=0&#djiflightcontroller_virtualstickcontrolmodecategory_sendvirtualstickflightcontroldata_inline

紧急坠毁，除了上面这个办法没有其他办法了。并且御2行业版也不支持紧急坠毁的功能。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
收到，感谢支持！ 
我先试试看，有疑问再来请教。
