### ISSUE TITLE
请问WaypointActionType.START_TAKE_PHOTO怎么停止?

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#512]
设备：御2专业版
msdk: 4.11.2
手机: 安卓10, api29
问题：
通过msdk指定一个位置点的属性时，可以设置WaypointActionType.START_TAKE_PHOTO让飞机自动拍照。 
疑问点: 
1, 这个自动拍照是一直持续下去，还是只执行一次？ 
2, 如果是一直持续下去，什么时候停止，哪个接口可以停止它？
3, 这个照片能不能通过msdk下载?  

麻烦指导，谢谢!

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34040'>Zendesk ticket #34040</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

WaypointActionType.START_TAKE_PHOTO只在航点任务中的航点生效，只拍摄一张。等航点任务全部结束以后可以通过MediaManager Class去下载。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
收到  我试试
