### ISSUE TITLE
Cannot exclude distortion-correction and fly-safe-database libraries

### ISSUE THREAD

**Issue by Padreco-lbr** [dji-sdk/Mobile-SDK-Android#513]
Commands on application build.gradle to exclude the mentioned libraries doesn't work.
Libraries are still taking up space on the compiled apk at folder assets/expansion/internal after uncommenting the 'exclude' sentences.

It currently corresponds to almost 40% of my app's size (~40mb), so please provide a fix for it.

Steps to reproduce:
- Uncomment
```
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'
```
- Build the sample code and check the resulting APK file structure

PS: Updated to reflect actual repository file instead of my other attempts

**Comment by kenargo** [comment]
Try this

 

implementation('com.dji:dji-uxsdk:4.11.2', {
    /**
     * Uncomment the "library-anti-distortion" if your app does not need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom.
     * Uncomment the "fly-safe-database" if you need database for release, or we will download it when DJISDKManager.getInstance().registerApp
     * is called.
     * Both will greatly reducing the size of the APK.
     */
    exclude module: 'library-anti-distortion'
    exclude module: 'fly-safe-database'

    // Remember to exclude AMAP of the Play Store will remove the app
    exclude group: 'com.amap.api'
})
compileOnly('com.dji:dji-sdk-provided:4.11.2')

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34045'>Zendesk ticket #34045</a>:<br><br>Dear Client
Thank you for contacting DJI.

You can exclude other libraries if you want by looking on Maven repo. But excluding lib may cause fatal error, so please be careful with that.
Link: https://mvnrepository.com/artifact/com.dji

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by Padreco-lbr** [comment]
> Try this implementation('com.dji:dji-uxsdk:4.11.2', { /** * Uncomment the "library-anti-distortion" if your app does not need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom. * Uncomment the "fly-safe-database" if you need database for release, or we will download it when DJISDKManager.getInstance().registerApp * is called. * Both will greatly reducing the size of the APK. */ exclude module: 'library-anti-distortion' exclude module: 'fly-safe-database' // Remember to exclude AMAP of the Play Store will remove the app exclude group: 'com.amap.api' }) compileOnly('com.dji:dji-sdk-provided:4.11.2') ...

Thanks for the reply, but as you can see from the apk file structure, it didn't solve the problem:
![image](https://user-images.githubusercontent.com/23504838/80709799-4ee3da80-8ac4-11ea-877e-d533d0123c02.png)


> Agent comment from William Wong in [Zendesk ticket #34045](https://djisdksupport.zendesk.com/agent/tickets/34045):
> 
> Dear Client
> Thank you for contacting DJI.
> 
> You can exclude other libraries if you want by looking on Maven repo. But excluding lib may cause fatal error, so please be careful with that.

This is not a solution, I am not asking to exclude other libraries, but to effectively see the result of this comment on your sample code's app/buid.gradle:
>/** * Uncomment the "library-anti-distortion" if your app does not need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom. * Uncomment the "fly-safe-database" if you need database for release, or we will download it when DJISDKManager.getInstance().registerApp * is called. * Both will greatly reducing the size of the APK. */

**Comment by sugudrones** [comment]
this helped in my case
```
 implementation ("com.dji:dji-uxsdk:4.11.2", {
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'
        exclude group: 'com.amap.api'
    })
    implementation ("com.dji:dji-sdk:4.11.2",{
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'
    })
    compileOnly ("com.dji:dji-sdk-provided:4.11.2",{
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'
    })
```

**Comment by Padreco-lbr** [comment]
Managed to make it work, the only way is adding exclusions to usx-sdk as well, for some reason:
```
api("com.dji:dji-uxsdk:$djiSdkVersion", {
    exclude module: 'library-anti-distortion'  
    exclude module: 'fly-safe-database'
})
api("com.dji:dji-sdk:$djiSdkVersion", {
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'
})
```

**Comment by kenargo** [comment]
You are using ’api’ annotation, you should be using the following.  I tested and excluding vs not and as shown below the apk size was less by 65 MB with the exclusions than without.

 

implementation ('com.dji:dji-uxsdk:4.13', {

    /**

     * Comment the "library-anti-distortion" if your app does need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom.

     * Comment the "fly-safe-database" if you do not need database for release, or we will download it when DJISDKManager.getInstance().registerApp

     * is called.

     * Both will greatly reducing the size of the APK.

     */

    exclude module: 'library-anti-distortion'

    exclude module: 'fly-safe-database'

 

    /**

     * Uncomment the following line to exclude amap from the app.

     * Note that Google Play Store does not allow APKs that include this library.

     */

    // exclude group: 'com.amap.api'

})

compileOnly ('com.dji:dji-sdk-provided:4.13')

**Comment by Padreco-lbr** [comment]
There's no problem with using api notation, I do so because I centralize my dependencies on a core module.
The problem was that the exclusion is required on the **UX-SDK** as well.
