### ISSUE TITLE
请问是否有 Android 版的 DJI GS PRO？

### ISSUE THREAD

**Issue by rangerzhou** [dji-sdk/Mobile-SDK-Android#514]
你好，在 DJI GS PRO 下载页面 https://www.dji.com/ground-station-pro/info#downloads 只有 ISO 客户端 APP， 请问是否有 Android 版本的呢？代码是否有开源呢？谢谢

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/34064'>Zendesk ticket #34064</a>:<br><br>您好 GS PRO的问题请联系 support@dji.com 。

**Comment by Michael-DJI** [comment]
@rangerzhou 没有，Android版本的行业官方App是DJI Pilot

**Comment by rangerzhou** [comment]
@Michael-DJI  知道了，谢谢
