### ISSUE TITLE
怎么获取PreFlightStatus

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#515]
设备：御2专业版, m600, m210
msdk: 4.11.2
手机: 安卓10, api29
问题：
看到uxsdk中的PreFlightStatusWidget能够显示未连接、准备起飞(视觉模式)、准备起飞(GPS)等状态，但是很不准，有时候明明有连接却显示无连接，所以想放个textview获取数据自己显示，不用这个控件。 
疑问点: 
怎么获取preflightstatus?

麻烦指导，谢谢!

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/34068'>Zendesk ticket #34068</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
可以通过如下key获取：

    DiagnosticsKey._PRE_FLIGHT_STATUS_


非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
@siddutgikar 你好 问题没解决， 获取DiagnosticsKey.PRE_FLIGHT_STATUS只是显示个"PRE_FLIGHT_STATUS", 而下划线版DiagnosticsKey._PRE_FLIGHT_STATUS_根本不存在。
我要的是动态的"视觉模式"、"GPS"这些状态值, 而不是状态标签。
麻烦再帮忙找个办法 谢谢

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/34068'>Zendesk ticket #34068</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，确实是PRE_FLIGHT_STATUS key，可能是系统转码导致的显示格式错误。

我要的是动态的"视觉模式"、"GPS"这些状态值, 而不是状态标签。
-->客服这边为您找到getFlightMode方法，您检查下是否是您需要的。
 ![](https://djisdksupport.zendesk.com/attachments/token/dC0QGUJL7Ybhp7qMXIbVXAV0o/?name=inline2137018693.png)​

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/dC0QGUJL7Ybhp7qMXIbVXAV0o' target='zd_attach'>inline2137018693.png</a>

**Comment by addriumruss** [comment]
收到  非常感谢~  flightmode应该可以用
