### ISSUE TITLE
Cannot take photos with shutter button on smart controller

### ISSUE THREAD

**Issue by tobiasfriden** [dji-sdk/Mobile-SDK-Android#516]
Hello,

I am building an app using mobile SDK for Smart controller with Mavic 2 Zoom. However, I have some large issues with getting the camera to trigger when pushing the shutter button on the controller.

I have tried two approaches:
Calling the `remoteController.setShutterButtonBindingEnabled(true)` but this returns the error "not supported.
Listening to the `HardwareStateCallback` of the remotecontroller, but this doesn't trigger when the shutter button is clicked.

This is a show stopper for my app so any help would be appreciated.

**Comment by flythecode** [comment]
Smart Controller?

**Comment by tobiasfriden** [comment]
Yes, the controller with integrated android device for Mavic 2:s
https://www.dji.com/se/smart-controller

**Comment by Michael-DJI** [comment]
@flythecode what's the version of MSDK you were using?

**Comment by flythecode** [comment]
@tobiasfriden try to change the setting of the camera lock button in the setup menu, I think it caused me a problem.

**Comment by tobiasfriden** [comment]
@flythecode this resolved the issue, thanks!

**Comment by ge17779** [comment]
Hello, I have the same problem here. Can you explain to me how you managed to solve it?

**Comment by Sugar666666tang** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到。
