### ISSUE TITLE
setMSXLevel its not supported in firmware 1.01.0640

### ISSUE THREAD

**Issue by mgrova** [dji-sdk/Mobile-SDK-Android#517]
Hello !
I'm trying to change the MSX level in the camera of the Mavic Enteprise 2 Dual but the DJIerror return that is not supported.
The firmware's version is higher than 01.01.0520.

Any suggestion to fix this error?

Thanks in advance !

**Comment by Michael-DJI** [comment]
@mgrova could you please show your code?

**Comment by mgrova** [comment]
Of course !
```
final BaseProduct product = VideoDecodingApplication.getProductInstance();
mCamera = product.getCameras().get(1);

mCamera.setDisplayMode(SettingsDefinitions.DisplayMode.MSX, new CommonCallbacks.CompletionCallback() {
                            @Override
                            public void onResult(DJIError error) {
                                if (error == null) {
                                    showToast("Switch to MSX Succeeded");
                                } else {
                                    showToast(error.getDescription());
                                }
                            }
                        });

mCamera.setMSXLevel(mSValMSX, new CommonCallbacks.CompletionCallback() {
@Override
public void onResult(DJIError djiError) {
    if (djiError == null) {
         showToast("Set MSX Level");
     } else {
         showToast(djiError.getDescription());
     }
}
});
```
in this code mSValMSX is the uint_8 that I want use to change the MSX level.

**Comment by Michael-DJI** [comment]
please check what' s the display name of this camera:
mCamera = product.getCameras().get(1);

**Comment by mgrova** [comment]
when I get the camera 1, the metod "isThermal()" returns true.

Besides that, the toast "Switch to MSX Succeded" appears. But after that, is shown the toast with error.getDescription() that I guess comes from setMSXLevel method.

Thanks in advance!

**Comment by Michael-DJI** [comment]
@mgrova try to sleep 2 seconds before setMSXLevel()

**Comment by manuoso** [comment]
Hello, we have put the sleep for 4 seconds and the result is the same. The viewer shows how it switches to MSX mode but the setMSXLevel method does not work. The error it gives is that it is not supported.
I checked the version several times and it is higher that appears in the documentation to use this function.
On the other hand, in the official app I can vary this value. Surely it is that it is necessary to activate some other option apart from switching to MSX mode to use the method of changing the MSX Level.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34209'>Zendesk ticket #34209</a>:<br><br>Dear Client
Thank you for contacting DJI.

Hi, what is your sdk version, I think this issue has been fixed in 4.11.2. Maybe try to update your sdk version to the lateast version.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by manuoso** [comment]
Ah! it was that. Thanks it is already fixed, I have updated the version of the SDK. Thanks for everything!

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34209'>Zendesk ticket #34209</a>:<br><br>Dear Client
Thank you for contacting DJI.

It is really nice to hear that you have solved your problem, good luck for your further development and feel free to come to us if you encounter any problems.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by Michael-DJI** [comment]
@manuoso
