### ISSUE TITLE
How to measure wind velocity and direction

### ISSUE THREAD

**Issue by leonjke** [dji-sdk/Mobile-SDK-Android#518]
Hello!
I am studying the documentation for the Mobile SDK. I need to get the direction of the wind and its velocity. Is it possible to get wind direction and speed data through the DJI Mobile API? I can't find it anywhere.. 

And there was an idea to determine the velocity and direction of the wind depending on the number of revolutions of the motors. Yes, this is a bad idea. But is it possible to get the number of engine revolutions via DJI Mobile API?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34240'>Zendesk ticket #34240</a>:<br><br>Dear Client
Thank you for contacting DJI.

We dont have any sensors that measure any parameters related to wind and motor revolution. So we have no API that provide those parameters, really sorry.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
