### ISSUE TITLE
请问怎么判断当前是自由飞行还是mission航线飞行状态，谢谢

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#519]
设备: 御2, m210, m600
sdk: msdk 4.11.2
环境: android10
需求： 
mission航线飞行过程中，突发需要定点飞行, 需要判断当前是否处于航线飞行状态。
麻烦帮忙提供个解决方法，
谢谢~

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34259'>Zendesk ticket #34259</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

不太明白您的意思，是突然需要重新定新的航点飞行吗？如果是的话需要终止航点任务重新建立上传执行。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by luoyexk** [comment]
FlightMode里的GPS_WAYPOINT状态应该是你说的航线飞行中

```
val aircraft = DJISDKManager.getInstance().product as Aircraft
aircraft.flightController.setStateCallback{
                if (it.flightMode == FlightMode.GPS_WAYPOINT) {
                    // 航点飞行
                }
            }
```

或者
```
DJISDKManager.getInstance().missionControl.isTimelineRunning
```

**Comment by addriumruss** [comment]
@luoyexk 收到，非常感谢!
@dji-dev 你的支持水平太差，回家多学习吧。
