### ISSUE TITLE
Exception from DJIAnalyticsEvent

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#52]
After upgrading to the 3.4.1 SDK i got all the time this error shown within the log.
So the sdk is working like expected for, so no real bug, but it is completely blowing full my log.

Exception serializeDatadji.internal.analytics.model.DJIAnalyticsEvent cannot be cast to dji.internal.network.DJIAnalyticsEvent

Moreover there are some more logs which are always shown. 
I assume that it is possible to configure the SDK log so i can "debug" my logs and not the logs of the sdk??

Regards

Using: 3.4.1 Android SDK

**Comment by oliverou** [comment]
Hi @xxmaestroxx, thanks for your feedback! We will fix this issue in our next Android SDK version, for now, we provide a workaround for you:

Please add your own tag in your debug logs code, like this `Log.v("YourTag", "Log message")`, then type in "YourTag" in the search box as shown below:

![500k 6r u8lwz0g1hn2 re](https://cloud.githubusercontent.com/assets/13310805/20421532/7ff2781c-ad9f-11e6-802d-bf339d2eb2c1.png)

Then, it should filter all the SDK logs and only shows your debug logs. Hope this help!

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
