### ISSUE TITLE
TimelineElement如何使用4.12重构的Waypint Mission和Waypoint 2.0

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#523]
WaypointV2Mission使用demo没有在该版本中更新，
我想知道目前怎么和`MissionControl.getInstance().scheduleElements`结合使用

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/34355'>Zendesk ticket #34355</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

目前Waypoint2.0只支持M300RTK，如果您的飞机不是的话还是使用之前的WaypointMission。您可以使用elementFromWaypointMission把航点任务变成一个TimelineElement，然后添加到list里面用scheduleElements来调用。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
