### ISSUE TITLE
飞控指南针异常

### ISSUE THREAD

**Issue by dashifuguye** [dji-sdk/Mobile-SDK-Android#525]
设备：M600   
MSDK：4.11.2  
Android 8
问题描述：自己开的发APP，在连接飞机时调用setDiagnosticsInformationCallback函数，回调函数返回8015，代表指南针异常。但此时飞机指示灯为绿灯慢闪，使用DJI GO打开一切正常。拔掉数据线重新连接飞机是无效的，杀掉app重新连接飞机也无效，但重启飞机后显示正常。这个问题最近出了很多次，但不是必现的，请问除了重启飞机的办法，还有没有其他办法可以解决这个问题？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/34618'>Zendesk ticket #34618</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，您可以尝试升级到最新4.12版本再次测试，
如果问题依旧，麻烦填写如下表格补充详细信息与我们再次联系。
https://formcrafts.com/a/dji-developer-feedback-cn

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
> Agent comment from Luce Luo in [Zendesk ticket #34618](https://djisdksupport.zendesk.com/agent/tickets/34618):
> 
> 尊敬的用户，
> 
> 您好！感谢您联系DJI 大疆创新。
> 抱歉，您可以尝试升级到最新4.12版本再次测试，
> 如果问题依旧，麻烦填写如下表格补充详细信息与我们再次联系。
> https://formcrafts.com/a/dji-developer-feedback-cn
> 
> 非常感谢您的理解与配合，祝您生活愉快！
> 
> Best Regards,
> 
> DJI 大疆创新SDK技术支持

请问是升级MSDK还是升级OSDK ?

**Comment by dashifuguye** [comment]
升级MSDK4.12版本后暂时未出现该问题，所以关掉
