### ISSUE TITLE
精灵RTK网络RTK开启后显示连接失败

### ISSUE THREAD

**Issue by braveeric** [dji-sdk/Mobile-SDK-Android#527]
设置回调函数后，开启RTK，设置RTK模式为网络RTK，飞机RTK参数可正确解析刷新，网络RTK状态一直为CONNECTING，已成功引用com.dji:library-networkrtk-helper:2.0.0，当前SDK版本为4.10，请问需要升级为最新的SDK版本还是需要其他的配置，已购买千寻网络RTK服务

**Comment by Jim-DJI** [comment]
您好，对于您的使用场景我们这边会模拟一下定位一下问题。建议将MSDK版本升级到4.12配合使用，4.12内部对rtk做了一些小小优化。谢谢对MSDK的支持

**Comment by braveeric** [comment]
> 您好，对于您的使用场景我们这边会模拟一下定位一下问题。建议将MSDK版本升级到4.12配合使用，4.12内部对rtk做了一些小小优化。谢谢对MSDK的支持

请问开启和大疆账户绑定的网络RTK服务和开启自定义网络RTK服务是同一个api吗？我利用DJISDKManager.getInstance().getRTKNetworkServiceProvider().startNetworkService接口成功开启了自定义网络RTK服务，能够获取相关的数据，但大疆账户绑定的网络RTK服务状态一直是connecting，而且我也可以获取账户的状态是BOUND，也能获取到套餐到期时间，但就是无法开启网络RTK服务

**Comment by braveeric** [comment]
在连接飞机rtk成功后，设置自定义网络rtk成功后开始网络服务，成功获取飞机rtk信息和自定义网络rtk模拟基站信息，但过了一段时间后，程序崩溃，根据日志追踪错误报在sdk内部，日志信息如下：
1 java.util.ArrayList$Itr.next(ArrayList.java:831)
2 dji.internal.rtk.rtcm.RtcmManager$1.run(Unknown Source)
3 android.os.Handler.handleCallback(Handler.java:761)
4 android.os.Handler.dispatchMessage(Handler.java:98)
5 android.os.Looper.loop(Looper.java:156)
6 android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Jim-DJI** [comment]
> > 您好，对于您的使用场景我们这边会模拟一下定位一下问题。建议将MSDK版本升级到4.12配合使用，4.12内部对rtk做了一些小小优化。谢谢对MSDK的支持
> 
> 请问开启和大疆账户绑定的网络RTK服务和开启自定义网络RTK服务是同一个api吗？我利用DJISDKManager.getInstance().getRTKNetworkServiceProvider().startNetworkService接口成功开启了自定义网络RTK服务，能够获取相关的数据，但大疆账户绑定的网络RTK服务状态一直是connecting，而且我也可以获取账户的状态是BOUND，也能获取到套餐到期时间，但就是无法开启网络RTK服务

使用MSDK v4.12? 出现问题后无法恢复？看到你下面的回复连接rtk成功？

**Comment by Jim-DJI** [comment]
> 在连接飞机rtk成功后，设置自定义网络rtk成功后开始网络服务，成功获取飞机rtk信息和自定义网络rtk模拟基站信息，但过了一段时间后，程序崩溃，根据日志追踪错误报在sdk内部，日志信息如下：
> 1 java.util.ArrayList$Itr.next(ArrayList.java:831)
> 2 dji.internal.rtk.rtcm.RtcmManager$1.run(Unknown Source)
> 3 android.os.Handler.handleCallback(Handler.java:761)
> 4 android.os.Handler.dispatchMessage(Handler.java:98)
> 5 android.os.Looper.loop(Looper.java:156)
> 6 android.os.HandlerThread.run(HandlerThread.java:61)

是使用v4.12?

**Comment by braveeric** [comment]
> 在连接飞机rtk成功后，设置自定义网络rtk成功后开始网络服务，成功获取飞机rtk信息和自定义网络rtk模拟基站信息，但过了一段时间后，程序崩溃，根据日志追踪错误报在sdk内部，日志信息如下：
> 1 java.util.ArrayList$Itr.next(ArrayList.java:831)
> 2 dji.internal.rtk.rtcm.RtcmManager$1.run(Unknown Source)
> 3 android.os.Handler.handleCallback(Handler.java:761)
> 4 android.os.Handler.dispatchMessage(Handler.java:98)
> 5 android.os.Looper.loop(Looper.java:156)
> 6 android.os.HandlerThread.run(HandlerThread.java:61)
> 
> 是使用v4.12? 看日志好像没有升级到4.12，建议用4.12再测试一遍，谢谢

谢谢回复，升级到4.12，网络rtk已连接成功
