### ISSUE TITLE
Not needed log entries e.g. E/UsbAccessoryService: rate 1,05 MB

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#53]
Within the log I always see different log lines from the sdk which are not interesting for my or did not give me any usable hint and make it very hard for me to read my log easily.

Can you change this to log with interesting or understandable context or make the log configurable for the sdk.

e.g.:
-E/UsbAccessoryService: rate 1,05 MB
-D/UsbAccessoryService: putVideoBuffer length超过100k=31.639648
-DJIBaseProduct: get class : dji.sdk.battery.ai
-D/DJIShootPhotoStep: NOT shooting!!!!!!!!!!!!!!!
-E/DJIShootPhotoStep: isContinuousShoot: false
....

Regards

Using: 3.4.1 Android SDK

**Comment by xxmaestroxx** [comment]
Hey DJI,

what is the status of this issue?

Regards
Maestro

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
