### ISSUE TITLE
Matrice 210 V2 Gimbal Control Issue

### ISSUE THREAD

**Issue by ericwarden** [dji-sdk/Mobile-SDK-Android#530]
Hey all,

We're seeing an issue where changing the primary source of the M210 V2 to the other gimbal is not updating which gimbal is controlled by the remote controller. I noticed the same issue using the sample code found in this repo. If the controller is controlling gimbal 1, going to the VideoFeederView and changing the primary source to the RIGHT_CAM will still keep the controller moving gimbal 1.

To test further, I added a button with the following function:

```
private void onClickRightAndLeftBtn() {
    if (airLink != null) {
        if (airLink.isOcuSyncLinkSupported()) {
            KeyManager.getInstance().performAction(assignSourceToPrimaryChannelKey, allocSourceCallback, PhysicalSource.RIGHT_CAM, PhysicalSource.LEFT_CAM);
            KeyManager.getInstance().setValue(primaryVideoBandwidthKey, 0.5f, setBandwidthCallback);
        } else {
            KeyManager.getInstance().setValue(lbBandwidthKey, 0.0f, null);
            KeyManager.getInstance().setValue(mainCameraBandwidthKey, 0.5f, setBandwidthCallback);
        }
    }
}
```

Which is just the opposite of the `onClickLeftAndRightBtn` function where the right camera is being set as the primary camera. The code works and the feeds swap but the controller still maintains control over gimbal 1.

We also tried using the `setControllingGimbalIndex` but no matter which param we give it (either 0 or 1) it returns an error saying `Illegal Param`.

It doesn't seem to be a firmware bug because the gimbal behavior appears to work correctly in the DJI Pilot app. I'm hoping to receive some guidance here as maybe we're missing something in the documentation about the proper way to change gimbal control.

DJI SDK: 4.12
M210 V2 firmware: 01.00.0590
Remote Controller: 01.00.0590
Gimbal 1: 00.02.06.04
Gimbal 2: 01.01.02.44 

Thanks,
Eric

**Comment by dji-dev** [comment]
This issue can be solved by updating the gimbal firmware to the latest version.
