### ISSUE TITLE
MSDK4.12 Crash on xiaomi Pad4 (Android8.1.0) 

### ISSUE THREAD

**Issue by dashifuguye** [dji-sdk/Mobile-SDK-Android#539]
MSDK: 4.12  
XIAOMI PAD4  Android8.1.0  27  
M600 Pro  

自己使用MSDK开发的app，在飞行中出现崩溃。使用Bugly记录的相关log如下：

**# Thread-19686(3487) SIGSEGV(SEGV_MAPERR)**
```

1 #00 pc 000000000001c80c /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so (memcpy+92) [arm64-v8a::dde9714f5c9d16eae73172b503ad0c36]
--
2 #01 pc 00000000000ef5d4 /data/app/com.clobotics.windpower-3dW3r4PHobFmlWofRVm0-A==/lib/arm64/libFR.so (_ZN3DJI12FlightRecord15AddPKCS7PaddingEPvmi+104) [arm64-v8a::]
3 #02 pc 000000000017223c [anon:.bss] (_ZN3DJI12FlightRecord15EncryptionLayer17AESEncryptionDataERKNSt6__ndk110shared_ptrINS0_12WriterBufferEEE+688)
4 #03 pc 00000000000fb5d4 /data/app/com.clobotics.windpower-3dW3r4PHobFmlWofRVm0-A==/lib/arm64/libFR.so (_ZN3DJI12FlightRecord11FileManager9WriteItemERKNSt6__ndk110shared_ptrINS0_12WriterBufferEEE+60) [arm64-v8a::]
5 #04 pc 0000000000169128 [anon:.bss] (_ZN3DJI12FlightRecord17ProtocolOFDMDebug22ReceiveOFDMDebugLogSrcENSt6__ndk110shared_ptrINS0_6SourceILNS0_10SourceTypeE11EhEEEENS0_15ISourceListener11ProcessTypeE+144)
6 #05 pc 0000000000127e64 /data/app/com.clobotics.windpower-3dW3r4PHobFmlWofRVm0-A==/lib/arm64/libFR.so [arm64-v8a::]
7 #06 pc 00000000000f9600 /data/app/com.clobotics.windpower-3dW3r4PHobFmlWofRVm0-A==/lib/arm64/libFR.so (_ZNSt6__ndk113packaged_taskIFvvEEclEv+88) [arm64-v8a::]
8 #07 pc 00000000000f8340 /data/app/com.clobotics.windpower-3dW3r4PHobFmlWofRVm0-A==/lib/arm64/libFR.so (_ZZN3DJI12FlightRecord6WorkerC1EvENKUlvE_clEv+520) [arm64-v8a::]
9 #08 pc 00000000000f80c0 /data/app/com.clobotics.windpower-3dW3r4PHobFmlWofRVm0-A==/lib/arm64/libFR.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3DJI12FlightRecord6WorkerC1EvEUlvE_EEEEEPvSC_+44) [arm64-v8a::]
10 #09 pc 0000000000067ec4 /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so [arm64-v8a::dde9714f5c9d16eae73172b503ad0c36]
11 #10 pc 000000000001f2f4 /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so [arm64-v8a::dde9714f5c9d16eae73172b503ad0c36]
12 java:
13 [Failed to get Java stack]

```
![image](https://user-images.githubusercontent.com/21324724/84234557-0f7ac600-ab27-11ea-9ac9-3f4177a75ed3.png)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/35633'>Zendesk ticket #35633</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
> Agent comment from Luce Luo in [Zendesk ticket #35633](https://djisdksupport.zendesk.com/agent/tickets/35633):
> 
> 尊敬的用户，
> 
> 您好！感谢您联系DJI 大疆创新。
> 为了快速收集问题细节，麻烦您详细填写如下表格。
> https://formcrafts.com/a/dji-developer-feedback-cn
> 
> 在收到您的详细细节信息后，我们将会进行快速处理。
> 
> 非常感谢您的理解与配合，祝您生活愉快！
> 
> Best Regards,
> 
> DJI 大疆创新SDK技术支持

已填写

**Comment by dashifuguye** [comment]
> Agent comment from Luce Luo in [Zendesk ticket #35633](https://djisdksupport.zendesk.com/agent/tickets/35633):
> 
> 尊敬的用户，
> 
> 您好！感谢您联系DJI 大疆创新。
> 为了快速收集问题细节，麻烦您详细填写如下表格。
> https://formcrafts.com/a/dji-developer-feedback-cn
> 
> 在收到您的详细细节信息后，我们将会进行快速处理。
> 
> 非常感谢您的理解与配合，祝您生活愉快！
> 
> Best Regards,
> 
> DJI 大疆创新SDK技术支持

还有一个问题，使用MSDK4.12，小米平板4，Android8.1.0，文件管理器DJI/package name/文件夹下没有相关数据，但是华为M5（Android9.0）有数据

**Comment by dashifuguye** [comment]
降级到4.11.2后暂时没有出现问题，所以关闭
