### ISSUE TITLE
Illegal Param Error

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#54]
When i'm using DJIGoToStep or other mission step sometimes the error "Illegal Param" occurs.
Is it possible to make it more contextsensitive, like saying which param was illegal? or what is the range or sth. helpful?

Moreover i will grep up and point from another issue, where it's mentioned that sometime errors occurs, which are not really errors. These are more like informations as errors, maybe you can split this up.

Regards

Using: 3.4.1 Android SDK

**Comment by talobin** [comment]
Please check out two new classes: `MissionControl` and `GotoAction`.
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
