### ISSUE TITLE
飞机的避障回调函数

### ISSUE THREAD

**Issue by braveeric** [dji-sdk/Mobile-SDK-Android#546]
1，在任务规划飞行过程中触发了避障效果，飞机开始悬停，请问是否有触发避障的回调API？
2，在DJI plot中触发避障效果同样会悬停，但是可继续执行任务，请问相关的API是什么？

现在的目的是想在规划自动飞行过程中如果触发避障导致悬停时能够弹出界面提示用户继续任务或者返航，目前采用的规划方法是timeline方法，航点设置用的是TimelineMission.elementFromWaypointMission（WaypointMission var0）

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/36083'>Zendesk ticket #36083</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

1. setVisionDetectionStateUpdatedCallback
Link：https://developer.dji.com/api-reference/android-api/Components/IntelligentFlightAssistant/DJIIntelligentFlightAssistant.html#djiintelligentflightassistant_setvisiondetectionstateupdatedcallback_inline

2. 目前没有相关的API，Pilot上是内部做了逻辑，我并不知道Pilot的内部逻辑是什么。个人有个思路就是，你在执行TIMELINE任务的时候遇到避障了导致悬停了，可以先暂停TIMELINE任务然后用程序调整飞行器高度左右之类的去尝试避障，然后在Resume任务。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
