### ISSUE TITLE
How can I get a frame from DJI H.264 vedio?

### ISSUE THREAD

**Issue by wuyan12138** [dji-sdk/Mobile-SDK-Android#548]
I want to using Opencv to deal with the vedio from the DJI Drones, however, what troubles me is that I do not konw how to get a frame from the vedio, what's more, how can I transfer it to Mat? Is there any bolgs or any way can help me? thanks a lot

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/36125'>Zendesk ticket #36125</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Here is a sample about how to fetch YUV data, please check if it can help you.
https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample

And we have not any test with Mat, sorry can't help you more about this.

Thanks,

Luce Luo
DJI Dev Team

**Comment by wuyan12138** [comment]
@dji-dev Is that means I can not transfer DJI Camera Raw data to Mat directly ? Is there other ways if I want to deal with the vedio from DJI Camera using OpenCV ? Can you give me some advice ? thanks a lot.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/36125'>Zendesk ticket #36125</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Yes, we have no test for the Mat or OpenCV and can't promise it can work well with it.
What we can promise that you can receive the video buffer from the onReceive method.
For specific case, you need to develop your own.

Thanks,

Luce Luo
DJI Dev Team

**Comment by wuyan12138** [comment]
@dji-dev thank you very much. May be I need to use some inefficient way to achieve my target.

**Comment by wuyan12138** [comment]
@dji-dev By the way, I truly help DJI can support OpenCV Develop in future released SDK, which will give us more possibilities

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/36125'>Zendesk ticket #36125</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Ok, many thanks for your advice.

Thanks,

Luce Luo
DJI Dev Team
