### ISSUE TITLE
WaypointActionType 其他类型是否可用

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#549]
```
public enum WaypointActionType {
    STAY(0),
    START_TAKE_PHOTO(1),
    START_RECORD(2),
    STOP_RECORD(3),
    ROTATE_AIRCRAFT(4),
    GIMBAL_PITCH(5),
    CAMERA_ZOOM(7),
    CAMERA_FOCUS(8),
    PHOTO_GROUPING(11),
    FINE_TUNE_GIMBAL_PITCH(16),
    RESET_GIMBAL_YAW(17);
}
```

[sdk文档对WaypointActionType 的描述](https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypoint_DJIWaypointAction.html?search=waypointactiontype&i=0&#djiwaypoint_djiwaypointactiontype_inline) 只有`STAY`, `START_TAKE_PHOTO`, `START_RECORD`, `STOP_RECORD`, `ROTATE_AIRCRAFT`, `GIMBAL_PITCH` , 其余的:
 CAMERA_ZOOM(7),
    CAMERA_FOCUS(8),
    PHOTO_GROUPING(11),
    FINE_TUNE_GIMBAL_PITCH(16),
    RESET_GIMBAL_YAW(17); 能否正常使用?

MSDK v4.12

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/36297'>Zendesk ticket #36297</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

请以文档的为主，文档没有写得应该是未完成的枚举类型，使用的话可能会有异常行为。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
