### ISSUE TITLE
WAYPOINT_DISTANCE_TOO_CLOSE 任务点距离过近导致任务终止

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#552]
通过TimelineElement的方式执行任务,两点之间距离过近导致终止,如何规避

```
private val elements = mutableListOf<TimelineElement>()

fun startMission(){
     missionControl.scheduleElements(elements)
}

```

**Comment by luoyexk** [comment]
如执行到elements index为5的元素时, 因与index为4的WaypointMission的最后一个WayPoint距离太近,导致执行一半就终止

**Comment by luoyexk** [comment]
日志:
省略前部多个执行正常的TimelineMission
Element:dji.sdk.mission.timeline.TimelineMission@5c5a11f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.TimelineMission@5c5a11f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.TimelineMission@5c5a11f event:FINISHED errId:null errDes:null
// @460418f GoToAction(Float) 
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:STARTED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:PROGRESSED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@460418f event:FINISHED errId:null errDes:null
// @b747b04 GoToAction(LocationCoordinate2D)动作
Element:dji.sdk.mission.timeline.actions.GoToAction@b747b04 event:STARTED errId:null errDes:null
Element:dji.sdk.mission.timeline.actions.GoToAction@b747b04 event:FINISHED errId:229 errDes:The waypoint distance is too close
Element:null event:STOPPED errId:null errDes:null

**Comment by wuyan12138** [comment]
Oops! We met the same problem as yours, the first point we upload always too close leading to that it shows "mission finished" though it just take off, have you solved this problem?

**Comment by luoyexk** [comment]
> Oops! We met the same problem as yours, the first point we upload always too close leading to that it shows "mission finished" though it just take off, have you solved this problem?

not yet

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/36354'>Zendesk ticket #36354</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
相邻航点间距离需要在0.5m-2km之间，您自行检查下。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
