### ISSUE TITLE
DJIMissionManagerError and DJIGeoError classes exist in multiple packages

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-Android#56]
DJI Android SDK version - 3.4.1
DJI Product: Phantom 4
Android version: 6.0.1
Android device: Samsung Galaxy Tab S2
Android Studio version: 2.2.2

DJIMissionManagerError and DJIGeoError classes are found in two packages:

dji.sdk.base
dji.common.error

The ones in dji.common.error APPEAR to be the more recent ones, but it is confusing, and can lead to bugs.  For example, if you are doing a direct comparison between a static variable from the dji.common.error.DJIMissionManagerError class, and the returned error is from dji.sdk.base.DJIMissionManagerError (or vice-versa).

Please remove the unused files (I'm assuming it will be from dji.sdk.base) to make it clear which object should be used.

Thanks!

**Comment by oliverou** [comment]
Hi @jgrantr, thanks for the feedback. This issue will be fixed in the next version of the SDK.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
