### ISSUE TITLE
[SDK 4.12] onFirmwareUpgradeProgressUpdated never working

### ISSUE THREAD

**Issue by hplong** [dji-sdk/Mobile-SDK-Android#560]
SDK Version: 4.12
Drone: Mavic Pro
I cannot trigger onFirmwareUpgradeProgressUpdated of the UpgradeFirmwareListener.
However, when I downgraded SDK version 4.11.2, I can trigger onFirmwareUpgradeProgressUpdated.
Thanks.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/36765'>Zendesk ticket #36765</a>:<br><br>Dear Client
Thank you for contacting DJI.

The doc says It is only supported by Mavic Air, Mavic 2 series. The doc will update when every version is released. But I will try on Mavic Pro and Mavic 2 Pro to see where is the issue.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by hplong** [comment]
I also checked on the Mavic 2 Zoom, It seems can't trigger onFirmwareUpgradeProgressUpdated.
Thanks.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/36765'>Zendesk ticket #36765</a>:<br><br>Dear Client
Thank you for contacting DJI.

I have replicated the error and I am going to report this to the dev team.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
