### ISSUE TITLE
如何从sdk拿无行机的serial number ?

### ISSUE THREAD

**Issue by KahWeing** [dji-sdk/Mobile-SDK-Android#563]
请问有没有方法拿到无行机的serial number ? Matric 200 V2

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/36989'>Zendesk ticket #36989</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

只有无人机的部件有序列号，getSerialNumber。
Link：https://developer.dji.com/api-reference/android-api/Components/BaseComponent/DJIBaseComponent.html#djibasecomponent_getserialnumber_inline

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
