### ISSUE TITLE
AFC Enable Switch

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#569]
![image](https://user-images.githubusercontent.com/20855787/88000604-9fe9f480-cb30-11ea-993a-937b7e2f6ac3.png)

图被墙了, 可通过全局vpn可查看

AFC Enable Switch这个功能对应MSDK的哪个接口

目前遇到一个问题:
当此开关处于关闭状态时, 无法通过调用`setFocusMode(FocusMode.AFC)`设置对焦模式为AFC, 而是变成了AF. 在飞行任务中拍的照片很多都是因为对焦问题导致模糊; 当此开关打开时, 就能通过`setFocusMode(FocusMode.AFC)`设置为AFC

在USDK的FocusModeWidget控件中, 查看到该Boolean值是通过SharedPreference获取, 获取方式: ` E.a(this.getContext(), "afcenabled", false);`

机型: P4P, MAVIC 2 ZOOM
MSDK: 4.12

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/37132'>Zendesk ticket #37132</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
与启用连续自动变焦对焦按钮无关，MSDK上通过setFocusMode(FocusMode.AFC)方法即可达到开启AFC的效果，
对于UXSDK，应该是FocusModeWidget这个控件问题，即通过点击无法切换为AFC模式。
您可以检查确认下，在UXSDK中通过调用setFocusMode(FocusMode.AFC)，FocusModeWidget控件位置应该是会显示为AFC的。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
