### ISSUE TITLE
Unknow Device

### ISSUE THREAD

**Issue by lillogoal** [dji-sdk/Mobile-SDK-Android#57]
HI to all,
i have a big problem with SAMPLE O CAMERA (ANDROID SDK).

ANDROID STUDIO: 2.2.2
MIN SDK: 4.4.1
DEVICE MOTO G3 (2016)
ANDROID VERSION: 6.0.1

THIS IS LOGCAT: 11-23 21:25:59.496 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: Camera needCreateNew: false
11-23 21:25:59.496 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: Gimbal needCreateNew: false
11-23 21:25:59.499 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: FlightController needCreateNew: false
11-23 21:25:59.499 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: oldComponent: dji.sdk.flightcontroller.a@6f43b86
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: update battery platformType: Unknown
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: Battery needCreateNew: false
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: HandHeldController needCreateNew: false
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: RemoteController needCreateNew: false
11-23 21:25:59.500 23837-23837/com.wesii.wesiiplay E/DJIBaseProduct: MOBILE_REMOTE_CONTROLLER needCreateNew: false
11-23 21:26:01.431 23837-23884/com.wesii.wesiiplay E/wm220: ****resetSwitchFromWifiFlag
11-23 21:26:01.842 23837-23954/com.wesii.wesiiplay E/c: udt 连接建立 ip:192.168.1.3port:9000
11-23 21:26:02.356 23837-24453/com.wesii.wesiiplay E/UDT-JNI: Connection was broken.
11-23 21:26:02.357 23837-24453/com.wesii.wesiiplay E/c: udt 连接断开 recvLen=-2 ip:192.168.1.3port:9000

**Comment by oliverou** [comment]
Hi @lillogoal, thanks for your feedback, please check my reply in Android-FPVDemo issue: <https://github.com/DJI-Mobile-SDK-Tutorials/Android-FPVDemo/issues/16>

**Comment by lillogoal** [comment]
ok you, but I noticed that with the official app dji go. how is it that with the official app works well? the Chamber (osmo) is detected and the connection goes perfectly. How Can i do ? @oliverou

**Comment by lillogoal** [comment]
@oliverou here my answer.

DJI SDK Is 3.4.1 YES.
THIS IS MY GRADLE:
`ndroid {
compileSdkVersion 25
buildToolsVersion "24.0.2"
defaultConfig {
applicationId "com.wesii.wesiiplay"
minSdkVersion 19
targetSdkVersion 25
versionCode 1
multiDexEnabled true

    versionName "1.0"
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
}`

I also tried to compile with android sdk 22. But nothing changes nothing.
NO NO i can't open dji go and my app in same time.
