### ISSUE TITLE
Mavic Air 2 Support?

### ISSUE THREAD

**Issue by Manouchehri** [dji-sdk/Mobile-SDK-Android#573]
Decided it might be a better idea to split out #455 to track the progress on the Mavic Air 2. Current ETA was last reported as September in https://github.com/dji-sdk/Mobile-SDK-Android/issues/455#issuecomment-624423625.

**Comment by dji-lisafedane** [comment]
You can also watch the issue at DJI's Developer's forum here: https://forum.dji.com/forum.php?mod=viewthread&tid=213821&extra=page%3D1%26filter%3Dtypeid%26typeid%3D748%26typeid%3D748

**Comment by justinelliotmeyers** [comment]
any idea if this will drop in August? trying to plan out some flights but still have to fly the bird hands on...  Thanks!!

**Comment by CalvinHou** [comment]
what?

**Comment by brothercorvo** [comment]
Any update?

**Comment by neluturo** [comment]
Any update on this?

**Comment by Manouchehri** [comment]
Looks like it's been bumped to 11/29/2020.

> I can confirm the possibility of dates, as already mentioned the SDK team is shooting to have the release before the end of Q4.  The roadmap lists an estimated date of 11/29/2020 but please note, that this is an estimate.  You can view the roadmap here: https://developer.dji.com/user/roadmap/#msdk

https://forum.dji.com/forum.php?mod=redirect&goto=findpost&ptid=213821&pid=2307556

**Comment by alzin** [comment]
I am still struggling with the new release SDK to get Mavic Air 2 working with it?
We are in 2021, So any update on this because there is poor documentation from DJI on how to get started??

**Comment by Manouchehri** [comment]
The SDK came out awhile ago, closing this.
