### ISSUE TITLE
SDK is not working if you set project's minSdkVersion > 22

### ISSUE THREAD

**Issue by rmyhal** [dji-sdk/Mobile-SDK-Android#574]
The SDK stops working if you set minSdkVersion in your project more than 22 and there no error messages.

**Comment by kenargo** [comment]
Yes, I came across this one yesterday and was just debugging to figure out why previous apps worked and suddenly they lock at startup.

 

I found that minSdkVersion 22 works, minSdkVersion 23 or higher locks up the app with a white screen!

 

With minSdkVersion = 22 there is a slight white screen delay but it doesn’t lock up hard, at least not for me.  I tested both compileSdkVersion 29 and 30

 

Same behavior, you cannot use minSdkVersion 23 or higher!

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/37483'>Zendesk ticket #37483</a>:<br><br>Dear Client
Thank you for contacting DJI.

From SdkVersion 21 and later, multidexenable will divide to serval packages. This might lead to cannot find Class/Package in a dex file. You need to specify the dex location in build.gradle. We suggest you just stick on 19.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by rmyhal** [comment]
Thanks for the reply. @dji-dev 
But I don't want to support devices with Android version 4. Android has a lot of limitations on lower android versions and it supposes to me write more code and handle more edge cases. I want to have ability to set minSDKVersion 23-24 or even more. Is there any solution to achieve that? Maybe somehow update build.gradle?

**Comment by kenargo** [comment]
I have the same requirements for Android

**Comment by kenargo** [comment]
To clarify what I believe the support person’s response was trying to say…

 

For SDK 21 and above multi-dex is enabled by default AND since 21 and above uses ART runtime, which supports multiple DEX files there can be many classesX.dex files which causes issues with DJI’s SDK to find it’s components. 

 

I would still prefer a solution other than supporting lower SDK release especially now that support for x86 is pretty much being dropped by DJI

 

Reference:  https://developer.android.com/studio/build/multidex#mdex-on-l

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/37483'>Zendesk ticket #37483</a>:<br><br>Dear Client
Thank you for contacting DJI.

We have a solution for you now. In AndroidManifest.xml,<Application> tag add android:extractNativeLibs="true".

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by kenargo** [comment]
All better, no more crash, the ticket can be closed

**Comment by rmyhal** [comment]
@dji-dev Also helped for me too. Thanks!
