### ISSUE TITLE
DJISDKManager.getInstance().registerApp never come back (ANR)

### ISSUE THREAD

**Issue by eyalmnm** [dji-sdk/Mobile-SDK-Android#575]
Hello,
I have tried to run both FPVDemo and my application(with their own keys) but after calling registerApp the application stoped and callback methods never being called and got ANR.
How it can be fixed

defaultConfig {
        applicationId "com.em_projects.dronecontroller"
        minSdkVersion 23
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

packagingOptions{
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"
        exclude 'META-INF/rxjava.properties'
    }

**Comment by kenargo** [comment]
Lower minSdkVersion below 23 or the sdk locks up

-------- Original message --------From: Eyal Muchtar <notifications@github.com> Date: 7/30/20  6:48 AM  (GMT-08:00) To: dji-sdk/Mobile-SDK-Android <Mobile-SDK-Android@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [dji-sdk/Mobile-SDK-Android] DJISDKManager.getInstance().registerApp never come back (#575) 
Hello,
I have tried to run both FPVDemo and my application(with their own keys) but after calling registerApp the application stoped and callback methods never being called.
How it can be fixed
defaultConfig {
applicationId "com.em_projects.dronecontroller"
minSdkVersion 23
targetSdkVersion 29
versionCode 1
versionName "1.0"
multiDexEnabled true
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}

packagingOptions{
doNotStrip "//libdjivideo.so"
doNotStrip "//libSDKRelativeJNI.so"
doNotStrip "//libFlyForbid.so"
doNotStrip "//libduml_vision_bokeh.so"
doNotStrip "//libyuv2.so"
doNotStrip "//libGroudStation.so"
doNotStrip "//libFRCorkscrew.so"
doNotStrip "//libUpgradeVerify.so"
doNotStrip "//libFR.so"
exclude 'META-INF/rxjava.properties'
}

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/37550'>Zendesk ticket #37550</a>:<br><br>Dear Client
Thank you for contacting DJI.

We have a solution for you now. In AndroidManifest.xml,<Application> tag add android:extractNativeLibs="true".

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by huBrant** [comment]
hello @dji-dev 
Above solution actually not worked for me !
registerApp always doesn't work?
I give you my code.
How it can be fixed


build.gradle

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

repositories {
    mavenLocal()
    mavenCentral()
}

android {
    compileSdkVersion 29
    buildToolsVersion '29.0.3'
    useLibrary 'org.apache.http.legacy'
defaultConfig {
        applicationId "lidar.com.earthbook"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 33
        versionName "1.1.33"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            // On x86 devices that run Android API 23 or above, if the application is targeted with API 23 or
            // above, FFmpeg lib might lead to runtime crashes or warnings.

            abiFilters 'arm64-v8a', 'x86_64'

        }
    }

//    buildTypes {
//        release {
//            minifyEnabled true
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//        }
//        debug {
//            shrinkResources true
//            minifyEnabled true
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//        }
//    }

    signingConfigs {
        config {
            storeFile file("earthbookstore")
            keyAlias "earthbook_store"
            storePassword "xxx"
            keyPassword "xxx"

        }

    }

    buildTypes {
        release {

            signingConfig signingConfigs.config
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    packagingOptions {
        doNotStrip "*/*/libdjivideo.so"
        doNotStrip "*/*/libSDKRelativeJNI.so"
        doNotStrip "*/*/libFlyForbid.so"
        doNotStrip "*/*/libduml_vision_bokeh.so"
        doNotStrip "*/*/libyuv2.so"
        doNotStrip "*/*/libGroudStation.so"
        doNotStrip "*/*/libFRCorkscrew.so"
        doNotStrip "*/*/libUpgradeVerify.so"
        doNotStrip "*/*/libFR.so"
        doNotStrip "*/*/libDJIFlySafeCore.so"
        doNotStrip "*/*/libdjifs_jni.so"
        doNotStrip "*/*/libsfjni.so"
        doNotStrip "*/*/libDJICommonJNI.so"
        doNotStrip "*/*/libDJICSDKCommon.so"
        doNotStrip "*/*/libDJIUpgradeCore.so"
        doNotStrip "*/*/libDJIUpgradeJNI.so"
        doNotStrip "*/*/libDJIWaypointV2Core.so"
        doNotStrip "*/*/libAMapSDK_MAP_v6_9_2.so"
        doNotStrip "*/*/libDJIMOP.so"
        doNotStrip "*/*/libDJISDKLOGJNI.so"
        exclude 'META-INF/rxjava.properties'
        exclude 'assets/location_map_gps_locked.png'
        exclude 'assets/location_map_gps_3d.png'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}


dependencies {
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'com.squareup:otto:1.3.8'
    implementation ('com.dji:dji-uxsdk:4.14-trial1', {
        /**
         * Comment the "library-anti-distortion" if your app does need Anti Distortion for Mavic 2 Pro and Mavic 2 Zoom.
         * Comment the "fly-safe-database" if you do not need database for release, or we will download it when DJISDKManager.getInstance().registerApp
         * is called.
         * Both will greatly reduce the size of the APK.
         */
        exclude module: 'library-anti-distortion'
        exclude module: 'fly-safe-database'

        /**
         * Uncomment the following line to exclude amap from the app.
         * Note that Google Play Store does not allow APKs that include this library.
         */
        // exclude group: 'com.amap.api'
    })
    implementation 'com.github.nkzawa:socket.io-client:0.6.0'
    compileOnly 'com.dji:dji-sdk-provided:4.14-trial1'
implementation 'org.osmdroid:osmdroid-android:6.0.0'
    implementation 'org.osmdroid:osmdroid-wms:6.0.1'
    implementation 'com.wu-man:android-oauth-client:0.4.5@aar'
    implementation 'com.opencsv:opencsv:4.6'
    implementation 'com.squareup.okhttp3:okhttp:3.10.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    implementation 'de.hdodenhof:circleimageview:3.0.0'
    implementation 'androidx.core:core:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0-rc01'
    implementation 'androidx.annotation:annotation:1.0.0'
    implementation 'com.pixplicity.sharp:library:1.1.3@aar'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}


AndroidManifast.xml

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="lidar.com.earthbook">
    
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.USB_PERMISSION" />
    <uses-permission android:name="android.permission.CAMERA" />



    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true" />
    <uses-feature
        android:name="android.hardware.usb.host"
        android:required="false" />
    <uses-feature
        android:name="android.hardware.usb.accessory"
        android:required="true" />

    <application
        android:name=".internal.controller.DJISampleApplication"
        android:allowBackup="true"
        android:configChanges="keyboardHidden|screenSize"
        android:icon="@drawable/logo_launcher"
        android:label="@string/app_name"
        android:largeHeap="true"
        android:extractNativeLibs="true"
        android:networkSecurityConfig="@xml/network_security_config"
        android:screenOrientation="portrait"
        android:supportsRtl="true"
        android:requestLegacyExternalStorage="true"
        android:theme="@style/Theme.AppCompat.Light.NoActionBar"
        android:usesCleartextTraffic="true"
        tools:ignore="AllowBackup,GoogleAppIndexingWarning"
        tools:replace="allowBackup">
        <activity android:name=".internal.FileManagerCsvForm"></activity>
        <activity android:name=".internal.testpage_viewpicker" />
        <activity android:name=".internal.UAV_limit_area_web" />
        <activity android:name=".internal.SendGpsPageMap" />

        <uses-library
            android:name="org.apache.http.legacy"
            android:required="false" />

        <meta-data
            android:name="com.dji.sdk.API_KEY"
            android:value="xxxxx" />
  
        <activity android:name=".internal.UAV_photoandvideo_edit" />
        <activity android:name=".internal.DJIDeviceModel" />
        <activity
            android:name=".internal.MainActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".internal.MainMenu"
            android:launchMode="singleTask"
            android:extractNativeLibs="true"
            android:screenOrientation="portrait">

            <intent-filter>
                <action android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED" />
            </intent-filter>

            <meta-data
                android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED"
                android:resource="@xml/accessory_filter" />
        </activity>

   </application>

</manifest>

**Comment by Jai-GAY** [comment]
looks like I may be [having the same issue](https://github.com/dji-sdk/Mobile-SDK-Android/issues/710#issuecomment-806336206).

**Comment by jim-mcandrew** [comment]
I also have this issue. Setting android:extractNativeLibs seems to help until I build my app as an appbundle, and then the issue returns. Any ideas?

**Comment by DJI-William** [comment]
This issue is if you dont set android:extractNativeLibs="true", the Android Studio will automatically add android:extractNativeLibs="false" when tries to build up an apk. It means that the so in apk will not be compressed. Also not de-compressed when run. Which will cause crash. We will continuse looking for answer.

**Comment by jim-mcandrew** [comment]
>  if you dont set android:extractNativeLibs="true"

I added that line and it still happens, but only after building it as an appbundle.

**Comment by DJI-William** [comment]
I have updated our app bundle demo with minSDK to 23. Actually the main code I have changed is the AndroidManifest.xml.
I changed android:extractNativeLibs="true" and tools:replace="android:extractNativeLibs". It works.
[https://github.com/DJI-Mobile-SDK-Tutorials/DJI-Android-SDK-Bundle-Sample](url)

**Comment by jim-mcandrew** [comment]
I downloaded the updated sample app, build an appbundle out of it and then installed it (with bundletool.jar) and it hangs on launch...

**Comment by DJI-William** [comment]
![image](https://user-images.githubusercontent.com/77274755/125059906-68c47880-e0de-11eb-90c4-1f00853f8a50.png)
Have you read the ReadMe of how to test locally. I have built up a app.aab file and de-compress it into apks and install it on device, it works. If the app hangs on registering it means the file doesn't find the necessory .so files. If you unzio the app.aab file you should fine many .so in assets like this.
![image](https://user-images.githubusercontent.com/77274755/125060254-c22ca780-e0de-11eb-9859-fa1534c353d1.png)

**Comment by jim-mcandrew** [comment]
> it means the file doesn't find the necessory .so files
It looks like my aab file has the so files:
[
![Screen Shot 2021-07-09 at 9 37 39 AM](https://user-images.githubusercontent.com/6760170/125103280-d0100780-e0a1-11eb-87e6-4a4652e30d7c.png)
](url)

> Have you read the ReadMe of how to test locally. 
Can you point me to the readme file you are referring to and which part of it?

**Comment by DJI-William** [comment]
Link：https://github.com/DJI-Mobile-SDK-Tutorials/DJI-Android-SDK-Bundle-Sample/tree/master/sample
![image](https://user-images.githubusercontent.com/77274755/125223325-28dbdc00-e2fe-11eb-99c7-72d4325f1723.png)

**Comment by jim-mcandrew** [comment]
Thank you. Is there any way to accomplish this without using dynamic feature modules?

**Comment by jim-mcandrew** [comment]
Ok, I believe I found a solve. I noticed a few new options in the gradle.properties file (org.gradle.daemon, org.gradle.parallel, org.gradle.configureondemand) and when I copied them over I inadvertently removed `android.bundle.enableUncompressedNativeLibs=false`

If I add this line back in, I am able to upgrade to 4.15 and still build the appbundle without dynamic feature modules.
