### ISSUE TITLE
如何播放起飞，降落声音

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#576]
我看到DJI GO4中在起飞降落时都有播放”起飞“ ”降落“，我要怎么播放这个声音？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/37577'>Zendesk ticket #37577</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
DJI GO 4是深度定制的，MSDK不具备播放相关声音功能，
建议您检测飞机起降状态后自行使用安卓相关实现语音。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
