### ISSUE TITLE
Aircraft is in warning zone dialog 自动弹出问题

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#577]
这个弹窗是哪个控件弹出的,每次进入界面的时候都自动弹出,能拒绝该弹窗自动弹出么
![无标题](https://user-images.githubusercontent.com/20855787/89143278-9fb01700-d57c-11ea-969d-23b6c2c02492.jpg)

**Comment by luoyexk** [comment]
PreFlightCheckListPanel

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/37624'>Zendesk ticket #37624</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

请问问题是不是已经解决了？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by luoyexk** [comment]
其实没有解决, 我把最大高度设置为119米, 避免警告窗口弹出. 

![image](https://user-images.githubusercontent.com/20855787/89252702-1a486780-d64d-11ea-865d-0b0e234249b6.png)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/37624'>Zendesk ticket #37624</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

你这个框没有办法不弹出，这是对WarningZone的一个机制。你点击OK他就会消失了。你这个办法也可以。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
