### ISSUE TITLE
Smart Controller Doesn't Detect Drone Without Internet

### ISSUE THREAD

**Issue by nickdonnellyriis** [dji-sdk/Mobile-SDK-Android#580]
Drone: Mavic 2 Pro
SDK Version: 4.13
Device: DJI Smart Controller

The drone is not being detected after the SDK is registered if there is no internet (there **is** internet during the first registration).

Reproduction steps:
1. Start the app for the first time with internet connection available. The SDK registers without issue.
2. Try to connect the drone, it works fine (`onProductConnected is called`).
3. Force kill the app and turn off wifi.
4. Start the app, the SDK `onRegister` callback is called twice:

```
SDK Init: Calling registerApp
SDK Init: Starting process DJISDKInitEvent{initializationState=START_TO_INITIALIZE, currentTime=1596460009688}
SDK Init: Starting process DJISDKInitEvent{initializationState=ASSETS_LOADED, currentTime=1596460012657}
SDK Init: Starting process DJISDKInitEvent{initializationState=ASSETS_LOADED, currentTime=1596460014067}
SDK Init: DJI SDK registered successfully!
SDK Init: DJI SDK registered successfully!
```

5. Try to connect the drone, no components are loaded and `onProductConnect` is not called.

It is working on other android devices and a usb-based connection.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/37663'>Zendesk ticket #37663</a>:<br><br>Drone: Mavic 2 Pro
SDK Version: 4.13
Device: DJI Smart Controller

The drone is not being detected after the SDK is registered if there is no internet (there **is** internet during the first registration).

Reproduction steps:
1. Start the app for the first time with internet connection available. The SDK registers without issue.
2. Try to connect the drone, it works fine (`onProductConnected is called`).
3. Force kill the app and turn off wifi.
4. Start the app, the SDK `onRegister` callback is called twice:

```
SDK Init: Calling registerApp
SDK Init: Starting process DJISDKInitEvent{initializationState=START_TO_INITIALIZE, currentTime=1596460009688}
SDK Init: Starting process DJISDKInitEvent{initializationState=ASSETS_LOADED, currentTime=1596460012657}
SDK Init: Starting process DJISDKInitEvent{initializationState=ASSETS_LOADED, currentTime=1596460014067}
SDK Init: DJI SDK registered successfully!
SDK Init: DJI SDK registered successfully!
```

5. Try to connect the drone, no components are loaded and `onProductConnect` is not called.

It is working on other android devices and a usb-based connection.

**Comment by dji-dev** [comment]
Agent comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/37663'>Zendesk ticket #37663</a>:<br><br>I have attempted to duplicate this reported bug on my Smart RC and Mavic 2 Pro but I can't replicate it.  When the WiFi is turned off on my Smart RC, I am still able to consistently connect it to the drone with version 4.13 MSDK sample app.

Does your RC or drone need any firmware updates?

Lisa Fedane
DJI Developer Support, US

Join DJI's Developer Community in our new Forum for Technical Discussions, Announcements and More:
https://forum.dji.com/forum-139-1.html?from=developer
