### ISSUE TITLE
H264 decoding with gstreamer

### ISSUE THREAD

**Issue by cartovarc** [dji-sdk/Mobile-SDK-Android#587]
Hi, 
We are using an Mavic 2 Zoom drone and DJI SDK 4.11
We are trying to decode the videoBuffer with raw H264 video data, in external software using Gstreamer with the following commands:
gst-launch-1.0 udpsrc port=5600 !  h264parse ! avdec_h264 ! videoconvert ! videorate ! autovideosink
and
ffplay -f h264 -i udp://127.0.0.1:5600

// Here we get H264 RAW data
mReceivedVideoDataListener = new VideoFeeder.VideoDataListener() {

    @Override
    public void onReceive(byte[] videoBuffer, int size) {
        if (mCodecManager != null) {
            mCodecManager.sendDataToDecoder(videoBuffer, size);
        }
        UDPVideoSender.getInstance().sendFrame(videoBuffer, size);
    }
};

We send videoBuffer through UDP socket client and we get that distortinated output [VIDEO](https://www.youtube.com/watch?v=qYCB20P24-c)
Also we tried to use TCP for sending videoBuffer but the same happens.
Could you give me an example of how to correctly decode this data outside Android?
Do you have any more detailed documentation of how the video is encoded in that videoBuffer? In the API of the SDK we do not find information about this.
Thanks!

**Comment by cartovarc** [comment]
I moved to 4.13 SDK version and still happens

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/37991'>Zendesk ticket #37991</a>:<br><br>Dear Client
Thank you for contacting DJI.

Please refer to this demo.
https://github.com/DJI-Mobile-SDK-Tutorials/Android-VideoStreamDecodingSample

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by cartovarc** [comment]
Hi, we don't need to decode inside android app. We need to process this H.264 frames outside the android app.

According to API reference provideTranscodedVideoFeed method "provides standard  H.264 video feed for more general usages" but the stream looks distorted. 

Can the H.264 streaming be decoded outside of MSDK?
How can we get undistorted H.264 video feed for Mavic 2 series?

Thanks!

**Comment by cartovarc** [comment]
if anyone has the same problem, apparently in this repository they manage h264 stream using Gstreamer
https://github.com/The1only/rosettadrone
@The1only

**Comment by cartovarc** [comment]
The problem was a duplicated VideoDataListener so streaming was continually pushed twice.

**Comment by OlivierMartineau** [comment]
> VideoDataListener

Hey @cartovarc, I have exactly the same problem.

First, I don't get any data from "primaryVideoFeed", only from "provideTranscodedVideoFeed"
And I only get data when "DJICodecManager" is initialized.

May I ask you what you were doing that was pushing the streaming twice?

**Comment by OlivierMartineau** [comment]
Thanks for answering 👍 

For this I think you can directly do 
VideoFeeder.getInstance().getPrimaryVideoFeed().destroy();

A previous code would just add a null listener.

I'll check if it gets better with removing listeners, but I'm not really confident.
I find it weird that TranscodedFeed is so buggy and I don't get the Primary one.
Currently messing with YuvDataListener, to try to get what's sent to the surface (it's less buggy, I have hope).

I'll get you posted.
