### ISSUE TITLE
NullPointerException when requesting getFirmwareVersion on a component

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#59]
I'm encountering a NullPointerException occasionally when requesting the firmware version from a component.

Using v3.4.0 of the mobile SDK

```java
Exception java.lang.NullPointerException: Attempt to read from field 'byte[] dji.midware.data.a.a.a.p' on a null object reference
dji.midware.data.model.P3.DataCommonGetVersion.getFirmVer ()
dji.internal.version.a$a.onSuccess ()
dji.midware.data.model.P3.DataCommonGetVersion.start ()
dji.midware.data.model.P3.DataCommonGetVersion.start ()
dji.internal.version.a.b ()
dji.internal.version.a.c ()
dji.internal.version.a$a.onSuccess ()
dji.midware.data.manager.P3.u.callbackSuccess ()
dji.midware.data.manager.P3.u.access$200 ()
dji.midware.data.manager.P3.w.run ()
java.lang.Thread.run (Thread.java:761)
```

**Comment by oliverou** [comment]
Hi @jtuchek,  please try the latest Android SDK 3.4.1 and check if the issue still exists. Also, could you tell me which component you use to get the firmware version? 

Also, please provide the following info for use to reproduce the issue:

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Which firmware version of the aircraft do you use?
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

**Comment by jtuchek** [comment]
I cannot, it was pulled from our crash reporting system and I don't have those things being attached for additional information at the moment.

**Comment by jtuchek** [comment]
I don't have a complete list of information - I pulled this from our crash reporting software.

Affected Android Devices:
HTC Nexus 9 API 24
Dell Venue 8 API 23

DJI Device used:
Phantom 4 (firmware unknown)

**Comment by oliverou** [comment]
@jtuchek, we have just launched the Android SDK 3.5. Could you download it and try if the issue still exist? Thanks!
