### ISSUE TITLE
MSDK 4.13 一定需要'arm64-v8a' 么？

### ISSUE THREAD

**Issue by Mac-sir** [dji-sdk/Mobile-SDK-Android#590]
Demo 设置 ndk {  abiFilters 'armeabi-v7a' } 运行demo ，就会creash ：

#00 pc 00008e84 /lib/arm/libDJIMOP.so2020-08-17 14:23:54.456 2037-2037/? A/DEBUG:     #01 pc 0000ab57 lib/arm/libDJIMOP.so2020-08-17 14:23:54.456 2037-2037/? A/DEBUG:     #02 pc 0000c88d lib/arm/libDJIMOPJni.so (Java_dji_mop_core_MOPCore_init+236)

设置  ndk {  abiFilters 'armeabi-v7a'，'arm64-v8a' }  就正常运行。

请问  MSDK 4.13 一定需要'arm64-v8a' 么？ 有什么方法可以不使用'arm64-v8a'？

**Comment by Mac-sir** [comment]
设备是 M300 RTK  (Android 7.1.2)

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/38138'>Zendesk ticket #38138</a>:<br><br>您好，如果是arm64-v8a的设备是必须要加上arm64-v8a的

**Comment by Mac-sir** [comment]
我从机型上去查了一下设备，御2双光和M300都是arm64-v8a，其中御2双光就运行的好好的，M300就会崩溃，同是v8a 还有特殊的存在？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DJI"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 下午3:07
收件人: "dji-sdk/Mobile-SDK-Android";
抄送: "Author";
主题: Re: [dji-sdk/Mobile-SDK-Android] MSDK 4.13 一定需要&#39;arm64-v8a&#39; 么？ (#590)





 
Agent comment from Hummels Lei in Zendesk ticket #38138:

您好，如果是arm64-v8a的设备是必须要加上arm64-v8a的
 
&mdash;

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by Michael-DJI** [comment]
用的同一台手机吗 @Mac-sir

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/38138'>Zendesk ticket #38138</a>:<br><br>您好，只有M300要用到MOP功能。添加 arm64-v8a 是为了解决MOP功能代码的兼容性问题。

**Comment by Mac-sir** [comment]
好的，谢谢。

**Comment by z376368673** [comment]
> 好的，谢谢。

您好 我也正在做类似的项目 能不能留个联系方式 相互交流？

**Comment by FuXiangGit** [comment]
楼主这个问题解决了吗？同求
