### ISSUE TITLE
Mini 连接后显示IMU ERROR, 重启App再进入显示正常

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#594]
通过以下方式监听IMU

```
private val imuObservable: Observable<IMULogic.IMUEvent> = LogicEventBus.getInstance().register(
        IMULogic.IMUEvent::class.java
 ).observeOn(Schedulers.computation())

fun checkIMU(){
  val imuAction = object : Action1<IMULogic.IMUEvent> {
      override fun call(p0: IMULogic.IMUEvent?) {
         postResult(p0?.message)
      }
  }
  imuObservable.subscribe(imuAction)
  LogicManager.getInstance().startIMULogic()
}

fun postResult(msg: Message?){
  val type = msg?.type ?: return
  val hasError = when (type) {
    Message.Type.WARNING,
    Message.Type.ERROR -> true
    Message.Type.GOOD -> false
    else -> false
  }
  // 如果是首次使用, 必是ERROR
  // 此时后台杀死App, 再次进入, 返回GOOD
}
```

返回Error 偶发, 但是重启App后就好了

监听方式通过查看PreFlightChecklistPanel控件的源码实现

返回Message
```
msg = {Message@18555} 
 description = null
 flag = 0
 shouldBlink = false
 title = "Abnormal"
 type = {Message$Type@18542} "ERROR"
 shadow$_klass_ = {Class@14851} "class dji.internal.logics.Message"
 shadow$_monitor_ = -2070277348
```

**Comment by luoyexk** [comment]
在设置里清除App 数据后可复现

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/38404'>Zendesk ticket #38404</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

不确定是不是PreFlightChecklistPanel的问题，你直接从MSDK里面调用IMU相关函数看看是否会报错呢？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by luoyexk** [comment]
1. 在查看PreFlightChecklistPanel时, IMU显示红色异常字样

2. 怎么判断IMU是否异常，Compass还可以通过`flightController?.compass?.hasError()`判断, 但IMU没有相关接口。

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/38404'>Zendesk ticket #38404</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

调用startIMUCalibration可以看一下IMU校准是否正常，一般第一次启动需要校准IMU。
IMU相关类：https://developer.dji.com/api-reference/android-api/Components/IMUState/DJIIMUState.html

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
