### ISSUE TITLE
API Level 29

### ISSUE THREAD

**Issue by cwbsl** [dji-sdk/Mobile-SDK-Android#595]
How can it be that Google Play sends an E-Mail to update targetSDKVersion to at least API Level 29 and the sample code still targets API level 28 2 months before the deadline by Google?
When will this be updated to the newest version?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/38410'>Zendesk ticket #38410</a>:<br><br>Dear Client
Thank you for contacting DJI.

Please change the tartgetAPI to 29, our SDK already support API version 29. We just forget to change the Sample Project's target API version.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by cwbsl** [comment]
Thanks, it also works with API 29. I just had the problem beginning of this year that the SDK wasn't compatible with a new API level and there was nothing we could do. But it works good now, thanks!
