### ISSUE TITLE
Too much log coming from DJI SDK

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#6]
The SDK is often logging __a lot__ of lines in the debug logcat. They all start with: 头校验失败.

It is possible to remove the logcat output in the SDK? A library should probably never spam the log output, ideally.

**Comment by SilverChangjian** [comment]
Thanks for your reporting the bugs, this has been fixed by our colleague.

Sorry for the annoyance.

**Comment by JonasVautherin** [comment]
Still not fixed in 2.4.1.

I get messages such as `upload t3.5` or `fullBuffer 长度不够`. Ideally, the release versions of the SDK should not spam the "Debug" logcat channel...

**Comment by SilverChangjian** [comment]
In 3.0.1, we fix the logging problems. I would close this issues.

**Comment by Nitaym** [comment]
Not fixed in 3.4. Can we reopen this?

**Comment by oliverou** [comment]
Hi @Nitaym, we have just launched the new Android SDK 3.4.1, please try it and check if the issue still exists, thanks!

**Comment by Nitaym** [comment]
Yes, verified in 3.4.1
