### ISSUE TITLE
Release Notes?

### ISSUE THREAD

**Issue by Nitaym** [dji-sdk/Mobile-SDK-Android#60]
I'm trying to find the changes between the different SDK versions. Namely - What was changed in the latest (3.5) release.

Could you please post some release notes?

Thanks

**Comment by oliverou** [comment]
Hi @Nitaym, please get the release notes from DJI Developer Website: <https://developer.dji.com/mobile-sdk/downloads/>

![screen shot 2016-12-15 at 4 14 16 pm](https://cloud.githubusercontent.com/assets/13310805/21216415/a09f991c-c2e1-11e6-912e-80fc21f9dc26.png)

**Comment by Nitaym** [comment]
Got it, thanks!

**Comment by JonasVautherin** [comment]
That issue can probably be closed, now.

**Comment by oliverou** [comment]
Since the issue is resolved, close it now.

**Comment by mordka** [comment]
https://developer.dji.com/mobile-sdk/downloads/

1. That page needs account to access.
2. After logging in and accessing the release notes, there is AWS IAM error: `The AWS Access Key Id you provided does not exist in our records.`

@oliverou Could you just upload the release notes to the code repo? As it is done with UX library already?
