### ISSUE TITLE
Landing Gear can't be controlled by dji mobile sdk

### ISSUE THREAD

**Issue by pelosi** [dji-sdk/Mobile-SDK-Android#607]
### Landing Gear Issue

The Landing Gear can be controlled successfully by toggling the landing gear switch of a remote controller

It is configured in DJI GO app:
    - Self-Adaptive Landing Gear: Disabled
    - Disable Landing Gear Auto Lock: Enabled

But Android app for DJI Mobile SDK won't work and the following errors occur.

**"The feature is unsupported"**

In details, the states or errors are:

- isLandingGearMovable: true (ok)
- landingGearState: null (fail)
- landingGearMode: null (fail)
- getAutomaticMovementEnabled / onResult / djiError: The feature is unsupported.  (fail)
- setAutomaticMovementEnabled / onResult / djiError: The feature is unsupported.  (fail)
- deploy / onResult / djiError: The feature is unsupported.  (fail)
- retract / onResult / djiError: The feature is unsupported.  (fail)

Devices and sdk:
- Matrice 600 Pro
- Android Samsung Gallaxy Tab S4
- DJI mobile SDK 4.11

How can i control a landing gear to be retract and deploy using mobile sdk?

### PS. can i turn on and off LEDs in motor arms for Matrice 600 pro using mobile sdk?

Best Regards.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/38817'>Zendesk ticket #38817</a>:<br><br>Dear Client
Thank you for contacting DJI.

I am sorry to inform you that the M600/M600 Pro does not support landing gear control through SDK. You can set LED through setLEDsEnabledSettings.
Link：https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html#djiflightcontroller_setledsenabledsettings_inline
 ![](https://djisdksupport.zendesk.com/attachments/token/WF9xXmz94ok6SwByXTKGAdkLx/?name=inline-624299135.png)​

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/WF9xXmz94ok6SwByXTKGAdkLx' target='zd_attach'>inline-624299135.png</a>
