### ISSUE TITLE
fetchFileData 出现图片损坏(Picture is damaged)

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#611]
使用fetchFileData后, 偶发的出现图片破损情况, 破损的图片往往是第一张下载的, 但是该图片在SD卡中是正常

这张下载后的图片大小, 元数据, 中图, 缩略图全部正常, 只有大图出现显示异常

![image](https://user-images.githubusercontent.com/20855787/92444392-65720f00-f1e5-11ea-80df-72399be79260.png)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/38935'>Zendesk ticket #38935</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
