### ISSUE TITLE
OSMO mobile 4 supported?

### ISSUE THREAD

**Issue by ienariden** [dji-sdk/Mobile-SDK-Android#612]
Hi, I'd like to know if OSMO mobile 4 is supported from SDK. Because I tryied the sample App for android and the device sometime get connected but not always, anyway, when the device get connection, the the sample features are not working (moving with speed, etc etc).
Is it the model supported by SDK?
Thank you

**Comment by ienariden** [comment]
Solved, I figured out that after turning on the device I had to push the M button again in order to "wake it up". After that it seem to connect and work.

**Comment by utya** [comment]
@ienariden do you connect sdk sample app to osmo 4?

**Comment by ienariden** [comment]
> 
> 
> @ienariden do you connect sdk sample app to osmo 4?

Yes, after setting the device in the center position with M button, it started to connect.

**Comment by utya** [comment]
@ienariden its very strange. Because officialy sdk doesnt support osm4. Can you control angles of the phone via sdk app?
