### ISSUE TITLE
关于DJI GO APP和MSDK的一些疑问

### ISSUE THREAD

**Issue by dashifuguye** [dji-sdk/Mobile-SDK-Android#617]
使用MSDK如何获取DJI GO APP 中的无线信道质量、遥控器信号以及数传信号

![image](https://user-images.githubusercontent.com/21324724/93035939-fbd48380-f670-11ea-9683-85941dfcbf85.png)

![image](https://user-images.githubusercontent.com/21324724/93035963-098a0900-f671-11ea-8d38-3e3294b7e90d.png)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/39111'>Zendesk ticket #39111</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

无线信道质量，WiFiSignalWidget
Link：https://developer.dji.com/api-reference/android-uilib-api/Widgets/DUXWiFiSignalWidget.html

遥控器信号，RemoteControllerSignalWidget
Link：https://developer.dji.com/api-reference/android-uilib-api/Widgets/RemoteControllerSignalWidget.html

数传信号，VideoSignalWidget
Link：https://developer.dji.com/api-reference/android-uilib-api/Widgets/VideoSignalWidget.html

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
你好，你说的是UX SDK，并不是Mobile SDK，我想问的是Mobile SDK里有对应的函数吗？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/39111'>Zendesk ticket #39111</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

UXSDK也是再Mobile SDK的基础上封装的，你是想获得封装前的原始值对吧。

无线信道质量，setUplinkSignalQualityCallback
Link：https://developer.dji.com/api-reference/android-api/Components/AirLink/DJIAirLink.html#djiairlink_setuplinksignalqualitycallback_inline

遥控器信号，getSignalQuality
Link：https://developer.dji.com/api-reference/android-api/Components/RemoteController/DJIRemoteController_DJIRCInfo.html#djiremotecontroller_djircinfo_signalquality_inline

数传信号，setDownlinkSignalQualityCallback
Link：https://developer.dji.com/api-reference/android-api/Components/AirLink/DJIAirLink.html#djiairlink_setdownlinksignalqualitycallback_inline

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
好的，我试试，感谢

**Comment by dashifuguye** [comment]
另外想问下，有没有api可以知道飞机是否正在没电迫降

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/39111'>Zendesk ticket #39111</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

没电迫降这个需要你自己去定义。在达到了某个警戒线的时候去定义它的行为，通常是Level1返航，Level2降落。
 ![](https://djisdksupport.zendesk.com/attachments/token/Gi7KESbENmVdMVGKkWmdaREIu/?name=inline645217540.png)​

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/Gi7KESbENmVdMVGKkWmdaREIu' target='zd_attach'>inline645217540.png</a>

**Comment by dashifuguye** [comment]
好的，DJI SDK内部有设置没电迫降的电量吗？我们使用的M600，发现有时候电量到13%或者14%就会自动降落了，而msdk中设置的setSeriousLowBatteryWarningThreshold参数值是10。

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/39111'>Zendesk ticket #39111</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

你可以自己设置这个参数，这个参数是可以自由设定的。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
