### ISSUE TITLE
Update to compileSdkVersion = 29

### ISSUE THREAD

**Issue by Consti10** [dji-sdk/Mobile-SDK-Android#623]
It would be great if the sdk supported building for the latest version of android.
Currently, it throws the following error message:
 Attempt to invoke virtual method 'java.io.File android.content.Context.getExternalFilesDir(java.lang.String)' on a null object reference

Probably the sdk did not make the proper changes to react to the storage changes introduced with api 29

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/39379'>Zendesk ticket #39379</a>:<br><br>Dear Client
Thank you for contacting DJI.

Our 4.13.1 MSDK has adapted with AndroidSDKversion 29. You also need to change TargetSDKVersion to 29.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by Consti10** [comment]
Thanks for your prompt response

**Comment by Consti10** [comment]
However, the sample here https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle
still uses api 28.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/39379'>Zendesk ticket #39379</a>:<br><br>Dear Client
Thank you for contacting DJI.

The sample hasn't been up to date, you can try and update here your result.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by luoyexk** [comment]
> However, the sample here https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/build.gradle
> still uses api 28.

Our products on Google Play have used version 29.

```
        compileSdkVersion = 29
        buildToolsVersion = '29.0.2'
        minSdkVersion = 23
        targetSdkVersion = 29
```
