### ISSUE TITLE
OSMO3 & 4 support

### ISSUE THREAD

**Issue by YichaoW** [dji-sdk/Mobile-SDK-Android#626]
Does mobile SDK support osmo3 or 4? I found that DJI does not sell osmo2 in China anymore.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/39660'>Zendesk ticket #39660</a>:<br><br>Dear Client
Thank you for contacting DJI.

SDK currently does not support Osmo 3 and 4 and currently we don't have plan to support them.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
