### ISSUE TITLE
Fetch media from Phantom 4 always fail

### ISSUE THREAD

**Issue by ltluc253** [dji-sdk/Mobile-SDK-Android#63]
I use method [fetchMediaData](https://developer.dji.com/iframe/mobile-sdk-doc/android/reference/dji/sdk/Camera/DJIMedia.html#fetchMediaData) to fetch media from Phantom devices. It work fine for Phantom 3, but SDK alway return error below when fetching data from Phantom 4
- Execution of this process has timed out
- Download media file error: Media download result: the client aborted the download

I've checked my code. It have same flow with your sample code. I also check your sample app, It fetch media data success 5/10 times. Please help me resolve this problem.
My Environment:
 - DJI Product: Phantom 4, (Phantom 3 is working OK)
 - Android device: Nexus 9
 - Android version 5.0.1
 - Android Studio 2.2
 - DJI SDK version 3.5.1

Thank you

**Comment by kenargo** [comment]
Are you putting the camera into download mode?  It will report a timeout error if you don't set the camera mode. ⁣

**Comment by ltluc253** [comment]
@kenargo Yes, I call [setCameraModeMediaDownload](https://developer.dji.com/iframe/mobile-sdk-doc/android/reference/dji/sdk/Camera/DJIMediaManager.html#setCameraModeMediaDownload(dji.sdk.base.DJIBaseComponent.DJICompletionCallback)) before start fetch media data. I think issue cause by performance of  fetchMediaData method.
When the app start fetch media data, RAM amount of app increase very fast

**Comment by SilverChangjian** [comment]
Hi @ltluc253 , thanks for reporting this bugs.The method `setCameraModeMediaDownload` has been deprecated. Please use setCameraMode() in DJICamera instead of setCameraModeMediaDownload() in DJIMediaManager.

**Comment by ltluc253** [comment]
@SilverChangjian thank for your support. I also use setCameraModeMediaDownload() to change DJICamera mode to MediaDownload, but it doesn't work :( 
Is there another way to fetch media files from Drone?

**Comment by SilverChangjian** [comment]
Do you mind to share part of your code which will do the media fetch? That would be helpful for us to locate the problem.

**Comment by ltluc253** [comment]
@SilverChangjian Please check my flow
- I Get camera mode first
`                camera.getCameraMode(new DJICommonCallbacks.DJICompletionCallbackWith<DJICameraSettingsDef.CameraMode>() {
                    @Override
                    public void onSuccess(DJICameraSettingsDef.CameraMode cameraMode) {
                        if (cameraMode != DJICameraSettingsDef.CameraMode.MediaDownload) {
                            setCameraMediaDownloadMode();
                        } else {
                            startFetchMedia();
                        }
                    }
                });`
- Set camera mode to MediaDownload if current state is differrence
`    private void setCameraMediaDownloadMode(){
        DJICamera camera = DroneApplication.getCameraInstance();
        if (camera != null) {
            camera.setCameraMode(DJICameraSettingsDef.CameraMode.MediaDownload, djiError -> {
                if (djiError == null){
                    startFetchMedia();
                }
            });
        }
    }`
- Start fetch media list and compare. Note MediaInPoint Object is my Object is used to map between DJIMedia and Waypoint and our Point object
`    private void startFetchMedia(){
        DJICamera camera = DroneApplication.getCameraInstance();
        if (camera != null) {
            camera.getMediaManager().fetchMediaList(new GetMediaListTask(medias -> {
                if (medias != null && mMedias!= null) {
                    for (MediaInPoint mediaInPoint : mMedias) {
                        try {
                            Iterator<DJIMedia> iterator = medias.iterator();
                            while (iterator.hasNext()) {
                                DJIMedia djiMedia = iterator.next();
                                if (isSameMedia(mediaInPoint.getDJIMedias(), djiMedia)) {
                                    Log.d(TAG, "Has same media: " + djiMedia.getFileName());
                                    mediaInPoint.setDJIMedias(djiMedia);
                                    break;
                                }
                            }
                        } catch (Exception e) {
                            Crashlytics.logException(e);
                        }
                    }
                    downloadFile(0);
                }
            }));
        }
    }`
- Download Media in List
`private void downloadFile(int mediaIndex) {
        MediaInPoint mediaInPoint = mMedias.get(mediaIndex);
        DJIMedia media = mediaInPoint.getDJIMedias();
        File destDir = new File(mMediaFolderPath);
        media.fetchMediaData(destDir, media.getFileNameWithoutExtension(), new DJIMediaManager.CameraDownloadListener<String>(){

            private int mLastProgress = -1;

            @Override
            public void onStart() {}

            @Override
            public void onRateUpdate(long l, long l1, long l2) {}

            @Override
            public void onProgress(long l, long l1) {
            }

            @Override
            public void onSuccess(String s) {
                LogUtils.d(TAG, "The file has been store: " + s);
                downloadFinish(s);
            }

            @Override
            public void onFailure(DJIError djiError) {
                Log.e(TAG, "Download media file error: " + (djiError != null ? djiError.getDescription() : "no"));
                downloadFinish(null);
            }

            private void downloadFinish(String path) {
                //Process Next media in List
            }
        });
    }`

Please help review my flow of code, it work fine when I test on Phantom 3

**Comment by yormi** [comment]
Hi folks !

I encountered the same exact problem. I'm a bit clueless about how to solve this.

Any progress? Ideas ? Or maybe workaround ?

**Comment by khanhvu161188** [comment]
Any update for this issue?

**Comment by wenqianqiao** [comment]
Hi Do you meet the same problem for this issue on the Phantom 4 with the latest firmware on the Andrroid SDK version 4.1.1?

**Comment by khanhvu161188** [comment]
both old and new sdk give the same error

Khanh Vu
________________________________

**Comment by ltluc253** [comment]
In download progress, RAM usage increase to fast and onFailure to be called. It look like DJI SDK create new byte buffer for each data frame which is receive from Drone, and it don't release or reuse byte buffer of frame which is failure in CRC checking => using too much RAM in download progress, a low performance of code. RAM memory may be increase the hundred of MB in download process, even the downloaded file size least than 10 MB.
Try to download a large amount of files continuous, it will be failure many times

**Comment by khanhvu161188** [comment]
I do not know why DJI team did not fix this critical issue till now

**Comment by oliverou** [comment]
Hi @ltluc253 @khanhvu161188 , @yormi , we just launch the Android SDK 4.2, could you download it and try if this issue still exist?

If the issue still exist, please provide the following infos for us to better investigate the issue:

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
-  Android Studio version you are using (Like Android Studio 2.2, etc)

Thanks!

**Comment by ltluc253** [comment]
Hi @oliverou, @khanhvu161188 , @yormi 
This issue is been fixed on SDK version 4.2.1. Thank for effort of dev team.

**Comment by chubecode** [comment]
issues happen again on Phantom 4 Pro with latest SDK version..
