### ISSUE TITLE
How to get RTK status

### ISSUE THREAD

**Issue by Jaquelineds** [dji-sdk/Mobile-SDK-Android#634]
I'm trying to get the status of the RTK (connected or not connected) and I'm not getting the expected result. Is this the correct way for me to get this? I think that maybe the FlightControllerKey is another key (not RTK_STATE).

```
 val watchRTKState: Observable<String> by lazy {
        Observable.create { emitter: ObservableEmitter<String> ->
            KeyManager.getInstance()
                .getValue(
                    FlightControllerKey.createRTKKey(FlightControllerKey.RTK_STATE),
                    object : GetCallback {
                        override fun onSuccess(@NonNull value: Any?) {
                            if (value != null && value is RTKState) {
                                emitter.onNext(value.isRTKBeingUsed.toString())
                                Log.e(TAG, "Status do RTK obtido com sucesso: $value")
                            }
                        }
                        override fun onFailure(@NonNull error: DJIError?) {
                            Log.e(TAG, "Falha na obtenção do status do RTK: $error")
                        }
                    })
        }
    }
```

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40121'>Zendesk ticket #40121</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Please use the official method setStateCallback, it's not recommended to use the KEY way anymore.
 ![](https://djisdksupport.zendesk.com/attachments/token/ijHuoKmXMpTxxumEUmpiSFA4t/?name=inline-1580109591.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/ijHuoKmXMpTxxumEUmpiSFA4t' target='zd_attach'>inline-1580109591.png</a>

**Comment by Jaquelineds** [comment]
It worked for me! I'm am closing this issue now
