### ISSUE TITLE
RTMP livestream manager lag

### ISSUE THREAD

**Issue by annesteenbeek** [dji-sdk/Mobile-SDK-Android#638]
I'm using the RTMP livestream to view the video feed on my laptop. However, I'm noticing there is a "big" lag between the RTMP and the video feed of about 15 seconds.
This in itself isn't that big of a problem, however, I want to sync up the RTMP video with GPS data. Would this be possible?
Or is there any method to measure the delay?
I have already tried the `getStartTime()` method, however, this just returns the time the stream started, not the delay.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40216'>Zendesk ticket #40216</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The lag relates to so many factors, such as the internet, server, HD signal, etc.
So sorry that there is no way to sync up the RTMP video with GPS data, the MSDK doesn't support it with the Livestream feature.

Thanks,

Luce Luo
DJI Developer Support

**Comment by annesteenbeek** [comment]
Ok, I think I could sync it up by checking for the black screens that occur when taking an image, however, it might be an interesting feature to add the ability to sync live video feed and GPS/IMU with the MSDK. This could be of great value for remote sensing purposes.

Thanks for the response.
