### ISSUE TITLE
Why the thread named SwUdpService was aways running

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#643]
![无标题](https://user-images.githubusercontent.com/20855787/97256171-4ab73080-184d-11eb-8b6e-13d9808e5f84.jpg)

![image](https://user-images.githubusercontent.com/20855787/97256281-9a95f780-184d-11eb-9851-95879eabb82f.png)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40461'>Zendesk ticket #40461</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team

**Comment by luoyexk** [comment]
已发送
