### ISSUE TITLE
sdk能否实现先发送完成航点任务然后再起飞。

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#644]

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40496'>Zendesk ticket #40496</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
航点任务是可以在地面发送成功后再起飞的，也可以在空中发送任务。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
