### ISSUE TITLE
Repeated Remove AUD in logs

### ISSUE THREAD

**Issue by Nitaym** [dji-sdk/Mobile-SDK-Android#65]
-  Description of the issue.
The message "Remove AUD" is repeated many times a second in the debug log (instead, if you choose to keep it, of the verbose log").
This message really gives a hard time debugging other issues

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
Every run

-  Crash logs (If you can find it, it would be very helpful)
-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
3.5

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Phantom 4, Mavic Pro

-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
Android 6 and above

-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
Nexus 5

-  Android Studio version you are using (Like Android Studio 2.2, etc)
2.2.3

**Comment by oliverou** [comment]
Hi @Nitaym , thanks for the feedbacks, we will remove such logs in the upcoming SDK version.

**Comment by vo** [comment]
I also have this problem.

- Description of the issue.
The message "Remove AUD" is repeated many times a second in the debug log

- Steps to reproduce the bug or crash issues(It would be great if you can provide this)
Every run

- Crash logs (If you can find it, it would be very helpful)

- DJI Android SDK version you are using (Like Android SDK 3.4, etc)
4.0.2

- DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Phantom 4, Mavic Pro

- Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
Android 6 and above

- Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
Nexus 7, NVIDIA Shield K1

- Android Studio version you are using (Like Android Studio 2.2, etc)
2.3.1

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by greuff** [comment]
SDK version 4.4.1: problem still exists:

...
03-21 11:57:58.228 10455-10973/com.dimetor.androiddji D/DJI: Remove AUD
03-21 11:57:58.246 10455-10973/com.dimetor.androiddji D/DJI: Remove AUD
03-21 11:57:58.279 10455-10973/com.dimetor.androiddji D/DJI: Remove AUD
03-21 11:57:58.309 10455-10973/com.dimetor.androiddji D/DJI: Remove AUD
03-21 11:57:58.345 10455-10973/com.dimetor.androiddji D/DJI: Remove AUD
03-21 11:57:58.393 10455-10973/com.dimetor.androiddji D/DJI: Remove AUD
...
