### ISSUE TITLE
Timeline bug添加2个自动任务。当第一个任务执行过程中，遥控器切换模式或者点击返回或者降落按钮导致飞机自动任务结束时。timeline会自动触发并上传第二个任务的航点。

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#651]

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40619'>Zendesk ticket #40619</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

请问你的机型是哪部，MSDK版本是多少，飞控固件版本是多少？我们安排测试工程师测试一下。另外，如果你是用航点任务的话可以考虑一下使用WaypointMission或者WaypointV2Mission。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by SJJ-dot** [comment]
我猜都能猜到你们为什么会出现这个bug。
