### ISSUE TITLE
Hotpoint mission M300

### ISSUE THREAD

**Issue by japelaez6894** [dji-sdk/Mobile-SDK-Android#655]
Hi,

We are trying to implement a Hotpoint mission for Matrice 300, since in the API reference it is said that the only non-compatible series is Spark. However, when executing the following code, we obtain a `NOT_SUPPORTED` state for the HotpointMissionOperator. Is it not compatible, thus? Is it a bug?

```
private HotpointMissionOperator hotpointMissionOperator = null;

if (DJISDKManager.getInstance().getMissionControl() != null) {
                hotpointMissionOperator = DJISDKManager.getInstance().getMissionControl().getHotpointMissionOperator();
                Log.i(TAG, "hotpointMissionOperatorState = " + hotpointMissionOperator.getCurrentState().toString());
```

DJI Android SDK version: 4.13.1
DJI Product: Matrice 300 RTK

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40708'>Zendesk ticket #40708</a>:<br><br>Dear Client
Thank you for contacting DJI.

I am sorry that the hotpointMission is built long time ago and we havn't update it for a long time. Therefore it does not support some advanced model such as M300RTK. Indeed, the M300RTK does not support hotpointMission and I will report to the documentation engineer for changing it. Sorry.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
