### ISSUE TITLE
registerErrorHandler 我看到dji sdk有一些崩溃。这么处理有没有问题？

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#656]
```kotlin
            dji.thirdparty.rx.plugins.RxJavaPlugins.getInstance().registerErrorHandler(object : RxJavaErrorHandler() {

                override fun handleError(e: Throwable?) {
                    val thread = Thread.currentThread()
                    Logger.e(e, "捕获异常 thread：$thread")
                    val lastErrorHandler = thread.uncaughtExceptionHandler
                    thread.uncaughtExceptionHandler = Thread.UncaughtExceptionHandler { t, e ->
                        thread.uncaughtExceptionHandler = lastErrorHandler
                    }
                }
            })
```

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40727'>Zendesk ticket #40727</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

你好，dji.thirdparty.rx.plugins.RxJavaPlugins是在哪里找到的包？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by SJJ-dot** [comment]
> RxJavaPlugins

？？你们的SDK.

**Comment by SJJ-dot** [comment]
> Agent comment from William Wong in [Zendesk ticket #40727](https://djisdksupport.zendesk.com/agent/tickets/40727):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> 你好，dji.thirdparty.rx.plugins.RxJavaPlugins是在哪里找到的包？
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持

？？你们的SDK.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40727'>Zendesk ticket #40727</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

你好，这个包是第三方库，只是被包在了dji library里，使用方法在网上搜索ReactiveX/RxJava的第一代库可以搜到。你这样设置应该问题不大，UncaughtExceptionHandle可以检测出某个由于未捕获的异常而终结的情况，可以有效地防止线程泄露问题。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
