### ISSUE TITLE
v2航点触发器。按时间循环那个，怎么能主动停止 SIMPLE_INTERVAL

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#661]
```
 WaypointTrigger.Builder()
                    .setTriggerType(ActionTypes.ActionTriggerType.SIMPLE_INTERVAL)
                    .setIntervalTriggerParam(WaypointIntervalTriggerParam.Builder()
                            .setType(ActionTypes.ActionIntervalType.TIME)
```

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/40810'>Zendesk ticket #40810</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
无法主动停止，只能等待执行完毕或者通过停止整个Mission方式停止。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
