### ISSUE TITLE
SDK 4.13.1 是否支持 Mini2 

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#662]
最新SDK能兼容新出Mini2么

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40812'>Zendesk ticket #40812</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

目前SDK团队没有支持Mini 2的计划，产品团队仍在内部讨论。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by luoyexk** [comment]
多谢！
