### ISSUE TITLE
Mini 2 Support?

### ISSUE THREAD

**Issue by mtvrdinic** [dji-sdk/Mobile-SDK-Android#668]
Any plans on adding support for Mini 2? Will it get supported at all since it's lost the Mavic branding?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/40980'>Zendesk ticket #40980</a>:<br><br>Dear Client
Thank you for contacting DJI.

Currently the SDK team has no plan to support Mini 2 recently, the project team still needs to discuss internally.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by TheunisKotze** [comment]
So there's support for the mavic mini, but not the mini 2 ? why ?

**Comment by mo8Zomo0** [comment]
Yes, I also find the lack of the API is a big issue

**Comment by arismelachroinos** [comment]
> Agent comment from William Wong in [Zendesk ticket #40980](https://djisdksupport.zendesk.com/agent/tickets/40980):
> 
> Dear Client
> Thank you for contacting DJI.
> 
> Currently the SDK team has no plan to support Mini 2 recently, the project team still needs to discuss internally.
> 
> Hopefully our solution can help you.
> Kindly Regards,
> DJI Developer Support

So, how did the discussion go?

**Comment by Michael-DJI** [comment]
4.16 will support mini2

**Comment by dmastag** [comment]
4.16 is released now, does this mean that Mini 2 Support is in?
