### ISSUE TITLE
Video streaming APIs

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#67]
Is there any functional difference in receiving video data back from `DJICamera` vs `DJILBAirLink`?

Or any reason to get video from the LightBridge AirLink instead? Since there isn't similar methods in the OcuSync implementation for the Mavic or the FPV camera on the Inspire 2.

**Comment by oliverou** [comment]
Hi @jtuchek, please use the one in AirLink only when the instance of DJICamera is not available.
