### ISSUE TITLE
与OSDK开发的设备通讯失败，返回错误 DJIPipelineError: The target device refuses to connect.", -10017

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#671]
dji.mop.common.Pipelines#connect

DJIPipelineError: The target device refuses to connect.", -10017

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41014'>Zendesk ticket #41014</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by SJJ-dot** [comment]
改成使用 `sendDataToOnboardSDKDevice` 这个方法了
