### ISSUE TITLE
refreshFileListOfStorageLocation - Execution of this process has timed out(255)

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#673]
调用[refreshFileListOfStorageLocation](https://developer.dji.com/api-reference/android-api/Components/Camera/DJIMediaManager.html?search=refreshfilelistofstoragelocation&i=0&#djimediamanager_refreshfilelistofstoragelocation_inline)时出现`Execution of this process has timed out(255)`

什么情况下会抛出这个异常，目前测试无法复现该问题，但生产上遇到了

MSDK：4.13.1
无人机固件：最新
手柄：最新

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41076'>Zendesk ticket #41076</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
这个是个超时错误，导致原因可能是SD卡内文件太多，拉取中断导致，也可能是旧版SDK的问题，建议您使用最新版本，尝试多次拉取试试。

如果问题出现概率很大，为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn
在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
