### ISSUE TITLE
FPVWidget视频总是有水印

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#677]
环境：御2，msdk4.0, 安卓10
使用示例程序，看到其中视频播放是FPVWidget控件，之前还没有水印，但是最近总是浮着一层水印"Mavic 2 Pro Camera"。
请问怎么去掉这个水印？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/41134'>Zendesk ticket #41134</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

你看看用setSourceCameraNameVisibility能否去掉。
Link：https://developer.dji.com/api-reference/android-uilib-api/Widgets/DULFPVWidget.html#duxfpvwidget_setsourcecamerasidevisibility_inline

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
按上面方法成功搞定 感谢支持！
