### ISSUE TITLE
DJIGimbalAttitudeStep in custom mission not working in SDK 3.5.1

### ISSUE THREAD

**Issue by JamesMastermanDev** [dji-sdk/Mobile-SDK-Android#68]
I have some code that creates a custom mission. One of the first mission steps is to tilt the gimbal using a DJIGimbalAttitudeStep. This worked fine in any of the 3.3.x and 3.4.x versions of the SDK. 

In SDK 3.5.1, the gimbal no longer responds to this mission step. 

I am creating the step as follows, to tilt the gimbal at 45 degrees downwards, then adding to a custom mission. This worked perfectly in early SDK versions, but in SDK 3.5.1 the gimbal does not respond.

new DJIGimbalAttitudeStep(DJIGimbalRotateAngleMode.AbsoluteAngle,
                                                new DJIGimbalAngleRotation(true, -45, DJIGimbalRotateDirection.Clockwise),
                                                  null,
                                                 null),
                                                 new DJICompletionCallback()
                                                {
                                                  @Override
                                                  public void onResult(DJIError djiError)
                                                  {
                                                    if(djiError != null)
                                                    {
                                                       Log.e(getClass().getSimpleName(), "GimbalAngle error " + djiError.getDescription());
                                                     }
                                                  }
                                                });

- I am using Android 6.0.1 on Samsung S2 tablets and S7 phones. 
- SDK 3.5.1
- Phantom 4 running the latest firmware (1.2.602.0)
- Android studio 2.2.3

**Comment by xxmaestroxx** [comment]
Hey DJI,

what is the status of this issue?

Regards
Maestro

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Also, for controlling Gimbal Attitude, please check out the new `MissionControl` and `GimbalAttitudeAction` classes.
Thanks!
