### ISSUE TITLE
msdk 使用P4R 想要在室内飞行执行航线任务，是否能够实现呢？如果可以需要做哪些工作呢

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#681]
msdk 使用P4R 想要在室内飞行执行航线任务，是否能够实现呢？如果可以需要做哪些工作呢

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/41353'>Zendesk ticket #41353</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

室内没有办法飞航线任务，因为GPS/RTK信号太弱了。室内只能根据视觉系统飞行+虚拟摇杆飞行。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
