### ISSUE TITLE
SD卡，内置存储卡相关功能需求

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#682]
SDK有没有主动查询 StorageState的方法，且不通过KeyManager（因为你们不推荐使用）
如果没有是否考虑提供主动获取StorageState的方法。

通过`setStorageStateCallBack`获取最新的StorageState过于被动

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/41362'>Zendesk ticket #41362</a>:<br><br>SDK有没有主动查询 StorageState的方法，且不通过KeyManager（因为你们不推荐使用）
如果没有是否考虑提供主动获取StorageState的方法。

通过`setStorageStateCallBack`获取最新的StorageState过于被动

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41362'>Zendesk ticket #41362</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，除了setStorageStateCallBack方法外，没有其他您指的主动获取方法。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
