### ISSUE TITLE
能不能拿到飞机的当前的时间。无人机的文件创建修改时间和手机的时间对不上

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#685]
能不能拿到飞机的当前的时间。无人机的文件创建修改时间和手机的时间对不上

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/41436'>Zendesk ticket #41436</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

无人机的时间是根据手机时间同步的，按理来说时间是一样的，以前也有客户说起过这个问题，但是我测试的时候没有办法复现，你能找到必现步骤吗？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by SJJ-dot** [comment]
> Agent comment from William Wong in [Zendesk ticket #41436](https://djisdksupport.zendesk.com/agent/tickets/41436):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> 无人机的时间是根据手机时间同步的，按理来说时间是一样的，以前也有客户说起过这个问题，但是我测试的时候没有办法复现，你能找到必现步骤吗？
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持

首先我要能拿到你们无人机当前的时间才好调试，其次我怀疑是你们的文件系统的bug。现在的表现就是照片的时间和手机对不上，后面有空的话我会去试试能不能稳定复现。
