### ISSUE TITLE
限飞区重叠是否需要解锁所有重叠的空域

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#688]
![B89F17D4-AA26-47bd-90E1-61601867E82D](https://user-images.githubusercontent.com/20855787/100432146-252f7800-30d4-11eb-8674-e892afcb8a6d.png)

![duplicate-restricted](https://user-images.githubusercontent.com/20855787/100574989-294ad800-3316-11eb-8eb5-c424621f0949.jpg)

如下两个问题：
1. 限飞区重叠禁飞区和授权区解禁流程疑问
如图1：限飞区包含禁飞区，授权区，在已经申请解禁证书后，
调用 `reloadUnlockedZoneGroupsFromServer()`和 `syncUnlockedZoneGroupToAircraft()`后，是否还需要调用`unlockFlyZones(authorizationIds)`，即解锁以当前区域最高安全级别为准，最高安全级别被解锁，其他的限制就不用考虑，比如授权，限高等；

2. 限飞区重叠禁飞区解禁流程疑问
如图2：当前区域有两个禁飞区，但是`void enableCustomUnlockZone(@Nullable CustomUnlockZone zone, @Nullable final CompletionCallback callback)`只有允许串一个区域，文档中说明，激活一个将自动取消其他已激活的区域，这种情况下，如何解禁

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41513'>Zendesk ticket #41513</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，能够确认下您目前使用的是否是MSDK？
这边没查找到您描述的方法“调用 reloadUnlockedZoneGroupsFromServerCoroutine()和 syncUnlockedZoneGroupToAircraftCoroutine()后，是否还需要调用unlockFlyZonesCoroutine(authorizationIds)”。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by luoyexk** [comment]
`void getUnlockedFlyZonesForAircraft(@NonNull final CompletionCallbackWith<List<FlyZoneInformation>> callback)`这个方法名称是否写错，应该为`getUnlockedFlyZonesFromAircraft`，和Custom unlocking里的`getCustomUnlockZonesFromAircraft`对应

For -> From

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41513'>Zendesk ticket #41513</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
命名没有错误，getUnlockedFlyZonesForAircraft来源有两个，详见API文档描述：
 ![](https://djisdksupport.zendesk.com/attachments/token/bR6H2gDV8RPgb5PYWcd3Wlsbs/?name=inline2108624164.png)​

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/bR6H2gDV8RPgb5PYWcd3Wlsbs' target='zd_attach'>inline2108624164.png</a>

**Comment by luoyexk** [comment]
@dji-dev  

第一个问题有时间看下


> ![B89F17D4-AA26-47bd-90E1-61601867E82D](https://user-images.githubusercontent.com/20855787/100432146-252f7800-30d4-11eb-8674-e892afcb8a6d.png)
> 
> ![duplicate-restricted](https://user-images.githubusercontent.com/20855787/100574989-294ad800-3316-11eb-8eb5-c424621f0949.jpg)
> 
> 如下两个问题：
> 
> 1. 限飞区重叠禁飞区和授权区解禁流程疑问
>    如图1：限飞区包含禁飞区，授权区，在已经申请解禁证书后，
>    调用 `reloadUnlockedZoneGroupsFromServer()`和 `syncUnlockedZoneGroupToAircraft()`后，是否还需要调用`unlockFlyZones(authorizationIds)`，即解锁以当前区域最高安全级别为准，最高安全级别被解锁，其他的限制就不用考虑，比如授权，限高等；
> 2. 限飞区重叠禁飞区解禁流程疑问
>    如图2：当前区域有两个禁飞区，但是`void enableCustomUnlockZone(@Nullable CustomUnlockZone zone, @Nullable final CompletionCallback callback)`只有允许串一个区域，文档中说明，激活一个将自动取消其他已激活的区域，这种情况下，如何解禁
