### ISSUE TITLE
Mavic2 Pro sample-code构建的app无法通过usb连接到手柄

### ISSUE THREAD

**Issue by AlmostNoMemory** [dji-sdk/Mobile-SDK-Android#690]
你好开发者！

4.13.1版本的sample-code 构建安装到手机上之后，能正常注册之类的
![IMG_20201201_145807](https://user-images.githubusercontent.com/45009040/100707541-ce80b180-33e5-11eb-985c-971d09890b2d.jpg)
![IMG_20201201_145844](https://user-images.githubusercontent.com/45009040/100707550-d0e30b80-33e5-11eb-864a-baa842311c04.jpg)

但是使用usb线把手机连接到遥控器的usb端口之后没有反应。
就是并没有如文档里写的那样，在把手机连接到遥控器上之后，会弹出DJI SDK Sample的对话框

遥控器的安卓版本是7  检查更新已经是最新的了
手机是红米9a和小米note8，安卓版本是10

请问下是什么问题呢？ 是因为遥控器不支持吗？
遥控器的版本是这样的：
![IMG_20201201_150457](https://user-images.githubusercontent.com/45009040/100708122-bbbaac80-33e6-11eb-830d-3b764fb197cc.jpg)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/41613'>Zendesk ticket #41613</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

只能安装到遥控器里使用，没有办法用手机外接遥控器。或者你使用不带屏幕的遥控器，就可以外接手机了。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by AlmostNoMemory** [comment]
> Agent comment from William Wong in [Zendesk ticket #41613](https://djisdksupport.zendesk.com/agent/tickets/41613):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> 只能安装到遥控器里使用，没有办法用手机外接遥控器。或者你使用不带屏幕的遥控器，就可以外接手机了。
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持

**Comment by AlmostNoMemory** [comment]
> Agent comment from William Wong in [Zendesk ticket #41613](https://djisdksupport.zendesk.com/agent/tickets/41613):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> 只能安装到遥控器里使用，没有办法用手机外接遥控器。或者你使用不带屏幕的遥控器，就可以外接手机了。
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持

好的 了解了 非常感谢解答！

**Comment by Swordce** [comment]
如果手上只有这款遥控器，那怎么做开发调试呢
