### ISSUE TITLE
isVirtualStickControlModeAvailable preconditions

### ISSUE THREAD

**Issue by jeryini** [dji-sdk/Mobile-SDK-Android#697]
I'm looking at the documentation for [isVirtualStickControlModeAvailable](https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html#djiflightcontroller_virtualstickcontrolmodecategory_isvirtualstickcontrolmodeavailable_inline). Description mentions the following:
```
Indicates whether the virtual stick control interface can be used. Virtual stick mode is only available when all of the follow requirements are met:
* Virtual stick mode is enabled.
* No waypoint, hotpoint, or follow-me mission is running.
* FlightOrientationMode is set to AIRCRAFT_HEADING
* Terrain-follow is disabled if the aircraft supports this feature.
* Tripod mode is disabled if the aircraft supports this feature.
```
If a call to `isVirtualStickControlModeAvailable()` returns `False`, I'm trying to check the state to all these preconditions so that I can notify user about the root cause. Most of them are easy to check via SDK API calls, but I'm confused about the following two.

### No waypoint, hotpoint, or follow-me mission is running
I'm using the following code to check for this:
```
public boolean isWaypointMissionRunning() {
        return missionControl.getWaypointMissionOperator().getCurrentState() == WaypointMissionState.EXECUTING;
    }

    public boolean isHotpointMissionRunning() {
        return missionControl.getHotpointMissionOperator().getCurrentState() == HotpointMissionState.EXECUTING;
    }

    public boolean isFollowMeMissionRunning() {
        return missionControl.getFollowMeMissionOperator().getCurrentState() == FollowMeMissionState.EXECUTING;
    }
```
But the term **running** is ambiguous, does **running** really mean that mission is only in the state of `FollowMeMissionState.EXECUTING`, or does it cover some other state? Also I'm looking at [MissionControl docs](https://developer.dji.com/api-reference/android-api/Components/Missions/DJIMissionControl.html#djimissioncontrol) and I'm not sure, do I also have to check the Timeline scheduled elements and not just the mission control operators?

### Tripod mode is disabled if the aircraft supports this feature.
Is that correct that Tripod mode should be disabled? I'm currently checking flight controller switch that is in position **P** or **F**:
```
remoteController.setHardwareStateCallback(new HardwareState.HardwareStateCallback() {
                    @Override
                    public void onUpdate(HardwareState hardwareState) {
                        if (remoteControllerFlightModes != null) {
                            HardwareState.FlightModeSwitch currentPosition = hardwareState.getFlightModeSwitch();

                            if (currentPosition != null) {
                                RemoteControllerFlightMode currentFlightMode = remoteControllerFlightModes[currentPosition.value()];

                                // To enable remote control of the drone, the switch position has to be in mode P or mode F
                                // https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html?search=remotecontrollerflightmode&i=0&#djiflightcontroller_djiflightcontrollerremotecontrollerflightmode_inline
                                isRemoteControllerSwitchModeCorrect = (currentFlightMode == RemoteControllerFlightMode.P || currentFlightMode == RemoteControllerFlightMode.F);
                            }
                        }
                    }
                });
```
Should I also check the actual [FlightMode](https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController_DJIFlightControllerCurrentState.html?search=tripod&i=0&#djiflightcontroller_djiflightcontrollercurrentstate_flightmode_inline) as well? How is this flight mode state connected to switch state? Can you actually activate tripod mode without moving the flight controller switch button? Also how come this precondition about the switch state on flight controller needing to be in P/F mode is not mentioned in the docs? On my Mavic 2 Zoom I tried all three switch positions and the position P is the only one where a call to `isVirtualStickControlModeAvailable()` returns `True`.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41766'>Zendesk ticket #41766</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
1. The **running** really mean that mission is in the state of `EXECUTING.`
2. The virtual stick can't be used with timeline, so you need to ensure the timeline is not running isTimelineRunning.
3. The Tripod Mode should be disabled before using the virtual stick.
The Tripod Mode can be enabled/disabled by the MSDK only for the Mavic Pro & Mavic Mini.
For the other drones need to be done manually.
 ![](https://djisdksupport.zendesk.com/attachments/token/C6BdJ1WBvsTMcckmO0SuCPio8/?name=inline1651900545.png)​
4. Only in the P mode, the virtual stick will work.
The S/T mode will not work, the FlightMode as the below show.
So sorry if any detail is ambiguous.
 ![](https://djisdksupport.zendesk.com/attachments/token/3KceOLMZ5ny8T4Q1agLkhz6xW/?name=inline1131569671.png)​
Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/C6BdJ1WBvsTMcckmO0SuCPio8' target='zd_attach'>inline1651900545.png</a><br><a href='https://djisdksupport.zendesk.com/attachments/token/3KceOLMZ5ny8T4Q1agLkhz6xW' target='zd_attach'>inline1131569671.png</a>

**Comment by jeryini** [comment]
Hello @dji-dev !

Many thanks for these answers. I do have a couple of follow up questions based on your answers:
1. For Tripod mode you outlined in the screenshot method `getTripodModeEnabled`.  Shouldn't a call to [getFlightMode](https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController_DJIFlightControllerCurrentState.html?search=tripod&i=0&#djiflightcontroller_djiflightcontrollercurrentstate_flightmode_inline) also return `FlightMode.TRIPOD` if Tripod mode is enabled?
2. You said that only if remote controller is in the **P (Positioning mode)** will virtual stick work. But what about **F (Function  mode)**? It says in [the documentation](https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html?search=f&i=0&#djiflightcontroller_djiflightcontrollerremotecontrollerflightmode_inline) that it basically performs the same thing as Positioning mode?
3. Is it enough that I check that remote controller switch is in P (maybe also F) mode? Would I also have to check that [FlightMode](https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController_DJIFlightControllerCurrentState.html#djiflightcontroller_djiflightcontrollerflightmode_inline) state is in certain condition? For example not in `TRIPOD` and `GPS_SPORT`, but which values are actually allowed so that a call to `isVirtualStickControlModeAvailable` wouldn't return `False` due to wrong `FlightMode` state?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41766'>Zendesk ticket #41766</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
1. Yes, the flight mode should return the `FlightMode.TRIPOD` if Tripod mode is enabled.

2. I see. The F mode is for old drones, such as M600.
And in the F mode, the virtual stick also can be used.

3. The FlightMode is a complex set, and not recommended to use this state to determine it completely.
Just ensure the mode is not in S/T, and not in other missions(WP, hotpoint, timeline, etc), actions (gohome, takeoff, land, etc), the drone is hovering or on the land, the virtual stick can work.

Thanks,

Luce Luo
DJI Developer Support

**Comment by jeryini** [comment]
Thank you for additional explanation. That answers my original question.
