### ISSUE TITLE
DJIGroundStationWaypoint - private short heading

### ISSUE THREAD

**Issue by 7178301** [dji-sdk/Mobile-SDK-Android#7]
Regarding DJIDroneType.DJIDrone_Vision

DJI Phantom 2 Vision requires the following heading input [-3.14159,3.14159]
The DJI Phantom 2 Vision firmware dictates this input and is contradictory to the the following documentation

[Mobile SDK Documentation #Heading ](http://developer.dji.com/iframe/mobile-sdk-doc/android/dji/sdk/api/GroundStation/DJIGroundStationWaypoint.html#heading)

Heading of type short can't have decimal values, therefor breaking the heading for the DJI Phantom 2 Vision

Either the DJI Phantom Vision 2 Firmware should be updated, or the old data type of float should be restored.

**Comment by SilverChangjian** [comment]
Thanks for providing this problem, however, the P2V+ sdk has not been updated since 2.0. I suggest that you could re use the lower version for developing the app for P2V+. Thanks.

**Comment by 7178301** [comment]
Unfortunately versions below 2.1 are not publicly available from what i can see.
The DJI website only lists Version 2.1 and above.
This version of the SDK also has the incompatible heading type of short for the Phantom 2 range. 

Ideally our requirement is to support the Phantom 2/3 and the Inspire range. 
A unified/generic library is required for this since importing different libraries to support the heading type with the same package naming convention is not possible.

**Comment by SilverChangjian** [comment]
Actually, the mobile SDK could support all P3, Inspire, and P2V+ series products.
