### ISSUE TITLE
Phantom 4 Pro camera features not supported 

### ISSUE THREAD

**Issue by haogodent2** [dji-sdk/Mobile-SDK-Android#70]
Setup:
Android DJI Mobile SDK v3.5.1
Tablet: LG G8, android v7
Drone: Phantom 4 Pro, firmware: V01.02.0304  - 2/7/17
Android Studio 2.2.2

Issues: 
setHue() and playbackManager not supported for Phantom 4 Pro.

I currently use the playbackManager to figure out whether or not there are media files available for transfer on the drone. However, this feature doesn't seem to be supported by Phantom 4 Pro running the latest official firmware yet even though the documentation doesn't state that. Please address this issue when possible.

**Comment by oliverou** [comment]
Hi @haogodent2, thanks for your feedback! the Phantom 4 Pro doesn't support `setHue()` and DJIPlaybackManager, we will update the documentation to clarify it in our future SDK version.

**Comment by haogodent2** [comment]
Thanks for the clarification. In this can do you have any suggestion for how best to check if media files are available on the drone's sd card? I can use fetchMediaList but this could take a while if there are a large number of files.

**Comment by talobin** [comment]
Hi @haogodent2 ,
Currently there is not a method to do this.
We are working on adding this feature to our SDK.
Will keep you posted

**Comment by talobin** [comment]
@haogodent2 Unfortunately the camera firmware does not have this capability.
This will not be a possible thing to do.
