### ISSUE TITLE
MSDK能不能手动同步时间，有没用大佬知道同步时间的代码在哪里，无人机的时间不准确太恼火了。

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#701]
MSDK能不能手动同步时间，有没用大佬知道同步时间的代码在哪里，无人机的时间不准确太恼火了。
MSDK能不能手动同步时间，有没用大佬知道同步时间的代码在哪里，无人机的时间不准确太恼火了。
MSDK能不能手动同步时间，有没用大佬知道同步时间的代码在哪里，无人机的时间不准确太恼火了。
MSDK能不能手动同步时间，有没用大佬知道同步时间的代码在哪里，无人机的时间不准确太恼火了。
MSDK能不能手动同步时间，有没用大佬知道同步时间的代码在哪里，无人机的时间不准确太恼火了。
MSDK能不能手动同步时间，有没用大佬知道同步时间的代码在哪里，无人机的时间不准确太恼火了。

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41834'>Zendesk ticket #41834</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
抱歉，SDK没有手动同步时间的方法。
每次连接App后会自动同步手机时间。

如果时间同步有问题，为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
