### ISSUE TITLE
p4ppro timeline 任务上传失败，没有重试，上传也没有结束，无法取消

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#702]
![aa](https://user-images.githubusercontent.com/15243969/101432537-fde27180-3943-11eb-8fef-0a75e5680b2a.png)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/41844'>Zendesk ticket #41844</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

Sample的Timeline示例代码跑起来如何呢？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by SJJ-dot** [comment]
> Agent comment from William Wong in [Zendesk ticket #41844](https://djisdksupport.zendesk.com/agent/tickets/41844):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> Sample的Timeline示例代码跑起来如何呢？
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持

这个日志证明确实有这个bug。偶现。每个bug都要稳定复现才改？难怪这么个SDK，bug这么多。
