### ISSUE TITLE
航点命令添加了录制视频的动作但是经常不录制视频。今天测试，模拟器运行每次都会录制，实地飞行10次只有3次录制了视频，飞行完马上开模拟器原地测试能够正常录制，关闭模拟器，实地飞无法开启录制。  希望能够定位问题。是否是无人机的故障，环境温度大约7°

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#724]
航点命令添加了录制视频的动作但是经常不录制视频。今天测试，模拟器运行每次都会录制，实地飞行10次只有3次录制了视频，飞行完马上开模拟器原地测试能够正常录制，关闭模拟器，实地飞无法开启录制。

希望能够定位问题。是否是无人机的故障，环境温度大约7°

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42588'>Zendesk ticket #42588</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

从log上来看飞控向相机发送了录像指令，但是相机固件回了Error导致开启录像失败。首先你检查下P4R是否升级导最新固件，这个问题已经在固件中优化过了，另外你把对焦从AFC换成MF试试能否解决问题，因为我怕飞机一直在自动对焦，对焦的时候时不可以拍照录像的。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by SJJ-dot** [comment]
固件没有提示升级，但是重新刷新了固件之后确实不录象的现象变少了，但是仍然存在。没有发现规律。
