### ISSUE TITLE
RTK issue when setting homepoint

### ISSUE THREAD

**Issue by cwbsl** [dji-sdk/Mobile-SDK-Android#725]
When using `DJIApplication.getAircraftInstance().getFlightController().setHomeLocationUsingAircraftCurrentLocation()` I get the following error:

Error: Not Support

I use the newest Firmware on the SDK RC + also on the drone itself as well as the newest DJI Assistant 2 (2.0.10).

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42593'>Zendesk ticket #42593</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team

**Comment by cwbsl** [comment]
It's done

**Comment by cwbsl** [comment]
After writing with support it seems that the P4RTK doesn't support `setHomeLocationUsingAircraftCurrentLocation()` and we have to use `getAircraftLocation()` to get the current drone's coordinates and pass them in `setHomeLocation()`
