### ISSUE TITLE
UsbAccessoryService.VideoStreamSource和DJICodecManager.VideoSource有啥区别

### ISSUE THREAD

**Issue by dashifuguye** [dji-sdk/Mobile-SDK-Android#726]
UsbAccessoryService.VideoStreamSource和DJICodecManager.VideoSource，是一样的吧？

![image](https://user-images.githubusercontent.com/21324724/103501285-b985bb00-4e88-11eb-9063-578d0aad2c9f.png)
![image](https://user-images.githubusercontent.com/21324724/103501294-be4a6f00-4e88-11eb-808c-9dcb0bf2fb60.png)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42680'>Zendesk ticket #42680</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
目前没有什么区别，更建议使用DJICodecManager.VideoSource，通俗易懂。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
好的，谢谢
