### ISSUE TITLE
请问御mini使用msdk有什么限制？

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#728]
御mini, msdk4.13.1, 安卓10，
请问御mini使用msdk是否能正常飞行航线、起飞、降落、返航这些，谢谢~

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42749'>Zendesk ticket #42749</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

不行，Mavic Mini不支持任何Mission类的任务。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by Michael-DJI** [comment]
Mini固件限制，不支持航线飞行（waypoint mission）
