### ISSUE TITLE
最新SDK何时能够支持Mini2呢

### ISSUE THREAD

**Issue by Chauncy-Guo** [dji-sdk/Mobile-SDK-Android#729]
最新SDK何时能够支持Mini2呢

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42752'>Zendesk ticket #42752</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，目前没有明确的计划去支持Mavic Mini2机型，
建议您可以关注SDKRoadmap后续SDK释放计划。
https://developer.dji.com/user/roadmap/#msdk

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by Michael-DJI** [comment]
4.16会支持，目前发布时间还不定
