### ISSUE TITLE
LocationCoordinate3D enquiry

### ISSUE THREAD

**Issue by Jai-GAY** [dji-sdk/Mobile-SDK-Android#730]
[DJIFlightController_DJILocationCoordinate3D](https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController_DJILocationCoordinate3D.html)

Is there a particular GPS system or format or standard return from this API?
It was not accurate in Singapore when I retrieve from getLongitude and getLatitude with 10 satellite counts.

[example WGS84](https://en.wikipedia.org/wiki/World_Geodetic_System)

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42754'>Zendesk ticket #42754</a>:<br><br>Dear Client
Thank you for contacting DJI.

Actually we are using WGS84 co-ordinate system.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by Jai-GAY** [comment]
when I compare it with CrystalSky Go App side-by-side, it was able to show the position within a few meters +- accuracy.
DJIFlightController_DJILocationCoordinate3D was a few hundred meters out from my position with equal satellite counts.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42754'>Zendesk ticket #42754</a>:<br><br>Dear Client
Thank you for contacting DJI.

This is weird, can you give me some screenshot or evidance please?

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by Jai-GAY** [comment]
I shall monitor and see I can reproduce next week, this week everyday is raining here.

**Comment by Jai-GAY** [comment]
I like to know how do I get the UA location's Altitude base on AMSL (sea level)?
Is there such an API?

**Comment by kenargo** [comment]
There is no API but there are various online services that you can call that will convert the AGL to AMSL.   They are not overly accurate depending on the service you use but they are OK.
