### ISSUE TITLE
请问有没DJIDiagnosticType中error code的名单？

### ISSUE THREAD

**Issue by Wecorpservicesgit** [dji-sdk/Mobile-SDK-Android#732]
需要通过error code对所有诊断结果进行归类，但是在开发问答里找不到所有错误的error code所以无法对号入座。

**Comment by dashifuguye** [comment]
可以参考下DiagnosticsBaseHandler.DJIDiagnosticsError

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42774'>Zendesk ticket #42774</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

看看这个。
Link：https://developer.dji.com/api-reference/android-api/Components/Diagnostics/DJIDiagnostics.html?search=djidiagnosticserror&i=0&#djidiagnostics_djidiagnosticserror_inline

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by Wecorpservicesgit** [comment]
> DiagnosticsBaseHandler.DJIDiagnosticsError

请问在哪能找到？

**Comment by Wecorpservicesgit** [comment]
> Agent comment from William Wong in [Zendesk ticket #42774](https://djisdksupport.zendesk.com/agent/tickets/42774):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> 看看这个。
> Link：https://developer.dji.com/api-reference/android-api/Components/Diagnostics/DJIDiagnostics.html?search=djidiagnosticserror&i=0&#djidiagnostics_djidiagnosticserror_inline
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持

不好意思，但是我提问的原因就是这个文档里没有提供对应错误码。

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42774'>Zendesk ticket #42774</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

你是指数字错误码吗？这个目前没有开出来。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
> > DiagnosticsBaseHandler.DJIDiagnosticsError
> 
> 请问在哪能找到？

直接在AS中输入DiagnosticsBaseHandler.DJIDiagnosticsError，然后导入对应的包，就可以进入看到了  

    public static enum DJIDiagnosticsError {
        CAMERA_UPGRADE_ERROR(1001),
        CAMERA_SENSOR_ERROR(1002),
        CAMERA_OVER_HEAT(1003),
        CAMERA_ENCRYPTION_ERROR(1004),
        CAMERA_NO_SD_CARD(1005),
        CAMERA_SD_CARD_ERROR(1006),
        CAMERA_SD_CARD_NO_SPACE(1007),
        CAMERA_SD_CARD_FULL(1008),
        CAMERA_SD_CARD_READ_ONLY(1009),
        CAMERA_SD_CARD_NOT_FORMATTED(1010),
        CAMERA_CHIP_OVER_HEAT(1011),
        CAMERA_TemperaturesTooHighToStopRecord(1012),
        GIMBAL_GYROSCOPE_ERROR(2001),
        GIMBAL_PITCH_ERROR(2002),
        GIMBAL_ROLL_ERROR(2003),
        GIMBAL_YAW_ERROR(2004),
        GIMBAL_CONNECT_TO_FC_ERROR(2005),
        BATTERY_DISCHARGE_OVER_CURRENT(3001),
        BATTERY_DISCHARGE_OVER_HEAT(3002),
        BATTERY_LOW_TEMPERATURE(3003),
        BATTERY_CELL_BROKEN(3004),
        BATTERY_NEED_STUDY(3005),
        BATTERY_ILLEGAL(3006),
        SINGLE_BATTERY_MODE(3007),
        FAKE_BATTERY_MODE(3008),
        BATTERY_CYCLE_TIME_OVER(3009),
        BATTERY_DIFF_USAGE(3010),
        BATTERY_OVER_LOAD(3011),
        BATTERY_LOW_VOLTAGE(3012),
        BATTERY_DANGEROUS_WARNING_SERIOUS(3013),
        BATTERY_COMMUNICATION_FAIL(3014),
        BATTERY_SHORT_CUT(3015),
        REMOTE_CONTROLLER_FPGA_ERROR(4001),
        REMOTE_CONTROLLER_TRANSMITTER_ERROR(4002),
        REMOTE_CONTROLLER_BATTERY_ERROR(4003),
        REMOTE_CONTROLLER_GPS_ERROR(4004),
        REMOTE_CONTROLLER_ENCRYPTION_ERROR(4005),
        REMOTE_CONTROLLER_NEED_CALIBRATION(4006),
        REMOTE_CONTROLLER_BATTERY_LOW(4007),
        REMOTE_CONTROLLER_IDLE_TOO_LONG(4008),
        REMOTE_CONTROLLER_RESET(4009),
        REMOTE_CONTROLLER_OVER_HEAT(4010),
        REMOTE_CONTROLLER_GO_HOME_FAIL(4011),
        CENTRAL_BOARD_CONNECT_TO_BATTERY_ERROR(5001),
        CENTRAL_BOARD_CONNECT_TO_GPS_ERROR(5002),
        CENTRAL_BOARD_CONNECT_TO_FC_ERROR(5003),
        VIDEO_DECODER_ENCRYPTION_ERROR(6001),
        VIDEO_DECODER_CONNECT_TO_DESERIALIZER_ERROR(6002),
        AIR_ENCODER_ERROR(7001),
        AIR_ENCODER_UPGRADE(7002),
        AIR_LINK_NO_SIGNAL(7003),
        AIR_LINK_LOW_RC_SIGNAL(7004),
        AIR_LINK_STRONG_RC_RADIO_SIGNAL_NOISE(7005),
        AIR_LINK_LOW_RADIO_SIGNAL(7006),
        AIR_LINK_STRONG_RADIO_SIGNAL_NOISE(7007),
        AIR_LINK_WIFI_MAGNETIC_INTERFERENCE_HIGH(7008),
        FLIGHT_CONTROLLER_IMU_NEED_CALIBRATION(8001),
        FLIGHT_CONTROLLER_IMU_CALIBRATION_INCOMPLETE(8002),
        FLIGHT_CONTROLLER_IMU_DATA_ERROR(8003),
        FLIGHT_CONTROLLER_IMU_ERROR(8004),
        FLIGHT_CONTROLLER_IMU_INIT_FAILED(8005),
        FLIGHT_CONTROLLER_BAROMETER_INIT_FAILED(8006),
        FLIGHT_CONTROLLER_BAROMETER_ERROR(8007),
        FLIGHT_CONTROLLER_ACCELEROMETER_INIT_FAILED(8008),
        FLIGHT_CONTROLLER_GYROSCOPE_ERROR(8009),
        FLIGHT_CONTROLLER_ATTITUDE_ERROR(8010),
        FLIGHT_CONTROLLER_DATA_RECORD_ERROR(8011),
        FLIGHT_CONTROLLER_TAKEOFF_FAILED(8012),
        FLIGHT_CONTROLLER_SYSTEM_ERROR(8013),
        FLIGHT_CONTROLLER_IMU_HEATING(8014),
        FLIGHT_CONTROLLER_COMPASS_ABNORMAL(8015),
        FLIGHT_CONTROLLER_COMPASS_NEED_RESTART(8016),
        FLIGHT_CONTROLLER_USING_WRONG_PROPELLERS(8017),
        FLIGHT_CONTROLLER_MOTOR_START_ERROR(8018),
        FLIGHT_CONTROLLER_NO_PROPELLER(8019),
        FLIGHT_CONTROLLER_MOTOR_STOP_REASON(8020),
        FLIGHT_CONTROLLER_THREE_PROPELLER_EMERGENCY_LANDING(8105),
        FLIGHT_CONTROLLER_LANDING_PROTECTION(8106),
        FLIGHT_CONTROLLER_AIRCRAFT_PROPULSION_SYSTEM_ERROR(8107),
        VISION_SYSTEM_NEED_CALIBRATION(9000),
        VISION_PROPELLER_GUARD(9001),
        VISION_SENSOR_ERROR(9002),
        VISION_SENSOR_CALIBRATION_ERROR(9003),
        VISION_SENSOR_COMMUNICATION_ERROR(9004),
        VISION_SYSTEM_ERROR(9005),
        GIMBAL_LOCATE_ERROR(9006),
        RTK_POSITIONING_ERROR(9007),
        RTK_ORIENTEERING_ERROR(9008),
        VISION_WEAK_AMBIENT_LIGHT(9009),
        FLIGHT_CONTROLLER_MC_READING_DATA(10001),
        FLIGHT_CONTROLLER_KERNEL_BOARD_HIGH_TEMPERATURE(10002),
        FLIGHT_CONTROLLER_MC_DATA_ERROR(10003),
        FLIGHT_CONTROLLER_BATTERY_NOT_IN_POSITION(10004),
        FLIGHT_CONTROLLER_ENABLE_NEAR_GROUND_ALERT(10005),
        FLIGHT_CONTROLLER_MOTOR_BLOCKED(10006),
        FLIGHT_CONTROLLER_NOT_ENOUGH_FORCE(10007),
        FLIGHT_CONTROLLER_OUT_OF_FLIGHT_RADIUS_LIMIT(10008),
        FLIGHT_CONTROLLER_OVER_HEAT_GO_HOME(10009),
        FLIGHT_CONTROLLER_COMPASS_INSTALL_ERROR(10010),
        FLIGHT_CONTROLLER_GPS_ERROR(10011),
        FLIGHT_CONTROLLER_OUT_OF_CONTROL_GOING_HOME(10012),
        FLIGHT_CONTROLLER_HEIGHT_LIMIT_REASON_NO_GPS(10013),
        FLIGHT_CONTROLLER_HEIGHT_LIMIT_REASON_COMPASS_INTERRUPT(10014),
        FLIGHT_CONTROLLER_NO_REAL_NAME_HEIGHT_LIMIT(10015),
        FLIGHT_CONTROLLER_STRONG_GALE_WARNING(10016),
        FLIGHT_CONTROLLER_WATER_SURFACE_WARNING(10017),
        FLIGHT_CONTROLLER_PADDLE_HAS_ICE_ON_IT(10018),
        FLIGHT_CONTROLLER_GPS_SIGNAL_BLOCKED_BY_GIMBAL(10019),
        FLIGHT_CONTROLLER_COVER_FLIGHT_ENABLE_LIMIT(10020),
        FLIGHT_CONTROLLER_MOTOR_STOP_FOR_ESC_SHORT_CIRCUIT(10021),
        FLIGHT_CONTROLLER_ENV_STATE_TEMP_TOO_LOW(10022),
        FLIGHT_CONTROLLER_ENV_STATE_TEMP_TOO_HIGH(10023),
        FLIGHT_CONTROLLER_HEADING_CONTROL_ABNORMAL(10024),
        FLIGHT_CONTROLLER_AIRCRAFT_VIBRATION_ABNORMAL(10025),
        FLIGHT_CONTROLLER_TILT_CONTROL_ABNORMAL(10026),
        FLIGHT_CONTROLLER_ONLY_SUPPORT_ATTI_MODE(10027),
        FLIGHT_CONTROLLER_LOW_VOLTAGE_GOING_HOME(10028),
        FLIGHT_CONTROLLER_SMART_LOW_POWER_GO_HOME(10029),
        FLIGHT_CONTROLLER_LOW_VOLTAGE_LANDING(10030),
        a(1);

        private int value;

        private DJIDiagnosticsError(int var3) {
        }

        private boolean _equals(int var1) {
            return false;
        }

        public static DiagnosticsBaseHandler.DJIDiagnosticsError find(int var0) {
            return null;
        }

        public int value() {
            return 0;
        }
    }

**Comment by Wecorpservicesgit** [comment]
> Agent comment from William Wong in [Zendesk ticket #42774](https://djisdksupport.zendesk.com/agent/tickets/42774):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> 你是指数字错误码吗？这个目前没有开出来。
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持

https://github.com/dji-sdk/Mobile-SDK-Android/issues/732#issuecomment-756518645

**Comment by Wecorpservicesgit** [comment]
@dashifuguye 非常感谢
