### ISSUE TITLE
msdk无法检测到payload

### ISSUE THREAD

**Issue by dashifuguye** [dji-sdk/Mobile-SDK-Android#733]
app使用的msdk4.13.1版本，飞机是M300RTK，使用自己开发的PSDK相机。当先打开app，然后再给飞机上电，msdk的DJISDKManager.SDKManagerCallback.onComponentChange无法检测到PAYLOAD，DJISDKManager.getInstance().getProduct().getPayload() 返回null，导致的问题就是无法显示PSDK相机图像；但是如果先打开飞机，过一会再打开app，上面的这个函数就可以检测到PAYLOAD，DJISDKManager.getInstance().getProduct().getPayload()不为null，这时可以显示PSDK相机图像。如果想在第一种情况下显示PSDK相机，应该如果做？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42786'>Zendesk ticket #42786</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

听起来像是你的代码写得有问题，你先试试Demo能否复现你的问题。
Link：https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/payload/PayloadActivity.java

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
你好，我试了demo，可以复现我说的问题，但不是稳定复现

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42786'>Zendesk ticket #42786</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

建议你再用Pilot试试看能否复现，如果不能复现就是MSDK的问题。目前没有好的解决办法，可能是通信协议的问题，只能保证先上电，再开app连接了。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
试过了pilot，不能复现问题。有没有别的解决办法？或者辛苦修复下MSDK？

**Comment by dashifuguye** [comment]
DJISDKManager.SDKManagerCallback()中， 
`
@Override
 public void onComponentChange(BaseProduct.ComponentKey componentKey, BaseComponent oldComponent, BaseComponent newComponent) {
}  
`   
当先启动M300飞机，过一会再打开app，就可以在这个函数中检测 componentKey =PAYLOAD；但如果先打开app，再打开飞机，就检测不到PAYLOAD，只能看到AIRLINK、FLIGHTCONTROLLER、BATTERY、REMOTECONTROLLER。这个或许可以帮助你们解决问题

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42786'>Zendesk ticket #42786</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

好的，我把你的问题报告给研发，排期解决，目前先保证先开app后上电吧。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
请问MSDK 4.14解决这个问题了吗？我看release note里没有提到这块呢

**Comment by DJI-William** [comment]
4.15.1会修复这个问题。
