### ISSUE TITLE
如何知道直播与RTMP服务器的连接状态

### ISSUE THREAD

**Issue by abc456879213** [dji-sdk/Mobile-SDK-Android#734]
我发现直播没有断网重连的机制，我想通过监听与RTMP服务器的连接状态来做一个重启直播的功能。
另外请问getLiveVideoBitRate()方法拿到的码率是推流的码率吗？为啥断网后还是2000kps？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42806'>Zendesk ticket #42806</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

目前没有做监控RTMP服务器状态的接口，断开了还有推流码率这个应该是bug。我建议你自己做个推流功能，来满足你的需求。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by Michael-DJI** [comment]
4.15已经增加了方法，调用LiveStreamManager 里面的addLiveErrorStatusListener可以监听（界面退出时记得调用removeLiveErrorStatusListener）

**Comment by abc456879213** [comment]
> 4.15已经增加了方法，调用LiveStreamManager 里面的addLiveErrorStatusListener可以监听（界面退出时记得调用removeLiveErrorStatusListener）

@Michael-DJI 了解，谢谢！
