### ISSUE TITLE
Zenmuse H20 save just one camera source

### ISSUE THREAD

**Issue by japelaez6894** [dji-sdk/Mobile-SDK-Android#736]
Hi,

I'm working with Zenmuse H20 and I've observed that, when taking pictures or recording videos using `WaypointAction` class, several files are generated (one per each lens/sensor). However, I'm selecting the lens with `setCameraVideoStreamSource` and, according to the API documentation, a single file should be generated (the one of the selected lens): 

![imagen](https://user-images.githubusercontent.com/46809670/103880716-c5b48700-50d9-11eb-95c2-30b22271ae4c.png)

Am I doing something wrong or have I misunderstood the way it should work?

Name | Desc
-- | --
SDK Version | 4.14 TRIAL1
Drone | Matrice 300 RTK
Camera | H20
Firmware version (drone) | 01.00.0214
Firmware version (camera) | 01.00.0211

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42815'>Zendesk ticket #42815</a>:<br><br>Dear Client
Thank you for contacting DJI.

setCameraVideoStreamSource is setting the current video stream, use setCaptureCameraStreamSettings to acheive your goal.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
