### ISSUE TITLE
APP Confirm to Land   Aircraft has landed to 0.3m(1.0ft). Continue landing?

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#737]
御2, msdk4.13.1, 安卓10。
同样的飞行场地，偶尔在返航时会弹出提示框"APP Confirm to Land   Aircraft has landed to 0.3m(1.0ft). Continue landing?", 莫名其妙的。
请问怎么避免这个弹框？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42942'>Zendesk ticket #42942</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
这是降落保护功能，可以使用confirmLanding确认着陆。

如果需要取消该弹窗，可以使用setLandingProtectionEnabled关闭降落保护功能。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
