### ISSUE TITLE
 DJISDKManager.getInstance().getFlightHubManager().updateActivationState()

### ISSUE THREAD

**Issue by China-gzz** [dji-sdk/Mobile-SDK-Android#739]
DJISDKManager.getInstance().getFlightHubManager().updateActivationState(new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError error) {
                    if (error == null) {
                        ToastUtils.setResultToToast("authorized successfully");
                        ToastUtils.setResultToText(tvAuthStatus, "Authorized: true");
                    } else {
                        ToastUtils.setResultToToast("authorized failed ：" + error.getDescription());
                        ToastUtils.setResultToText(tvAuthStatus, "Authorized: false");

                  
                    }
                }
            });

走到错误的回调，报user not found in FlightHub，这个是什么问题，已经在无人机登记网站上登记过了

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42959'>Zendesk ticket #42959</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，目前MSDK与FlightHub无法一起使用，不建议您使用。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
