### ISSUE TITLE
如何动态调整预览视频大小

### ISSUE THREAD

**Issue by chenxiaojin** [dji-sdk/Mobile-SDK-Android#74]
-  DJI Android SDK version : 3.5.1
-  DJI Product : Phantom 3 4K,
-  Android system version: Android 6.0.1
-  Android device: XIAOMI 4
-  Android Studio version : 2.2.3
根据DJI SDK Demo使用TextureView和DJICodecManager可以显示预览视频。但是，当缩放TextureView后，视频无法根据TextureView的大小适配。 
DJICodecManager只能获取视频长宽，无法重新设置长宽。 重新实例化DJICodecManager可以重新适配TextureView, 但体验非常差, 卡顿明显。
而DJI GO app在切换预览视频大小时则非常流畅， 想问下如何有什么方案可动态对预览视频进行调整？

**Comment by GIS-HowardZhang** [comment]
朋友，我很无奈地建议你用英文问，中文很难有人理你的，这是Github不是中文论坛。

**Comment by talobin** [comment]
Please check out https://github.com/dji-sdk/Mobile-UILibrary-Android.
It has built in FPVWidget that you can resize.
Will close the issue now.
