### ISSUE TITLE
请问msdk是否可以虚拟摇杆操作?

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#742]
御2，msdk4.13.1, 安卓10，
现在需要对接一个外部摇杆，是否可以把外部摇杆的偏移映射到msdk的虚拟摇杆上？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42994'>Zendesk ticket #42994</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

可以做到，但是你怎么让手机读取到外部摇杆的摇杆数值是一个问题。你可以看下这个Demo。他是用joystick贴图的操作来映射的。
Link：https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/mobileremotecontroller/MobileRemoteControllerView.java

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
@dji-dev 你好，感谢热情解答！ 
请问上面这个例子能控制真实飞机吗？ 好像都是对Simulator进行操作，这个Simulator是指模拟器吧

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42994'>Zendesk ticket #42994</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

可以控制飞机，你不打开Simulator就好了。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
好的 多谢~

**Comment by addriumruss** [comment]
@dji-dev 官网这个介绍"A simulated remote controller on the mobile device to control the aircraft when the physical remote controller is absent. The mobile remote controller only supports Mode 2 control style and flight mode P. It is supported by Mavic Pro using WiFi. This object is available from the Aircraft subclass off BaseProduct."
请问正常情况下，有遥控，走正常数传而不是wifi，再通过msdk的MobileRemoteController是否还能控制飞机？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/42994'>Zendesk ticket #42994</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

应该不行，但是你可以试试，这个功能完全是为手机能够直连飞机设计的。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by Michael-DJI** [comment]
> @dji-dev 官网这个介绍"A simulated remote controller on the mobile device to control the aircraft when the physical remote controller is absent. The mobile remote controller only supports Mode 2 control style and flight mode P. It is supported by Mavic Pro using WiFi. This object is available from the Aircraft subclass off BaseProduct."
> 请问正常情况下，有遥控，走正常数传而不是wifi，再通过msdk的MobileRemoteController是否还能控制飞机？

走遥控连接飞机，不能用MobileRemoteController控制飞机，但是可以用VirtualStick控制，可以查一下相关接口
