### ISSUE TITLE
请问精灵4 RTK 如何启用？

### ISSUE THREAD

**Issue by rangerzhou** [dji-sdk/Mobile-SDK-Android#743]
是否有相关教程以及示例，目前通过如下方法设置 RTK:
```
Aircraft aircraft = (Aircraft) DJISDKManager.getInstance().getProduct();
        if (aircraft != null) {
            FlightController flightController = aircraft.getFlightController();
            RTK rtk = flightController.getRTK();
            // 检查设备是否支持 RTK
            boolean rtkSupported = flightController.isRTKSupported();
            if (rtkSupported) {
                // 启用 RTK 模块
                Objects.requireNonNull(rtk).setRtkEnabled(true, new CommonCallbacks.CompletionCallback() {
                    @Override
                    public void onResult(DJIError djiError) {
                        showToast("启用 RTK 模块: " + djiError);
                    }
                });

                // 判断是否成功开启 RTK
                Objects.requireNonNull(rtk).getRtkEnabled(new CommonCallbacks.CompletionCallbackWith<Boolean>() {
                    @Override
                    public void onSuccess(Boolean aBoolean) {
                        showToast("获取 RTK 状态成功: " + aBoolean);
                    }

                    @Override
                    public void onFailure(DJIError djiError) {
                        showToast("获取 RTK 状态失败: " + djiError);
                    }
                });

            }

            // 设置信号源: 网络 RTK
            Objects.requireNonNull(flightController.getRTK()).setReferenceStationSource(ReferenceStationSource
                    .BASE_STATION, new CommonCallbacks.CompletionCallback() {
                @Override
                public void onResult(DJIError djiError) {
                    showToast("设置信号源为: BASE_STATION: " + djiError);
                }
            });
            flightController.getRTK().addReferenceStationSourceCallback(new ReferenceStationSource.Callback() {
                @Override
                public void onReferenceStationSourceUpdate(ReferenceStationSource referenceStationSource) {
                    showToast("查看当前信号源: " + referenceStationSource.toString());
                }
            });
        }
```
但是 startMission 的时候总是提示：`RTK is not ready`，恳请各位大佬指点一二，谢谢！！！

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43019'>Zendesk ticket #43019</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
首先，确认下，您的RTK解决方案是哪一类，是否正确设置。
如下setReferenceStationSource，解决方案有3种：
第一种物理基站，BASE_STATION
第二种第三方网络RTK（M210 V2 RTK, M300 RTK, P4M和P4RTK均支持），即由第三方提供的NTRIP RTK信息服务，需要使用setCustomNetworkSettings接口设置第三方账户信息（由第三方提供），并启动startNetworkService开启RTK信息传输
第三种网络RTK（P4RTK, P4M, M300 RTK），即与DJI签订的RTK信息解决方案，需要先添加相关另行RTK库，设置坐标系统setNetworkServiceCoordinateSystem，同时确保activateNetworkService已经激活您的RTK计划，激活仅需要一次，如果在PILOT上激活了无需重复激活，并启动startNetworkService开启RTK信息传输
​ ![](https://djisdksupport.zendesk.com/attachments/token/xxyzVsbGdw0vyCRjqsil201J3/?name=inline-480044116.png)​
然后，使能RTKsetRtkEnabled
最后，通过isRTKBeingUsed获取RTK数据是否正在被使用，判断getPositioningSolution为FIXED_POINT状态即为精度最高
所有流程均可参考DJI PILOT的操作流程。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by rangerzhou** [comment]
@dji-dev 
非常感谢解答，根据您的解答，我理解开启流程如下：
1. 检查设备是否支持 RTK
···
FlightController.getRTK() != null
···
2. 启用 RTK 模块
···
rtk.setRtkEnabled+
···
3. 设置 RTK 信号源
···
rtk.setReferenceStationSource
···
4. 设置网络 RTK 帐号
4.1 对于第三方网络RTK，设置第三方网络帐号
```
            NetworkServiceSettings settings = new NetworkServiceSettings.Builder()
                    .userName("testUser")
                    .password("123456")
                    .ip("192.168.123.2")
                    .port(9102)
                    .mountPoint("MMPT32_GGB").build();
            rtkNetworkServiceProvider.setCustomNetworkSettings(settings);
rtkNetworkServiceProvider.setCustomNetworkSettings(settings);
```
4.2 对于与DJI签订的RTK信息解决方案
4.2.1 设置坐标系统
···
rtkNetworkServiceProvider.setNetworkServiceCoordinateSystem
···
4.2.2 确保已经激活 RTK 计划
···
rtkNetworkServiceProvider.activateNetworkService
···
5. 启动网络 RTK 服务
···
rtkNetworkServiceProvider.startNetworkService
···
6. 检查网络 RTK 是否成功启动
···
rtkNetworkServiceProvider.addNetworkServiceStateCallback
···
7. 获取RTK数据是否正在被使用，判断getPositioningSolution
···
            rtk.setStateCallback(new RTKState.Callback() {
                @Override
                public void onUpdate(RTKState rtkState) {
                    Log.d(TAG, "RTK数据是否正在被使用" + rtkState.isRTKBeingUsed());
                    // 判断 getPositioningSolution 为 FIXED_POINT 状态即为精度最高
                    Log.d(TAG, "getPositioningSolution: " + rtkState.getPositioningSolution());
                }
            });
···


还有如下问题：
1. 对于由第三方提供的NTRIP RTK信息服务，是否需要 4.2.1 和4.2.2 步骤？
2. 对于与DJI签订的RTK信息解决方案，在Pilot 中登录对应帐号后激活就行了是吗？激活是收费的？如果是登录帐号激活，在自己写的 APP 中登录对应帐号就意味着激活了是吗？也就是说是否激活是和登录帐号绑定的？
3. 第一种物理基站解决方案 BASE_STATION是免费的吗？需要以上7个步骤中的哪几个？
4. 以上 1-7 步骤是否还需要补充？

恳请大佬帮忙解答，跪谢！！！

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43019'>Zendesk ticket #43019</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。

1. 对于由第三方提供的NTRIP RTK信息服务，是否需要 4.2.1 和4.2.2 步骤？
-->不需要


1. 对于与DJI签订的RTK信息解决方案，在Pilot 中登录对应帐号后激活就行了是吗？激活是收费的？如果是登录帐号激活，在自己写的 APP 中登录对应帐号就意味着激活了是吗？也就是说是否激活是和登录帐号绑定的？
-->是的，在Pilot中激活后无需MSDK中重复激活，激活不收费，购买套餐是收费的， 登录了对应账号并不意味激活，激活是额外的操作（需要确定套餐激活生效时间的）如果对RTK的使用流程不太了解，激活和登录账号是绑定的，您可以在Pilot上操作下，更多RTK套餐使用说明可以咨询产品支持 support@dji.com,


1. 第一种物理基站解决方案 BASE_STATION是免费的吗？需要以上7个步骤中的哪几个？
-->需要购买物理基站，需要1,2,3


1. 以上 1-7 步骤是否还需要补充？
-->没有了


非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by rangerzhou** [comment]
@dji-dev 
你好，感谢您的解答，在 PILOT 中激活 RTK，如下图所示：
![RTK开关](https://raw.githubusercontent.com/rangerzhou/ImageHosting/master/Pictures/RTK%E5%BC%80%E5%85%B3.png)

**1. 只要 RTK 开关打开了即认为激活了？或者在代码中activateNetworkService成功意味着激活成功？**
下图中的提示：
![Refuse](https://raw.githubusercontent.com/rangerzhou/ImageHosting/master/Pictures/%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%B7%B2%E6%8B%92%E7%BB%9D%E8%AF%B7%E6%B1%82.png)
**2. 状态显示服务器已拒绝请求，意思是指我没有购买套餐是吗？**

**3. 当我点击购买套餐，显示如下：**
![QianXun](https://raw.githubusercontent.com/rangerzhou/ImageHosting/master/Pictures/DJI_QianXun.jpg)
意思是与DJI签订的RTK信息解决方案，默认就是千寻帐号是吗？如果是，代码中需要加上我上面回答步骤中的第 4.1 对吗？

**4. 当前我在代码中去掉了4.1步骤，航点模式开始任务时，提示RTK is not ready，是否是因为我没有添加4.1步骤？如果添加4.1步骤，并且要确保我已经购买了RTK套餐（千寻帐号）是吗？只要我添加了4.1，并且购买了RTK套餐，此错误即可解决对吗？**
![RTKISNOTREADY](https://raw.githubusercontent.com/rangerzhou/ImageHosting/master/Pictures/RTK_is_not_ready.png)

问题有点多，期待您百忙之中回答解惑，真心感谢您！

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43019'>Zendesk ticket #43019</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
1. 打开RTK不算激活成功，仅是RTK的总开关，激活需要先购买套餐，再进入套餐激活，购买后pilot会有相关提示的。

2. 是的

3. 购买的DJI网络套餐默认是千寻的，相关的千寻账户密码等信息会绑定到遥控器和您的DJI账户，无需在SDK中加入4.1步骤

4. 网络RTK不需要4.1步骤，仅非与DJI签订的第三方RTK需要，您购买DJI RTK网络套餐激活后，参照之前提供的步骤即可：
第三种网络RTK（P4RTK, P4M, M300 RTK），即与DJI签订的RTK信息解决方案，需要先添加相关另行RTK库，设置坐标系统setNetworkServiceCoordinateSystem，同时确保activateNetworkService已经激活您的RTK计划，激活仅需要一次，如果在PILOT上激活了无需重复激活，并启动startNetworkService开启RTK信息传输

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by rangerzhou** [comment]
@dji-dev 
非常感谢您的指导，基本上都清楚了，还有一点点小疑问：
**1. 如果我不在 PILOT 中激活RTK，而是在代码中通过activateNetworkService激活，是否需要添加 4.1 步骤配置千寻账户密码？**

**2.根据 DJI大疆学堂中的 RTK使用 视频教程，需要在遥控器中插入无线网卡，但是精灵4 RTK开发用的遥控器似乎没有可以插入无线网卡的地方？ **

祝您生活愉快，工作顺利，再次拜谢！

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43019'>Zendesk ticket #43019</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
1. 只要是与DJI签订的网络RTK，不管在哪里激活都是不需要4.1填写信息的
2. 配合开发控，无需网卡，网络是来自您连接的手机。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by rangerzhou** [comment]
> Agent comment from Luce Luo in [Zendesk ticket #43019](https://djisdksupport.zendesk.com/agent/tickets/43019):
> 
> 尊敬的用户，
> 
> 您好！感谢您联系DJI 大疆创新。
> 
> 1. 只要是与DJI签订的网络RTK，不管在哪里激活都是不需要4.1填写信息的
> 2. 配合开发控，无需网卡，网络是来自您连接的手机。
> 
> 非常感谢您的理解与配合，祝您生活愉快！
> 
> Best Regards,
> 
> DJI 大疆创新SDK技术支持

谢了，最后一个问题再麻烦您指导一下：
**网络RTK激活后，是和遥控器绑定还是和DJI账户绑定，还是两者都绑定？一个RTK激活能否同时用于开发遥控器和非开发遥控器？**

祝您生活愉快，工作顺利！

**Comment by laohongshu** [comment]
> > Agent comment from Luce Luo in [Zendesk ticket #43019](https://djisdksupport.zendesk.com/agent/tickets/43019):
> > 尊敬的用户，
> > 您好！感谢您联系DJI 大疆创新。
> > 
> > 1. 只要是与DJI签订的网络RTK，不管在哪里激活都是不需要4.1填写信息的
> > 2. 配合开发控，无需网卡，网络是来自您连接的手机。
> > 
> > 非常感谢您的理解与配合，祝您生活愉快！
> > Best Regards,
> > DJI 大疆创新SDK技术支持
> 
> 谢了，最后一个问题再麻烦您指导一下：
> **网络RTK激活后，是和遥控器绑定还是和DJI账户绑定，还是两者都绑定？一个RTK激活能否同时用于开发遥控器和非开发遥控器？**
> 
> 祝您生活愉快，工作顺利！

网络RTK绑定遥控器SN，与账号和飞机无关。第三方网络RTK可以，DJI自身的网络RTK不行。

**Comment by rangerzhou** [comment]
> > > Agent comment from Luce Luo in [Zendesk ticket #43019](https://djisdksupport.zendesk.com/agent/tickets/43019):
> > > 尊敬的用户，
> > > 您好！感谢您联系DJI 大疆创新。
> > > 
> > > 1. 只要是与DJI签订的网络RTK，不管在哪里激活都是不需要4.1填写信息的
> > > 2. 配合开发控，无需网卡，网络是来自您连接的手机。
> > > 
> > > 非常感谢您的理解与配合，祝您生活愉快！
> > > Best Regards,
> > > DJI 大疆创新SDK技术支持
> > 
> > 
> > 谢了，最后一个问题再麻烦您指导一下：
> > **网络RTK激活后，是和遥控器绑定还是和DJI账户绑定，还是两者都绑定？一个RTK激活能否同时用于开发遥控器和非开发遥控器？**
> > 祝您生活愉快，工作顺利！
> 
> 网络RTK绑定遥控器SN，与账号和飞机无关。第三方网络RTK可以，DJI自身的网络RTK不行。

了解，感谢！
