### ISSUE TITLE
Mini 2 Support

### ISSUE THREAD

**Issue by lucvan** [dji-sdk/Mobile-SDK-Android#747]
Please include support for the Mini 2 on this SDK.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43087'>Zendesk ticket #43087</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that there is no exact SDK plan to support the Mavic Mini 2 for the being time.
Please attention to the SDK roadmap if any changed in further.
https://developer.dji.com/user/roadmap

Thanks,

Luce Luo
DJI Developer Support

**Comment by fidian** [comment]
To save people from creating a developer account, I'll relay that the roadmap does not list the Mini 2 for the release slated for 2021-06-20, and the release cycle appears to be every 6 months.

**Comment by TimSC** [comment]
People on the forums keep asking for this, including me. https://forum.dji.com/forum.php?mod=viewthread&tid=229162&extra=page%3D1

**Comment by TimSC** [comment]
A more optimistic response from DJI support is here #773

**Comment by TimSC** [comment]
Has this support been added? @Michael-DJI

**Comment by fidian** [comment]
I do not see the Mini 2 listed on the roadmap yet, and the latest release on the roadmap is the one for June 20, 2021.

**Comment by TimSC** [comment]
Support is out for android in release 2021.12.29 https://www.youtube.com/watch?v=blqJDTm5f5s Thanks DJI!

Still not out for iOS yet.
