### ISSUE TITLE
请问是否通过msdk持续转动云台？

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#748]
msdk4.13.1、4.14, 御2、m300+z30、安卓10
希望类似摇杆模式，持续转动云台。请问是否能实现，有没有示例程序？谢谢!

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43130'>Zendesk ticket #43130</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
可以的，您可以通过速度模式去控制云台，参考demo：
https://github.com/dji-sdk/Mobile-SDK-Android/tree/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/gimbal

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by addriumruss** [comment]
@dji-dev 感谢支持！
示例上有启动速度转动代码，但是不知道怎么停止？

**Comment by addriumruss** [comment]
@dji-dev 另外速度设置后，请问怎么设置顺时针、反时针转动？  
速度模式有点模糊，是否设置速度模式后镜头就一直转动？ 但是又没找到停止接口。
如果不是这样，速度模式它是否自动停止？根据什么设置自动停止呢？
谢谢！

**Comment by addriumruss** [comment]
@dji-dev 还有个问题，请问怎么持续控制焦距伸缩？
谢谢！

**Comment by Michael-DJI** [comment]
请参考官方的教程和sample
