### ISSUE TITLE
isDigitalZoomScaleSupported returns "false" with X3 Camera

### ISSUE THREAD

**Issue by chenxiaojin** [dji-sdk/Mobile-SDK-Android#75]
DJI Android SDK version : 3.5.1
DJI Product : Inspire 1,
Android system version: Android 6.0.1
Android device: XIAOMI 4
Android Studio version : 2.2.3

I am using Inspire 1 with X3 camera,  and I call the DJICamera.isDigitalZoomScaleSupported function, the returns value is false.
But the same function of IOS SDK returns true. 

Is it Android SDK problem ?

**Comment by talobin** [comment]
@chenxiaojin 
Please always use our latest SDK. This problem has been fixed in the latest version (4.3.2)
