### ISSUE TITLE
关于航点飞行的高度

### ISSUE THREAD

**Issue by Wecorpservicesgit** [dji-sdk/Mobile-SDK-Android#751]
简单来问，如果起飞点高于地面10米，无人机的第一个航点的高度设的是20米，那么无人机在这个点的实际高于地面高度以及显示高度是30米还是20米？

**Comment by Wecorpservicesgit** [comment]
在[这个参数](https://developer.dji.com/api-reference/android-api/Components/Missions/DJIWaypoint.html#djiwaypoint_altitude_inline)里，ground指的是起飞点的地面还是实际地面？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43226'>Zendesk ticket #43226</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
"第一个航点的高度设的是20米"
-->MSDK中高度是相对的，飞机会飞到相对于起飞点高20米的位置（即实际中的30米），MSDK显示的高度也是20米

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
