### ISSUE TITLE
Questions About Mobile SDK Limitations

### ISSUE THREAD

**Issue by eliezerb** [dji-sdk/Mobile-SDK-Android#752]
Dear Support, 

We've been compiling a couple of questions regarding some possible limitations of the current SDK. Our equipment is a Matrice 210 v2 RTK with a XT2 camera and we're using the latest version of the Android SDK.

1. We were not able to identify a way to change the camera yaw during the execution of a `WaypointMission'. The only option we had was to change the pitch angle, using the GIMBAL_PITCH action. But that doesn't address our issue. Is there a way of achieving the same effect but for the Yaw? The Gimbal mode used in YAW_FOLLOW.

2. If the drone is In Flight and the Go To Home action is sent to the device, when the aircraft is within 20 meters of the Home Point, the lading starts immediately. Is there a way to prevent this behavior, and proceed with the original behavior: a) aircraft pauses; b) aircraft goes to the return to home altitude; c) return to the home point; d) landing.

3. When executing field missions with de Matrice 210 RTK and the D-RTK Base Station, after setting the RTK reference position to the equipment, often the message "Cannot Take Off" continually is presented in the user interface. After resetting the drone manually the message goes away and the aircraft can fly on the RTK mode. Is this the normal behavior? If so, is there a way we can reboot the aircraft using the Mobile SDK?

4. During the execution of a Waypoint Mission, when the aircraft executes the START_RECORDING action, the command sometimes doesn't start the video recording and sometimes it starts but eventually automatically stops after some seconds. Is there any know issue related to recording videos?

5. We need to include some metadata / custom information into the recorded files by the XT2 camera, or even renaming the output file for proper identification after the videos are recorded. Is there a way of doing any of those actions within the Mobile SDK?

Thanks in advance for the support.

Best regards.

E.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43234'>Zendesk ticket #43234</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
1. Sorry as you said that only the GIMBAL_PITCH action supported, but you can rotate the drone's heading with the action ROTATE_AIRCRAFT as a workaround.

2. It's GO HOME logic and can't around, please access the spec of the drone.

3. This issue needs to confirm with the engineer first and will contact you again.
Also, there is no reboot method for the M210 V2 RTK drone.


4. The SDK provides the setMediaFileCustomInformation to store the custom info but not supported by the XT2 camera.
 ![](https://djisdksupport.zendesk.com/attachments/token/1PxxReXceuC6b2U6B5piePeMA/?name=inline1733707816.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/1PxxReXceuC6b2U6B5piePeMA' target='zd_attach'>inline1733707816.png</a>

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43234'>Zendesk ticket #43234</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
3. After confirming with the engineer, it should not need to reboot the drone after setting the RTK reference position to the equipment.
So we need to investigate further,  please contact us again with more detail via the form, will handle it in another thread.
https://formcrafts.com/a/dji-developer-feedback-en

4. This issue also need to investigate further,  please contact us again with more detail via the form, will handle it in another thread.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Developer Support
