### ISSUE TITLE
如何获取民航客机靠近的警告信息

### ISSUE THREAD

**Issue by yand9807** [dji-sdk/Mobile-SDK-Android#753]
您好，我看到在pilot上有民航客机靠近的警告，如何在mobilesdk中获取这个警告信息？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43256'>Zendesk ticket #43256</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

MSDK目前没有检测民航客机接近的功能。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
