### ISSUE TITLE
精灵3A gimbalPitch invalid

### ISSUE THREAD

**Issue by dengdeyan** [dji-sdk/Mobile-SDK-Android#755]
新的版本，精灵3A在上传航线任务时，相机俯仰值只能是大于-30，小于-30的角度提示gimbal pitch invalid range, M210上传正常。

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43301'>Zendesk ticket #43301</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

不同的飞机/云台能转动的角度不一样，这个是固件在做限制，你调用一下getCapabilities查一下云台能转动pitch多少度，另外把setPitchRangeExtensionEnabled打开。你之前的版本没有问题吗？你在切回去看看是否之前的版本可以用？是4.13.1吗？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dengdeyan** [comment]
您好，普通的正射-90度俯仰角，肯定是在范围之内的，4.14不行，4.13.1和之前的版本可以，现在是精灵3A有这个问题，M210可以，没有试更多的型号。

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43301'>Zendesk ticket #43301</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

听你的描述感觉这是问题，我已经跟研发提单解决这个问题，预计在5月修复。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43301'>Zendesk ticket #43301</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

确认是bug，将于4.14正式版修复，预计在2月底发布。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43301'>Zendesk ticket #43301</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

我们最近出了4.15版本，你的问题解决了吗？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
