### ISSUE TITLE
WaypointMissionOperatorListener回调和FlightControllerState.Callback返航执行状态不触发

### ISSUE THREAD

**Issue by SaltedFishJoe** [dji-sdk/Mobile-SDK-Android#756]
MSDK版本：4.14-trial1
无人机型号：御2Zoom
无人机固件版本：V01.00.0670
问题描述：
1. WaypointMissionOperatorListener的onExecutionStart偶发不回调。
2. 使用WaypointMission的finishedAction为GO_HOME，任务结束返航后，FlightControllerState.Callback的回调中FlightControllerState的GoHomeExecutionState的值一直到GO_DOWN_TO_GROUND。此时无人机保持地面2米悬停，不会触发COMPLETED值。

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43322'>Zendesk ticket #43322</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
1. 麻烦填写下问题详细收集表单，收到更多信息后将会快速为您处理。
https://formcrafts.com/a/dji-developer-feedback-cn

2. 从现象上看，飞机悬停处于待确认着陆状态，您可以使用confirmLanding方法确认着陆。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by SaltedFishJoe** [comment]
感谢回复。
1.测试未能再复现。
2.确实是需要执行confirmLanding。
