### ISSUE TITLE
请问怎么平滑、持续的调节焦距，类似摇杆转动云台速度模式？

### ISSUE THREAD

**Issue by addriumruss** [dji-sdk/Mobile-SDK-Android#757]
M600, Z30, Msdk4.14, 安卓10
现在需要接入外部摇杆，平滑的转动云台和焦距。
云台转动采用速度模式解决了， 现在焦距没找到速度模式，采用camera.setOpticalZoomFocalLength总是一顿一顿的，它只能传入整数，无法做到平滑调节。
请问还有没有什么其它办法？
谢谢！

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43455'>Zendesk ticket #43455</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
十分抱歉，调整焦距没有速度模式，仅支持传参的方式，暂没有其他办法。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
