### ISSUE TITLE
sample无法连接上无人机spark

### ISSUE THREAD

**Issue by hwanyu112** [dji-sdk/Mobile-SDK-Android#758]
第一次通过遥控器飞行器一起连上了手机，DJI GO 4里一切正常，直接打开DJI SDK Sample显示连接上了，里面demo的功能也可以使用。但过了几个小时再次尝试连接时DJI GO 4里显示已连接，也可以控制，打开DJI SDK Sample却显示没有设备连接，这是怎么回事啊？
使用的是华为P40Pro，安卓10
无人机是spark
用的master版本的MSDK Sample

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43473'>Zendesk ticket #43473</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

应该是DJI GO 4占用了端口，所以连接不上，你到后台把所有app杀掉，再打开demo就行了。还是不行的话，重新插拔usb线。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dewens12** [comment]
是否支持Mavic Air在不插入耳机的情况下使用DJI护目镜？

Dwayne Ewens, MBA
832-622-2960 cell

________________________________
