### ISSUE TITLE
请问如何实现msdk调节相机焦距

### ISSUE THREAD

**Issue by hwanyu112** [dji-sdk/Mobile-SDK-Android#759]
想通过输入具体参数来实现相机的调焦，不知道有没有类似的demo，还有目前支持的可调节相机参数有哪些呢？谢谢

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43529'>Zendesk ticket #43529</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

首先要看你的机型支不支持设置焦距。红框是设置光学变焦和混合变焦的焦距，在Camera类里。
 ![](https://djisdksupport.zendesk.com/attachments/token/zMYtl7gd2dqxLJEa3m8wMup2V/?name=inline1327982886.png)​

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/zMYtl7gd2dqxLJEa3m8wMup2V' target='zd_attach'>inline1327982886.png</a>

**Comment by dewens12** [comment]
对Phantom 4 Pro V2.0的支持吗

Dwayne Ewens, MBA
832-622-2960 cell

________________________________

**Comment by hwanyu112** [comment]
> Agent comment from William Wong in [Zendesk ticket #43529](https://djisdksupport.zendesk.com/agent/tickets/43529):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> 首先要看你的机型支不支持设置焦距。红框是设置光学变焦和混合变焦的焦距，在Camera类里。
> ![](https://camo.githubusercontent.com/ec1b93684049bc8063d4d1be8790e0db244777e745b12a7044fa3b5b873b8f1f/68747470733a2f2f646a6973646b737570706f72742e7a656e6465736b2e636f6d2f6174746163686d656e74732f746f6b656e2f7a4d59746c376764326471784c4a4561336d38774d757032562f3f6e616d653d696e6c696e65313332373938323838362e706e67)​
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持
> [inline1327982886.png](https://djisdksupport.zendesk.com/attachments/token/zMYtl7gd2dqxLJEa3m8wMup2V)

谢谢解答！M210和M300支持调节那些相机参数呢？
