### ISSUE TITLE
After sd card format, sdcardstate callback is not called.

### ISSUE THREAD

**Issue by louie2107** [dji-sdk/Mobile-SDK-Android#76]
DJI Android SDK version : 3.5.1
DJI Product : Phantom 4,
Android system version: Android 6.0.1
Android device: Nexus 7
Android Studio version : 2.2.3

When calling format sd card, sometimes the sdcardstate callback is not called, when it should be.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
