### ISSUE TITLE
如何检测无人机是否被其他App连接

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#760]
#### 场景：

1. 手机默认设置使用AppA连接无人机
2. 无人机和手柄已经打开，手柄连接手机时，AppA成功连接无人机
3. 按Home使AppA后台运行
4. 打开我方App，弹出是否运行我方App连接无人机的对话框，用户选择允许
5. 允许后用户始终无法在我方App连接无人机，因为AppA一直在后台连接无人机

这种场景，如何知道AppA在连接无人机，并告知用户？

此时`DJISDKManager.getInstance().product`一直返回空

而iOS端，不需要关注这些问题，只要切换到另一个App，该App会成功地连接无人机

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43673'>Zendesk ticket #43673</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

Android端没有办法检测，因为连接不上就会一直为空，没有办法判断飞机是否被其他设备正在连接。出现这种情况只能手动打开后台把后台程序清除才可以连上。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
