### ISSUE TITLE
DJIWaypointAction does not executed with DJIWaypointMission 

### ISSUE THREAD

**Issue by chenxiaojin** [dji-sdk/Mobile-SDK-Android#77]
DJI Android SDK version : 3.5.1
DJI Product : Phantom 3 4K,
Android system version: Android 6.0.1
Android device: XIAOMI 4
Android Studio version : 2.2.3

this is my code for create DJIWaypointMission:

                DJIWaypointMission waypointMission = new DJIWaypointMission();        
                waypointMission.flightPathMode = DJIWaypointMission.DJIWaypointMissionFlightPathMode.Normal;

                Mission.WayPointMission wyMission = mission.getWayPoint();
                waypointMission.autoFlightSpeed = wyMission.getSpeed();
                waypointMission.maxFlightSpeed = wyMission.getSpeed();
                List<DJIWaypoint> waypoints = new ArrayList<>();

                for (Mission.WayPointMission.WayPoint wayPoint : wyMission.getCombinaData()) {
                    
                    latlngs = GPSUtil.convert2GPS(wayPoint.getLatitude(), wayPoint.getLongitude());
                    DJIWaypoint point = new DJIWaypoint(latlngs[0], latlngs[1], wayPoint.getAltitude());
                    // add action
                    addPanoramaAction(point);
                    
                    waypoints.add(point);
                }
                waypointMission.addWaypoints(waypoints);
                // finish action
                waypointMission.finishedAction = getFinishedAction(wyMission.getFinishAction());

                executeMission(waypointMission);

wyMission.getCombinaData()'s size is 2
and the addPanoramaAction function code is:
                
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, -180));       
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0));       
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, -135));        
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0));       
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, -90));        
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0));        
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, -45));       
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0));      
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, 0));       
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0));       
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, 45));
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0));
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, 90));
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0));
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, 135));
                waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0));
`

the aircraft fly to the waypoint without execute any waypoint action, and then fly to next waypoint.

Why the action is not executed?
Is there a problem with my code?

**Comment by chenxiaojin** [comment]
@oliverou Hi, can you help me with it?

**Comment by dji-dev** [comment]
From the code we couldn't see any errors.  Have you observed the rotate drones command doing? or both the rotation as well as the taking photos doesn't work.

**Comment by chenxiaojin** [comment]
All actions are not executed, the aircraft arrived at the first point, immediately flew to the next point, rotation action does not work, too.

IOS SDK doesn't have this problem, and I can't find any error from the code.
Have you ever tested a waypoint mission before? Does anyone else have feedback this problem?

**Comment by chenxiaojin** [comment]
@dji-dev 
Hi, here is the same prbolem: http://forum.dev.dji.com/thread-26807-1-1.html

**Comment by chenxiaojin** [comment]
@dji-dev Hi, I delete the following code:
```
waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.RotateAircraft, -180));       
waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.StartTakePhoto, 0)); 
```
then the waypoint action can be executed.  

It is the problem of DJIWaypointActionType.RotateAircraft range ?

**Comment by mandemeskel** [comment]
I believe that limit is for actions per waypoint:
> The number of waypoint actions should not be larger than MAX_ACTION_COUNT.  [...]The maximum number of waypoint actions you can add is 15.

`static final int MAX_ACTION_COUNT = 15`

**Comment by kenargo** [comment]
Correct,  per Waypoint

⁣Sent from Blue ​

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
For any Mission related task, please check out our new `MissionControl` class.
For WayPointMission, please check out our new `WaypointMissionOperator` class.
Thanks!
