### ISSUE TITLE
Mini 2 support

### ISSUE THREAD

**Issue by zeroed-tech** [dji-sdk/Mobile-SDK-Android#773]
Just adding another issue to request SDK support for the mini 2, this is a key feature that the mini 1 had and is missing.

And before you close this issue saying you aren't planning to support it and to keep an eye on the roadmap, please note that the roadmap isn't a roadmap, everything on it is complete. Does this mean development on the SDK for all platforms is finished?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/44062'>Zendesk ticket #44062</a>:<br><br>Dear Client
Thank you for contacting DJI.

No, we havn't update the Roadmap yet, there will be a 4.14 official version release on Monday and we are working on 4.15. I will tell product manager to update the Roadmap soon. The Mini 2 will not be supported in MSDK 4.X version but will support in MSDK 5.X version. But there is no estimate release date for MSDK 5.X version yet. So I cannot say we will support Mini 2 soon. But anyway at the end of the day, it will be supported.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by zeroed-tech** [comment]
Sounds great @dji-dev , just knowing support is going to happen at some point is enough for me, everything is seen previously said it was never going to happen.

Thanks for letting me know
