### ISSUE TITLE
downloadMission() returns "failed"

### ISSUE THREAD

**Issue by chenxiaojin** [dji-sdk/Mobile-SDK-Android#78]
DJI Android SDK version : 3.5.1
DJI Product : Phantom 3 4K,
Android system version: Android 6.0.1
Android device: XIAOMI 4
Android Studio version : 2.2.3

I have uploaded the waypoint mission by prepareMission(), and then through the downloadMission() download task, but it returns "failed". 
SDK Sample Code has the same problem.
Why can't download mission?

By the way,  sometimes app may crashed for  some reasons,  If a mission is executing, how can I get the mission info ? 
I have a tested, DJIMissionManager.getCurrentExecutingMission() returns null after restart app, and now downloadMission() returns "failed" , how can I get the executing mission info ?

**Comment by jtuchek** [comment]
@chenxiaojin I believe downloadMission only works with `WaypointMission` types.

Also, getCurrentExecutingMission only seems to be kept in the Android process, not the aircraft - so it won't be tolerant if the application crashes/closes for whatever reason.

**Comment by oliverou** [comment]
Hi @chenxiaojin , we have released Android SDK 4.0 recently, could you give it a try and check if the issue still exist? Thanks!

**Comment by SilverChangjian** [comment]
Hi, this feature highly depends on the firmware logic. The aircraft would not provide the uploaded list of the waypoint mission until the mission has already started.
