### ISSUE TITLE
New version 4.14 Rendor problem occur once Run app

### ISSUE THREAD

**Issue by KIYONG-KWON** [dji-sdk/Mobile-SDK-Android#784]
Until i run the code, all layouts can be viewed normally in Android Studio. However, once \i run the code, Rendor problems arise in some layouts. Even if Rendor problem occurs, the build is normal.
Please help.

java.lang.VerifyError: Constructor must call super() or this() before return Exception Details: Location: dji/sdk/sdkmanager/DJISDKManager. ()V @0: return Reason: Error exists in the bytecode Bytecode: 0x0000000: b12a 5959 5c5c 5c5c 5c5c 5cb7 00aa 03b5 0x0000010: 00ac 01b5 00ae bb00 b059 03b7 00b3 b500 0x0000020: b5b8 00b9 be04 64b5 00bb 01b5 00bd bb00 0x0000030: bf59 b700 c0b5 00c2 01b5 00c4 01b5 00c6 0x0000040: 01b5 00c8 01b5 00ca 01b5 00cc 01b5 00ce 0x0000050: 01b5 00d0 bb00 1559 2ab7 00d3 b500 d5bb 0x0000060: 0013 592a b700 d6b5 00d8 bb00 da59 03b7 0x0000070: 00dd b500 dfb8 00e4 b800 e757 a700 354b 0x0000080: b200 e92a b800 ef03 bd00 04b8 00f5 b200 0x0000090: e9bb 00f7 59b7 00f8 12fa b800 96b6 00fe 0x00000a0: 2ab6 0102 b600 feb6 0105 03bd 0004 b800 0x00000b0: f5b1 Exception Handler Table: bci [117, 127] => handler: 127 Stackmap Table: full_frame(@127,{},{Object[#169]}) same_frame(@177)    at com.dji.sdk.sample.internal.view.MainContent.initUI(MainContent.java:230)   at com.dji.sdk.sample.internal.view.MainContent.onFinishInflate_Original(MainContent.java:134)   at com.dji.sdk.sample.internal.view.MainContent.onFinishInflate(MainContent.java:-1)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1136)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1097)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)   at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:204)   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1161)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1119)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1097)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:1126)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1097)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)   at android.view.LayoutInflater.inflate(LayoutInflater.java:682)   at android.view.LayoutInflater.inflate(LayoutInflater.java:501) Copy stack to clipboard   Tip: Try to refresh the layout.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/44337'>Zendesk ticket #44337</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
That's so weird.
Maybe you can try to clean&rebuild the project and then uninstall/install to try again.
Or please try with another phone check if it's an incompatibility problem.

Thanks,

Luce Luo
DJI Developer Support

**Comment by KIYONG-KWON** [comment]
If I run clean solution, Render Problem disappears immediately and I can see all layouts again. However, some layouts cannot be shown due to a Render problem error once it build. This problem is the same whether it is a mobile phone or AVD that uses Android 10 OS.

For your information, the following error occurred in the initial state after the clean solution was executed and then it changes to Rendor Problem error after build.
I have little experience in Android development, so please understand even if it is a basic question.
---------------------------------------------------------------------------------------------
The following classes could not be found:
- com.dji.sdk.sample.internal.view.MainContent (Fix Build Path, Edit XML, Create Class)
Tip: Try to build the project.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/44337'>Zendesk ticket #44337</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
What Android Studio version you are using?
I try to clean and build it again with my 4.1 Android Studio, it works well.
And there is no other user report this problem, I have no idea for the being time.
 ![](https://djisdksupport.zendesk.com/attachments/token/qrxQaaCtxxcjdUJxsD30p3Ij6/?name=inline-682972429.png)​
Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/qrxQaaCtxxcjdUJxsD30p3Ij6' target='zd_attach'>inline-682972429.png</a>
