### ISSUE TITLE
不同机型在没有SD卡时调用refreshFileListOfStorageLocation返回异常不一致

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#793]
机型：mavic 2 zoom

在没有插入sd卡时，调用`refreshFileListOfStorageLocation(StorageLocation var1, CompletionCallback var2)`，其中var1为`SettingsDefinitions.StorageLocation.SDCARD`，返回`DJIError.MEDIA_REQUEST_SERVER_ABORT`这个异常。

对于机型P4P 或者 iOS SDK调用上述方法时返回`DJICameraError.SD_CARD_NOT_INSERTED`这个异常，返回结果行为不一致

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/44673'>Zendesk ticket #44673</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
您使用的安卓MSDK固件版本多少？

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by luoyexk** [comment]
MSDK: 4.14
Aircraft: 01.00.0670
Remote Controller: 01.00.0640

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/44673'>Zendesk ticket #44673</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
这边尝试测试是没有问题的，会返回没插卡提示“Camera has no SD Card”。
如果返回DJIError.MEDIA_REQUEST_SERVER_ABORT错误，一般是没有进入下载模式，或者传输不稳定导致，建议您检查下。
 ![](https://djisdksupport.zendesk.com/attachments/token/uXDktSQHhWlMAGJDTilw4TQAQ/?name=inline-1476802843.png)​



非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by luoyexk** [comment]
你的回答解决了问题。确实如此

mavic 2 zoom

在`SettingsDefinitions.CameraMode.SHOOT_PHOTO`模式下没有插入SD卡调用`mediaManager.refreshFileListOfStorageLocation(SettingsDefinitions.StorageLocation.SDCARD, refreshFileListListener);`会出现`DJIError.MEDIA_REQUEST_SERVER_ABORT`，

在`SettingsDefinitions.CameraMode.MEDIA_DOWNLOAD`模式下没有插入SD卡调用`mediaManager.refreshFileListOfStorageLocation(SettingsDefinitions.StorageLocation.SDCARD, refreshFileListListener);`会出现`Camera has no SD Card`，

P4P

在`SettingsDefinitions.CameraMode.SHOOT_PHOTO`模式下没有插入SD卡调用`mediaManager.refreshFileListOfStorageLocation(SettingsDefinitions.StorageLocation.SDCARD, refreshFileListListener);`会出现`DJICameraError.SD_CARD_NOT_INSERTED`，
