### ISSUE TITLE
MediaFile映射错误

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#794]
机型：P4P
SDK 版本：4.14

在不关机的情况下，切换SD卡拍摄，调用`MediaFile.fetchFileData`的方法时，下载了错误文件；
操作流程：

~~1. 插入A sd卡，拍摄1张照片，例如生成了DJI_001.JPG，代码中记录对象mediaFileA1~~

~~2. 插入B sd卡，拍摄1张照片，例如也生成了DJI_001.JPG，代码中记录对象mediaFileB1~~

~~3. 此时缓存得到了两个mediaFile对象，调用`mediaFileA1.fetchFileData`，会下载B卡的DJI_001.JPG~~

准备流程：

1. 准备好两张格式化好的卡A，B
2. B卡拍1张照片，生成`DCIM\100MEDIA\DJI_0001.JPG`
3. 拔出B卡，退出程序

复现流程：

1. 插入A卡，进入程序
2. 拍1张照片，此时A卡也生成`DCIM\100MEDIA\DJI_0001.JPG`
3. 拔出A卡，插入B卡
4. 调用`MediaFile.fetchFileData`，开始下载
5. 下载完成
6. 即mediaFile指向的是A卡，却下载了B卡的文件，这是不正确的行为，没有进行文件校验，只是单纯的通过路径下载

iOS未复现该BUG，Android 100%复现

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/44674'>Zendesk ticket #44674</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

首先这个场景基本上是很罕见的，其次在下载照片直接你需要先调用refreshFileListOfStorageLocation后再调用getSDCardFileListSnapshot，这样保证你获取的MediaFileList是B卡的FileList，再下载B卡的照片。另外，从最后的结果来看是没有错的，你确实下载了B卡的照片。你是从MediaFileCallBack里面拿的MediaFile吧，你认为换卡后下载得还是A卡的照片其实已经不是了，是因为MediaFile的数据结构没有包含照片信息，我估计是路径信息。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by luoyexk** [comment]
插入A卡拍摄照片时，从MediaFileCallBack里得到的mediaFileA，此时不关程序不关无人机换B卡后，使用的mediaFileA下载文件，应该直接抛出异常，不应该下载B卡里同名同文件夹里的照片，毕竟mediaFileA里还是有一些metadata可以做校验。

如果单纯的通过路径下载照片，那是否可以认为，在刚开机SD卡状态为RESET时，不必调用`refreshFileListOfStorageLocation`，直接构造一个MediaFile对象下载指定路径的文件，岂不是省时省力，因为现在`refreshFileListOfStorageLocation`会消耗大量的时间，对于128G的SD卡都要等几分钟

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/44674'>Zendesk ticket #44674</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

我觉得这个问题修改意义不大，我会把它作为一个bug单上报，由研发产品经理决定是否修改。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by NoticeVengus** [comment]
这样不打算修复么

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/44674'>Zendesk ticket #44674</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

你好，我已经将你们的问题反馈上去了，近期有答复我会立即回复你们。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/44674'>Zendesk ticket #44674</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

研发评估是用法问题，下载照片前应该刷新SD卡列表，再获取SD卡再下载，不做修改。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
