### ISSUE TITLE
setRTKMaintainPositioningAccuracyModeEnabled 这个有没有必要开启呢？看注释看不太懂。

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#797]
开启后在10分钟以内定位精度会更准确吗？对遥控器断连后的定位有没有帮助呢？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/44850'>Zendesk ticket #44850</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
指的是当对视RTK信号时候，飞机在10分钟内将会尝试保持定位精度。
使用RTK情况下，对遥控器断连后维持机体更精准定位肯定是有帮助的。

 ![](https://djisdksupport.zendesk.com/attachments/token/kzoSXVpUkgHGckP3K1p4EK2nv/?name=inline-160383443.png)​

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/kzoSXVpUkgHGckP3K1p4EK2nv' target='zd_attach'>inline-160383443.png</a>

**Comment by SJJ-dot** [comment]
嗯，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月12日(周五) 下午2:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dji-sdk/Mobile-SDK-Android] setRTKMaintainPositioningAccuracyModeEnabled 这个有没有必要开启呢？看注释看不太懂。 (#797)




 
Agent comment from Luce Luo in Zendesk ticket #44850:

尊敬的用户，
 
您好！感谢您联系DJI 大疆创新。
 指的是当对视RTK信号时候，飞机在10分钟内将会尝试保持定位精度。
 使用RTK情况下，对遥控器断连后维持机体更精准定位肯定是有帮助的。
 
​
 
非常感谢您的理解与配合，祝您生活愉快！
 
Best Regards,
 
DJI 大疆创新SDK技术支持
inline-160383443.png
