### ISSUE TITLE
libdjivideo.so crashes

### ISSUE THREAD

**Issue by y22ma** [dji-sdk/Mobile-SDK-Android#8]
Hello!

I'm writing an application that performs image processing on the decoded video stream using the DJIReceivedVideoFrameCallBack API, and I'm on v2.4 of the SDK.

We often experience segfault within libdjivideo.so, at ff_combine_frame+286 according to ADB. This is found on Marshmellow and Lollipop across multiple makes of Android devices. 

Please kindly advise!

**Comment by bradhoekstra** [comment]
This is the log output when this segmentation fault happens:

    10-21 13:19:36.761 13846-13904/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x98ec0000 in tid 13904 (Thread-2313)
    10-21 13:19:36.767 194-194/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    10-21 13:19:36.767 194-194/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0/MRA58K/2256973:user/release-keys'
    10-21 13:19:36.767 194-194/? A/DEBUG: Revision: '0'
    10-21 13:19:36.767 194-194/? A/DEBUG: ABI: 'arm'
    10-21 13:19:36.767 194-194/? A/DEBUG: pid: 13846, tid: 13904, name: Thread-2313  >>> com.vertical.dji.tracker <<<
    10-21 13:19:36.767 194-194/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x98ec0000
    10-21 13:19:36.792 194-194/? A/DEBUG:     r0 97f69600  r1 98ebfffa  r2 00000017  r3 0000000a
    10-21 13:19:36.793 194-194/? A/DEBUG:     r4 9b7c02c8  r5 9abfc7cc  r6 9abfc7c8  r7 9b7c0010
    10-21 13:19:36.793 194-194/? A/DEBUG:     r8 9abfc880  r9 98ebfa10  sl 000005e1  fp 80000000
    10-21 13:19:36.793 194-194/? A/DEBUG:     ip 40000000  sp 9abfc728  lr 00000097  pc b6ccf688  cpsr 28030030
    10-21 13:19:36.796 194-194/? A/DEBUG:     #00 pc 00017688  /system/lib/libc.so (__memcpy_base+127)
    10-21 13:19:36.796 194-194/? A/DEBUG:     #01 pc 001ad563  /data/app/com.vertical.dji.tracker-1/lib/arm/libdjivideo.so (ff_combine_frame+286)

**Comment by bradhoekstra** [comment]
And the same thing, but this time when running the DJI SDK Demo:

    10-21 13:46:11.483 22764-23113/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9f340000 in tid 23113 (Thread-2408)
    10-21 13:46:11.485 194-194/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    10-21 13:46:11.485 194-194/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0/MRA58K/2256973:user/release-keys'
    10-21 13:46:11.485 194-194/? A/DEBUG: Revision: '0'
    10-21 13:46:11.485 194-194/? A/DEBUG: ABI: 'arm'
    10-21 13:46:11.485 194-194/? A/DEBUG: pid: 22764, tid: 23113, name: Thread-2408  >>> com.dji.sdkdemo <<<
    10-21 13:46:11.485 194-194/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x9f340000
    10-21 13:46:11.507 194-194/? A/DEBUG:     r0 9de7e400  r1 9f33fffa  r2 0000001a  r3 0000000a
    10-21 13:46:11.507 194-194/? A/DEBUG:     r4 9c2002c8  r5 9e2ff7c4  r6 9e2ff7c0  r7 9c200010
    10-21 13:46:11.507 194-194/? A/DEBUG:     r8 9e2ff880  r9 9f33fc10  sl 000003e4  fp 80000000
    10-21 13:46:11.507 194-194/? A/DEBUG:     ip 40000000  sp 9e2ff720  lr 0000000d  pc b6ccf688  cpsr 200f0030
    10-21 13:46:11.510 194-194/? A/DEBUG:     #00 pc 00017688  /system/lib/libc.so (__memcpy_base+127)
    10-21 13:46:11.510 194-194/? A/DEBUG:     #01 pc 001ad563  /data/app/com.dji.sdkdemo-1/lib/arm/libdjivideo.so (ff_combine_frame+286)

**Comment by SilverChangjian** [comment]
Thanks for providing this problem, we will try to reproduce it and solve ASAP.

**Comment by y22ma** [comment]
@SilverChangjian just following up to see if you have an update on the status of this issue.

**Comment by sidkanchan** [comment]
@SilverChangjian I am seeing this issue as well. But it only seems to occur on our Marshmallow devices.

```
11-05 13:57:19.657: A/libc(22845): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8e3c0000 in tid 22998 (Thread-8589)
11-05 13:57:19.709: A/DEBUG(371): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-05 13:57:19.709: A/DEBUG(371): Build fingerprint: 'google/shamu/shamu:6.0/MRA58K/2256973:user/release-keys'
11-05 13:57:19.710: A/DEBUG(371): Revision: '0'
11-05 13:57:19.710: A/DEBUG(371): ABI: 'arm'
11-05 13:57:19.710: A/DEBUG(371): pid: 22845, tid: 22998, name: Thread-8589  >>> com.hivemapper.android.hivemapper.acceptance <<<
11-05 13:57:19.710: A/DEBUG(371): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8e3c0000
11-05 13:57:19.708: W/debuggerd(371): type=1400 audit(0.0:291): avc: denied { search } for name="com.google.android.gms" dev="dm-1" ino=408057 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
11-05 13:57:19.744: A/DEBUG(371):     r0 93bed300  r1 8e3bfffa  r2 00000010  r3 0000000a
11-05 13:57:19.744: A/DEBUG(371):     r4 89a802c8  r5 88dc07c4  r6 88dc07c0  r7 89a80010
11-05 13:57:19.744: A/DEBUG(371):     r8 88dc0880  r9 8e3bfd10  sl 000002da  fp 80000000
11-05 13:57:19.744: A/DEBUG(371):     ip 40000000  sp 88dc0720  lr 00000081  pc b6c9e688  cpsr 20010030
11-05 13:57:19.747: A/DEBUG(371): backtrace:
11-05 13:57:19.747: A/DEBUG(371):     #00 pc 00017688  /system/lib/libc.so (__memcpy_base+127)
11-05 13:57:19.747: A/DEBUG(371):     #01 pc 001ad563  /data/app/com.hivemapper.android.hivemapper.acceptance-1/lib/arm/libdjivideo.so (ff_combine_frame+286)
```

**Comment by mrjzhao** [comment]
Thanks for the reporting. This bug will only occur when using ffmpeg to decode the video data in Android 6.0. We will try to solve it.  But we recommend you to use hardware decoding.

**Comment by y22ma** [comment]
@mrjzhao thanks for the tip. Already tried the HW decoder, and it's displaying fine, but we can't seem to get any data from DJIReceivedVideoFrameCallBack when HW decoder is used.

We need the decoded data for image processing, and just wondering if there's anything special we need to do to get access to that with HW decoding enabled.

**Comment by an-kumar** [comment]
Hey @y22ma I'm also trying to use decoded data for image processing, but I can't seem to get data from DJIReceivedVideoFrameCallBack even when using software decoding. Could you possibly show a code snippet showing how you got it to work?

I'm using DJI Phantom 3 pro -- my code is:

```
...
DJIDrone.getDjiCamera().setReceivedVideoDataCallBack(mReceivedVideoDataCallBack);
DJIDrone.getDjiCamera().setReceivedVideoFrameDataCallBack(new DJIReceivedVideoFrameCallBack() {
            @Override
            public void onResult(byte[] bytes, int i) {
                Log.v(vTAG, "size of bytes buffer: " + i);
            }
        });
    }
```

But that log message is never shown.

**Comment by SilverChangjian** [comment]
Will close this issue, please refer to the mobile 3.0.1 for new interfaces and new implementation. Now we support the hardware decoding.

**Comment by VicV** [comment]
@SilverChangjian again this is unfair, my projects all rely on the Phantom 2 and the 3.0.1 SDK does not support that.

All of the older packages segfaul in the video renderer. Am I just supposed to go drop $1400 on a new drone or are you actually going to fix your stuff?
