### ISSUE TITLE
Performance warning by libaesni.so

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#80]
Hey all, 

when i start up my application i always facing this warning:

W/linker: libaesni.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
03-30 20:51:29.276 31581-31698/W/System.err: javax.crypto.IllegalBlockSizeException: last block incomplete in decryption
03-30 20:51:29.276 31581-31698/de.vermessung3d.skyveo.dbg W/System.err:     at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:850)
03-30 20:51:29.276 31581-31698/ W/System.err:     at javax.crypto.Cipher.doFinal(Cipher.java:1340)
03-30 20:51:29.276 31581-31698/ W/System.err:     at dji.midware.c.a.a.b(Unknown Source)
03-30 20:51:29.276 31581-31698/ W/System.err:     at dji.internal.geo.login.GeoLoginController.decryptedString(Unknown Source)
03-30 20:51:29.276 31581-31698/ W/System.err:     at dji.internal.geo.login.GeoLoginController.getAccountInfoFromDb(Unknown Source)
03-30 20:51:29.276 31581-31698/ W/System.err:     at dji.internal.geo.login.GeoLoginController.init(Unknown Source)
03-30 20:51:29.276 31581-31698/ W/System.err:     at dji.internal.geo.login.GeoLoginController.access$200(Unknown Source)
03-30 20:51:29.276 31581-31698/ W/System.err:     at dji.internal.geo.login.GeoLoginController$1.handleMessage(Unknown Source)
03-30 20:51:29.276 31581-31698/ W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-30 20:51:29.276 31581-31698/ W/System.err:     at android.os.Looper.loop(Looper.java:135)
03-30 20:51:29.276 31581-31698/ W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

Do you now anything about this?? Or do you maybe have a fix for that??

This happen under SDK 3.5 on an Android 5.0.1 Device without any connected drone.

Regards
xxmaestroxx

**Comment by oliverou** [comment]
Hi @xxmaestroxx, we have released the Android SDK 4.2.1, could you help to try it and see if this issue still exist? Please check our developer website to get it: <http://developer.dji.com/mobile-sdk/downloads/>

**Comment by xxmaestroxx** [comment]
Seems to be fixed, not able to find this log lines again within my app.
