### ISSUE TITLE
msdk 报错The radius of mission is over the acceptable limit, pls try to login and check radius of waypoint

### ISSUE THREAD

**Issue by Chauncy-Guo** [dji-sdk/Mobile-SDK-Android#809]
报错信息：The radius of mission is over the acceptable limit, pls try to login and check radius of waypoint
![11301616065697_ pic](https://user-images.githubusercontent.com/30928209/111617998-d2163800-881e-11eb-939e-67d220a5710d.jpg)

遥控器和飞机间隔几米，不可能出现过远的问题。想请教下这是什么原因导致的

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/45179'>Zendesk ticket #45179</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

这个意思是你的航点任务中的航点设置的飞行距离过远。比如你现在设置的最大飞行距离是500米，你有个航点设置离起飞点1000米就会报错。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by Chauncy-Guo** [comment]
thanks
