### ISSUE TITLE
Missing translations strings in SDK 4 release

### ISSUE THREAD

**Issue by kenargo** [dji-sdk/Mobile-SDK-Android#81]
#### Is this issue about bugs or crash issues of DJI Android SDK and Sample Code?

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

-  Description of the issue.
There are 3missing string translations in SDK 4 release

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
Build, ideally using newest build tools because that will find all the missing translations

-  Crash logs (If you can find it, it would be very helpful)
N/A

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
4.0

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
N/A

-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
N/A

-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
N/A

-  Android Studio version you are using (Like Android Studio 2.2, etc)
2.3

Error:(195) Error: "dji_check_air_encoder_upgrade_reason" is not translated in "zh-CN" (Chinese: China) [MissingTranslation]
Error:(196) Error: "dji_check_air_encoder_upgrade_solution" is not translated in "zh-CN" (Chinese: China) [MissingTranslation]
C:\Users\kenargo\Documents\Android\Inspection\dJISDKLIB\src\main\res\values\strings.xml

These 3 totalmissing in CN:

    <string name="dji_check_air_encoder_upgrade_reason">Aircraft updating.</string>
    <string name="dji_check_air_encoder_upgrade_solution">Solution: Wait for the update complete.</string>

and this is missing from CH string

<string name="version_name">4.0</string>

**Comment by kenargo** [comment]
Corrected to say 3 missing; the others where because my app doesn't translate to CH and the new compile tools seams to require apps to have same resources as modules.

**Comment by dji-dev** [comment]
The 4.2 release has both strings:

- dji_check_air_encoder_upgrade_reason
- dji_check_air_encoder_upgrade_solution

translated to Chinese. What is the third string? Can you verify using the new release please?

**Comment by dji-dev** [comment]
We have confirmed that the 4.0 jar package was missing the two strings you list and they are now present in the AAR package for 4.2.1 release.  Thanks.
