### ISSUE TITLE
Fail to download a large amount image from Drone

### ISSUE THREAD

**Issue by ltluc253** [dji-sdk/Mobile-SDK-Android#82]
I modify code in SampleCode to download a large amount image but almost files is failed. This issue occur on both SDK version 3.5.1 and 4.0.
Here is my code modify to download amount of images from Drone
SDK ver3.5.1: https://github.com/ltluc253/ReportDjiSDK/blob/master/FetchMediaView_1.java
SDK ver4.0: https://github.com/ltluc253/ReportDjiSDK/blob/master/FetchMediaView.java
Almost of my change is in method `private void fetchMediaData(final int index)`
Is my solution to fetch a lot of image correct? If no, please help me the solution to resolve it. Our project is stucked here :(
My Test Environment is:
Drone: Phantom 3 Pro, 4, 4 Pro
Mobile: Nexus 5, 9

**Comment by kenargo** [comment]
In my experience fetching images only works for a small number of images and, because of how slow it can be and that you need to have the UAV powered and connected it is much easier to pull the SD card.

**Comment by ltluc253** [comment]
@kenargo Thank you
I'm facing this problem in my app. But DJI GO app can download medias from Drone. I think it use PlaybackManager to fetch medias.
In my project, iOS app work fine with this feature.

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
