### ISSUE TITLE
Set Custom RCSwitchFlightModeMapping

### ISSUE THREAD

**Issue by Avistadrone** [dji-sdk/Mobile-SDK-Android#827]
Greetings,

I would like to implement in my app the possibility of changing the Flight Mode Mapping between Tripod/Position/Sport and Atti/Position/Sport like DJI Pilot for Mavic 2 Enterprise. 

As far as I know there is no set method for the RCSwithcMapping, so I would like to know if there is any way of achieve this.

Thanks.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/45577'>Zendesk ticket #45577</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
No, it's impossible to set the Flight Mode Mapping, it's fixed and only get method.
getRCSwitchFlightModeMapping

Thanks,

Luce Luo
DJI Developer Support

**Comment by Avistadrone** [comment]
Hello,

Thanks for the answer.
How should I set the Atti Mode then? I tried with the FlightControllerKey.FLIGHT_MODE and mode FlightMode.ATTI but it responds with error eventhough it's the same mode that the Switch sets when the tripod mode is changed to ATTI.

Thanks.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/45577'>Zendesk ticket #45577</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that there is no way to enter the ATTI mode via the MSDK method, should use the RC to switch.

Thanks,

Luce Luo
DJI Developer Support

**Comment by Avistadrone** [comment]
Okay,

If I use the RC to switch I cannot change the tripod mode to atti, is there any workaround to achieve this behaviour?

Thanks.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/45577'>Zendesk ticket #45577</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Please try to enable this setMultipleFlightModeEnabled first.

Thanks,

Luce Luo
DJI Developer Support

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/45577'>Zendesk ticket #45577</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I try to find this method, toggleAttitudeFlightMode is it you want?
https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html#djiflightcontroller_toggleattitudeflightmode_inline

Thanks,

Luce Luo
DJI Developer Support

**Comment by Avistadrone** [comment]
Yes, that's exactly what I want.

Thank you very much, I will try it.

Best regards.
