### ISSUE TITLE
内存泄露问题

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#828]
https://github.com/dji-sdk/Mobile-SDK-Android/blob/241af9a45b2753873c601b3988192bb202ed4c30/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/battery/PushBatteryDataView.java#L48

无人机运行过程中，在该界面拔掉连接手柄的数据线，然后再退出该界面，此时该行代码Battery是空的，导致setStateCallback(null)失败，从而引发内存发生泄露。

是否有通过DJISDKManager.getInstance()主动移除回调对象的方法？或考虑增加释放内存的方法

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/45580'>Zendesk ticket #45580</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
您可以使用destroy这个方法释放资源。
 ![](https://djisdksupport.zendesk.com/attachments/token/HzwbE3qz7aWHF2q7v0cm0Rxgx/?name=inline-350717737.png)​

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持<br><a href='https://djisdksupport.zendesk.com/attachments/token/HzwbE3qz7aWHF2q7v0cm0Rxgx' target='zd_attach'>inline-350717737.png</a>

**Comment by dashifuguye** [comment]
> Agent comment from Luce Luo in [Zendesk ticket #45580](https://djisdksupport.zendesk.com/agent/tickets/45580):
> 
> 尊敬的用户，
> 
> 您好！感谢您联系DJI 大疆创新。
> 您可以使用destroy这个方法释放资源。
> ![](https://camo.githubusercontent.com/9ae11dfc5f284b1fb28a4e9dbc75a6419af0f4d1a90750c7ec0a3a338f7fc9e5/68747470733a2f2f646a6973646b737570706f72742e7a656e6465736b2e636f6d2f6174746163686d656e74732f746f6b656e2f487a77624533717a37615748463271377630636d30527867782f3f6e616d653d696e6c696e652d3335303731373733372e706e67)​
> 
> 非常感谢您的理解与配合，祝您生活愉快！
> 
> Best Regards,
> 
> DJI 大疆创新SDK技术支持
> [inline-350717737.png](https://djisdksupport.zendesk.com/attachments/token/HzwbE3qz7aWHF2q7v0cm0Rxgx)

请问这个destroy()方法可以释放分配的native内存吗？
