### ISSUE TITLE
WaypointAction has incorrect validation range

### ISSUE THREAD

**Issue by kenargo** [dji-sdk/Mobile-SDK-Android#83]
-  Description of the issue.
The method WaypointAction includes dev-time validation of the parameters.  The validation is incorrect for the following action:

northPoint.addAction(new WaypointAction(WaypointActionType.GIMBAL_PITCH, -60));

This is because the class defines the valid range as @IntRange(from = 0L,to = 32767L)

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
Add the above action to a waypoint

-  Crash logs (If you can find it, it would be very helpful)
N/A

-  DJI Android SDK version you are using (Like Android SDK 3.4, etc)
N/A

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
N/A

-  Android system version you are using (Like Android 6.0.1, Android 5.1.1, etc)
N/A

-  Android device you are using (Like Samsung Galaxy Note 5, Nexus 5, etc)
N/A

-  Android Studio version you are using (Like Android Studio 2.2, etc)
2.3

**Comment by DavisDevasia** [comment]
Decompiled source:
`public static class DJIWaypointAction {
        public DJIWaypoint.DJIWaypointActionType mActionType;
        public int mActionParam = 0;

        public DJIWaypointAction(DJIWaypoint.DJIWaypointActionType var1, int var2) {
            this.mActionType = var1;
            this.mActionParam = var2;
        }
    }`
the parameter is just an _int_.

Where did you see _This is because the class defines the valid range as @IntRange(from = 0L,to = 32767L)_?

**Comment by kenargo** [comment]
Camera gimbal can be negative values but validation is positive values only so it shows error in editor

**Comment by DavisDevasia** [comment]
where is it validated.?

**Comment by kenargo** [comment]
The error is in the SDK itself. 

 

@IntRange(from = 0L,to = 32767L)?

 

The validation is on an actions parameter.

**Comment by DavisDevasia** [comment]
Sorry but I didn't understand where do you see that validation.
In my code, I set negative values for Gimbal pitch and I do not see any error!

```
// Action: Adjust gimbal pitch from 0 to -60, with 3 sec delay in between...
                    waypoint.hasAction = true;
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.GimbalPitch,0));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.Stay,3000));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.GimbalPitch,-10));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.Stay,3000));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.GimbalPitch,-20));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.Stay,3000));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.GimbalPitch,-30));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.Stay,3000));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.GimbalPitch,-40));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.Stay,3000));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.GimbalPitch,-50));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.Stay,3000));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.GimbalPitch,-60));
                    waypoint.addAction(new DJIWaypoint.DJIWaypointAction(DJIWaypoint.DJIWaypointActionType.Stay,3000));
                    // Add the waypoint to the mission
                    mDJIWayPointMission.addWaypoint(waypoint);
```

This code runs perfectly. No error, no warnings! And it is performed during the mission without fail!

**Comment by kenargo** [comment]
Are you using newest tools?

 

The Android code for the SDK says to show an error if value < 0; the newest tools reports the validation as shown below.

**Comment by DavisDevasia** [comment]
Yes, I am using the latest tools.

What is your SDK version?

Can you please tell the filename and line number where this @IntRange is specified?

**Comment by kenargo** [comment]
This is with SDK 4 release and SDK sample.

 

Are you in DJI; SZ?

**Comment by DavisDevasia** [comment]
Sorry, I've been using SDK 3.5.1

**Comment by dji-dev** [comment]
The range validation was removed in SDK release 4.1 .
