### ISSUE TITLE
Andorid crash for SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by dashifuguye** [dji-sdk/Mobile-SDK-Android#831]
![image](https://user-images.githubusercontent.com/21324724/112777594-30d87e80-9075-11eb-98e6-be24341a68d8.png)
![image](https://user-images.githubusercontent.com/21324724/112777877-d1c73980-9075-11eb-8355-9a0bbb1c98e8.png)

android MSDK4.13.1，  
飞行器是M300，
机型是PM430  
最近因为这个问题崩溃的有点多，崩溃信息如上，请问有啥解决思路没

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/45626'>Zendesk ticket #45626</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

需要提供更详细的信息，比如如何复现，升级到4.14.1是否能复现呢？

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by dashifuguye** [comment]
> Agent comment from William Wong in [Zendesk ticket #45626](https://djisdksupport.zendesk.com/agent/tickets/45626):
> 
> 尊敬的开发者，
> 您好，感谢您联系DJI 大疆创新。
> 
> 需要提供更详细的信息，比如如何复现，升级到4.14.1是否能复现呢？
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> Best Regards,
> DJI 大疆创新SDK技术支持

升级到4.14.1后，不仅payload的相机画面会经常卡住，而且一样会崩溃

**Comment by dashifuguye** [comment]
经过多次测试，发现原因应该是OOM，每次destroy后native部分的内存无法释放，多次注册就会导致OOM。解决方案：将飞行部分作为一个单独的进程，退出飞行时直接杀掉进程呢，可以大概率降低OOM
