### ISSUE TITLE
Aircraft有时候会报空指针异常

### ISSUE THREAD

**Issue by abc456879213** [dji-sdk/Mobile-SDK-Android#832]
通过DJISDKManager.getInstance().getProduct()方法得到Aircraft对象并保存到全局变量，得到时Aircraft不是null，但在之后的调用中有可能变null，期间是没有对Aircraft进行修改的，只是通过它get数据。请问是什么原因？

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/45780'>Zendesk ticket #45780</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

报空指针说明大概率飞机和遥控器断连了。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
