### ISSUE TITLE
Display ObstacleRadar Mavic 2 Enterprise

### ISSUE THREAD

**Issue by Avistadrone** [dji-sdk/Mobile-SDK-Android#833]
Greetings,

I am trying to display the Radar Map both Horizontal and Vertical in my app for Mavic 2 Enterprise, however as it's stated in the documentation, the PerceptionInformation is only supported by Matrice 300. And thus, the RadarKey.RADAR_UPWARDS_OBSTACLE_AVOIDANCE_ENABLED and RadarKey.RADAR_HORIZONTAL_OBSTACLE_AVOIDANCE_ENABLED respond with error 'Not supported' as expected.

My question is, how can I implement this or at least get the distance to the obstacle? I believe that must be a way since in DJI Pilot the radar is displayed for the Mavic 2 Enterprise.

Thank you.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/45817'>Zendesk ticket #45817</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The RadarKey is for the M300RTK radar only.
For the M2E drone, please refer to this sample:
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/flightcontroller/FlightAssistantPushDataView.java

Thanks,

Luce Luo
DJI Developer Support

**Comment by Avistadrone** [comment]
Hello Again,

I literally copied the sample code but the onUpdate method is never called. Any idea why this happens? Obstacle detection is enabled.
By the way, It looks like this sample only get the info of the obstacle detection sensor in the plane (Front, Left, Rigth and Back). Ho do I get the value of the updward sensor?


Thank you.

**Comment by Avistadrone** [comment]
Closing this since this is already implemented in the UX SDK.
