### ISSUE TITLE
m300 startMission  UNKNOWN(10010)

### ISSUE THREAD

**Issue by stacker10** [dji-sdk/Mobile-SDK-Android#842]
loadWaypointMission 和 uploadMission 都是成功的  start的时候，返回错误unknown(10010)

getWaypointMissionOperator().startMission(new CommonCallbacks.CompletionCallback() {
            @Override
            public void onResult(DJIError djiError) {
               
                    ToastUtil.Long(djiError.toString());
     
            }
        });

**Comment by stacker10** [comment]
WaypointV2MissionOperator 和  WaypointMissionOperator都有同样的问题

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/46211'>Zendesk ticket #46211</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

M300不支持WaypointMission，只支持WaypointV2Mission。你跑Sample也会出现这样的问题吗？你先把飞机连入Assistant 2模拟器里，打开WaypointV2MissionOperatorView后，点击Load-Upload-Start即可。
Link：https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/missionoperator/WaypointV2MissionOperatorView.java

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持

**Comment by stacker10** [comment]
原因没有登录dji账号，但是有几次成功上传并且航点任务执行成功
