### ISSUE TITLE
SecondaryVideoOutput in Smart Controller and Mavic 2 Enterprise

### ISSUE THREAD

**Issue by Avistadrone** [dji-sdk/Mobile-SDK-Android#846]
Greetings,

In the app that I am developing, a second display is connected to the Smart Controller HDMI port, I would like to get only the camera view (with no OSD) in the second display. I tried the following keys:
RemoteControllerKey.SECONDARY_VIDEO_OUTPUT_ENABLED,true
RemoteControllerKey.SECONDARY_VIDEO_OUTPUT_PORT, SecondaryVideoOutputPort.HDMI
RemoteControllerKey.SECONDARY_VIDEO_OSD_ENABLED, false

As it's stated in the documentation they didn't work since they are not supported. However, in DJI Pilot, there are three options available (Duplicate, Clear Camera View and Camera View). So the Smart Controller should be able to send only the 'Camera View' to the HDMI port.  Any way to achieve this?

Thanks.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/46261'>Zendesk ticket #46261</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that the MSDK doesn't support the SecondaryVideoOutput with the M2E drone, see this documentation.
https://developer.dji.com/api-reference/android-api/Components/RemoteController/DJIRemoteController.html#djiremotecontroller_issecondaryvideooutputsupported_inline
 ![](https://djisdksupport.zendesk.com/attachments/token/fSnxN43SlnTXBqB6dlOhnzlxI/?name=inline256083806.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/fSnxN43SlnTXBqB6dlOhnzlxI' target='zd_attach'>inline256083806.png</a>

**Comment by Avistadrone** [comment]
Hi Luce,

Thanks for your answer. Any workaround to change the image that is sent to the HDMI port? There must be one, because you implemented in DJI Pilot the possibility to change betweeen the following options:
'Duplicate Screen', 'Clear camera view' and 'Camera View'.

Thanks,

Best regards.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/46261'>Zendesk ticket #46261</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry, they have differences between DJI Pilot and MSDK.
After confirming with the engineer, the MSDK doesn't support the SecondaryVideoOutput API on the SmartController but the HDMI is available.
So you can plug the HDMI directly and will have the view output.

Thanks,

Luce Luo
DJI Developer Support

**Comment by Avistadrone** [comment]
Hello Again Luce,

Thanks for the help, I know that the HDMI can be plugged but it duplicates the screen.
I will try to get the image and send it to the hdmi port directly.

Best regards.

**Comment by DJI-William** [comment]
@Avistadrone In order to display the camera video stream directly on a bigger screen, try use SurfaceView in your app to display the video would solve the problem.
