### ISSUE TITLE
Enable Virtual Stick 后自稳问题

### ISSUE THREAD

**Issue by johnzhao2125** [dji-sdk/Mobile-SDK-Android#848]
您好，我编译了这个demo code并在我的Mavic Mini上测试，发现一个问题。当我点击 flight controller 中 Virtual Stick 的 Enable Virtual Stick按钮时，无人机会失去自稳能力，向一个方向一直偏航飞去。我想请问如何在使用虚拟摇杆时可以使用大疆的自稳功能，谢谢。

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/46364'>Zendesk ticket #46364</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
有GPS条件下可以使用setVirtualStickAdvancedModeEnabled开启维稳功能。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
