### ISSUE TITLE
Duplicated documentation

### ISSUE THREAD

**Issue by kenargo** [dji-sdk/Mobile-SDK-Android#86]
In Camera.setSystemStateCallback the Precondition and Post condition text is duplicated

Precondition: 
You must first define a Callback object to pass in as a parameter. 

Post Condition: 
The Callback object that was passed in as a parameter will call its onResult function at regular intervals. 
The onResult function takes a CameraSystemState object as a parameter.era's SD card information callback. 

Precondition: 
You must first define a Callback object to pass in as a parameter. 

Post Condition: 
The Callback object that as passed in as a parameter will call its onResult function at regular intervals. 
The onResult function takes in a SDCardState object as a parameter.

**Comment by oliverou** [comment]
Hi @kenargo , thanks for the feedbacks, already update the online API Reference. Close the ticket now.
