### ISSUE TITLE
setThermalMeteringArea和 setThermalSpotMeteringTargetPoint方法使用问题

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#860]
如何将View的相关参数转换成这两个方法中需要的RectF和PointF

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47109'>Zendesk ticket #47109</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
 ![](https://djisdksupport.zendesk.com/attachments/token/0sOqRTBI35dlB61gi876jGiU8/?name=inline1711930092.png)
返回温度点的坐标系是基于图传View，左上角为原点，x轴向下为正，y轴向右为正
图传整个View x轴可分为10000刻度，y轴可分成10000刻度

您可以参考上述内容自行转换。


非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持<br><p><em><small>°°°</small></em></p>
