### ISSUE TITLE
Mavic 2 Enterprise Advanced Supported?

### ISSUE THREAD

**Issue by tobiasfriden** [dji-sdk/Mobile-SDK-Android#861]
Is the Mavic 2 Enterprise Advanced supported by Mobile SDK? It is mentioned on this page: https://www.dji.com/se/mavic-2-enterprise-advanced/faq that it supports 3rd-party apps but we cannot get it to work with MSDK (no telemetry/video or anything in the app).
If not, when will it be supported?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/47159'>Zendesk ticket #47159</a>:<br><br>Dear Client
Thank you for contacting DJI.

We will support MSDK in 4.15 version, estimted released date is 21st June. We have already provided 4.15Beta version for Pro account user. You can upgrade your account to Pro account and go to developer website to download.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support<br><p><em><small>°°°</small></em></p>
