### ISSUE TITLE
将mobileStationLocation坐标点绘制到高德地图上，绘制的点与飞机位置没有重合。fusionMobileStationLocation同样如此

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#867]
飞机p4r，msdk 最新的。

**Comment by SJJ-dot** [comment]
开启了rtk精度保持有没有关系

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47372'>Zendesk ticket #47372</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
大疆飞机基本是基于WGS-84坐标体系（设置了setNetworkServiceCoordinateSystem坐标系统则依据设置的），绘制到高德地图需要自行进行坐标转换。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持<br><p><em><small>°°°</small></em></p>
