### ISSUE TITLE
Enter Travel Mode

### ISSUE THREAD

**Issue by stacker10** [dji-sdk/Mobile-SDK-Android#873]
M300  MSDK 4.14.1 遥控器 显示Enter Travel Mode，获取不到视频和飞机状态信息、卫星信息、电池等信息

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47499'>Zendesk ticket #47499</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
使用DJI Pilot软件检查下是不是进入了运输模式。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
