### ISSUE TITLE
SDK is not working when project set to minSdkVersion >= 23

### ISSUE THREAD

**Issue by Jai-GAY** [dji-sdk/Mobile-SDK-Android#876]
As what other [user experience last year](https://github.com/dji-sdk/Mobile-SDK-Android/issues/574), when I [set it to 23, it hangs, white screen with no error](https://github.com/dji-sdk/Mobile-SDK-Android/blob/241af9a45b2753873c601b3988192bb202ed4c30/Sample%20Code/app/build.gradle#L17).

Tested on Mi 11 M2011K2G Android 11. Android Studio v4.2, [SDK version 4.14.1](https://github.com/dji-sdk/Mobile-SDK-Android/releases/tag/v4.14.1).

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47675'>Zendesk ticket #47675</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that It's recommended to set it to 19.
If you want to set the above version, please follow this thread.
https://github.com/dji-sdk/Mobile-SDK-Android/issues/574

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by Jai-GAY** [comment]
[android:extractNativeLibs="true"](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) solved the issue. thanks for the response.
