### ISSUE TITLE
关于代码开源

### ISSUE THREAD

**Issue by Jackson-Liu-1** [dji-sdk/Mobile-SDK-Android#877]
我想查看一下sdk的API源码，请问源码是开源的吗？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47824'>Zendesk ticket #47824</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，SDK是不开源的，无法提供源码。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
