### ISSUE TITLE
Matrice RTK 300 RTK Waypointv2 Error "Unknown" when starting the message

### ISSUE THREAD

**Issue by yali25** [dji-sdk/Mobile-SDK-Android#878]
Hi,

I try to get a WaypointV2 mission to run inside the DJI Simulator. I use the following code.

I get the following  messages:
1. Mission loaded
2. Mission Uploaded
3. Something went Wrong Unknown

So when I call startMission, I get the error shown in above in (3.) 
What I'am doing wrong?

Thank you for your help

` if (waypointV2MissionOperator.getCurrentState().equals(WaypointV2MissionState.READY_TO_UPLOAD) || waypointV2MissionOperator.getCurrentState().equals(WaypointV2MissionState.READY_TO_EXECUTE)) {
            waypointV2MissionOperator.loadMission(this.ourMission, new CommonCallbacks.CompletionCallback<DJIWaypointV2Error>() {
                @Override
                public void onResult(DJIWaypointV2Error djiWaypointV2Error) {
                    if (djiWaypointV2Error == null) {
                        canUploadMission = true;
                        //ToastUtils.setResultToToast("Mission is loaded successfully");
                        showToast("1. Mission loaded");
                        waypointV2MissionOperator.uploadMission(new CommonCallbacks.CompletionCallback<DJIWaypointV2Error>() {
                            @Override
                            public void onResult(DJIWaypointV2Error djiWaypointV2Error) {
                                if (djiWaypointV2Error != null) {
                                    //ToastUtils.setResultToToast(djiWaypointV2Error.getDescription());
                                    showToast(djiWaypointV2Error.getDescription());
                                }else {
                                    showToast("2. Mission Uploaded");
                                    canStartMission = true;
                                    waypointV2MissionOperator.startMission(new CommonCallbacks.CompletionCallback<DJIWaypointV2Error>() {
                                        @Override
                                        public void onResult(DJIWaypointV2Error djiWaypointV2Error) {
                                            if(djiWaypointV2Error == null) {
                                                //ToastUtils.setResultToToast(djiWaypointV2Error == null ? "Mission is started successfully" : djiWaypointV2Error.getDescription());
                                                showToast(djiWaypointV2Error == null ? "Mission was started successfully" : djiWaypointV2Error.getDescription());
                                            }
                                            else{
                                                showToast("Something went Wrong"+djiWaypointV2Error.getDescription());
                                            }
                                        }
                                    });

                                }
                            }
                        });
                    } else {
                        //ToastUtils.setResultToToast(djiWaypointV2Error.getDescription());
                        showToast(djiWaypointV2Error.getDescription());
                    }
                }
            });
        } else {
            // ToastUtils.setResultToToast("The mission can be loaded only when the operator state is READY_TO_UPLOAD or READY_TO_EXECUTE");
            showToast("The mission can be loaded only when the operator state is READY_TO_UPLOAD or READY_TO_EXECUTE");
        }`

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/47833'>Zendesk ticket #47833</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry, I'm not sure about the problem.
Here is an official sample, please test and refer to it.
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/missionoperator/WaypointV2MissionOperatorView.java

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by yali25** [comment]
Thank you for your help.
Is there also an example on how to connect to the RTK base station?

**Comment by stacker10** [comment]
I've had the same problem before because I didn't have a login account
It may also be that the setting of the waypoint is not standardized, or it is too far from the starting point

**Comment by yali25** [comment]
> I've had the same problem before because I didn't have a login account
> It may also be that the setting of the waypoint is not standardized, or it is too far from the starting point

Thank you for your answer.

In my case the problem was that I modified the GUI (enabling button etc.) inside the onResult callback method of the uploadMission function. 
This thread helped me: https://github.com/dji-sdk/Mobile-SDK-Android/issues/863

I think the conclusion was that when printing messages etc. it must be inside the runOnUIThread{ } block.

**Comment by DJI-William** [comment]
You are correct, don't do anything complex logic in onResult block, this should be short.
