### ISSUE TITLE
如何切换飞行模式，比如从T/P/S切换到A/P/S

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#879]

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/48029'>Zendesk ticket #48029</a>:<br><br>您好，产品使用相关的问题请联系 support@dji.com
<br><p><em><small>°°°</small></em></p>

**Comment by Swordce** [comment]
API中有相关的接口么，我看pilot中的面板可以设置切换飞行模式

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/48029'>Zendesk ticket #48029</a>:<br><br>API中没有这样的方法，pilot里面也不能切换飞行模式的。
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/48029'>Zendesk ticket #48029</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

可以，只是4.14新出的功能，toggleAttitudeFlightMode。
Link：https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html#djiflightcontroller_setcontrolmode_inline

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
