### ISSUE TITLE
Mavic: Camera.setMediaFileCallback(@Nullable MediaFile.Callback callback) not called for new photos

### ISSUE THREAD

**Issue by martindroneharmony** [dji-sdk/Mobile-SDK-Android#88]
Hello,

1. Problem description:
For Mavic the Camera.setMediaFileCallback(@Nullable MediaFile.Callback callback) is not called for new photos. It is called though for new video.

2. Steps to reproduce the bug:
-> Register a callback on Camera.setMedaFileCallback().
-> Shoot a photo
-> Your registered callback will not be called

3. Involved software / firmware:

- DJI Android mobile SDK 4.0
- DJI Assistant 2 version 1.1.0.2
- DJI Firmware for mavic v01.03.05
- DJI Firmware for RC v01.03.05 (According to DJI Go 4 App v4.0.5 as well as the DJI Assistant 2 both firmwares are up to date)
- Android 7.0, API 24
- Sony Xperia Z4
- Android Studio 2.3

4. We described our experience and trials to fix the bug in this DJI dev froum thread:
http://forum.dev.dji.com/forum.php?mod=viewthread&tid=33195&page=1&extra=#pid229850

**Comment by oliverou** [comment]
Hi @martindroneharmony, currently, Android SDK 4.0 doesn't support this feature for Mavic Pro.

**Comment by martindroneharmony** [comment]
Thank you @oliverou . In the meantime we will implement a workaround until the SDK will support it (hope it will be soon :-) ).

**Comment by martindroneharmony** [comment]
You might want to consider updating the sdk documentation, pointing out to developers that the callback does not work for mavic pro when shooting photos.

**Comment by oliverou** [comment]
Hi @martindroneharmony , we have released the DJI Android SDK 4.3.2, and support `Camera.setMediaFileCallback`  for new photos and videos in Mavic Pro now. Please try it.

**Comment by martindroneharmony** [comment]
Hi oliverou,

We tested it and it works now. Thanks for letting me know, that way we could include improved code changes based on this fix in our latest release of our mission planner.
