### ISSUE TITLE
Can't create a custom Compass Calibration

### ISSUE THREAD

**Issue by SouzaMath** [dji-sdk/Mobile-SDK-Android#881]
Hello there!
I'm trying to create a Custom Dialog for the Compass Calibration, but when I call the function **startCalibration()** from the class **Compass**, the SDK calls a Dialog with the instructions to calibrate that comes from the SDK.

Someone know how can I use my custom Dialog?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48079'>Zendesk ticket #48079</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Here is easy sample, please check if any help.
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/flightcontroller/CompassCalibrationView.java

Thanks,

Luce Luo
DJI Dev Team
<br><p><em><small>°°°</small></em></p>

**Comment by SouzaMath** [comment]
My code is like the sample, but everytime I the function startCalibration() is called, the dialog below is showed over my custom dialog.
![Screenshot_2021-02-26-21-15-49](https://user-images.githubusercontent.com/66540999/119339982-4084d580-bc68-11eb-8968-4e36e0d33756.png)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48079'>Zendesk ticket #48079</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I see.
It seems that you are using the UXSDK, the UXSDK has integrated this dialog.
If you want to customize it, please use the MSDK or open-source UXSDK.
https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by SouzaMath** [comment]
I'm using both MSDK and UXSDK. 
I use the UXSDK for widgets like [Compass](https://developer.dji.com/api-reference/android-uilib-api/Widgets/DUXCompassWidget.html) 'cause it's most easily to show.
I need to remove the UXSDK to create a custom dialog for compass calibration? Don't have an easy way to block the UXSDK to interfere into the MSDK? 
Remembering that the function I'm using to start the calibration is this: https://developer.dji.com/api-reference/android-api/Components/Compass/DJICompass.html?search=compass&i=0&#djicompass_startcalibration_inline

**Comment by luoyexk** [comment]
Have you put the `dji.ux.workflow.CompassCalibratingWorkFlow` in your layout? Remove it.
