### ISSUE TITLE
Show Visual and Thermal Camera at Same Time

### ISSUE THREAD

**Issue by SouzaMath** [dji-sdk/Mobile-SDK-Android#883]
Hello there!
I have a Matrice 200  series V2 with RTK and a XT2 camera. 
I wan't to show in my app both **XT2 Visual** and **XT2 Thermal** streams at same time on two separated Fragments.
I tried to with the DisplayMode.PIP, but it's not like what I wan't.

This image below it's most like what I wan't to do...
![image](https://user-images.githubusercontent.com/66540999/119397788-04c02f00-bcad-11eb-8834-51a49c89bd87.png)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48126'>Zendesk ticket #48126</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The SDK only supports to show one of them or in PIP, MSX way.
In PIP mode, also can set the position via setPIPPosition method.
Please check if any help.
DisplayMode
 ![](https://djisdksupport.zendesk.com/attachments/token/ImwksZ1TGlJk91oKH2jrINQEI/?name=inline-779833462.png)​
 ![](https://djisdksupport.zendesk.com/attachments/token/HF7Zh3NrCZkVVlCYRC9oI36cv/?name=inline-1349008295.png)​
Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/ImwksZ1TGlJk91oKH2jrINQEI' target='zd_attach'>inline-779833462.png</a><br><a href='https://djisdksupport.zendesk.com/attachments/token/HF7Zh3NrCZkVVlCYRC9oI36cv' target='zd_attach'>inline-1349008295.png</a>
<br><p><em><small>°°°</small></em></p>
