### ISSUE TITLE
unlockFlyZones   Network Server Data Error(255)

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#885]
调用FlyZoneManager.unlockFlyZones(ids)，什么情况下返回该异常 Network Server Data Error(255)

在我们的app在登录状态下解锁，出现该异常，此时立刻到DJI Go4，可以解锁

**Comment by luoyexk** [comment]
发生时间：休斯顿 5-25 14:04:36
机型: Mavic 2 Zoom
固件最新

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48193'>Zendesk ticket #48193</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by Hoker-** [comment]
这个一般是服务器判断无法解禁造成的，只有授权区可以被解禁（FlyZoneCategory.AUTHORIZATION），可能输入的flyzoneID错误。
