### ISSUE TITLE
Mavic: Sometimes Camera.startRecordVideo() fails (throws error) but recording started regardless.

### ISSUE THREAD

**Issue by martindroneharmony** [dji-sdk/Mobile-SDK-Android#89]
1. Problem description:
Method Camera.startRecordVideo() sometimes reports a fail with a DJI Error TimeoutException although the recording of the video started successfully. 

2. Reproducable by a simple code like this (rerun the code until you run into the problematic behavior): 
```Java
private volatile boolean isRecording = false;
    private void _debugMissionLogDownload() {
        Camera camera = DJIBaseFragmentActivity.getAircraftInstance().getCamera();
        if (!isRecording) {
            camera.startRecordVideo(djiError -> {
                if (djiError == null) {
                    isRecording = !isRecording;
                    msgManager.info("START SUCCESSFUL.");
                } else {
                    msgManager.info("ERROR ON START: " + djiError.getDescription());
                }
            });
        } else {
            camera.stopRecordVideo(djiError -> {
                if (djiError == null) {
                    isRecording = !isRecording;
                    msgManager.info("STOP SUCCESSFUL.");
                } else {
                    msgManager.info("ERROR ON STOP: " + djiError.getDescription());
                }
            });
        }
```
3. Involved software / firmware:

- DJI Android mobile SDK 4.0
- DJI Firmware for mavic v01.03.05
- DJI Firmware for RC v01.03.05 (According to DJI Go 4 App v4.0.5 as well as the DJI Assistant 2 version 1.1.0.2 both firmwares are up to date)
- Android 7.0, API 24
- Sony Xperia Z4
- Android Studio 2.3

4. Our current workaround to cope with the unreliable fail:
In case of fail check for recording callbacks to make sure the start recording really failed.

5. A similar issue (which we did not report seperately): Camera.stopRecordVideo() sometimes succeeds but the mavic continues to record video.

--> Conclusion: Camera.stopRecordVideo() and Camera.startRecordVideo() are not robustly reporting the right event (success / fail).

**Comment by oliverou** [comment]
Hi @martindroneharmony , thanks for your feedbacks, we have addressed this issue and will fix it in the upcoming sdk release.

**Comment by martindroneharmony** [comment]
Sounds great, looking forward to the fix!

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!

**Comment by martindroneharmony** [comment]
Hi talobin,
as far as we can tell we did not experience this issue anymore (but to be fair, we did not any targeted tests for this issue in a while).
