### ISSUE TITLE
电池报警阈值设置接口提示not support

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#890]
使用机型为御2双光版和M300
调用方法getLevel1CellVoltageThreshold，setLevel1CellVoltageThreshold

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48218'>Zendesk ticket #48218</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
如果返回不支持提示，即当前产品不支持该功能。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
