### ISSUE TITLE
解禁测试

### ISSUE THREAD

**Issue by joylhn** [dji-sdk/Mobile-SDK-Android#892]
禁飞区解禁测试怎么做？
没有空域解禁授权文件，怎么申请测试？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48328'>Zendesk ticket #48328</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
SDK解禁流程可以参考如下文档介绍：
https://developer.dji.com/mobile-sdk/documentation/android-tutorials/GEODemo.html

申请解禁授权可以访问如下网站了解：
https://www.dji.com/cn/flysafe/self-unlock

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
