### ISSUE TITLE
WaypointV2Mission pointOfInterestAltitude

### ISSUE THREAD

**Issue by tobiasfriden** [dji-sdk/Mobile-SDK-Android#893]
Hello,

How is the `pointOfInterestAltitude` used in the `WaypointV2Mission`?
Will it be used to control the pitch of the camera towards the point of interest? This is not clear in the documentation.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/48340'>Zendesk ticket #48340</a>:<br><br>Dear Client
Thank you for contacting DJI.

The aircraft's heding will always towards to the point of interest during WaypointV2Mission.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by tobiasfriden** [comment]
Hello,

Yes, I understand that the heading will be pointing towards the point of interest but what about the gimbal pitch?
The point of interest altitude is not necessary in order to calculate the heading so why is there such a setting if it does not control the gimbal?

**Comment by DJI-William** [comment]
The gimbal pitch is not related with the pointOfInterest. Only the heading is point towards to the point.
