### ISSUE TITLE
getTakeoffLocationAltitude from FlightController.setStateCallback not being updated more than once

### ISSUE THREAD

**Issue by idani301** [dji-sdk/Mobile-SDK-Android#894]
Drone : Mavic 2 Enterprise, Mavic Pro (I can check on M300 or M210 v2 as well if needed)

Description : The method getTakeoffLocationAltitude  is supposed to provide the altitude of the drone before it's taking-off.
We only get 1 time value from getTakeoffLocationAltitude , after that, if we turn off the drone and turn it on or even move the drone up/down(before take off of course), we will get only the first value or NaN. 

For example : 
Turn the drone on. 
receive the value 20.4 from getTakeoffLocationAltitude every 100 millisecond on the callback setStateCallback. 
hold the drone with the hand, value is still 20.4. 
now while holding the drone with the hand we will close the app and reopen it, the value is updated to 22.1

now the last value received is 22.1. if we turn the drone off and turn it on, the value on getTakeoffLocationAltitude will always be NaN. 
if we close the app and reopen it, the getTakeoffLocationAltitude  will show the value +-22.0.

We strongly beleive it's a bug because closing the app and reopen it result new values on the getTakeoffLocationAltitude from setStateCallback in many situations.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48394'>Zendesk ticket #48394</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team
<br><p><em><small>°°°</small></em></p>

**Comment by Michael-DJI** [comment]
4.15 will fix it, btw you could try this:
Object heightAboveSeaLevel = KeyManager.getInstance().getValue(FlightControllerKey.create(FlightControllerKey.TAKEOFF_LOCATION_ALTITUDE));

**Comment by gauravguptathinksys** [comment]
I am also getting NaN every time, I used 4.15
So I tried below way to get altitude

`Object heightAboveSeaLevel = KeyManager.getInstance().getValue(FlightControllerKey.create(FlightControllerKey.TAKEOFF_LOCATION_ALTITUDE));
`
I am getting value but initial value is 260.00  not taking from 0

What is the measurement unit of this altitude and why it is showing from 260 

could you please tell me @Michael-DJI
