### ISSUE TITLE
Execution of this process has timed out是什么原因造成的？

### ISSUE THREAD

**Issue by abc456879213** [dji-sdk/Mobile-SDK-Android#899]
有时候调用API会提示错误“Execution of this process has timed out”，前一次还成功的，下一次就报这个错误了。
获取无人机SN码、获取媒体文件的预览图、设置焦距都有出现过这个错误。

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48546'>Zendesk ticket #48546</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
常见的超时错误，可能是通信质量不好导致，多试几次即可。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by Michael-DJI** [comment]
未来建议填写如下表单反馈相关问题：
https://formcrafts.com/a/dji-developer-feedback-cn
