### ISSUE TITLE
fetchMediaData does not write the file 

### ISSUE THREAD

**Issue by JonasVautherin** [dji-sdk/Mobile-SDK-Android#9]
The function `public void fetchMediaData(java.io.File destDir, DJIMediaInfo mDjiMedia, DJIDownloadListener<DJIMediaFile> mCall)` does not seem to work on Inspire 1 (latest stable firmware) and P3 Pro + Advanced (latest dev firmware). Tested both in my code and with your DEMO app. 

The image looks like it is downloaded (`onProgress` is called many times and the download takes forever, then `onSuccess` is called), but it is not written in `destDir`. Also, `onSuccess` gives a `DJIMediaFile` that is apparently useless because it is always null.

**Comment by JonasVautherin** [comment]
In case somebody is interested, I tested that on Android 4 and Android 5.

**Comment by SilverChangjian** [comment]
Hi, JonasVautherin, it is a bug. The image files are stored in the `DJI/project pack name/CACHE_IMAGE` and are not moved to the dir location

**Comment by JonasVautherin** [comment]
Looking forward to testing the next version of the SDK, then.

I am not sure why you need to move the image, but if you need a cache, you might want to read about [getCacheDir](http://developer.android.com/reference/android/content/Context.html#getCacheDir()), instead of creating your own and not cleaning it properly.

**Comment by JonasVautherin** [comment]
It is better with 2.4.1: instead of creating an empty directory with the name of the image, it creates an empty image. Is it something that was tested on your side? The changelog for SDK 2.4.1 says that: 
    > The file downloaded by ‘fetchMediaData' will be stored in the correct place.

Did you also test that the file downloaded by `fetchMediaData` is not empty?

**Comment by JonasVautherin** [comment]
Do you have any comment on that issue?

**Comment by SilverChangjian** [comment]
We are reproducing this bug, however, we could download the file successfully using our demo. We will try to create a new app for testing this bug. Thanks for your supporting.
