### ISSUE TITLE
Keyed interface crashes when Jack is enabled

### ISSUE THREAD

**Issue by fukuchidaisuke** [dji-sdk/Mobile-SDK-Android#90]
I added the following code in android.defaultConfig of "Sample Code/app/build.gradle"

```groovy
        jackOptions {
            enabled true
        }
```

I ran the sample, and tapped `open`, `Keyed Interface Sample`.
Then, I tapped `Switch Camera Mode` two times.
The following error occurred and the sample stopped.

```
04-05 10:57:59.859 4246-4361/com.dji.sdk.sample E/AndroidRuntime: FATAL EXCEPTION: SingleBackgroundLooper
                                                                  Process: com.dji.sdk.sample, PID: 4246
                                                                  java.lang.NoSuchMethodError: No static method dji_keysdk_KeyManager$$Lambda$1_lambda$addListener$7(Ldji/keysdk/callback/KeyListener;Ldji/sdksharedlib/b/c;Ldji/sdksharedlib/store/DJISDKCacheParamValue;Ldji/sdksharedlib/store/DJISDKCacheParamValue;)V in class Ldji/keysdk/KeyManager; or its super classes (declaration of 'dji.keysdk.KeyManager' appears in /data/app/com.dji.sdk.sample-2/base.apk)
                                                                      at dji.keysdk.KeyManager$$Lambda$1.onValueChange(Unknown Source)
                                                                      at dji.sdksharedlib.listener.DJISDKCacheListenerLayer$ValueChangeRunnable.run(Unknown Source)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.os.HandlerThread.run(HandlerThread.java:61)
```

When I did not enable jack, no error occurred.

I used the following devides and softwares.

* Nexus 7 or Zenfone2 Laser
* Mavic Pro
* Android Studio 2.3.1
* Android 6.0.1
* This repositorie's 2dabeea87b54771e10d56126189071b4f5d1f243

**Comment by mikepschneider** [comment]
I get this also using Android Studio 3.0 Canary 3. (which doesn't have jack mode but supports java 8) when I try to use the UI Library code.

**Comment by Michael-DJI** [comment]
@fukuchidaisuke pls provide the version of DJI SDK, thanks

**Comment by mikepschneider** [comment]
Android_Mobile_SDK_4.2.1_170703.zip
dji-uilibrary_4.2.1.aar

**Comment by kenargo** [comment]
If you are loading both that could be the issue.  The UI lib includes the sdk,  no need to load the sdk are a separate module. 

⁣Sent from BlueMail ​

**Comment by Michael-DJI** [comment]
@fukuchidaisuke have you add the 
`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`
and pls avoid using Jack, it's not recommended now:
https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html

**Comment by Michael-DJI** [comment]
@mikepschneider  Hi, Mike, could pls show some pieces of your code? and pls provide the model info of your phone and your drone, thanks

**Comment by oliverou** [comment]
Hi @kenargo , we have separated the UI Library and SDK in 4.2.1, so you may need to import both of them in your Android project.

**Comment by kenargo** [comment]
I did not know,  thanks for updating

⁣Sent from BlueMail ​

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
