### ISSUE TITLE
MediaFile.Callback not called with Matrice 600

### ISSUE THREAD

**Issue by andrewdittmer** [dji-sdk/Mobile-SDK-Android#901]
I don't receive the media file callback using Matrice 600 drone after using camera.setMediaFileCallback. I know that a photo was taken, because I can see it when I run the DJI Go app. Is this expected? If so, what is a recommended workaround? Thanks,

I'm using dji dependencies 4.14:
implementation ('com.dji:dji-sdk:4.14')
compileOnly ('com.dji:dji-sdk-provided:4.14')

Matrice has the latest firmware.

Andrew.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48591'>Zendesk ticket #48591</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Can you tell me what camera you are using?

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by andrewdittmer** [comment]
Hi Luce Luo,

We are using the DJI Zenmuse Z30.

**Comment by andrewdittmer** [comment]
FYI, here's how we set the camera's mediaFileCallback.
```
    val onNewFileCreatedCallback = MediaFile.Callback { mediaFile ->
        Log.i(TAG, "New file created in the connected DJI device")
    }

    camera.setMediaFileCallback(onNewFileCreatedCallback)
```

**Comment by DJI-William** [comment]
I am sorry to tell you this is an ancient bug. setMediaFileCallback is not working for Z30 and XT2, firmware issue. But these products are end of development.
