### ISSUE TITLE
MSDK的遥控器定位

### ISSUE THREAD

**Issue by z-jiahui** [dji-sdk/Mobile-SDK-Android#902]
1. 程序中调用高德的sdk定位后在大疆的高德map中显示误差很大（高精度模式），有几百米，是什么原因呢？
2. 或者大疆的MSDK中有什么函数可以调用遥控器比较精确的位置吗？
谢谢。

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48620'>Zendesk ticket #48620</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
SDK返回的坐标是基于WGS-84坐标体系，如果需要在高德等地图显示，需要自行进行坐标转换。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by Michael-DJI** [comment]
未来建议填写如下表单反馈相关问题：
https://formcrafts.com/a/dji-developer-feedback-cn
