### ISSUE TITLE
Mission Cancel when controller used

### ISSUE THREAD

**Issue by laboBea** [dji-sdk/Mobile-SDK-Android#904]
Dear all,

Is there a way to cancel the waypoint mission when anything on the controller is pressed. It is for security reasons.

Does it exist a function that listens at the controller trying to be used during the waypoint missions?

Because I have noticed that when a waypoint mission starts it can only be stoped with the stopWaypointMission function and during the waypoint mission the controller can't in fact directly take control of the drone if the mission is in progress. I want to cancel the waypoint mission when anything on the controller is moved or pressed.

Thank you,
Best regards.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/48705'>Zendesk ticket #48705</a>:<br><br>Dear Client
Thank you for contacting DJI.

You should use RemoteController.setHadrwareStateCallback to listen any incoming remote controller's button feedback and weite your own logic. You can just bind the stopWaypointMission function with the button click/press event to achieve your goal.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by laboBea** [comment]
Dear Agent

Thank you for your answer, the problem is that RemoteController is an abstract class and I can't create an instance of itself to call the setHardwareStateCallback function.

Is there a way to get an instance of remote controller when the controller is connected?

Best regards,
