### ISSUE TITLE
关于图片下载的问题

### ISSUE THREAD

**Issue by 505057618** [dji-sdk/Mobile-SDK-Android#905]
MediaFile 调用getThumbnail什么的都没问题，但是调用fetchFileData去下载，一直报execution could not be executed,不知道什么原因，能不能告知一下是哪种原因导致，还是说下载前要调用其他代码，相机模式已经设置成mediaDownload,飞机用了精灵4pro和御2双光版测试的都一样

**Comment by Michael-DJI** [comment]
麻烦用表单反馈，还可以附上日志，谢谢
https://formcrafts.com/a/dji-developer-feedback-cn
