### ISSUE TITLE
Waypoint mission AddAction Problems

### ISSUE THREAD

**Issue by laboBea** [dji-sdk/Mobile-SDK-Android#907]
Dear all,

When creating a Waypoint mission and adding the Actions to the waypoints the drone (DJI Mavic Pro) has problems in executing some of the actions.

For instance, when executing the actions:
```
waypoint.addAction(WaypointAction(WaypointActionType.GIMBAL_PITCH, -90))
waypoint.addAction(WaypointAction(WaypointActionType.START_TAKE_PHOTO, 0))
```

Everything works fine, the gimbal points down on waypoints and it takes the photo at each waypoint during all the mission, but if I add the action focus to the same code, like for example:

```
waypoint.addAction(WaypointAction(WaypointActionType.GIMBAL_PITCH, -90))
waypoint.addAction(WaypointAction(WaypointActionType.CAMERA_FOCUS, 0))
waypoint.addAction(WaypointAction(WaypointActionType.START_TAKE_PHOTO, 0))
```

The drone stops at the first waypoint and never continues the mission. Do someone has a solution? For me it is really important that the action focus is done.

Best regards,

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/48913'>Zendesk ticket #48913</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that the action CAMERA_FOCUS is not supported, please do not use it.
The supported actions, please follow the documentation.
WaypointActionType
 ![](https://djisdksupport.zendesk.com/attachments/token/sV22Q6PQsZ24w9uc1Fj4BB6oR/?name=inline-1899023169.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/sV22Q6PQsZ24w9uc1Fj4BB6oR' target='zd_attach'>inline-1899023169.png</a>
<br><p><em><small>°°°</small></em></p>
