### ISSUE TITLE
M300 Smart Track with H20T

### ISSUE THREAD

**Issue by idani301** [dji-sdk/Mobile-SDK-Android#908]
Hi, how do you use Smart Track with H20T on mobile sdk?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/48941'>Zendesk ticket #48941</a>:<br><br>Dear Client
Thank you for contacting DJI.

Sorry, M300 does not support ActiveTrackMission.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by idani301** [comment]
I was actually asking about the Smart Track of the H20T with the M300, like you can see in this video : 

https://www.youtube.com/watch?v=1INm2PY0uQE

Is there any way to use those functions with the mobile sdk?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/48941'>Zendesk ticket #48941</a>:<br><br>Dear Client
Thank you for contacting DJI.

This is actually the Smart Track function, it is called ActiveTrackMission, the gimbal/camera will follow the selected target. Unfortunately, the MSDK does not have this function. This is developed by Pilot team.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by idani301** [comment]
Thank you very much
