### ISSUE TITLE
Waypoint Mission Camera Focus

### ISSUE THREAD

**Issue by laboBea** [dji-sdk/Mobile-SDK-Android#910]
Dear all,

When performing a Waypoint Mission is there a way to perform the focus of the camera before the action START_TAKE_PHOTO?

The mission is performed in a constant altitude so it should be performed a single time at the beginning of the mission, and I would like to avoid the fact of doing a manual focus everytime I need to perform a mission.

Thank you,
Marc

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49050'>Zendesk ticket #49050</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that the waypoint mission v1 has no focus action, maybe you can consider fixing the focus before executing the mission.

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by laboBea** [comment]
Dear Agent,

Is there a way to do it without manual focus? 
I know the altitude of the flight, so does it exist a command that controlles the camera focus or that automatically calculates the optimal needed focus and I can input it as a parameter inside the coding?

Best regards,

**Comment by Michael-DJI** [comment]
For M300, the latest 4.15 MSDK will support the focus and zoom action with WP2.0 interfaces
