### ISSUE TITLE
直播设置码率

### ISSUE THREAD

**Issue by 505057618** [dji-sdk/Mobile-SDK-Android#911]
我看pilot上直播可以设置高清，标清，超清，自适应，对应的选择码率就会发生变化，请问一下这是哪一个接口

**Comment by stacker10** [comment]
同样的疑问
有没有碰到livemanager直播时，视频卡顿的情况

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/49073'>Zendesk ticket #49073</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

下周一会发布4.15版本，届时LiveStreamManager会增加调节码率和分辨率，还有自适应功能的接口。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
