### ISSUE TITLE
MSDK m300 rtk  使用 liveManager 推流，出现卡顿情况

### ISSUE THREAD

**Issue by stacker10** [dji-sdk/Mobile-SDK-Android#912]
MSDK m300 rtk  使用 liveManager 推流，出现卡顿情况
有没有推流时设置清晰度的方法

还是说需要自己获取视频流，进行编解码，再推出去。有没有对应的api

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49082'>Zendesk ticket #49082</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
4.15版本会推出设置清晰度的方法，预计本月21号释放，您可以等待下。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
