### ISSUE TITLE
TurnOnMotor() returned Undefined error

### ISSUE THREAD

**Issue by zijian98** [dji-sdk/Mobile-SDK-Android#914]
HI, I am trying to add on some tasks like turning on/off motors and taking off / landing from the demo app but none of the commands seems to work as it returned an undefined error (It worked sometimes but it reset the app back to the camera page). I'm still new so I'm wondering if there's any missing commands?

`package com.dji.FPVDemo;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import dji.common.error.DJIError;
import dji.common.util.CommonCallbacks;
import dji.sdk.flightcontroller.FlightController;

public class TakeoffActivity extends AppCompatActivity implements View.OnClickListener {

    public Button mReturn, mON, mOFF, mTakeOff, mLanding;
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_takeoff);

        mON = (Button) findViewById(R.id.btn_On);
        mON.setOnClickListener(this);
        mOFF = (Button) findViewById(R.id.btn_Off);
        mOFF.setOnClickListener(this);
        
        mTakeOff = (Button) findViewById(R.id.btn_takeoff2);
        mTakeOff.setOnClickListener(this);
        
        mLanding = (Button) findViewById(R.id.btn_landing);
        mLanding.setOnClickListener(this);

        mReturn = (Button) findViewById(R.id.btn_return);
        mReturn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                goBacktoMain();
            }
        });
    }

    @Override
    public void onClick(View v) {
        FlightController flightController = FPVDemoApplication.getAircraftInstance().getFlightController();
        if (flightController == null)
        {
            return;
        }
        switch (v.getId()) {

            case R.id.btn_On: {
                flightController.turnOnMotors(new CommonCallbacks.CompletionCallback() {
                    @Override
                    public void onResult(DJIError djiError) {
                        showToast(djiError.getDescription());
                    }
                });
                break;
            }
            case R.id.btn_Off: {
                flightController.turnOffMotors(new CommonCallbacks.CompletionCallback() {
                    @Override
                    public void onResult(DJIError djiError) {
                        showToast(djiError.getDescription());
                    }
                });
                break;
            }
            case R.id.btn_takeoff2: {
                flightController.startTakeoff(new CommonCallbacks.CompletionCallback() {
                    @Override
                    public void onResult(DJIError djiError) {
                        showToast(djiError.getDescription());
                    }
                });
                break;
            }
            case R.id.btn_landing: {
                flightController.startLanding(new CommonCallbacks.CompletionCallback() {
                    @Override
                    public void onResult(DJIError djiError) {
                        showToast(djiError.getDescription());
                    }
                });
                break;
            }
            default:
                break;
        }
    }

    public void goBacktoMain() {
        Intent intent = new Intent(this, MainActivity.class);
        startActivity(intent);
    }

    private void showToast(final String toastMsg) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Toast.makeText(getApplicationContext(), toastMsg, Toast.LENGTH_LONG).show();

            }
        });
    }

    
}`

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49090'>Zendesk ticket #49090</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://formcrafts.com/a/dji-developer-feedback-en

Thanks,

Luce Luo
DJI Dev Team
<br><p><em><small>°°°</small></em></p>

**Comment by zijian98** [comment]
The code do works sometimes but most of the times it returned Undefined Error. What could be the reasons?

**Comment by Hoker-** [comment]
maybe you was in isInNonFlyZone zone, you can get error information through
DJISDKManager.getInstance().getProduct().setDiagnosticsInformationCallback(diagnosticsList -> {});
