### ISSUE TITLE
M300无法获取获取RemoteController

### ISSUE THREAD

**Issue by dawenxi484** [dji-sdk/Mobile-SDK-Android#916]
我想为m300遥控器的c1和c2按钮绑定监听事件，但是代码运行的结果是经常获取RemoteController为null，成功的几率很低，是我的代码有啥问题吗，还是获取RemoteController的时机不对？ 

之所以在registrationCallback中获取RemoteController，是因为在业务代码中调用getRemoteController()时为null，于是我选择在registrationCallback中验证是否可以获取gRemoteController。

onProductConnect回调事件不是意味着产品连接正常，为啥会无法获取RemoteController？，奇怪的是可以获取FlightController。
我使用sdk版本是com.dji:dji-sdk-provided:4.14，固件均已升级。

下面是我的代码
```java
 DJISDKManager.getInstance().registerApp(MainActivity.this, registrationCallback);
    private DJISDKManager.SDKManagerCallback registrationCallback = new DJISDKManager.SDKManagerCallback() {

        @Override
        public void onRegister(DJIError error) {
           
        }

        @Override
        protected void finalize() throws Throwable {
            super.finalize();
        }

        @Override
        public void onProductDisconnect() {
            XToastUtils.warning("无人机连接断开");

        }

        @Override
        public void onProductConnect(BaseProduct product) {

            Aircraft aircraft = (Aircraft) product;
            RemoteController remoteController = aircraft.getRemoteController();

        }

        @Override
        public void onProductChanged(BaseProduct baseProduct) {

        }

        @Override
        public void onComponentChange(BaseProduct.ComponentKey key,
                                      BaseComponent oldComponent,
                                      BaseComponent newComponent) {


        }

        @Override
        public void onInitProcess(DJISDKInitEvent event, int totalProcess) {

        }

        @Override
        public void onDatabaseDownloadProgress(long current, long total) {

        }
    };
```

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49134'>Zendesk ticket #49134</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
时机不对，onProductConnect仅意味连接到产品，还需要一些时间初始化其他部件如遥控器，电池等，可以监听onComponentChange，确认遥控器连接后再去获取RemoteController即可。
参考：
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/internal/view/MainContent.java#L518

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by Hoker-** [comment]
KeyManager.getInstance().addListener(RemoteControllerKey.create(RemoteControllerKey.CONNECTION), (oldValue, newValue) -> { });
如果关心遥控的连接状态，建议直接监听遥控的连接事件。
