### ISSUE TITLE
Can one SDK mobile device control multiple drones?

### ISSUE THREAD

**Issue by KIYONG-KWON** [dji-sdk/Mobile-SDK-Android#922]
Can one SDK mobile device control multiple drones? I am not familiar with the Android environment, so please understand that I am asking basic questions.

If N mobile devices are used to control N drones and they are connected through a single hub, how can the mobile devices and RCs be matched?

The system I want is a form of cluster control of multiple drones in the Desktop Application.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/49239'>Zendesk ticket #49239</a>:<br><br>Dear Client
Thank you for contacting DJI.

One SDK app can only control one drone.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by KIYONG-KWON** [comment]
Thank you for quick response.

**Comment by KIYONG-KWON** [comment]
I noted One SDK app can only control one drone. 
By the way, i have another question. 

When multiple RCs and mobile devices (SDKs) are connected using a single hub, is there a way to match each other? In other words, I wonder if there is a way to identify a specific RC and connect only to that RC even if multiple RCs are connected to the mobile device (SDK).

**Comment by Michael-DJI** [comment]
> I noted One SDK app can only control one drone.
> By the way, i have another question.
> 
> When multiple RCs and mobile devices (SDKs) are connected using a single hub, is there a way to match each other? In other words, I wonder if there is a way to identify a specific RC and connect only to that RC even if multiple RCs are connected to the mobile device (SDK) through a single hub.

I think you mean use the USB Hub to connect each other, I think it's impossible. thank you!
