### ISSUE TITLE
编译AndroidX出错

### ISSUE THREAD

**Issue by Gangyao-01** [dji-sdk/Mobile-SDK-Android#923]
编译报错：This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
在local.properties中添加：
android.useAndroidX=true
android.enableJetifier=true
后依然一样报错，并且这两行显示为灰色：Unused property 

还有无人机摄像头传回的实时视频流改为surfaceView显示也可行吗？
谢谢

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49318'>Zendesk ticket #49318</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
MSDK需要AndriodX支持，可以参考下如下官方示例。
https://github.com/dji-sdk/Mobile-SDK-Android

surfaceView用于显示也是可以的。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
