### ISSUE TITLE
How does waypoint mission operator works?

### ISSUE THREAD

**Issue by zijian98** [dji-sdk/Mobile-SDK-Android#926]
Hi, I'm using the waypoint mission manager to create a pre programmed flight path. However, when I changed the location in the code and tried to run it on my app, I got an invalid waypoint coordinates. How do I fix it?

I'm trying to launch the actual aircraft rather than the simulator.

Phantom 4 Pro V2

Thanks

**Comment by Michael-DJI** [comment]
please check this out: https://developer.dji.com/cn/document/93de0347-bcb2-40c8-b37d-298253a05045
