### ISSUE TITLE
MissionManagerError documentation question

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#93]
MISSION_RESULT_WAYPOINT_DISTANCE_TOO_LONG
MISSION_RESULT_WAYPOINT_TOTAL_TRACE_TOO_LONG
MISSION_RESULT_WAYPOINT_TRACE_TOO_LONG

What are the distances we need to know to prevent these errors returning from the DJIMissionManagerError? I'm struggling find the documentation useful to actually determine what these means or how to effectively prevent them. What, in some measurable distance unit, is considered too long?

**Comment by oliverou** [comment]
Hi @jtuchek , thanks for the feedbacks. For the **MISSION_RESULT_WAYPOINT_DISTANCE_TOO_LONG**, the maximum distance is 2km, for the ** MISSION_RESULT_WAYPOINT_TOTAL_TRACE_TOO_LONG**, the maximum total trace is 40km, for the last **MISSION_RESULT_WAYPOINT_TRACE_TOO_LONG**, the maximum trace is 30km. Hope this help! Will update the Android API documentation with these infos. Thanks!

**Comment by jtuchek** [comment]
@oliverou thanks for the feedback - those are helpful 👍

**Comment by jtuchek** [comment]
Question, just to clarify I have the correct understanding of this - is this correct?

MISSION_RESULT_WAYPOINT_DISTANCE_TOO_LONG: is for the distance from one waypoint to another. Where 0th item to 1st item must be within 2km of each other.

MISSION_RESULT_WAYPOINT_TOTAL_TRACE_TOO_LONG: is the total distance between points 0th to 1st, continued up to 99.

I'm not exactly sure what differentiates `MISSION_RESULT_WAYPOINT_TRACE_TOO_LONG` from `MISSION_RESULT_WAYPOINT_TRACE_TOO_LONG` or how they are different.

Also, is it correct to state that distance is tracked with altitude - or is distance for these only considered to be on the same 2D plane?

**Comment by GIS-HowardZhang** [comment]
Here are some details from DJI SDK3.5 Documentation, FAQ.

-How do I fix the Mission Error "Distance between two adjacent waypoints is too large."?
-The Waypoint Mission automates the aircraft to fly through a list of waypoints, visiting one after the other. A limitation of the mission is that consecutive waypoints must have a separation of less than 2km and greater than 0.5m. In addition, the first and last waypoint of the mission must also have a separation of less than 2km and greater than 0.5m. If the separation of any consecutive waypoints or the separation of the first and last waypoint is larger than 2km, then this error will be raised.

-How do I fix the Mission Error "The total distance of waypoints is too large." ?
-For a waypoint mission, the total planned flight distance must be less than 40km. The total planned flight distance includes the sum of the:
•	Distance from current aircraft location to first waypoint
•	Sum of all distances between waypoints in mission
•	Distance from last waypoint to the homepoint.

SDK4.0 might be the same.

**Comment by oliverou** [comment]
Hi @GIS-HowardZhang , thanks for the help to explain it. You are correct. @jtuchek , you can also check this question in the [FAQ documentation](http://developer.dji.com/mobile-sdk/documentation/faq/index.html#how-do-i-fix-the-mission-error-the-total-distance-of-waypoints-is-too-large) .

![waypointexplain](https://cloud.githubusercontent.com/assets/13310805/24892091/a2c6a6b4-1eac-11e7-900a-05d30c296bf9.png)

As you see in the above image, 

-  **MISSION_RESULT_WAYPOINT_TOTAL_TRACE_TOO_LONG** means **blue** line + **red** lines + **green** line, the maximum total trace is 40km.
-  **MISSION_RESULT_WAYPOINT_TRACE_TOO_LONG** means only **red** lines, the maximum trace is 30km.

 I may also help to update the related parts in the API Reference Documentations. Thanks!
