### ISSUE TITLE
how to control L1 to take photo (not record point cloud) and transmit the data（including photo and lidar data）to controller without push out SD card?

### ISSUE THREAD

**Issue by chenych2017** [dji-sdk/Mobile-SDK-Android#935]

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49566'>Zendesk ticket #49566</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The MSDK support take photos and save them into the SD card but not support output directly without an SD card.
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/camera/ShootSinglePhotoView.java

For the cloud data that have onReceiveLiveViewData method to receive the point cloud live view data, you can save it by yourself.

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
