### ISSUE TITLE
H20T Night Scene

### ISSUE THREAD

**Issue by idani301** [dji-sdk/Mobile-SDK-Android#936]
Is H20T Night Scene(function for the Zoom Lens) is supported in the MSDK?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49614'>Zendesk ticket #49614</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Yes, it's supported, please setFlatMode with PHOTO_HYPER_LIGHT.
 ![](https://djisdksupport.zendesk.com/attachments/token/gvrUGZC25TSUd1Fi1OmlaxqrA/?name=inline-1175944306.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/gvrUGZC25TSUd1Fi1OmlaxqrA' target='zd_attach'>inline-1175944306.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by idani301** [comment]
Thanks for the answer

I can see that getFlatMode is always VIDEO_NORMAL. 
If I try to use setFlatMode to PHOTO_HYPER_LIGHT on the camera I receive the error : 
"SDK error, please contact <dev@dji.com> for help."

Also, if I turn Night Scene on Dji Pilot and then connect my application, I still see the getFlatMode value on VIDEO_NORMAL. 
I should target the zoom lens for that specific command? if yes, which command should I use? since I can't see setFlatMode on the Lens class.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49614'>Zendesk ticket #49614</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry I made the mistake.
For the H20/H20T's night mode, should enable the setIRFilterEnabled but not the PHOTO_HYPER_LIGHT.
 ![](https://djisdksupport.zendesk.com/attachments/token/gI4XXi9pUSSdfOAMUa56QfNNu/?name=inline-74639103.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/gI4XXi9pUSSdfOAMUa56QfNNu' target='zd_attach'>inline-74639103.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by idani301** [comment]
Works perfectly thank you very much!
