### ISSUE TITLE
Is it possible "Move Position TO" Control?

### ISSUE THREAD

**Issue by KIYONG-KWON** [dji-sdk/Mobile-SDK-Android#938]
I looked at the SDK, but there doesn't seem to be an API that moves a drone to the GPS coordinates I want.
I want to use the SDK to send the drone to the GPS coordinates I want, and periodically calibrate the coordinates. 
We are considering calibrating the coordinates about once every second.

Can the system described above be implemented only with the functions provided by the DJI SDK?

It seems that the waypoint mission works based on gps, but considering the condition that the distance between the waypoint and the waypoint should be greater than 5m, it is not likely to be easy to use.

**Comment by DJI-William** [comment]
You can use sendVirtualStickFlightControlData to control the drone according to the GPS reading and aircraft heading reading to achieve your goal. Using waypointMission or the goto function in timelineMission can also achieve your goal, but this will requires upload mission, many steps. BTW, the minimun distance between each waypoint is 0.5m.

**Comment by KIYONG-KWON** [comment]
Since we want a system in which several drones move while maintaining their formation, we need to continuously correct the positions of each drone, and the period is about 1 second. 

Are you saying that it is possible to accurately move to a very close target point using the sendVirtualStickFlightControlData function?  Determining the input parameter of the sendVirtualStickFlightControlData API to move to the desired GPS coordinates requires a really complicated mathematical calculation, doesn't it?

**Comment by DJI-William** [comment]
Yes you are correct, this is the art of flight controller. We give you sendVirtualStickFlightControlData to allow you adjust the aircraft attitude. You need to use GPS/heading(compass) to do your acheive what you want to achieve.

**Comment by DJI-William** [comment]
Yes you are correct, this is the art of flight controller. We give you sendVirtualStickFlightControlData to allow you adjust the aircraft attitude. You need to use GPS/heading(compass) to do your acheive what you want to achieve.

**Comment by KIYONG-KWON** [comment]
Thank you. Clearly noted.

**Comment by KIYONG-KWON** [comment]
Let me ask you one more basic question. 
If the RollPitchControlMode is set to Velocity, it is understood that the Roll Pitch does not occur in the hovering state, but moves forward, backward, left and right at the speed entered as a parameter. Am I right?

**Comment by DJI-William** [comment]
Yes you are correct.

**Comment by KIYONG-KWON** [comment]
Thank you very much.
