### ISSUE TITLE
M300 V2航点动作偏航问题

### ISSUE THREAD

**Issue by joylhn** [dji-sdk/Mobile-SDK-Android#940]
航向模式使用 AUTO

飞机到达航点时执行如下动作：
执行 ROTATE_YAW 飞机偏航 到100，执行成功
执行拍照动作，此时飞机又自动进行了旋转，旋转到了朝向下一个航点的方向，因此飞机偏航角度不再是100，导致拍照不准

也就是说，飞机偏航动作执行成功了，但是偏航状态没有保持，执行拍照动作时又自动转回到朝向下一个航点的方向了

航向模式改为 GIMBAL_YAW_FOLLOW

飞机偏航100，执行成功
拍照动作，执行成功，此时飞机偏航状态不再改变
继续飞向下个航点，飞机机头不再自动转到朝向下个航点的位置，通俗点说就是飞机在歪着脖子飞

按照API解释，AUTO应该是 飞机执行完所有动作之后再 旋转偏航到朝向下一个航点
为何提前了，航点动作没有执行完，没有执行继续飞行动作时 就把 机头 转回去了呢？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49768'>Zendesk ticket #49768</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://djisdksupport.zendesk.com/hc/zh-cn/requests/new

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
这是由于你设置的航线动作的关联有问题，V2和V1有很大的区别，V1里面一定是执行完所有航点动作才会前往下一个航点，但是V2你必须要先设置一个航点动作停止飞行，最后再设置一个航点动作恢复飞行才能实现你想要的效果，你可以看看我们的Sample代码。
