### ISSUE TITLE
Mavic: MediaFile.getDateCreated() returns wrong time 

### ISSUE THREAD

**Issue by martindroneharmony** [dji-sdk/Mobile-SDK-Android#95]
1. Problem Description
MediaFile.getDateCreated() is returning the wrong time stamp (error in seconds). 
When comparing the EXIF data and the file creation or last change data of new photo media on the SD Card there is a mismatch to what MediaFile.getDateCreated() reports for the same files.

We shot pictures with a delta of 10 seconds on the mavic. This is what getDateCreated() reported to us:
DJI_0006.jpeg, Image time: 2017-04-06 23:05:29
DJI_0007.jpeg, Image time: 2017-04-06 23:06:04
DJI_0008.jpeg, Image time: 2017-04-06 23:06:09
DJI_0009.jpeg, Image time: 2017-04-06 23:06:14
DJI_0010.jpeg, Image time: 2017-04-06 23:06:19
DJI_0011.jpeg, Image time: 2017-04-06 23:06:24
DJI_0012.jpeg, Image time: 2017-04-06 23:06:29

It seems like the there is pattern in the time error hinting to a bug in the method that returns the time. I.e. for the test above the deltas were (15s, 5s, 5s, 5s, 5s, 5s). We would recommend using the file creation / last change time of the media file (these times were correct).

The behavior is the same when using Simulator or when flying the drone outside. The timings were always incorrect (up to almost 1 minute).

There is also no documentation what origin and what type of time getTime returns. We assume its a GPS derived UTC time, but it would be helpful if the documentation would explicitly state that. 

2. Steps to reproduce the bug:
Fetch MediaFiles and dump for all of them getDateCreated(). Compare them with image file creation / last change times or EXIF image metadata.

3. Involved software / firmware:
- DJI Android mobile SDK 4.0
- DJI Firmware for mavic v01.03.055
- DJI Firmware for RC v01.03.055 (According to DJI Go 4 App v4.0.5 as well as the DJI Assistant 2 version 1.1.0.2 both firmwares are up to date)
- Android 7.0, API 24
- Sony Xperia Z4
- Android Studio 2.3

**Comment by talobin** [comment]
@martindroneharmony Thanks for reporting this.
One of our dev will look into this and see if it still exists

**Comment by talobin** [comment]
@martindroneharmony SDK 4.4.1 should fix this issue already.
Please check it out.
Thanks!
