### ISSUE TITLE
4.15已经发布了，下个版本会支持MINI2吗

### ISSUE THREAD

**Issue by hackedbyxx** [dji-sdk/Mobile-SDK-Android#953]
每天都看road map

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/50018'>Zendesk ticket #50018</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
Mini2预计在5.0版本支持，暂时没有具体的释放时间，建议您可以关注后续版本。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
