### ISSUE TITLE
DJI SDK 4.15 issue for M2ED: getMaxHybridFocalLength() and getMinHybridFocalLength() as 240

### ISSUE THREAD

**Issue by mayurpatil307** [dji-sdk/Mobile-SDK-Android#955]
I am trying to achieve zoom feature with M2ED using DJI SDK4.15.
M2ED firmware version: 01.01.0800
But I am getting  getMaxHybridFocalLength() and getMinHybridFocalLength() both as 240 and unable to achieve zoom.

Please assist in resolving this.

Following is the code snippet:

if (null != camera) {
            if (camera.getDisplayName().equals(Camera.DisplayNameMavic2EnterpriseDual_VL) ||
                    camera.getDisplayName().equals(Camera.DisplayNameMavic2ZoomCamera)) {
                KeyManager.getInstance().getValue(CameraKey.create(CameraKey.HYBRID_ZOOM_SPEC, camera_id), new GetCallback() {
                    @Override
                    public void onSuccess(Object o) {
                        camera.getHybridZoomFocalLength(new CommonCallbacks.CompletionCallbackWith<Integer>() {
                            String message = "";
                            boolean success;
                            int currentZoomLevel;
                            int zoomStepCount;
                            int maxZoomLevelPossible;
                            int minZoomLevelPossible;

                            @Override
                            public void onSuccess(Integer integer) {
                                message = "[INFO] Zoom status fetched successfully";
                                success = true;
                                currentZoomLevel = integer;
                                zoomStepCount = ((SettingsDefinitions.HybridZoomSpec) o).getFocalLengthStep();
                                maxZoomLevelPossible = ((SettingsDefinitions.HybridZoomSpec) o).getMaxHybridFocalLength();
                                minZoomLevelPossible = ((SettingsDefinitions.HybridZoomSpec) o).getMinHybridFocalLength();
                            }

                            @Override
                            public void onFailure(DJIError djiError) {
                                logger.debug( "Could not fetch hybrid focal length settings: " + djiError.toString());
                            }
                        });
                    }

                    @Override
                    public void onFailure(DJIError djiError) {
                        logger.debug(i"Could not fetch hybrid zoom settings: " + djiError.toString());
                        return;
                    }
                });
            }

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/50065'>Zendesk ticket #50065</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.
https://djisdksupport.zendesk.com/hc/en-us/requests/new

Thanks,

Luce Luo
DJI Dev Team
<br><p><em><small>°°°</small></em></p>

**Comment by danidroidvx** [comment]
> DUSDK-13639

dod you get this working??? can you help me?

**Comment by danidroidvx** [comment]
> 
did you get this working???

**Comment by DJI-William** [comment]
Make sure your current displayMode is visual only and access camera(0).getMaxHybridFocalLength
