### ISSUE TITLE
MediaManager Image download problem

### ISSUE THREAD

**Issue by laboBea** [dji-sdk/Mobile-SDK-Android#969]
Hello,

When downloading photos with the MediaManagerDemo, they are stored in the folder: DJI/project pack name/CACHE_IMAGE
Instead to my destDir folder I have choosen, do anyone know what could be happening or how can I move them to my folder of choice? 

Thank you.

**Comment by kenargo** [comment]
Can you post the code you are using?  It should work.

 

From: laboBea ***@***.***> 
Sent: Thursday, July 15, 2021 1:24 AM
To: dji-sdk/Mobile-SDK-Android ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dji-sdk/Mobile-SDK-Android] MediaManager Image download problem (#969)

 

Hello,

When downloading photos with the MediaManagerDemo, they are stored in the folder: DJI/project pack name/CACHE_IMAGE
Instead to my destDir folder I have choosen, do anyone know what could be happening or how can I move them to my folder of choice?

Thank you.

**Comment by laboBea** [comment]
Solved the problem:
Initially destDir was declared with: Environment.getExternalStorageDirectory(), which is deprecated in Java.
Modified it to destDir = new File(Context.getExternalFilesDir(null).getPath()) 
And now is working fine.
Best regards,
