### ISSUE TITLE
startShootPhoto Error accessing the SD Card

### ISSUE THREAD

**Issue by SunYong** [dji-sdk/Mobile-SDK-Android#97]
ShootSinglePhotoView when click  Shoot Single Photo button show error "Error accessing the SD Card"

DJI Android SDK version 4.0

Android system version 5.1.1, 6.0.1

DJISampleApplication.getProductInstance()
                                .getCamera()
                                .startShootPhoto(new CommonCallbacks.CompletionCallback() {
                                    @Override
                                    public void onResult(DJIError djiError) {
                                        if (null == djiError) {
                                            ToastUtils.setResultToToast(getContext().getString(R.string.success));
                                        } else {
                                            ToastUtils.setResultToToast(djiError.getDescription());
                                        }
                                        post(new Runnable() {
                                            @Override
                                            public void run() {
                                                setEnabled(true);
                                            }
                                        });
                                    }
                                });

**Comment by oliverou** [comment]
Hi @SunYong , could you double check if the SD Card in your DJI Product has no issue? Try to test shoot photo feature in DJI Go app, or even format the SD card using DJI Go and try again.

**Comment by SunYong** [comment]
OK，I format the SD card and have a try。3Q~

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
