### ISSUE TITLE
区域测温返回的高低温坐标，怎么转换成屏幕上的点

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#973]

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/50539'>Zendesk ticket #50539</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
图传区域左右，上下均被分为了0-10000刻度，
根据返回的坐标自行映射即可。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
