### ISSUE TITLE
获取到的Camera，有没有方法能判断是否支持Lens

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#976]

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/50602'>Zendesk ticket #50602</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
可以通过调用getLenses方法，如果不返回空，即支持。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
