### ISSUE TITLE
无人机是否有设备唯一代码

### ISSUE THREAD

**Issue by wangxiaogang94** [dji-sdk/Mobile-SDK-Android#977]
无人机有没有设备唯一代码，
sdk能不能获取到设备唯一代码，
看api好像没有获取设备唯一代码的接口，
需求需要区分多台设备应该怎么做呢

**Comment by yand9807** [comment]
看文档里BaseComponent中的getSerialNumber(@NonNull CompletionCallbackWith<String> callback)就是获取飞机的唯一序列号的

**Comment by wangxiaogang94** [comment]
@yand9807 好的，谢谢

**Comment by dji-dev** [comment]
Agent comment from sean.zhou in <a href='https://djisdksupport.zendesk.com/agent/tickets/50607'>Zendesk ticket #50607</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

MSDK可以获取飞机各个组件的序列号，其中飞控的序列号可以作为无人机的唯一标识，FlightController类继承BaseComponent类，因此可以调用BaseComponent类中的getSerialNumber()方法获取组件的唯一标识。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by zhin2929** [comment]
> Agent comment from sean.zhou in [Zendesk ticket #50607](https://djisdksupport.zendesk.com/agent/tickets/50607):尊敬的开发者， 您好，感谢您联系DJI 大疆创新。
> 
> MSDK可以获取飞机各个组件的序列号，其中飞控的序列号可以作为无人机的唯一标识，FlightController类继承BaseComponent类，因此可以调用BaseComponent类中的getSerialNumber()方法获取组件的唯一标识。
> 
> 希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！
> 
> Best Regards, DJI 大疆创新SDK技术支持
> 
> _°°°_

现在5.0版本是在哪里呢？PayloadBasicInfo类吗？
