### ISSUE TITLE
AndroidManifest.xml  file --- dji.sdk.sdkmanager.GeoSyncFileService

### ISSUE THREAD

**Issue by chinanewer** [dji-sdk/Mobile-SDK-Android#98]
code：
`
        <service android:name="dji.sdk.sdkmanager.GeoSyncFileService"/>`

Error：
 ‘dji.sdk.sdkmanager.GeoSyncFileService’ is not assignable to 'android.app.Service'

**Comment by jtuchek** [comment]
That would be a problem.

GeoSyncFileService doesn't seem to actually extend an Android service. You could try removing that line from the AndroidManifest file until an update is pushed by DJI.

**Comment by SilverChangjian** [comment]
Sorry about this and thanks for reporting this error! In 4.0, we modify this service into a internal class and its lifecycle would be handled by the SDK Manager. Please remove this item in the AndroidManifest to clean up this error. The sample code would be updated soon. Thanks again for your support!

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Please feel free to reopen if the problem still exists.
Thanks!
